### ISSUE TITLE
Neo4j start fails with lsof >= 4.87

### ISSUE THREAD

**Issue by spacecowboy** [neo4j/neo4j#5443] opened 2015-09-24 14:54 UTC
On Arch Linux, running `bin/neo4j start`will fail with the following message (after about 3 seconds):

```
Starting Neo4j Server...WARNING: not changing user
process [30916]... waiting for server to be ready..... Failed to start within 120 seconds.
Neo4j Server failed to start, please check the logs for details.
If startup is blocked on a long recovery, use '.test/neo4j-enterprise-3.0.0-alpha/bin/neo4j start-no-wait' to give the startup more time.
```

But the server actually starts up fine. The problem is in the `detectrunning`method. To be precise, [the following command](https://github.com/neo4j/neo4j/blob/2.3/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j#L148):

```
newpid=$(lsof -i :$NEO4J_SERVER_PORT -F T -Ts | grep -i "TST=LISTEN" -B1 | head -n1)
newpid=${newpid:1}
```

The grep part makes the assumption that that `TST=LISTEN` will be printed on the line following the pid-number, which isn't true on my machine:

```
lsof -i :7474 -F T -Ts
```

Result

```
p7499
f232
TST=LISTEN
```

So the script will incorrectly use `f232` as the pid number and so the script will fail because `newpid` doesn't equal `STARTED_PID`.

Another way of doing which works on my machine would be

```
newpid=$(lsof -i :7474 -F T -Ts | grep -m1 -i "p*")
newpid=${newpid:1}
```

Which of course works if only "one entry" is returned by lsof. But is it expected that lsof can return multiple "entries" in this case?

Versions used (probably unrelated):
- GNU bash, version 4.3.42(1)-release (x86_64-unknown-linux-gnu)
- lsof 4.89
- grep (GNU grep) 2.21

**Comment by jotomo** [comment] 2015-09-24 22:32
Issue is caused by a change in lsof 4.88, everything <= 4.87 is fine, haven't seen any other distro besides Arch which yet uses a problematic version but that'll happen eventually. There are already a few issues open on this, as well as a PR which was closed because the author went MIA before signing the CLA. I think the plan was to eventually rework the script/the way the service is handled.
See #4505,  #3414

**Comment by spacecowboy** [comment] 2015-10-14 11:27
Fixed in #5601

**Comment by spacecowboy** [comment] 2015-10-15 10:58
Reopened since commit was reverted in

https://github.com/neo4j/neo4j/pull/5641
and
https://github.com/neo4j/neo4j/pull/5642

**Comment by jakewins** [comment] 2015-12-05 18:02
Closing this as the commit was manually merged, so GH missed closing this issue.

**Closed as completed by jakewins** 2015-12-05 18:02 UTC
