### ISSUE TITLE
Performance regression become slower in the new version

### ISSUE THREAD

**Issue by ddaa2000** [neo4j/neo4j#12919] opened 2022-08-17 11:48 UTC
I discovered that a query is much slower in the version4.4.10 compared with 4.3.17. I wonder if this is a performance defect?

**Neo4j Version:** 4.4.10 (compared with 4.3.17)
**Operating System:** Ubuntu 20.04
**API:** Java API

# Steps to reproduce
1. execute following queries to create the graph: [graph.txt](https://github.com/neo4j/neo4j/files/9359188/graph.txt)
2. execute the following query:
```
UNWIND [-476895865, 1724015025] AS a0 WITH * UNWIND [] AS a1 WITH min('3Ce') AS a2, min('Zi') AS a3, a0 WHERE (false OR true) UNWIND [253984662, 304197065, 1737038497] AS a4 RETURN a3 ORDER BY a3
```

# Expected behavior
The time consumed in 4.4.10 should be less than or similar to 4.3.17.

# Actual behavior
4.4.10 took 380ms while 4.3.17 only took 19ms to execute the query according to my test. I wonder if this is a performance defect

**Comment by HannesSandberg** [comment] 2022-08-22 07:14
Hi, thank you for bringing this up. We will investigate and report back to you!

**Comment by shrivastavrk** [comment] 2022-08-22 11:38
@HannesSandberg  while cypher team is checking on this issue, My team is also facing some issue, we also upgraded from v4.2.5 to v4.4.10,

we found out.
1. set clause taking more db hits compare to v4.2.5 
2. initial non-index based property filtering is also slower  in v4.4.10 compared to v4.2.5,
3. page caching is also not working perfectly here in latest version,

I am using windows neo4j desktop, and I have seen at least 25% slower execution time in latest version,
I have raised a community issue also with some basic query plan there 
[issue raised in community for reference ](https://community.neo4j.com/t5/general-discussions/v4-4-10-set-queries-are-taking-more-db-hits-than-v4-2-5/m-p/59337#M3576)

**Comment by pontusmelke** [comment] 2022-09-05 13:01
@ddaa2000 I ran the query on 4.4.10 and and 4.3.17 and I couldn't find any measurable difference. In order to assess performance you probably need to run the query multiple times to make sure caches are populated and other processes on the machine are not affecting the performance.

When running the above query on a cold database I get around 60ms for the first execution whereas rerunning the query whereas subsequent executions are around 1ms. The slower execution time on the first run is mostly due to that neo4j will cache the query-plan on first encounter so for subsequent request it can execute the query immediately.

I will close this issue since I am not able to reproduce your findings. If the problem should persist, don't hesitate to reopen or open a new issue.

@shrivastavrk It does not sound like the problem you are describing is the same as what is described in this issue. The query here doesn't touch anything that has been stored in the database and will hence not touch the page cache.

Best Regards,
Pontus

**Comment by mnd999** [comment] 2024-12-03 16:27
Closing as described above

**Closed as completed by mnd999** 2024-12-03 16:27 UTC
Labels: bug, team-cypher
