### ISSUE TITLE
CSV import bug for 3.3.2+

### ISSUE THREAD

**Issue by mlwish** [neo4j/neo4j#11094] opened 2018-02-23 21:49 UTC
I used NEO4J 3.3.1 on my mac to use neo4j-admin import shell to built graphs from CSV files and everything works fine. (followed by https://neo4j.com/docs/operations-manual/current/tools/import/)

I wanted to build the same database on my Ubuntu box(14.04) with NEO4J 3.3.2 so I scp all the CSV files from mac to ubuntu box and used the same shell to import CSV.

However, the importing data failed and neo4j complained the below ERRORS.
I tried to upgrade to 3.3.3 but it still failed in the same way. 
Finally I downgraded to 3.3.1 like what I have in Mac and it magically worked.

> WARNING Import failed. The store files in /home/mlo/neo4j-community-3.3.3/data/databases/tw_ml_v3.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
> org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:178)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:77)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.fetchNextOrNull(InputEntityDeserializer.java:41)
> 	at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
> 	at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.ParallelInputEntityDeserializer.lambda$new$0(ParallelInputEntityDeserializer.java:106)
> 	at org.neo4j.unsafe.impl.batchimport.staging.TicketedProcessing.lambda$submit$1(TicketedProcessing.java:103)
> 	at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:237)
> 	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:146)
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:126)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:78)
> 		at org.neo4j.unsafe.impl.batchimport.staging.Downstream.send(Downstream.java:56)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:58)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:26)
> 		at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
> 		at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
> 		at org.neo4j.concurrent.WorkSync.applyAsync(WorkSync.java:122)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:162)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:45)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:223)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:137)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:52)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:85)
> 		... 1 more
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283]
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
> 	Suppressed: org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.assertHealthy(DynamicTaskExecutor.java:146)
> 		at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor.submit(DynamicTaskExecutor.java:126)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.receive(ProcessorStep.java:78)
> 		at org.neo4j.unsafe.impl.batchimport.staging.Downstream.send(Downstream.java:56)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:58)
> 		at org.neo4j.unsafe.impl.batchimport.staging.SendDownstream.apply(SendDownstream.java:26)
> 		at org.neo4j.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
> 		at org.neo4j.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
> 		at org.neo4j.concurrent.WorkSync.applyAsync(WorkSync.java:122)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.sendDownstream(ProcessorStep.java:162)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.access$100(ProcessorStep.java:45)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep$Sender.send(ProcessorStep.java:223)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:137)
> 		at org.neo4j.unsafe.impl.batchimport.PropertyEncoderStep.process(PropertyEncoderStep.java:52)
> 		at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:85)
> 		... 1 more
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.input.InputException: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283]
> 	[CIRCULAR REFERENCE:org.neo4j.unsafe.impl.batchimport.executor.TaskExecutionPanicException: Executor has been shut down in panic]
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -283
> 	at java.lang.String.<init>(String.java:196)
> 	at org.neo4j.csv.reader.Extractors$StringExtractor.extract0(Extractors.java:329)
> 	at org.neo4j.csv.reader.Extractors$AbstractSingleValueExtractor.extract(Extractors.java:290)
> 	at org.neo4j.csv.reader.BufferedCharSeeker.tryExtract(BufferedCharSeeker.java:283)
> 	at org.neo4j.unsafe.impl.batchimport.input.csv.InputEntityDeserializer.deserializeNextFromSource(InputEntityDeserializer.java:138)
> 	... 7 more
> unexpected error: ERROR in input
>   data source: BufferedCharSeeker[source:/home/mlo/tw_ml_v3/merch_user_table.csv, position:2699377, line:9385]
>   in field: photo_id_number:string:15
>   for header: [id:ID(Merch_user), username:string, email:string, individual_name:string, store_url:string, is_banned:string, display_name:string, product_categories:string, date_last_active:string, tax_certificate:string, company_name:string, business_license:string, photo_id:string, warehouse_locations:string, photo_id_number:string, bd_rep:string]
>   raw field value: ??
>   original error: String index out of range: -283

**Comment by tolomaus** [comment] 2018-02-25 08:56
Hi,

Your issue looks very similar to one I encountered a couple of days ago and was caused by a non Latin (but still valid utf-8) character in my csv file. I found a workaround for it by removing all non latin characters from the file.

Could you verify if this workaround also fixes your problem? If not it may still be a different issue I have alltogether.

See also the discussion about it on slack: https://neo4j-users.slack.com/archives/C08J1B9P0/p1519332593000023

**Comment by mlwish** [comment] 2018-03-16 01:04
@tolomaus 
I cannot remove non Latin characters because I have a lot of chinese characters(utf-8) in my csv files.

**Comment by john-li-zenith** [comment] 2018-03-19 22:50
Any update on this bug? I encountered exactly same issue. However, the issue still persists even after i remove all non-latin characters.

**Comment by Lojjs** [comment] 2018-03-20 15:37
Hi and sorry for the late answer @mlwish . Utf-8 characters should be supported, so this sound like a bug. Would it be possible for you to send the failing data (line  9385 of your file) over so we could have a look at which character(s) are causing the error? Also @tolomaus , which non Latin character(s) did you have when encountering this issue? 

Best regards Louise, Neo4j Cypher team

**Comment by tolomaus** [comment] 2018-03-20 15:43
Hi Louise,

The "non-latin" workaround turns out to be unrelated. In fact the error can be "fixed" temporarily by simply changing the column ordering or removing a random line from the input. But the next time, with other inputs, it may fail again. 

See https://github.com/neo4j/neo4j/issues/11218 for more details. I created my own issue because I think it's unrelated to this one. At least I always get "String index out of range: -1" in the error message.

**Comment by mlwish** [comment] 2018-03-21 16:46
@Lojjs 

I don't have the original data. However, I can regenerate the error with different data set.
Please see the below error message with the failing data.

It complained the **display_name** in the data, however I do not see any bad data(**RandomBy__5615718e6fa88c4aca323191**) here.


Error in input data
Caused by:ERROR in input
  data source: BufferedCharSeeker[source:/home/mlo/graph_2018-03-19/merchant_table.csv, position:417511, line:2812]
  in field: display_name:string:2
  for header: [merchant_id:ID(Merchant), display_name:string, state:string, lifetime_gmv:double, gmv_30d:double, join_date:int, bd_rep:string, disabled_by:string, disable_date:int, ban_reason:string, countries:string, warehouse_locations:string, ip_magnitude:double]
  raw field value: ??
  original error: String index out of range: -1

WARNING Import failed. The store files in /home/mlo/neo4j-community-3.3.4/data/databases/graph_2018-03-19.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
unexpected error: ERROR in input
  data source: BufferedCharSeeker[source:/home/mlo/graph_2018-03-19/merchant_table.csv, position:417511, line:2812]
  in field: display_name:string:2
  for header: [merchant_id:ID(Merchant), display_name:string, state:string, lifetime_gmv:double, gmv_30d:double, join_date:int, bd_rep:string, disabled_by:string, disable_date:int, ban_reason:string, countries:string, warehouse_locations:string, ip_magnitude:double]
  raw field value: ??
  original error: String index out of range: -1

line 2812:
516796cf59e9995efe6ab3f0,RandomBy__5615718e6fa88c4aca323191,,0.0,0.0,1365743311,,Unknown,-1,,,,

**Comment by mlwish** [comment] 2018-03-28 19:56
When can we expect the fix to be deployed?

**Comment by tinwelint** [comment] 2018-03-31 09:56
The fix is now merged, although timing of 3.3.5 release is unknown to me right now.

**Closed as completed** 2018-04-05 06:27 UTC
Labels: bug, 3.3, team-kernel

**Comment by beautifulpage** [comment] 2018-04-25 09:36
Hi,Version 3.3.4 ,
![image](https://user-images.githubusercontent.com/5347165/39237434-1be5157c-48ae-11e8-80ae-b07f756f16cc.png)
it can not store punctuation “

**Comment by tinwelint** [comment] 2018-04-26 11:15
@beautifulpage I need your CSV data or at least a sample of it exhibiting this issue to be able to proceed. Also it looks like a new issue to me. Please create a new issue for it
