### ISSUE TITLE
Fails to load csv when multiline value ends with a newline (2.2.1)

### ISSUE THREAD

**Issue by Wiles** [neo4j/neo4j#4434] opened 2015-04-14 19:44 UTC
With the following example the code fails when trying to load the second record.

`LOAD CSV WITH HEADERS FROM 'https://gist.githubusercontent.com/Wiles/4e8b511be7ec9c99bffa/raw/aa289bb63c4f5ee1274071876dc3da22f3016897/gistfile1.txt' as line CREATE (n:Entry {a:line.a, b:line.b})`

Removing the trailing newline and it executes fine.

`LOAD CSV WITH HEADERS FROM 'https://gist.githubusercontent.com/Wiles/032f6d1556595edd5c73/raw/3dac026a9f9490284bcd11b9b0c3f118de62744b/gistfile1.txt' as line CREATE (n:Entry {a:line.a, b:line.b})`

**Comment by timmytofu** [comment] 2015-04-15 22:58
Whoops, I should've looked at the existing issues more carefully. It looks like @Wiles and I hit upon the same issue from different directions (neo4j#4439).

So, the problem is apparently any time a line in the CSV begins with a quote but is a continuation of the record from the previous line(s).

**Comment by cleishm** [comment] 2015-04-15 23:22
Thanks for the report! We'll try to resolve that asap.

**Comment by tinwelint** [comment] 2015-04-21 20:24
This has been fixed by https://github.com/neo4j/neo4j/commit/4f45b5939d198471d4649104fbec1f60d36ac3d9

**Closed as completed by tinwelint** 2015-04-21 20:24 UTC

**Comment by timmytofu** [comment] 2015-04-21 21:14
Great - any chance there will be a 2.2 maintenance release, or will this only be in 2.3?

**Comment by tinwelint** [comment] 2015-04-21 21:33
It will be included in 2.2.2 when that comes out as well, but I can't tell when that will be.

**Comment by ernestoe** [comment] 2015-07-24 07:57
Both this #4434 and #4439 are failing again.

**Comment by tinwelint** [comment] 2015-07-28 12:59
The test case that was added as part of the fix is still there and is working. You will need to provide an additional test case proving that this isn't working anymore. Which version are you testing this with?

**Comment by Ifdsr** [comment] 2015-07-28 14:18
Hello tinwelint, 

same here:
LOAD CSV WITH HEADERS FROM 'http://192.168.1.10/Mycsvfile.csv' AS csv
MERGE (:Example {ex_id: csv.EX_ID, titel: csv.Titel})

Error:
At http://192.168.1.10/Mycsvfile.csv:4 - Multi-line fields are illegal in this context and so this might suggest that there's a field with a start quote, but a missing end quote.

My version is 2.2.3 for linux (debian 8.1)
The error doesn't occur in windows (version 2.2.3)

THANKS!
IFDSR

**Comment by ernestoe** [comment] 2015-07-28 19:20
I didn't provide a new example as this one #4434 here proves to be failing. I'm running Community Edition version 2.2.3 in MacOS . This is a non-destructive example

```
LOAD CSV WITH HEADERS FROM 'https://gist.githubusercontent.com/Wiles/4e8b511be7ec9c99bffa/raw/aa289bb63c4f5ee1274071876dc3da22f3016897/gistfile1.txt' as line 
RETURN count(*)
```

gives

```
At https://gist.githubusercontent.com/Wiles/4e8b511be7ec9c99bffa/raw/aa289bb63c4f5ee1274071876dc3da22f3016897/gistfile1.txt:2 - Multi-line fields are illegal in this context and so this might suggest that there's a field with a start quote, but a missing end quote.
```

I created a new issue #5028 for this.

What is key here is the input file. It has multi-lines in the text fields.
