### ISSUE TITLE
MERGE does not match on unique node

### ISSUE THREAD

**Issue by mzoll** [neo4j/neo4j#11778] opened 2018-05-15 14:01 UTC
Hej, I am quite new to Neo4j and Cypher, but I think I stumbled about a bug in the interpretation of my Cypher statement, which kind of does not behave as anticipated or documented.

Issue
-----
With the following statement i create a hierarchical structure of `Users-[:OPEN]->Sessions-[:GEN]->Clicks-[:ON]->Pages`, of Web-clicks:

```cypher
LOAD CSV WITH HEADERS FROM "file:///clicks.csv" AS row
 
 //--- merge User
MERGE (u:User {userkey: toString(row.UserKey) })
ON CREATE SET u.created = row.LogTime

//--- merge session
WITH u, row
MERGE (u)-[:OPEN]->(s:Session {sessionkey: row.SessionKey, userkey: row.UserKey})<-[:REF]-(r:Referer)
ON CREATE SET s.created = row.LogTime 

//--- create click
WITH s, row
CREATE (s)-[:GEN]->(c:Click {requestid: row.RequestId,
  url: row.URL,
  time: row.LogTime,
  userkey: row.UserKey,
  sessionkey: row.SessionKey})

//--- merge page  
WITH c, row
MERGE (c)-[:ON]->(p:Page { domainpath: split(split(split(row.URL, '://')[1], '#')[0], '?')[0] } )
````

Here `Page` should be a trunkated page-URL, where protocol and parameters are stripped away (i.e. 'http://www.abc.com/aaa?b=123#456' is stripped to 'www.abc.com/aaa'). Also explicitly many Clicks should be able to point to the same `Page`; so `Page` can be seen as unique nodes only different by their property domain-path, which we can express with a Constraint

```cypher
CREATE CONSTRAINT ON (p:Page) ASSERT (p.domainpath) IS NODE KEY;
```

Now executing the above statement will fail if my dataset, on any click which repeats an domain-path which has been used in a previus clikc. The error being:
"Neo.ClientError.Schema.ConstraintValidationFailed: Node(737) already exists with label `Page` and property `domainpath` = 'www.abc.com/aaa'"

To my understanding of the way `MERGE` works, which is "use node(s) if match by label and properties exists and so complete the path, else create", this should not happen!

Workaround
--------------
To verify the issue, one can substitute the `//---merge page` section by

```cypher
WITH c, row
MERGE (p:Page { domainpath: split(split(split(row.URL, '://')[1], '#')[0], '?')[0] } )
WITH c, p
CREATE (p)<-[:ON]-(c)
```

which correctly executes.

Versions 
----------
Neo4j: Version: | 3.3.5 Edition: | Enterprise
OS: Windows 10 Professional
Interface: Neo4j Browser

**Comment by InverseFalcon** [comment] 2018-05-20 17:23
Hello,

This is not a bug, this is correct behavior for MERGE. From the documentation:

> When using MERGE on full patterns, the behavior is that either the whole pattern matches, or the whole pattern is created. MERGE will not partially use existing patterns — it’s all or nothing. If partial matches are needed, this can be accomplished by splitting a pattern up into multiple MERGE clauses.

There's a more in-depth breakdown and explanation in this knowledge base article on [understanding how MERGE works](https://neo4j.com/developer/kb/understanding-how-merge-works/).

In a nutshell, when the pattern does not exist in the graph, the entire pattern must be created. The only parts of the pattern that will use elements already present in the graph are variables that are already bound from previous matches. Otherwise any other elements in the match are created.

In your last MERGE to the `p:Page` node, this was not previously bound, so it will be created. To reuse an already existing `:Page` node in the graph with those properties, you need to MERGE to that node first, then use the variable from that MERGE in your pattern:

```
WITH c, row
MERGE (p:Page { domainpath: split(split(split(row.URL, '://')[1], '#')[0], '?')[0] } )
MERGE (c)-[:ON]->(p)
```

**Comment by mzoll** [comment] 2018-05-21 08:09
Okay , I see, then this is indeed no bug and correct behavior.
Still I wonder, why it is desiderable for MERGE to work in this 'all or nothing' fashion. Wouldn't partial matching, thus completion of a path by the shortest route, not be the more common use-case?

**Comment by InverseFalcon** [comment] 2018-05-21 09:09
@mzoll No, it would not. There needs to be a way to differentiate when the user wants a new node merged in vs reusing of an existing node.

Consider a graph of `:Student` nodes that can have `:ReportCard` nodes for a given term (in this case we'll model this with a `term` String property on the `:ReportCard` node).

Say that we know that all `:Student` nodes are in the graph, and we're in the process of adding grades to a student's report card for the current term, where the grades for classes are modeled as properties on a `:ReportCard` node, but as there is no set ordering as to when teachers add these grades, we cannot be sure that the `:ReportCard` node for the given term for the given student already exists, so we need to MERGE in this node (where it will match to it if it exists, and otherwise create it), and then add the relevant class grade property.

Our query would look something like this:

```
MATCH (s:Student {id:12345})
MERGE (s)-[:HAS_REPORT_CARD]->(r:ReportCard {term:6789})
SET ... //however grades are set
```

This works because if there is no such `:ReportCard` linked to the given student like this, it will create it, not attempt to find that node in the graph.

Here's a query that would behave the way you are expecting the MERGE to behave. That is, under the hood, your theoretical MERGE would behave the same way as this query:

```
MATCH (s:Student {id:12345})
MERGE (r:ReportCard {term:6789})
MERGE (s)-[:HAS_REPORT_CARD]->(r)
SET ... //however grades are set
```

The problem with this behavior is that we no longer have a way of merging in a single unique node per student. Instead it would find all `:ReportCard` nodes in the graph for the given term and link them. 

So on the first run, no such `:ReportCard` node would exist, so it would be created. So first run, for the first student, fine.

But for each subsequent student, it would be auto-completing to the single :ReportCard node in the graph for the given term and use that, and MERGE the relationship. The final result would be that every student in the school would be pointing to the single one `:ReportCard` node in the graph, and it would be a huge mess as all professors would be attempting to add grades to this one node, overwriting values, and no student would have their own personal `:ReportCard` node for the term, as there would be no possible way with Cypher to do such a thing.

This is why the behavior is the way it is currently. While it may not be immediately intuitive to you, it provides flexibility in how we add elements into the graph, and what constrains the uniqueness of the node (whether it's globally unique in the graph, or unique with respect to the nodes it is connected to).

The link I provided earlier has other such examples that are worth rereading.

**Comment by mzoll** [comment] 2018-05-21 09:29
Thanks for the explanation, I see the point in the scenario that you spin here.
However, I also find it worth to mention, that this problem of all students pointing to the same Report-card is due that the report cards themselves have no property that guaranties a unique distinction, aka holding the students name or registration-id, which could have been used in the MERGE statement as a unique identifier (maybe even as a unique key).

I understand that this relation is in principle, once created, held in the edge that points to the according student. But I also see the merit of keeping a unique distinction attribute as a node-property, as some tutorials recommend, because it allows access to nodes, without having to find a different node (here `:STUDENT`) on property match first and following its specified edge (here `HAS_CARD`) to the actual requested node (`:REPORT_CARD`),  and at the same time makes them uniquely distinguishable.

But I understand that this is rather a discussion aiming at effective database design then it is for the problem at hand. Thanks for the time taken to explain this to me.

**Comment by InverseFalcon** [comment] 2018-05-21 09:38
This does get into modeling issues, but we feel that if we're forced to add additional properties onto linked nodes (and not just at the first level, but at whatever depth we need for our model, which could get very cumbersome), then we're going in the face of graph modeling. At that point we've crossed from graph into something that seems much more like a relational db.

Certainly having some redundant properties in key areas for limited use cases can make sense, but forcing this type of modeling both adds more data that needs to be saved to the graph, and adds more complication as the chain of nodes relating to some central root node increases (and that's the easy case, when there is only a single central root node).

We actually used to have a something in Cypher that worked this way, a precursor to MERGE called [CREATE UNIQUE](https://neo4j.com/docs/developer-manual/current/cypher/clauses/create-unique/). It works similar to how you have described, eagerly looking for matching elements in the graph to use if a node wasn't previously bound. The feature has since been deprecated. It's just not flexible enough for our needs.

**Closed as completed** 2018-05-25 13:12 UTC
Labels: team-cypher
