### ISSUE TITLE
The Neo4j Debian repository structure

### ISSUE THREAD

**Issue by astesin** [neo4j/neo4j#6610] opened 2016-03-06 18:37 UTC
As neo4j behaviour changes significantly between MINOR versions (i.e. 2.1.\* and 2.2.\* are not 100% compatible), the very notion of 'stable' repository in questioned. I.e. suppose I have a project which runs on neo4j 2.1.7 and apt-get upgrade all of a sudden overwrites it with... 2.3.2 which breaks things badly (and upgrades db version from 2.1 to 2.3 silently).

This is not what one would expect, I think - desired behaviour is to replase 2.1.7 with 2.1.8, 2.1.9, ... bugfix releases, and upgrade of 2.1.\* to 2.2.\* (or 2.3.\* or 3.0.*) should require manual extended confirmation.

So I'd suggest structuring the Neo4j Debian repository by exact MAJOR.MINOR neo4j versions, and discard 'stable' et.al. Even for development-prerelease version, I'd prefer unambiguous "3.0" name over "testing".

WBR,
Andrii

**Comment by cleishm** [comment] 2016-03-06 21:41
Hey @astesin,

Putting aside whether an upgrade should automatically migrate the store, it is worth noting that debian itself uses a "stable" repository and upgrades software across major versions within it, which creates exactly the same type of concern you're noting. It's a little less obvious, perhaps, because debian releases are less frequent.

To avoid this type of issue, the debian project often suggests using the [apt-pinning](https://wiki.debian.org/AptPreferences#Pinning) mechanism. This should work for neo4j also. An appropriate preference entry might be:

```
Package: neo4j
Pin: version 2.3.*
Pin-Priority: 1001
```

Cheers,
Chris

**Comment by astesin** [comment] 2016-03-06 22:41
Thank you! I didn't know about this feature. BTW I'm using Ubuntu for years and I don't recall something that broke things after upgrade as soon as you are staying inside constant release (say while you are staying inside 14.04 things are pretty much stable, and only releae-upgrade may break some compatibility). What I mean, as soon as you say 'wily' in your deb command, you will get 15.10 compatible package and there is no 'stable' concept AFAIK.

WBR,
Andrii

**Comment by cleishm** [comment] 2016-03-07 00:11
Glad that helped, @astesin.

**Comment by astesin** [comment] 2016-03-07 01:26
Anyway, I'd like to express my sincere condolence to the poor soul who (all of a sudden) will have his/her neo4j 2.3._smth_ suddenly replaced by routine **apt-get upgrade** with 3.0._whatever_ 'stable' will be at that moment...

WBR, Andrii

**Comment by spacecowboy** [comment] 2016-03-07 09:10
Closing this issue as it seems to be working as intended (Neo4j behavior across versions aside). 

Please do not hesitate to open new issues if you need further assistance in the future.

**Closed as completed by spacecowboy** 2016-03-07 09:10 UTC
Labels: question

**Comment by astesin** [comment] 2016-03-07 10:03
Maybe it worth considering updationg the documentation (or web page where .deb installers live) with pointer to the apt-pinning mechanism for people who don't like unexpected 'stable' version upgrades? Thanks!
WBR, Andrii

**Comment by benbc** [comment] 2016-05-03 08:08
@astesin Thanks for reporting this problem. We're aware that the current behaviour may surprise people, but it's useful to have real-world reports. Our plan to improve this is to include the `major.minor` version in the package names (e.g. `apt-get install neo4j-2.3`), with virtual packages like `neo4j` and `neo4j-3` for people who want to take updates automatically. Would that satisfy your needs?

(cc @srbaker)

**Comment by astesin** [comment] 2016-05-03 10:47
@benbc yes, this seems to be a very reasonable idea. Under the same major version (say 2) automatic upgrade to the next minor is undesirable. I.e. 2.2.\* had enough differences from 2.1.\* to broke some code of ours. On the other side, upgrades between maintenance and bugfix releases inside 2.2.\* product line were painless and valuable. Thank you for making this good decision! Right now I installed 3.0.0 with .deb installer, and upgrade to 3.0.1 will be Ok (I hope) but I expect an upgrade from 3.0.whatever to 3.1.0 to be done manually, only. WBR, Andrii
