### ISSUE TITLE
Open transactions lead to crash of neo4j

### ISSUE THREAD

**Issue by ani82** [neo4j/neo4j#6924] opened 2016-04-12 18:51 UTC
Hi all,

I observed some likely unstable behavior in the current 2.3 branch related to open transactions.

**Versions**
- Neo4j version: 2.3.2
- Operating system: Debian Jessie (**EDIT:** i.e. Docker Image from library/neo4j:latest)
- **EDIT:** Settings: NEO4J_CACHE_MEMORY=2G
- **EDIT:** Hardware: 1vCPU, 3.75GB RAM, Limit for Neo4j 3GB
- API/Driver: Cypher REST + Py2Neo

**Steps to reproduce**
1. Run a transaction (TX) with remote server and local debugger
2. Pause TX locally for debugging, stop script with open TX before commit or revert
3. Repeat Step (2) 3-4 times within 5 minutes and stop each time before TX Commit
4. Socket timeout occurs for API and HTTP interface / port 7474

**Behavior**
- _Expected behavior_: Clear TX after grace period and recover to normal operation
- _Actual behavior_: Whole neo4j instance crashes and all sockets time out. That means port 7474 is neither responding for /api nor for HTTP / requests. Container subsystem is still accessible via SSH.

**console.log**

```
2016-04-12 20:12:29.384+0000 INFO  No SSL certificate found, generating a self-signed certificate..
20:12:33.250 [main] INFO  c.g.r.b.RuntimeKernelExtension - GraphAware Runtime disabled.
2016-04-12 20:12:36.203+0000 INFO  Successfully started database
2016-04-12 20:12:36.294+0000 INFO  Starting HTTP on port 7474 (1 threads available)
2016-04-12 20:12:36.677+0000 INFO  Enabling HTTPS on port 7473
2016-04-12 20:12:36.738+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
2016-04-12 20:12:36.935+0000 INFO  Mounting static content at /webadmin
2016-04-12 20:12:37.138+0000 INFO  Mounting static content at /browser
20:12:37.817 [main] INFO  c.g.s.f.b.GraphAwareBootstrappingFilter - Mounting GraphAware Framework at /graphaware
20:12:37.952 [main] INFO  c.g.s.f.c.GraphAwareWebContextCreator - Will try to scan the following packages: {com.**.graphaware.**,org.**.graphaware.**,net.**.graphaware.**}
20:12:41.948 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:42.003 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:42.011 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:43.752 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:44.084 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:44.660 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
20:12:44.661 [main] DEBUG c.g.s.t.LongRunningTransactionFilter - Initializing com.graphaware.server.tx.LongRunningTransaction
2016-04-12 20:12:45.046+0000 INFO  Remote interface ready and available at http://localhost:7474/
2016-04-12 20:12:45.668+0000 WARN  Failed authentication attempt for 'neo4j' from 127.0.0.1
2016-04-12 20:12:45.952+0000 INFO  Neo4j Server shutdown initiated by request
```

**Head (n=1000) of messages.log**

[message-head_n1000.log.zip](https://github.com/neo4j/neo4j/files/216541/message-head_n1000.log.zip)

To emphasize, I do not see any evidence that py2neo would be a relevant factor, because all Cypher queries are properly understood by the system.

**Comment by jexp** [comment] 2016-04-12 21:41
What does crash for you ? Neo4j or py2neo? I.e. can you execute operations in the web interface?

Can you share your data/log/*.log and data/graph.db/messages.log ?

So in general this should be reproducable by just opening 5 transactions and waiting? Or do you resume the debugger after timeouts occurred?

I'm not sure **what your "repeat"**

**Comment by ani82** [comment] 2016-04-13 07:22
Hi Michael,

see updated description: I mean to stop the debugger each time before the commit is executed. In pseudo syntax:

```
...
open TX
try:
    nodeid = ask graphaware time tree for a node with time = now
    node = build remote link to ID(nodeid)
    merge properties name and value on nodeid = ID(node) <-- STOP Debugger here
    close TX with commit
catch: TX rollback
```

This code works correctly when executed. However stopping the process at the breakpoint leads to the observed behavior.

**EDIT:** In the messages.log you can see that memory was first low 512GB with burst (container) to 3GB. I solved this meanwhile scaling to a fixed 2GB with burst to 3GB. Moreover, the first query at 20:12 had an error id = {id}, which was solved until 20:42.

**Comment by chrisvest** [comment] 2016-04-13 08:22
@ani82 The server has a fixed pool of transaction processing threads. I am suspecting that you end up getting all of these threads stuck in the debugger. In that case Neo4j won't be able to accept any new requests, because all the threads it uses to process requests are in use. The debugger will also prevent the threads from processing any query timeout signals we might send them.

Does this match what you are observing?

**Comment by ani82** [comment] 2016-04-13 08:35
Hi Chris,

this could explain some of the behavior. However, there must be more: I used IntelliJ/PyCharm as debuggers. The observed behavior is given with full stop of the debuggers.

I.e. each debugger is stopped and socket connections are closed by the debugger (likely, cannot dig into this source code). That means from local no open sockets remain. Can I provide you with more information? 

I mean this issue can also occur with a bunch of workers instead of 5 debugger processes, can't it?

I did a netstat -p tcp:
- running the debugger: 7 socket connections to remote port 7474
- closed TX: 4 socket connections remain for the browser GUI

**Comment by chrisvest** [comment] 2016-04-13 08:49
Yeah, if you start 5 very compute intensive queries, they could monopolise the transaction processing threads. How many CPU cores are available to Neo4j? The core count is used as the default value for the `org.neo4j.server.webserver.maxthreads` setting (being renamed to `dbms.threads.worker_count` in 3.0). If you run into this problem in practice, then increasing that setting should help you, if I'm right about what the problem is.

**Comment by ani82** [comment] 2016-04-13 08:50
One core / 2 CPU threads are available. Load is at 80%, therefore I did not think about doing a multiple.

**Comment by chrisvest** [comment] 2018-02-21 15:28
Closing this because this basically by design. We have a bounded thread-pool for executing REST transactions, to avoid run-away resource usage. Stopping transactions _at commit time_ is not very realistic. Transactions that take too long will either run into the `dbms.transaction.timeout` setting, or the `dbms.lock.acquisition.timeout` setting.

**Closed as completed by chrisvest** 2018-02-21 15:28 UTC
Labels: 2.3, team-kernel
