### ISSUE TITLE
Deleted node still found in index, but only if referenced in more than one index...

### ISSUE THREAD

**Issue by mikesname** [neo4j/neo4j#12783] opened 2021-11-01 21:55 UTC
I've discovered a change in behaviour in Neo4j 4.3 that looks like a bug to me. At least I can't see anything documented and the current behaviour looks like it could catch people out. 

**Neo4j version:** 4.3.6
**Operating system:** Ubuntu 20.04
**API/Driver:** Java API

### Steps to reproduce

1. Create a unique constraint on a property key for a given label
2. Create _at least one additional standard index_ on a second property for the same label

Then, in a **single transaction**:
1. Create a node with the label
2. Add properties for each index
3. Delete the node
4. Check the node is gone from both indexes using the properties for lookup

### Expected behaviour

 - The node should be gone from both unique and standard indexes after deletion

### Actual behaviour

 - The node is gone from the standard index
 - The node is found in the unique index using `findNode(label, key, value)`
 - Accessing data on the returned node results in an `EntityNotFoundException`

I've made a test case here:

https://github.com/mikesname/neo4j-deletion-test

There are two tests:

**Test 1** adds just a unique property constraint to the schema and creates and deletes the node with two properties. This passes in both 4.2.11 and 4.3.6.

**Test 2** adds both a unique property constraint and a standard index to the schema and creates and deletes the node. This passes in 4.2.11 but fails in 4.3.6.

**Comment by emmaholmbergohlsson** [comment] 2021-11-02 14:52
@mikesname Thank you for reporting, and especially for the nice tests that helped me find the bug in minutes.
This is definitely a bug and a fix is on the way. The problem is actually not because you have several indexes but because the node has several properties. For nodes and relationships that have several properties and are created and deleted in the same transaction, there were some cases where the transaction states for indexes indexing that node would not be updated correctly. The fix will come in the next 4.3 patch release

**Comment by emmaholmbergohlsson** [comment] 2021-11-09 16:48
@mikesname The fix is included in 4.3.7 that has just been released

**Closed as completed by emmaholmbergohlsson** 2021-11-09 16:49 UTC
Labels: bug, team-kernel

**Comment by mikesname** [comment] 2021-11-11 13:58
@emmaholmbergohlsson excellent, works great now. Thanks for that :+1:
