### ISSUE TITLE
Can't send BYTES type using Bolt protocol

### ISSUE THREAD

**Issue by bost-h** [neo4j/neo4j#7640] opened 2016-07-25 22:24 UTC
I tried to create a node with the python bolt driver, and I passed a `bytearray([42])` as a query parameter, then I got `neo4j.v1.exceptions.ProtocolError: Server closed connection`.
I did the same with a homemade golang driver, the server also shutdowns the connection, but very occasionally I get a `Neo.ClientError.Request.InvalidFormat: Unknown value type: BYTES`.

I don't think the issue comes from drivers, I inspected the packstream encoded data and it is well formed (`0xcc 0x01 0x2a` for a `bytearray([42])`)

**Neo4j Version:** 3.0.3
**Operating System:** I am using the official docker image tagged `latest`, which is currently the `3.0.3`
**API:** I am testing with a homemade golang driver but i confirmed the behaviour with the python driver https://github.com/neo4j/neo4j-python-driver
### Steps to reproduce
1. Install the python driver https://github.com/neo4j/neo4j-python-driver
2. Launch a Neo4j 3.0.3 server
3. Run the following code

``` python
from neo4j.v1.session import GraphDatabase, basic_auth


driver = GraphDatabase.driver("bolt://localhost", auth=basic_auth("neo4j", "neo4j"))
session = driver.session()

result = session.run("CREATE (n {data: {data}})", {"data": bytearray([42])})
session.close()
```
### Expected behaviour

The node should be created with no errors, and we should be able to pass binary data as a parameter
### Actual behaviour

Most of times I got a `neo4j.v1.exceptions.ProtocolError: Server closed connection`, but very occasionally I got a `Neo.ClientError.Request.InvalidFormat: Unknown value type: BYTES`.
The node is not created.

**Comment by spacecowboy** [comment] 2016-07-26 08:17
I believe the driver is working as intended for the most part here (the error message could be clearer at the very least).

If you look at http://neo4j.com/docs/developer-manual/current/#driver-types
you can see what types are supported by the drivers/neo4j. Neo4j has no type which maps to bytes/binary/raw.

I've labeled the issue as a feature request for a binary type. Does that sound reasonable?

**Comment by bost-h** [comment] 2016-07-26 08:34
It's true that the driver documentation says nothing about binary data, I was a bit confused because the driver try to handle it here https://github.com/neo4j/neo4j-python-driver/blob/1.1/neo4j/v1/packstream.py#L507 and I also found references to the packstream BYTES type among the neo4j source code (https://github.com/neo4j/neo4j/blob/6280974efc9b082d5f40044df362355134a8632b/community/bolt/src/main/java/org/neo4j/bolt/v1/packstream/PackStream.java#L114) so I expected it to work.

Of course if this is the expected behaviour, labeling this issue as a feature request seems good to me.

Thank you for your time.

**Comment by rimraff** [comment] 2016-11-07 20:49
Would definitely vote for that!

**Comment by technige** [comment] 2017-01-23 11:01
Currently, binary data is not supported throughout our entire stack. This is something that we do have on our roadmap however.

The mention of BYTES in PackStream comes from the original expectation to include this in 3.0 before realising the extent of the work to do so. The type still exists in readiness but is largely undocumented.

**Comment by ali-ince** [comment] 2018-10-02 10:00
Closing this as `BYTES` type binary-data is supported since neo4j version 3.2 and driver versions 1.4.

**Closed as completed by ali-ince** 2018-10-02 10:00 UTC
Labels: feature, team-drivers
