### ISSUE TITLE
neo4j-shell 2.1.2: Data containing "&&" fails to parse correctly

### ISSUE THREAD

**Issue by MatAtBread** [neo4j/neo4j#2579] opened 2014-06-14 09:33 UTC
````
neo4j-sh (?)$ create (t:Test {a:"abc&&def"}) return t;
Unknown command 'def"})'
neo4j-sh (?)$ 
````

This breaks imports from dumps where the data contains this pattern

**Comment by jakewins** [comment] 2015-12-06 06:17
Closing as duplicate of #2625

**Closed by jakewins** 2015-12-06 06:17 UTC
