### ISSUE TITLE
Sending '\n' via bolt results in IllegalArgumentException

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#7313] opened 2016-06-04 02:39 UTC
- Neo4j version: 3.0.2
- Reproduce by sending "\n" as a statement to RUN (via bolt)

```
2016-06-04 02:37:32.638+0000 ERROR [o.n.b.v.r.i.c.SessionWorker] Fatal, worker for session 'b50545d0-1fc3-4feb-ba8b-c5d524e02e03' crashed. Please contact your support representative if you are unable to resolve this. message converted to empty list
java.lang.IllegalArgumentException: message converted to empty list
    at org.neo4j.cypher.SyntaxException.findErrorLine(SyntaxException.scala:41)
    at org.neo4j.cypher.SyntaxException.toString(SyntaxException.scala:31)
    at org.neo4j.cypher.SyntaxException.getMessage(SyntaxException.scala:35)
    at org.neo4j.bolt.v1.runtime.internal.Neo4jError.from(Neo4jError.java:157)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine$State.error(SessionStateMachine.java:481)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine$State$2.runStatement(SessionStateMachine.java:136)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.run(SessionStateMachine.java:653)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorkerFacade.lambda$run$3(SessionWorkerFacade.java:68)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorkerFacade$$Lambda$181/409559632.accept(Unknown Source)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.execute(SessionWorker.java:116)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.run(SessionWorker.java:77)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by cleishm** [comment] 2016-06-04 02:53
Interestingly, it leaves the bolt connection active - and thus the client hangs waiting for a response that never comes (i.e. no FAILURE is sent).

**Comment by ehx-v1** [comment] 2016-06-07 12:23
I wonder, though, if this is a real issue, or if it's normal that a whitespace character only command is treated as "nothing". Or did I misunderstand the issue, and `\n` is not the only character in the statement?
Or is the comment the actual issue: That an "empty command" error is not propagating as failure?

**Comment by cleishm** [comment] 2016-06-07 14:48
Hi @ehx-v1,

The expected interaction should be the same as sending a single whitespace character:

```
TRACE [session]: enqu RUN{" "} (0x7f862a809ae0) in 0x7f862a41bb00
TRACE [session]: enqu PULL_ALL (0x7f862a809bc0) in 0x7f862a41bb00
DEBUG [session]: sent RUN (0x7f862a809ae0) in 0x7f862a41bb00
DEBUG [session]: sent PULL_ALL (0x7f862a809bc0) in 0x7f862a41bb00
DEBUG [session]: rcvd FAILURE in response to RUN (0x7f862a809ae0)
TRACE [results]: FAILURE in 0x7f862a41bb00 (response to RUN): {code:"Neo.ClientError.Statement.SyntaxError",message:"Unexpected end of input: expected whitespace, comment, CYPHER options, EXPLAIN, PROFILE or Query (line 1, column 2 (offset: 1))
\" \"
  ^"}
DEBUG [session]: rcvd IGNORED in response to PULL_ALL (0x7f862a809bc0)
TRACE [session]: enqu ACK_FAILURE (0x7f862a809ca0) in 0x7f862a41bb00
DEBUG [session]: sent ACK_FAILURE (0x7f862a809ca0) in 0x7f862a41bb00
DEBUG [session]: rcvd SUCCESS in response to ACK_FAILURE (0x7f862a809ca0)
TRACE [session]: ACK_FAILURE complete in 0x7f862a41bb00
```

Certainly the failure to send any response to the client is the main problem. I'd add that an exception appearing in the log is not appropriate either.

Cheers,
Chris

**Comment by ehx-v1** [comment] 2016-06-09 14:52
@jexp and others: Apparently the server doesn't treat `\n` as whitespace, so it isn't caught by Cypher, and thus results in a different exception which doesn't propagate as failure. At least that appears to me the root cause from what I read out of the contrast above.

**Comment by cleishm** [comment] 2016-06-09 15:47
The parser definitely treats a newline as whitespace. The problem is in calculating the position of the error (`org.neo4j.cypher.SyntaxException.findErrorLine(SyntaxException.scala:41`), because of https://github.com/neo4j/neo4j/blob/3.1/community/cypher/cypher/src/main/scala/org/neo4j/cypher/SyntaxException.scala#L31

E.g.:

```
scala> "\n".split('\n').toList
res0: List[String] = List()
```

**Comment by zhenlineo** [comment] 2018-10-02 09:11
Closing as the PR to fix this error has been merged (long time ago)

**Closed as completed by zhenlineo** 2018-10-02 09:11 UTC
Labels: bolt server, 3.0, team-drivers
