### ISSUE TITLE
Failed to establish secure connection to u'[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)' using latest neo4j docker image

### ISSUE THREAD

**Issue by SimplicityGuy** [neo4j/neo4j#9233] opened 2017-04-20 16:01 UTC
When trying to use the latest `neo4j` docker image from within a Python docker container, I fail to connect. This used to work fine with older versions of the `neo4j` docker image.

**Neo4j Version:** 3.1.3
**Operating System:** Debian Stretch, Mac OS X, Ubuntu 16.04
**API:** neo4j:latest

### Steps to reproduce
1. docker run -d -p 7687:7687 -p 7474:7474 -e NEO4J_AUTH=neo4j/123 --name=neo4j-test neo4j
2. docker run -it --link neo4j-test python:2.7 bash
3. within the Python container run: pip install neo4j-driver
4. Load an interactive Python shell and use this code:
```
from neo4j.v1 import GraphDatabase, basic_auth
db = GraphDatabase.driver("bolt://172.17.0.2:7687", auth=basic_auth("neo4j", "123"))
```

### Expected behavior
Connection to the database should work, as it did with neo4j:3.0.1

### Actual behavior
Exception thrown:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/api.py", line 112, in driver
    return driver_class(uri, **config)
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 63, in __init__
    pool.acquire()
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 39, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/usr/local/lib/python2.7/site-packages/neo4j/bolt/connection.py", line 386, in acquire_direct
    connection = self.connector(address)
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 62, in <lambda>
    pool = DirectConnectionPool(lambda a: connect(a, security_plan.ssl_context, **config), self.address)
  File "/usr/local/lib/python2.7/site-packages/neo4j/bolt/connection.py", line 470, in connect
    raise error
SecurityError: Failed to establish secure connection to u'[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)'
Failed to establish secure connection to u'[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:661)'
```

Note, this works fine using neo4j:3.0.1 version of the neo4j image.

**Comment by SimplicityGuy** [comment] 2017-04-20 16:03
Looks like some other folks have reported this in Docker hub already:
https://hub.docker.com/_/neo4j/

See comments from `hleb`.

**Comment by davidhousedev** [comment] 2017-04-20 16:15
The steps outlined by @SimplicityGuy work for versions as late as `neo4j:3.0.9`. However, for `neo4j:3.1.0` it produces a different issue. Rather than throwing a `SecurityError`, the Python environment will hang unresponsive.

After letting the script run for approximately five minutes, I sent a `KeyboardInterrupt` and received this traceback:
```
  >>> db = GraphDatabase.driver("bolt://172.17.0.2:7687", auth=basic_auth("neo4j", "123"))
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/api.py", line 112, in driver
    return driver_class(uri, **config)
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 63, in __init__
    pool.acquire()
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 39, in acquire
    connection = self.acquire_direct(address)  # should always be a resolved address
  File "/usr/local/lib/python2.7/site-packages/neo4j/bolt/connection.py", line 386, in acquire_direct
    connection = self.connector(address)
  File "/usr/local/lib/python2.7/site-packages/neo4j/v1/direct.py", line 62, in <lambda>
    pool = DirectConnectionPool(lambda a: connect(a, security_plan.ssl_context, **config), self.address)
  File "/usr/local/lib/python2.7/site-packages/neo4j/bolt/connection.py", line 466, in connect
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI else None)
  File "/usr/local/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
```

**Comment by SimplicityGuy** [comment] 2017-05-03 02:41
Any traction on getting this fixed?

**Comment by sundhaug92** [comment] 2017-05-11 23:30
A temporary fix might be to pass encrypted=False to the driver, however this is quite insecure in some threat-models.

**Comment by SimplicityGuy** [comment] 2017-05-12 13:33
Indeed the workaround suggested by sundhaug92 works. However this is just that... a workaround and not an optimal one at that. For now, we're locked to version 3.0.9 so that we don't change our code.

**Comment by srbaker** [comment] 2017-05-15 09:39
Heya. Thanks for the report, I am looking into this now.

**Comment by spacecowboy** [comment] 2017-05-15 15:15
@SimplicityGuy @davidhousedev @sundhaug92 

We have identified the issue and I'd just like to mention that to you guys.

## Explanation

The cause is a bug in `openssl` version `1.0.1`. This is the version installed in Debian Jessie, which is the base image for the Python Image used above (it uses `buildpack-deps:jessie`).

Not sure if it's the same bug, but a similar issue was reported a long time ago:

https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371

A minimal reproduction is (having neo4j running in another docker container) to use `openssl` directly on the command line.

Using `debian:jessie`:

```
apt update && apt install openssl
openssl s_client -connect 172.19.0.2:7473
```

will fail to perform the ssl handshake.

Switching to Debian Stretch fixes it, because it ships `1.1.0` of openssl. 

`1.0.2` of openssl is available in jessie-backports: https://packages.debian.org/jessie-backports/openssl

Installing openssl from jessie-backports (tested it) also fixes the issue.

I'll want to report this upstream but meanwhile you can fix this locally in your own python-docker images by doing:

## Workaround

```
echo "deb http://httpredir.debian.org/debian/ jessie-backports main" >> /etc/apt/sources.list && \
  apt update && apt install -y -t jessie-backports openssl
```

I tried that locally before running `pip install neo4j-driver` and I could connect successfully.

**Comment by wubing101** [comment] 2018-02-01 13:01
@spacecowboy  what to do in centos? thank you

**Comment by spacecowboy** [comment] 2018-02-01 13:35
@bingwork this issue relates to a problem in the Docker container. If you have issues with CentOS please create a new issue and describe your problem

**Comment by biwin** [comment] 2018-08-28 18:00
In my case this exception was thrown as I was bolting to port `7474` instead `7687`

**Comment by zhenlineo** [comment] 2018-10-02 09:03
Closing this issue as it is a bug not in neo4j and a workaround is provided to address this.

**Closed as completed by zhenlineo** 2018-10-02 09:03 UTC
Labels: bug, bolt server, team-drivers
