### ISSUE TITLE
Neo4j becomes completely irresponsive and freezes integration tests

### ISSUE THREAD

**Issue by sgehrig** [neo4j/neo4j#11969] opened 2018-07-11 15:31 UTC
When running neo4j (3.4.1-enterprise and community) in a CI environment we sometimes (more often than not recently) stumble upon a deadlock when talking to the neo4j from our test suite. Before running the test suite a completely new neo4j instance is being setup (to overcome some problems we had with neo4j getting slower and slower over time). Then, with each test, parts of our applications’s schema is setup before and torn down after the test (schema = constraints and indexes). At different points in time when running the test suite neo4j becomes irresponsive and it will not even shutdown correctly any more. This leads to the test suite freezing. 

At this point we see the following messages in the debug.log: 

```
2018-07-10 15:03:49.920+0000 INFO [o.n.k.i.a.i.IndexPopulationJob] Index population completed. Index [:ANALYTIC(id) [provider: {key=lucene+native, version=2.0}]] is POPULATING.
2018-07-10 15:04:14.460+0000 WARN [o.n.k.i.a.i.s.OnlineIndexSamplingJob] Not finished: Sampling index Index( UNIQUE, :NODE_VERSION(id) ) in 0 ms
2018-07-10 15:16:46.662+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by scheduler for time threshold @ txId: 20560 checkpoint started...
2018-07-10 15:16:48.242+0000 ERROR [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint failed Unable to force ContractCheckingIndexProxy -> FlippableIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@3b581cc, descriptor:Index( UNIQUE, :label[3](property[3]) )][target:org.neo4j.kernel.impl.api.index.IndexProxyCreator$$Lambda$472/1484659111@29395058]
org.neo4j.kernel.impl.store.UnderlyingStorageException: Unable to force ContractCheckingIndexProxy -> FlippableIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.impl.index.schema.fusion.FusionIndexAccessor@3b581cc, descriptor:Index( UNIQUE, :label[3](property[3]) )][target:org.neo4j.kernel.impl.api.index.IndexProxyCreator$$Lambda$472/1484659111@29395058]
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$10(IndexingService.java:630)
	at org.neo4j.kernel.impl.api.index.IndexMap.lambda$forEachIndexProxy$0(IndexMap.java:127)
	at org.neo4j.collection.primitive.hopscotch.PrimitiveLongObjectHashMap.visitEntries(PrimitiveLongObjectHashMap.java:86)
	at org.neo4j.kernel.impl.api.index.IndexMap.forEachIndexProxy(IndexMap.java:125)
	at org.neo4j.kernel.impl.api.index.IndexingService.forceAll(IndexingService.java:614)
	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:462)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:164)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:138)
	at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:64)
	at org.neo4j.kernel.impl.scheduler.ScheduledJobHandle.lambda$new$0(ScheduledJobHandle.java:83)
	at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot call force() when index state is CLOSED
	at org.neo4j.kernel.impl.api.index.ContractCheckingIndexProxy.openCall(ContractCheckingIndexProxy.java:206)
	at org.neo4j.kernel.impl.api.index.ContractCheckingIndexProxy.force(ContractCheckingIndexProxy.java:124)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$forceAll$9(IndexingService.java:614)
	at org.neo4j.kernel.impl.api.index.IndexingService.lambda$indexProxyOperation$10(IndexingService.java:623)
	... 15 more
[...]
```

https://gist.github.com/sgehrig/5a8d9b046ffd5339d90a401615a2e598 (full [debug.log](https://github.com/neo4j/neo4j/files/2185129/debug.log) attached)

The sequence when running the test suite is:

- create neo4j instance
- start test suite
- start test
   - create indexes and constraints
   - create necessary fixtures
   - run test
   - drop database content
   - drop indexes and constraints
- end test
- next test
   - …
- end test suite

**Neo4j Version:** 3.4.1-enterprise/community
**Operating System:** Ubuntu 16.04
**API:** graphaware/neo4j-php-client

### Expected behavior
Neo4j should not freeze.

### Actual behavior
Neo4j freezes.

**Comment by chrisvest** [comment] 2018-07-11 15:41
Would you be able to create an issue reproducer e.g. as a file that can be piped to `cypher-shell`?

**Comment by sgehrig** [comment] 2018-07-11 15:45
@chrisvest Phew - that might be hard. There are about 3000 tests in the test suite of which about 400 - 500 talk to the Neo4j instance. The whole test suite normally runs for about an hour and it fails unpredictably. We only notice that it failed when checking the Jenkins jobs and seeing one that seems to be running for several hours. It's always on a different test that the process (including the Neo4j instance) freezes.

If we had a rough idea what caused these freezes, I would be able to narrow it down and to try to create a reproducible test case.

Oh and because @sarmbruster_neo4j mentioned it on Slack: I cannot say whether this problem also happened with previous releases of Neo4j (3.3, 3.2, 3.1, 3.0) but we'll try to change the index model tomorrow and rerun the whole thing.

**Comment by sgehrig** [comment] 2018-07-12 08:31
@chrisvest I can provide a `query.log` that has been generated by a successful test suite run so that you can take a look at the queries executed. I also have a version of the `query.log` that only contains queries and their parameters. It contains about 46k queries. I cannot, however, share that log file publicly. 

We also enabled query logging on the CI server to ensure that we get a `query.log` on a failed test suite run as well.

**Comment by chrisvest** [comment] 2018-07-12 09:08
When Neo4j is frozen, grab a complete thread dump with `jstack` and post it here. That might help us narrow things down.

**Comment by sgehrig** [comment] 2018-07-12 10:14
That's what we get from `jstack -F`:

```
Attaching to process ID 30029, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.171-b11
Deadlock Detection:
java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f7f5c003000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:166)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.runtime.DeadlockDetector.createThreadTable(DeadlockDetector.java:149)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:56)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f7f5c003000
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
	... 17 more
Can't print deadlocks:Unable to deduce type of thread from address 0x00007f7f5c003000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f7f5c003000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:166)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:75)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	... 6 more
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f7f5c003000
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
	... 14 more
```

Does not look so good to me.

**Comment by sgehrig** [comment] 2018-08-13 15:25
Any news on this one or anything we can help with?

**Comment by mikesname** [comment] 2018-10-03 10:57
I have (seemingly) the same problem with 3.4.x (community.) For each test I set up a new impermanent DB, create indexes and constraints, run my code, and then shutdown the DB on teardown. 

On Travis-ci Neo4j will at some seemingly random point hang on shutdown. I've attached a jstack dump obtained by debugging my Travis job. 

I cannot reproduce outside the CI environment, even using the same Docker container, which is a bit mysterious.

[jstack.txt](https://github.com/neo4j/neo4j/files/2441699/jstack.txt)

**Comment by tinwelint** [comment] 2018-10-22 18:26
@mikesname your jstack.txt merely shows that the page cache is flushing dirty pages at closing time. Nothing frozen about it.

**Comment by mikesname** [comment] 2018-10-23 09:01
@tinwelint okay good to know! But it's sitting there using 100% CPU for an indefinite period of time whilst shutting down which seems strange to me... I will try and investigate further since this is blocking me updating to 3.4.

**Comment by KeatsPeeks** [comment] 2018-12-12 15:29
@mikesname have you found a solution ?

I think I have the exact same issue : test suite in docker, neo4j 3.4, 100% CPU at some seemingly random point.

**Comment by mikesname** [comment] 2018-12-12 19:25
@KeatsPeeks I'm afraid not, and it's so difficult to debug since only happens on Docker/Travis I'm basically fumbling in the dark.

Fortunately, 3.5.0 seems not to have to issue so I'm thinking I'll just skip straight to that version.

**Comment by burqen** [comment] 2019-11-19 15:18
@sgehrig Is this still a problem for you? It seems like @mikesname successfully overcome the problem by upgrading to 3.5. Would that work for you?
If not, to continue investigation we will need a stack trace. The problem that you see looks very similar to the one described here https://bugzilla.redhat.com/show_bug.cgi?id=1095504. Does that help you get the stack trace?

**Comment by sgehrig** [comment] 2019-11-20 06:47
@burqen I must admit that I haven't followed up on this issue recently because we are currently not working on our project any more that uses Neo4j. So I think it's fair to say that you can suspend this issue for now. I'll check the issue with the most recent Neo4j version as soon as I manage to find some spare time.

But thanks for keeping an eye on that one. Your support is much appreciated.

**Comment by burqen** [comment] 2019-11-20 07:50
@sgehrig If you're happy, I'm happy 😄 
Closing this issue for now then.

**Closed as completed by burqen** 2019-11-20 07:50 UTC
Labels: team-kernel, 3.4
