### ISSUE TITLE
Node deleted failed about path of unknown length

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13437] opened 2024-04-02 04:26 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.17.0 Community
operating system: windows 10
API：Cypher version 9
query: MATCH (n0)-[*..1]-(n0) DETACH DELETE n0

To create the initial graph:
CREATE ()

Expected behavior:
The query should delete the node.

Actual behavior:
Node deleted failed.

The query "MATCH (n0)-[*0..1]-(n0) DETACH DELETE n0" can delete the node.

**Comment by InverseFalcon** [comment] 2024-04-02 05:31
This is not a bug.

Please review the variants in our variable-length pattern documentation here:
https://neo4j.com/docs/cypher-manual/current/patterns/reference/#variable-length-relationships-rules

You'll note in that table that there is a _difference_ in the defaults used when the lower bound is omitted, between the older _variable-length relationship syntax_, and the newer _quantified path patterns_, in that the default lower bound for variable-length relationship patterns is 1, not 0.

Therefore `[*..1]` is actually the equivalent of `[*1..1]`. Since there is no relationship to traverse, no paths are found that match the pattern.

Likewise `[*]` with variable-length relationship syntax is "1 or more" instead of "0 or more".

The behavior for _quantified path patterns_ is different, and likely more in-line with your expectations.

As this is not a bug, I will be closing the issue.

**Closed as completed by InverseFalcon** 2024-04-02 05:31 UTC
Labels: bug
