### ISSUE TITLE
ExecutionFailed Error about aggregating function in call{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13201] opened 2023-05-29 09:09 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:match (a) call{with a return exists{return min(a)} as k} return 1
error message:
Neo.DatabaseError.Statement.ExecutionFailed
A bug has occurred in the slotted runtime: The target slotted execution context cannot hold the data to copy
From : SlotConfiguration417874941(longs=1, refs=2, discarded=0, markedDiscarded=0, slots=HashMap(VariableSlotKey(a) -> LongSlot(0,false,Node), VariableSlotKey(1) -> RefSlot(1,true,Any), VariableSlotKey(k) -> RefSlot(0,false,Boolean)))
To :   SlotConfiguration1638841323(longs=1, refs=1, discarded=, markedDiscarded=, slots=HashMap(VariableSlotKey(a) -> LongSlot(0,false,Node), VariableSlotKey(min(a)) -> RefSlot(0,true,Any)))

If I execute another query: "match (a) call{with a return exists{return min(a)} as k} return k",then the error goes away which is very strange.

Expected behavior:
The query should run successfully or at least it should not give such confusing error message.

Actual behavior:
The query failed.

**Comment by LinneaAndersson** [comment] 2023-05-29 11:35
@ljhhuxiaoba Thanks for reporting this, it seems like a bug to me. 

We will investigate it further and get back to you when we have some more information. 

Thanks again,
Linnéa

**Comment by JonasHolgersson** [comment] 2023-06-01 09:11
@ljhhuxiaoba Thanks for reporting, this is actually a duplicate of https://github.com/neo4j/neo4j/issues/13185 which has now been fixed for the 5.9 release.

**Closed as completed by JonasHolgersson** 2023-06-01 09:11 UTC
Labels: bug, team-cypher
