### ISSUE TITLE
Slow / crashing queries when trying to make paged requests on large label

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#3125] opened 2014-09-22 20:02 UTC
I'm trying to implement find_in_batches functionality for the neo4j gem which would execute queries similar to this:

```
  MATCH (n:`TownlandStreet`) RETURN n ORDER BY n.uuid LIMIT 3000
  MATCH (n:`TownlandStreet`) WHERE n.uuid > {primary_key_offset} RETURN n ORDER BY n.uuid LIMIT 3000
  MATCH (n:`TownlandStreet`) WHERE n.uuid > {primary_key_offset} RETURN n ORDER BY n.uuid LIMIT 3000 
```

Where for the second and on queries the primary_key_offset param is set to the max string from the previous batch.  It's something like "0f1ba6ab-e9a5-486d-94d1-acc2f3796ed2" which is generated by Ruby's SecureRandom.uuid method.  We recently put this UUID functionality into the gem because we were told not to depend on the neo4j IDs because they are re-used and may shift around in future versions.

If you're not familiar with the concept from ActiveRecord, it allows users to iterate through the database without loading all nodes into memory.  In my case, I'm trying to implement this functionality so that I can use it in the searchkick gem to load my data into an elasticsearch instance so that I can do full-text queries on the data.

So this works great for labels with smaller numbers of nodes, and even works fine on my label which has 1.2 million nodes, but on my label with 8.9 million nodes, it hangs on the first query (and lots of alternative queries that I try to do in a similar way).

So, is this something that I can do in a better way?  Is this something that can be optimized?  Thanks!

**Comment by klaren** [comment] 2017-10-19 08:24
Queries can only use the index for evaluation of the `WHERE` clause. `ORDER BY` have to load all nodes matching the `WHERE` clause and then sort the set internally in memory before returning, and `LIMIT` does not help here.

It is on the current roadmap to have index back `ORDER BY` as well, which will make your queries only load the desired 3000 nodes and execute in a timely fashion.

I'm going to close this issue for now. If you have additional input feel free to reopen.

Thanks for your feedback!

**Comment by cheerfulstoic** [comment] 2017-10-19 18:17
;(

Shouldn't an issue stay open until it's fixed?  That way I could actually be notified when the change comes into a release.  It would make me a lot more excited about trying out an alpha / beta releases with the change

**Comment by systay** [comment] 2017-10-20 05:00
You are right, @cheerfulstoic. I see no reason for not keeping this open and closing it once these queries can use this new functionality.
We do want you excited! :)

**Comment by cheerfulstoic** [comment] 2017-10-20 17:10
❤️ Thank you!

**Comment by craigtaverner** [comment] 2018-11-05 10:23
Hi @cheerfulstoic, Neo4j 3.5 will have index-backed order by to a sufficient extent to support your idea. But I think that it would have worked to some extent in older versions, as long as you stop using `ORDER BY`.

This is what I think makes sense:

## Neo4j 3.4

With Neo4j 3.4 and earlier you can rely on the fact that index searches will return results in a reproducible order, although not a defined order. You can use a combination of `SKIP` and `LIMIT`. It is important to _NOT_ include an `ORDER BY` in the query:

```
MATCH (n:`TownlandStreet`) WHERE n.uuid > '' RETURN n SKIP 0 LIMIT 3000;
MATCH (n:`TownlandStreet`) WHERE n.uuid > '' RETURN n SKIP 3000 LIMIT 3000;
MATCH (n:`TownlandStreet`) WHERE n.uuid > '' RETURN n SKIP 6000 LIMIT 3000;
```

You need the `WHERE n.uuid > ''`  to ensure you get this index backed. The alternative is to skip the WHERE clause on all queries and get the order defined by the label-scan. But definitely do not mix and match queries with and without predicates like you did in the original example above, because you will be mixing and matching different ordering behaviours.

## Neo4j 3.5

With Neo4j 3.5 there is new support for index-backed order-by (you can try a recent beta release, or wait for the GA which should not be long):

```
MATCH (n:`TownlandStreet`) WHERE n.uuid > '' RETURN n ORDER BY n.uuid LIMIT 3000;
MATCH (n:`TownlandStreet`) WHERE n.uuid > {primary_key_offset} RETURN n ORDER BY n.uuid LIMIT 3000;
MATCH (n:`TownlandStreet`) WHERE n.uuid > {primary_key_offset} RETURN n ORDER BY n.uuid LIMIT 3000;
```

This time you are using an explicit `ORDER BY`, and the index will be told to produce the results in that order, and no re-ordering will be done by Cypher. As with the 3.4 example above you need to have a predicate on every single query in order to ensure you use the same index on every one. However, this time the predicate can include, as you suggest, the lower bound (from the previous page), which will cause the filtering to be done deep inside the index.

You could also use the `SKIP` approach I suggested for 3.4, but that moves the filtering higher up the stack, so is not as efficient as your idea of doing it in the index itself.

**Closed by craigtaverner** 2018-11-05 10:23 UTC
Labels: cypher, feature, team-cypher

**Comment by cheerfulstoic** [comment] 2018-11-05 13:46
🎉
