### ISSUE TITLE
DB crash after try to drop fulltext index contains duplicate label

### ISSUE THREAD

**Issue by y4nn0ff** [neo4j/neo4j#12290] opened 2019-09-05 15:14 UTC
Neo4j version: 3.5.8 community
Operating system: Debian 9
API/Driver: Neo4j desktop 

Steps to reproduce
Create 1 fulltext index with duplicate labels :

```
CALL db.index.fulltext.createNodeIndex(
                    "SysDesignationIndex2",
                    ['toto','tata','toto'],
                    ["sys_designation1"],
                    { analyzer: "french", eventually_consistent: "true" }
                )
```

Expected behavior
The index is created, and I can drop it without a problem

Actual behavior
The index is created, but I can't remove it.

I get this message when I try to drop it : 
`call db.index.fulltext.drop('SysDesignationIndex2')`

`Neo.DatabaseError.Transaction.TransactionCommitFailed: Could not apply the transaction to the store after written to log`

And into the log I get : 

```
2019-09-05 14:57:31.281+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Transaction.TransactionStartFailed]: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details., reference 61c1e5d7-0d12-4602-8283-a20cd7804c28. The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
org.neo4j.graphdb.TransactionFailureException: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
    at org.neo4j.graphdb.facade.spi.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:193)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:691)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:375)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI.beginTransaction(TransactionStateMachineV1SPI.java:139)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI.beginTransaction(TransactionStateMachineV1SPI.java:98)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:293)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
    at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
    at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
    at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
    at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
    at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
    at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
    at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
    at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
    at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
    at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:61)
    at org.neo4j.kernel.impl.api.KernelImpl.beginTransaction(KernelImpl.java:88)
    at org.neo4j.graphdb.facade.spi.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:186)
    ... 21 more
Caused by: org.neo4j.kernel.api.exceptions.TransactionApplyKernelException: Failed to apply transaction: Transaction #340 at log position LogPosition{logVersion=0, byteOffset=20807} {started 2019-09-05 14:57:24.896+0000, committed 2019-09-05 14:57:24.905+0000, with 1 commands in this transaction, authored by -1, with master id -1, lock session 138, latest committed transaction id when started was 339, additional header bytes:
15
DA
21
68
9A
33
E2
23}
    at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:301)
    at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:78)
    at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:51)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:716)
    at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:586)
    at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:178)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:469)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:329)
    at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
    at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
    at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
    ... 12 more
Caused by: java.lang.NullPointerException
    at org.neo4j.kernel.impl.api.store.SchemaCache$SchemaCacheState.removeSchemaRule(SchemaCache.java:372)
    at org.neo4j.kernel.impl.api.store.SchemaCache.removeSchemaRule(SchemaCache.java:164)
    at org.neo4j.kernel.impl.cache.BridgingCacheAccess.removeSchemaRuleFromCache(BridgingCacheAccess.java:51)
    at org.neo4j.kernel.impl.transaction.command.NeoStoreTransactionApplier.visitSchemaRuleCommand(NeoStoreTransactionApplier.java:183)
    at org.neo4j.kernel.impl.transaction.command.Command$SchemaRuleCommand.handle(Command.java:647)
    at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:61)
    at org.neo4j.kernel.impl.api.TransactionApplierFacade.visit(TransactionApplierFacade.java:35)
    at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:70)
    at org.neo4j.kernel.impl.api.TransactionToApply.accept(TransactionToApply.java:130)
    at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.apply(RecordStorageEngine.java:294)
    ... 22 more
```

And when I try to query the database I get : 
`call db.indexes()`

`Neo.DatabaseError.Transaction.TransactionStartFailed: The database has encountered a critical error, and needs to be restarted. Please see database logs for more details.`

We know it makes no sense to have duplicate labels into an index, but it can happen does something wrong. 

To avoid this issue, We have added checks into the code to prevent this.

best regards

**Comment by burqen** [comment] 2019-09-05 15:38
@y4nn0ff Hello, thank you for reporting.
Can you describe in more detail how you reproduce this. I fail to do so using the following sequence of cypher statements:

```
CALL db.index.fulltext.createNodeIndex(
 "SysDesignationIndex2",
 ['toto','tata','toto'],
 ["sys_designation1"],
 { analyzer: "french", eventually_consistent: "true" }
 )
```
```
CALL db.index.fulltext.createNodeIndex(
 "SysDesignationIndex",
 ['toto','tata','toto'],
 ["sys_designation"],
 { analyzer: "french", eventually_consistent: "true" }
 )
```
```
call db.index.fulltext.drop('SysDesignationIndex2')
```
Note that I don't use the same property for the second index creation because if I do I get
`Neo.ClientError.Schema.IndexAlreadyExists: There already exists an index `

**Comment by chrisvest** [comment] 2019-09-05 15:43
@burqen It's not two indexes. The problem is with one index that has duplicate labels.

**Comment by y4nn0ff** [comment] 2019-09-05 16:08
@burqen as say chrisvest, it's only one index with duplicate labels.

You're right, my description was bad (wrong copy/paste). I've edited it.

**Comment by burqen** [comment] 2019-09-06 07:54
@y4nn0ff Aah, I see. Yes, that make sense... Or... doesn't make sense, whichever way you look at it. In any case, it should not be possible to create an index with duplicate labels in the first place and this is indeed a bug. Thanks again for reporting 👍 
We'll look into this and come back with a solution.

**Comment by burqen** [comment] 2019-09-06 11:32
@y4nn0ff Solution has been identified and will be part of next patch release.

**Comment by burqen** [comment] 2019-09-18 09:58
@y4nn0ff PR that fix this issue has been merged now. With this fix it should not be possible to create indexes with duplicate labels / relationship types / properties any more and we should be able to correctly remove such indexes without getting a NPE.

**Closed as completed** 2020-02-21 14:21 UTC
Labels: bug, team-kernel, 3.5
