### ISSUE TITLE
TransactionAccessedConcurrently Exception on some nodes after the server throws a Java concurrent timeout exception

### ISSUE THREAD

**Issue by jschmidtWK** [neo4j/neo4j#9541] opened 2017-06-20 15:08 UTC
During use of a Neo4J HA Cluster, the cluster will sometime throw a Java java.util.concurrent.TimeoutException when handling a Transaction. After this, the nodes locked during this particular transaction are in an abnormal state and will throw a Neo.ClientError.Transaction.TransactionAccessedConcurrently Exception when subsequently updated with a query like `MATCH (record:Label) WHERE (record.Id = {p0}) SET record += {updatedRecord}`. The blocking transaction will never expire and keep throwing exceptions, even by new clients or new instances of the app connecting to the cluster.

However, on the same blocked node, a query like `MATCH (node:Label) WHERE (node.Id = {p0}) SET node._WriteLock = 1`, followed by `MATCH (node:Label) WHERE (node.Id = {p0}) SET node._WriteLock = 0`  will execute successfully, as will any pure MATCH-RETURN reading queries.

Restarting the master to force a master re-election solves the problem until the next java.util.concurrent.TimeoutException is thrown.

The problem happens randomly, about once every 36 hours, sometimes less than 12 hours of uptime of a particular master. This cluster is under a fairly constant load of 10-100 reads and/or writes per second. So far, issues have been happening regardless of current I/O load on the cluster.

This cluster has been operating under this average load for more than a year, the incident began to appear about five days ago.

**Neo4j Version:** 3.0.0  
**Operating System:** Ubuntu 14.04.4  
**API:** C# Community Driver

Java stacktrace for java.util.concurrent.TimeoutException :

`2017-06-20 12:32:07.742+0000 WARN  /db/data/transaction/2552350 java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
java.lang.RuntimeException: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.neo4j.server.rest.transactional.StatementDeserializer.<init>(StatementDeserializer.java:77)
        at org.neo4j.server.rest.transactional.TransactionFacade.deserializer(TransactionFacade.java:86)
        at org.neo4j.server.rest.web.TransactionalService.lambda$executeStatements$28(TransactionalService.java:190)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:121)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:234)
        at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:66)
        at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:475)
        at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:121)
        at org.codehaus.jackson.impl.ByteSourceBootstrapper.ensureLoaded(ByteSourceBootstrapper.java:507)
        at org.codehaus.jackson.impl.ByteSourceBootstrapper.detectEncoding(ByteSourceBootstrapper.java:129)
        at org.codehaus.jackson.impl.ByteSourceBootstrapper.constructParser(ByteSourceBootstrapper.java:224)
        at org.codehaus.jackson.JsonFactory._createJsonParser(JsonFactory.java:785)
        at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:561)
        at org.neo4j.server.rest.transactional.StatementDeserializer.<init>(StatementDeserializer.java:72)
        ... 34 more
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more`

**Comment by jschmidtWK** [comment] 2017-06-23 14:28
Our best guess so far is that, as the VMs are hosted on Azure, and the incidents happened during a DDOS attack on Skype (AFAIK hosted on Azure), this might be the result of a network slowdown that prevented the server from completely writing its response within 30 seconds. The subsequent Exception might have been mishandled and "locked" the transaction in a state that prevented it from being completed or timed-out.

**Comment by jschmidtWK** [comment] 2018-10-15 12:10
@digitalstain Hi, is the issue being closed meaning it was resolved ?

We are still seeing this behavior crop up from time to time on our cluster despite an upgrade to 3.3.0.

**Comment by digitalstain** [comment] 2018-10-15 12:27
No, apologies, I interpreted your last comment as you having found the cause. I'll revert this to open.

**Comment by zhenlineo** [comment] 2018-11-29 10:09
Hi @jschmidtWK ,

Is it true that you are using the REST `/transaction/{id}` endpoint to execute the queries you shared? Will it help if you rollback the transaction after it fails?

Does this error only happen in a HA cluster? Can you also try to simulate in a single instance Neo4j server to see if you also receive the same issue?

Cheers,
Zhen

**Comment by jschmidtWK** [comment] 2018-12-03 11:11
Hi Zhen,
We are using the Neo4J community client (https://github.com/Readify/Neo4jClient/) which, AFAIK, targets the transaction endpoint.

Under normal circumstances, no transaction is left open, they are either committed or rolled-back.

I've only seen this error on an HA cluster, never on a standalone server.

Best Regards,
Jonathan

**Comment by RagnarW** [comment] 2018-12-11 12:23
Hi @jschmidtWK 

Could you verify that this is still an issue on 3.5?

**Comment by jschmidtWK** [comment] 2018-12-19 15:28
As we are currently transitioning to Causal clustering and the error, while crippling, is extremely uncommon, I'm not sure I'll be able to get back to you on this test. We will upgrade to 3.5 and I'll let you know if we encounter it or switch to Causal, whichever comes first.

**Comment by technige** [comment] 2020-01-02 15:33
Closing due to tumbleweed. Please reopen if tumbleweed blows away.

**Closed as completed by technige** 2020-01-02 15:33 UTC
Labels: team-cluster, team-drivers

**Comment by jschmidtWK** [comment] 2020-01-06 09:17
My apologies for not getting back to you. We transitioned successfully to Causal Clustering and haven't encountered the issue again since.
