### ISSUE TITLE
Generating nodes using "unwind range(...) create (...)" fails with "Error: undefined - undefined"

### ISSUE THREAD

**Issue by dmarkovitz** [neo4j/neo4j#7495] opened 2016-07-03 08:23 UTC
Hi

I'm trying to generate nodes using the following code:

`unwind range(1,700000) as id create (:t700k{id:id})`

1.
Generating 100K-600K nodes finishes successfully but the execution time seems to be exponential which is obviously an issue with scalability. 
Is this an expected behavior?

> Added 100000 labels, created 100000 nodes, set 100000 properties, statement executed in 1694 ms.
> Added 200000 labels, created 200000 nodes, set 200000 properties,
>  statement executed in 3478 ms.
> Added 300000 labels, created 300000 nodes, set 300000 properties, statement executed in 4622 ms.
> Added 400000 labels, created 400000 nodes, set 400000 properties, statement executed in 7240 ms.
> Added 500000 labels, created 500000 nodes, set 500000 properties, statement executed in 19388 ms.
> Added 600000 labels, created 600000 nodes, set 600000 properties, statement executed in 56200 ms.

2.
Generating 700K nodes fails with the following error - 
"Error: undefined - undefined"

There are also no [ERROR] records in C:\Users\dmarkovitz\Documents\Neo4j\default.graphdb\logs\debug.log
[debug.log.txt](https://github.com/neo4j/neo4j/files/344935/debug.log.txt)
### version

I'm working from the web browser

neo4j-community_windows-x64_3_0_3.exe
Neo4j Browser version 1.1.6
COMMUNITY EDITION 3.0.3
### systeminfo

OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 9020
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3401 Mhz
BIOS Version:              Dell Inc. A05, 12/5/2013
Total Physical Memory:     8,134 MB
Available Physical Memory: 864 MB
Virtual Memory: Max Size:  16,267 MB
Virtual Memory: Available: 6,599 MB
Virtual Memory: In Use:    9,668 MB

Thanks

Dudu

**Comment by chrisvest** [comment] 2016-07-03 11:51
This looks like a duplicate of #7494

**Closed as completed by chrisvest** 2016-07-03 11:51 UTC
