### ISSUE TITLE
SyntaxException while importing dumped Cypher

### ISSUE THREAD

**Issue by vejuhust** [neo4j/neo4j#2745] opened 2014-07-26 15:55 UTC
I used Neo4j 2.1.2 to dump my whole DB:
```
bin/neo4j-shell -host localhost -readonly -config conf/neo4j.properties -c "dump" > ./backup/$(date +"%y%m%d_%H%M%S").cypher
```
And I got this:
```
begin
create index on :`Line`(`guid`)
create (_0:`Line` {`direction`:"钟南街首末站西=>车坊首末站", `guid`:"9f1f41ea-8939-492b-a969-028ef588857b", `name`:"128"})
create (_1:`Line` {`direction`:"车坊首末站=>钟南街首末站", `guid`:"7e5f894b-db9a-43da-b5eb-8c6a170db5b8", `name`:"128"})
create _0-[:`SIBLING_LINE`]->_1
create _1-[:`SIBLING_LINE`]->_0
;
commit
```
But when I tried to import this from a new DB:
```
bin/neo4j-shell -host localhost -port 1337 -config conf/neo4j.properties -file backup/140726_234717.cypher 
bin/neo4j-shell -path /Users/Vej/Documents/Neo4j/neo4j-enterprise-2.1.2/data/graph.db/ -file backup/140726_225731.cypher
```
I always got this error:
```
ERROR (-v for expanded information):
	SyntaxException: Invalid input 'c': expected whitespace, comment, ';' or end of input (line 2, column 1)
"create (_12868:`Line` {`direction`:"钟南街首末站西=>车坊首末站", `guid`:"9f1f41ea-8939-492b-a969-028ef588857b", `name`:"128"})"
 ^
```
If I only keep this first create and remove other creates, it succeeds. It looks like a bug in your dump or import?

**Comment by jakewins** [comment] 2015-12-06 16:35
Closing as duplicate of #2625

**Closed by jakewins** 2015-12-06 16:35 UTC
