### ISSUE TITLE
Query breakage when using timestamp() along OPTIONAL clause

### ISSUE THREAD

**Issue by nosoccomtothom** [neo4j/neo4j#12128] opened 2019-01-08 14:06 UTC
Hi,
Coming from #12099 , when performing a query using timestamp function along an OPTIONAL clause the query breaks.

- Neo4j version: 3.5.1
- Operating system: Ubuntu 16.04.2 LTS
- API/Driver: Neo4j Browser 3.2.13
- Expected behavior
Return the proper results.
- Actual behavior
The query breaks (although works on CYPHER 3.1)

```
profile 
                WITH timestamp() as ts,'(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

Dump on debug.log

```
2019-01-08 13:51:30.543+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Unknown variable `ts`., reference 543c8aad-5943-4079-94eb-7bf316d3d6fe.
2019-01-08 13:51:30.543+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Unknown variable `ts`., reference 543c8aad-5943-4079-94eb-7bf316d3d6fe. Unknown variable `ts`.
org.neo4j.graphdb.NotFoundException: Unknown variable `ts`.
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.Variable$$anonfun$apply$1.apply(Variable.scala:30)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.Variable$$anonfun$apply$1.apply(Variable.scala:30)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at org.neo4j.cypher.internal.runtime.interpreted.MapExecutionContext.getOrElse(ExecutionContext.scala:77)
	at org.neo4j.cypher.internal.runtime.interpreted.commands.expressions.Variable.apply(Variable.scala:30)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$6$$anonfun$apply$1.apply(EagerAggregationPipe.scala:62)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$6$$anonfun$apply$1.apply(EagerAggregationPipe.scala:62)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$6.apply(EagerAggregationPipe.scala:62)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$6.apply(EagerAggregationPipe.scala:62)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$internalCreateResults$1.apply(EagerAggregationPipe.scala:119)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe$$anonfun$internalCreateResults$1.apply(EagerAggregationPipe.scala:118)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.profiler.ProfilingIterator.foreach(Profiler.scala:203)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:118)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:76)
	at org.neo4j.cypher.internal.runtime.interpreted.pipes.PipeWithSource.createResults(Pipe.scala:72)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.BaseExecutionResultBuilderFactory$BaseExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:61)
	at org.neo4j.cypher.internal.compatibility.InterpretedRuntime$InterpretedExecutionPlan.run(InterpretedRuntime.scala:84)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:205)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:224)
	at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:102)
	at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:300)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:269)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
	at org.neo4j.bolt.v3.runtime.ReadyState.processRunMessage(ReadyState.java:85)
	at org.neo4j.bolt.v3.runtime.ReadyState.processUnsafe(ReadyState.java:56)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
The query performs without issues using `CYPHER 3.1` .

Made some discovery, though, as it might not be related actually to the timestamp function although is the thrown error type. 
When modifying the query removing the OPTIONAL clause to

```
profile 
                WITH timestamp() as ts,'(?i)Name' as almost_name
                   MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

 it runs as expected.
Likewise, if the same original query the timestamp reference is removed, then no error is thrown either.

```
profile 
                WITH '(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH  n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

It is then my understanding that somehow the use of timestamp() along with OPTIONAL is causing the breakage.

Thanks for the support.

**Comment by Hunterness** [comment] 2019-01-09 07:47
Hi, since it's still there in 3.5.1 we will look into it :)

**Comment by Lojjs** [comment] 2019-01-15 12:29
@nosoccomtothom  I still cannot reproduce your error neither on 3.5.0 or 3.5.1 with an empty database. If you can send me which plans you are getting for the queries that does work and if possible a database/small example dataset for which the error occurs that would be helpful.

**Comment by nosoccomtothom** [comment] 2019-01-16 10:17
Hi @Lojjs 
I have performed the tests on the 3.4.11 Enterprise sandbox [https://neo4j.com/sandbox-v2/] with similar results when combining timestamp() and OPTIONAL MATCH (Neo.DatabaseError.General.UnknownError: key not found: ts).

I tried as well on the 3.5alpha09 (3.5.0 Enterprise) and worked. Bear into mind I use the Community Edition.

You may create some sample data as

merge (:Artist {name:'John Smith'})-[:HAS]->(:Alternate {name:'Jon Smith'})
merge (:Artist {name:'Victoria Moore'})-[:HAS]->(:Alternate {name:'Victoria More'})

On the 3.5.1 Community Edition I get:

**ts and MATCH query**
[ts_match_query.txt](https://github.com/neo4j/neo4j/files/2763688/ts_match_query.txt)
![ts_match](https://user-images.githubusercontent.com/391717/51243056-d6661280-1981-11e9-91fd-458c926c23b1.png)


**Name and OPTIONAL MATCH query**
[name_optional_match_query.txt](https://github.com/neo4j/neo4j/files/2763686/name_optional_match_query.txt)
![name_optional_match](https://user-images.githubusercontent.com/391717/51243039-cb12e700-1981-11e9-8e02-e6cbf5b5539d.png)


**Name, ts and OPTIONAL MATCH 3.1 query**
[cypher31_ts_optional_match.txt](https://github.com/neo4j/neo4j/files/2763687/cypher31_ts_optional_match.txt)
![cypher31_ts_name_optional](https://user-images.githubusercontent.com/391717/51243103-f39ae100-1981-11e9-9092-080aa74f3051.png)




I realise there could be some optimisation to the query not to perform a full scan on the whole database though haven't tackled it yet. Any suggestions are welcome!

Thanks for looking into it and let me know if I shall provide any further details.

**Comment by Lojjs** [comment] 2019-01-22 14:39
@nosoccomtothom Since the error seems to be thrown at runtime, can you try to prepend the broken query with `explain` instead of `profile` and send me the plan you get?

Because with the example data you provided, I still cannot reproduce any error for browser version 3.2.13 and server 3.5.1 community. With that data, I get this plan:

![plan](https://user-images.githubusercontent.com/7222590/51537442-dc129b00-1e4e-11e9-8bba-65fd3c432fd4.png)


and this result:

```
almost_name | label | n     | num_almost | ts
"(?i)Name"    | null    | null | 0                   | 1548162236297
```

**Comment by nosoccomtothom** [comment] 2019-01-22 14:51
Hi @Lojjs 

Please find attached the explain output and the warning thrown.

[explain_name_optional.txt](https://github.com/neo4j/neo4j/files/2783248/explain_name_optional.txt)

The warning thrown is
```
The provided property key is not in the database
One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: epochMillis)

```

Using Browser 3.2.15 on 3.5.1 community
![explain_name_optional](https://user-images.githubusercontent.com/391717/51543261-74178100-1e5d-11e9-86d0-83afb58f5972.png)

**Comment by Lojjs** [comment] 2019-02-05 12:10
@nosoccomtothom Thanks for the report of the `epochMillis` warning. It turned out that this warning is due to how we implement the timestamp function internally and is always thrown when calling the timestamp function in 3.5. That is of course not correct behaviour, so I have merged a fix for that which will be included in 3.5.3.

Unfortunately, this is not related to your original problem. I have looked through the plans that you have sent me and I cannot see anything that looks odd. I have also looked in our code on the place that throws error according to your stacktrace and my only conclusion is the the `ts` variable is not present in the context of the eager aggregation of some reason. But I still cannot reproduce it with the setup that you provided:

```
merge (:Artist {name:'John Smith'})-[:HAS]->(:Alternate {name:'Jon Smith'})
merge (:Artist {name:'Victoria Moore'})-[:HAS]->(:Alternate {name:'Victoria More'})
```

on 3.5.1 community, so I don't know why that may be.

Without any dataset where I am able to reproduce the error I'm afraid I cannot do much more.

**Comment by nosoccomtothom** [comment] 2019-02-05 13:58
Hi @Lojjs 
Again let me thank your support. I really appreciate you diving into the details. I tend o think it might all be related to the way OPTIONAL MATCH handles variables.

```
WITH timestamp() as ts,'(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

The example before fails.

If we try to bypass the `epochMills` so to define a constant for the 'ts' variable, the same error appears.`epochMills` then has nothing to do with the error as you pointed out on the previous message.

```
WITH 1234 as ts,'(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

`Neo.DatabaseError.General.UnknownError: Unknown variable `ts``

When removing the `ts` variable from the second `WITH`, everything works fine.

```
WITH 1234 as ts,'(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH  n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

Could it all be that `OPTIONAL MATCH` modifies the variable scope and as it is not fetching/using the ts variable, it vanishes `ts` from the scope?

When defining ts on the second WITH, the query works as expected.

```
WITH '(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH  1234 as ts, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```


Also with epochMills

```
WITH '(?i)Name' as almost_name
                     OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
                    WITH timestamp() as ts, n, count(n) as num_almost, labels(n) as label, almost_name
                    return *
```

With results

```

almost_name | label | n | num_almost | ts
-- | -- | -- | -- | --


"(?i)Name"	["Artist"]	
{
  "name": "Name",
  "update ts": 1544454012759,
  "start ts": 1544454012759
}
1	1549374768645

```

Thanks again.
If you fancy giving it another try on how OPTIONAL MATCH handles the variables in the scope would be great although I understand the situation.

**Comment by Lojjs** [comment] 2019-02-20 08:44
Can you confirm that if you open an **empty** 3.5.1 community instance, run the 2 lines of setup query that you sent me 

```
merge (:Artist {name:'John Smith'})-[:HAS]->(:Alternate {name:'Jon Smith'})
merge (:Artist {name:'Victoria Moore'})-[:HAS]->(:Alternate {name:'Victoria More'})
```

and then run

```
WITH timestamp() as ts,'(?i)Name' as almost_name
OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
return *
```

or

```
WITH 1234 as ts,'(?i)Name' as almost_name
OPTIONAL MATCH (n) WHERE (n:Artist OR n:Alternate) AND (n.name=~almost_name OR n.name='Name')
WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
 return *
```
you can see the error?  If not, you must have something else in your setup that you haven't told me about, e.g. other data or indexes. If you cannot send me any data (your real data set or an example one where this error does occur) within 2 weeks, I will unfortunately have to close this issue for now.

**Comment by nosoccomtothom** [comment] 2019-02-21 16:13
Hi @Lojjs 
Thanks for your interest.
I tried on a fresh 3.5.1 Community environment and with those two records worked fine.
I have removed on my local database the impacted indexes and rebuilt them with no change.
Sadly the current database is around 17Gb so is quite challenging to pass you all the data.
Tried reducing the involved nodes only to 'Artist' and the error kept appearing but didn't whtn using 'Alternate'.


```
WITH timestamp() as ts,'(?i)Name' as almost_name
OPTIONAL MATCH (n) 
WHERE (n:Artist) AND (n.name=~almost_name OR n.name='Name')
WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
return *;
Neo.DatabaseError.General.UnknownError: Unknown variable `ts`.

```

```
WITH timestamp() as ts,'(?i)Name' as almost_name
OPTIONAL MATCH (n) 
WHERE (n:Alternate) AND (n.name=~almost_name OR n.name='Name')
WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
return *;

╒═════════════╤═══════╤════╤════════════╤═════════════╕
│"almost_name"│"label"│"n" │"num_almost"│"ts"         │
╞═════════════╪═══════╪════╪════════════╪═════════════╡
│"(?i)Name"   │null   │null│0           │1550757975602│
└─────────────┴───────┴────┴────────────┴─────────────┘

```

```
CYPHER 3.1
WITH timestamp() as ts,'(?i)Name' as almost_name
OPTIONAL MATCH (n) 
WHERE (n:Artist) AND (n.name=~almost_name OR n.name='Name')
WITH ts, n, count(n) as num_almost, labels(n) as label, almost_name
return *;
╒═════════════╤══════════╤══════════════════════════════════════════════════════════════════╤════════════╤═════════════╕
│"almost_name"│"label"   │"n"                                                               │"num_almost"│"ts"         │
╞═════════════╪══════════╪══════════════════════════════════════════════════════════════════╪════════════╪═════════════╡
│"(?i)Name"   │["Artist"]│{"name":"Name","update ts":1544454012759,"start ts":1544454012759}│1           │1550758512411│
└─────────────┴──────────┴──────────────────────────────────────────────────────────────────┴────────────┴─────────────┘

```

I then thought it could be due to the lack of correctness of the database (inconsistencies on Artist nodes)? Strangely, though, the query performs without any issue on CYPHER 3.1.

Ran neo4j-admin check-consistency with the results:

```
2019-02-21 14:20:37.121+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Selected RecordFormat:StandardV3_4[v0.A.9] record format from store /var/lib/neo4j/data/databases/graph.db
2019-02-21 14:20:37.124+0000 INFO [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_4[v0.A.9]
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.........Checking node and relationship counts
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
```

Looks there are no inconsistencies although Artist nodes hide something …
If you suggest any data maintenance task to check the consistency of 'Artist' nodes I would certainly appreciate.

Please close this issue as it might not be related to any feature of the tool but inconsistency of the database.
Once again, I would like to thank your support and attention.

**Comment by craigtaverner** [comment] 2019-03-13 15:11
Is it possible to share your database with us for us to try debug? We have created an S3 bucket for you to upload to, which will handle that size database. Please message me directly on the neo4j-users.slack.com channel and I will share the bucket address with you for this purpose. My slack name is 'craig.taverner'.

**Comment by craigtaverner** [comment] 2019-03-26 10:14
Since we cannot reproduce this without data, we're closing the issue. If this becomes a problem again, please re-open the issue and provide sample data.

**Closed as completed by craigtaverner** 2019-03-26 10:14 UTC
Labels: cypher, team-cypher
