### ISSUE TITLE
MemoryPoolOutOfMemoryError for 5.2.0

### ISSUE THREAD

**Issue by tholiebig** [neo4j/neo4j#13008] opened 2022-12-14 17:03 UTC
**Neo4j Version:** 5.2.0
**APOC Version:** 5.2.1

I experience an error for 5.2.0 which did not occur with 5.1.0 or 4.4.X for the attached Cypher query ([import-query.txt](https://github.com/neo4j/neo4j/files/10230038/import-query.txt)) that imports the attached JSON document ([obfuscated.json.zip](https://github.com/neo4j/neo4j/files/10230046/obfuscated.json.zip)) with the help of APOC.

neo4j.conf:
```
dbms.security.procedures.allowlist=apoc.*,gds.*
dbms.security.procedures.unrestricted=jwt.security.*,apoc.*
server.memory.heap.initial_size=2g
server.memory.heap.max_size=6g
server.memory.pagecache.size=4g
```

apoc.conf:
```
apoc.import.file.enabled=true
apoc.import.file.use_neo4j_config=false
```
Error:
```
Neo.TransientError.General.MemoryPoolOutOfMemoryError
The allocation of an extra 46,5 GiB would use more than the limit 4,2 GiB. Currently using 873,6 MiB. dbms.memory.transaction.total.max threshold reached
```

**Comment by tholiebig** [comment] 2022-12-16 10:43
Also occurs in 5.3.0 Enterprise

**Comment by burqen** [comment] 2022-12-16 13:50
Hello @tholiebig ! Thank you for reporting. In 5.2 the default value for `dbms.memory.transaction.total.max` was changed from "unlimited" to 70% of heap to reduce the risk of `java.lang.OutOfMemoryError`. You will get back the old behaviour by setting `dbms.memory.transaction.total.max=0` (0 means unlimited).

See https://neo4j.com/release-notes/database/neo4j-5/ 
```
New default value 70% of heap for ‘dbms.memory.transaction.total.max’ to reduce the likelihood of memory intensive transactions from running out of memory.
```

**Comment by burqen** [comment] 2022-12-16 14:50
I was a little too fast there @tholiebig. The problem is probably not the default value of the setting but the large allocation number. Can you try to run your case with assertions enabled? This will verify that the memory counters are reset correctly. Run with  `-ea` flag to enable assertions.

**Comment by tholiebig** [comment] 2022-12-16 15:06
Hi @burqen Thanks for the quick response. I was able to run the import with the `dbms.memory.transaction.total.max=0` setting you suggested.
Do you want me to run this setting with the `-ea` flag?

**Comment by burqen** [comment] 2022-12-16 15:50
Thanks for reporting back @tholiebig 
I thought that the 70% corresponded to the 4,2 GiB in the error message and then the 45,5 GiB would not fit in 100%, so I'm a bit surprised that it worked to be honest. Did you have another limit set on that setting before changing it to `0`?

Anyway, iIf it works it works. No need to investigate further 👍 I'll close this issues now if you don't mind?

**Comment by tholiebig** [comment] 2022-12-16 15:59
No I haven't set any other limit. Yes, I'm also puzzled a bit.
I don't mind if you close this ticket.

**Comment by luzcalero** [comment] 2023-01-09 17:08
What would I do if I'm using AuraDS and experiencing this problem? Please don't close the ticket as I'm experiencing something very similar, but I'm not sure how I can modify my dbms to set the memory limit to 0 (unlimited)

**Comment by burqen** [comment] 2023-01-10 08:39
Hello @luzcalero, thank you for reporting! Since you are using Aura you have support included. Please turn to [aura.support.neo4j.com](http://aura.support.neo4j.com/) for further assistance.

**Closed as completed by burqen** 2023-01-10 08:39 UTC
Labels: bug, team-kernel

**Comment by vincrichard** [comment] 2023-03-17 06:10
Hello @burqen, I just want to highlight that the documentation has not been updated with this information. At least from this link, I assume the default was still unlimited.
https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_db.memory.transaction.max

**Comment by burqen** [comment] 2023-03-17 09:10
@vincrichard Thank you for reporting! I guess you meant to link to this setting here https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.memory.transaction.total.max, which indeed has the wrong default value. I will bring this to our documentations team.
