### ISSUE TITLE
Relationship, where condition for property existence and neo4j id check, cannot be done togheter

### ISSUE THREAD

**Issue by RobertoSannino** [neo4j/neo4j#12787] opened 2021-11-16 16:04 UTC
Running a query using conditions on a relationship, both for property existence and id check, as the following one:

`MATCH p=()-[r:KNOWS]->() WHERE id(r) = 0 AND r.prop IS NOT NULL RETURN p`

raise a **Neo.DatabaseError.General.UnknownError**:
`'boolean org.neo4j.cypher.operations.CursorUtils.relationshipHasProperty(org.neo4j.internal.kernel.api.Read, org.neo4j.internal.kernel.api.RelationshipScanCursor, long, org.neo4j.internal.kernel.api.PropertyCursor, int)'`

This only happens if the id condition is true and if the property is checked for existence (is null, is not null, exists), while if the searched id has no match, or the condition is for instance an equality one, the query runs without error.

**Neo4j Version:** 4.2.3 (docker-image)
**Operating System:** Mac OS bigSur 11.6
**API:** Docker

### Steps to reproduce
1. Create a new dataset
2. Run populate query: `CREATE (:Person)-[:KNOWS {prop: 'x'}]->(:Person)`
3. Run search query: ` MATCH p=()-[r:KNOWS]->() WHERE id(r) = 0 AND r.prop IS NOT NULL RETURN p`

### Expected behavior
The query should be performed without problems and should match the results

### Actual behavior
The query raise the mentioned error when the id is matched succesfully

**Comment by mnd999** [comment] 2021-11-17 11:24
I think this is already fixed in a later 4.2.x, I was not able to reproduce on 4.2.7 or 4.3.7. If you need to stick with 4.2.3, I think CYPHER RUNTIME=slotted should also work as a workaround.

**Comment by RobertoSannino** [comment] 2021-11-18 11:02
Using slotted runtime solved the issue, however it would be nice to have the CYPHER_RUNTIME_DEFAULT property both in config and docker env variable

**Comment by mnd999** [comment] 2022-01-19 13:17
Closing as this is fixed in latest patches.

**Closed as completed by mnd999** 2022-01-19 13:17 UTC
Labels: bug, team-cypher
