### ISSUE TITLE
randomUUID not working with Centos 6

### ISSUE THREAD

**Issue by folterj** [neo4j/neo4j#12116] opened 2018-12-22 18:58 UTC
randomUUID() not recognised after yum install of NEO4J (community edition) on CentOS6

- Neo4j version: 3.5.1
- Operating system: CentOS 6

Reproduce: after yum install, perform CALL dbms.functions() to assert randomUUID is not listed

**Comment by pontusmelke** [comment] 2019-01-09 07:35
Hi @folterj 
I tried on fresh install on fedora 29 and it is listed and I can call the function, are you sure you are running the correct version of Neo4j.

This is what I did:
- Follow the instructions to set up [repo](https://neo4j.com/docs/operations-manual/current/installation/linux/rpm/)
- run `>yum install neo4j-3.5.1` as root
- start `neo4j`
- go to neo4j browser or cypher-shell and run  `CALL dbms.functions()`

Best Regards,
Pontus

**Comment by folterj** [comment] 2019-01-09 10:37
Correct, Neo4j version 3.5.1 on CentOS 6.
I used 'yum install neo4j', and confirmed installed version after completion.
As this was a major issue with no apparent solution we decided to move to CentOS 7.

**Comment by pontusmelke** [comment] 2019-01-09 14:26
Sorry I just saw your post on the community site. I'll continue to investigate.

**Comment by pontusmelke** [comment] 2019-01-09 16:12
We have checked on CentOS 6 as well now and we are not able to reproduce the issue. Maybe something was wrong with your installation or something I am unaware of was fixed somehow. Anyway I'll close this issue since we cannot reproduce it and you already moved on to CentOS 7. However do not hesitate to reopen this issue or open a new one if you're seeing more issues.

Best Regards,
Pontus

**Closed as completed** 2019-01-09 16:12 UTC
Labels: team-kernel
