### ISSUE TITLE
Execution of complex query fails using the slotted runtime

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j#12441] opened 2020-03-30 11:32 UTC
### Environment

- Neo4j version: 4.0.1 Enterprise, default runtime (slotted)
- Operating system: Ubuntu 18.04
- JDK: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
- API/Driver: web UI

### Steps to reproduce

The following query fails:

```
CALL {
    MATCH (pX:Person)
    RETURN pX
}
WITH collect(pX) AS pXs
UNWIND pXs AS p1
MATCH
  (p1)-[:HAS_INTEREST]->(t:Tag),
  (p1)-[:KNOWS*1..2]-(p2)
RETURN p1, count(DISTINCT t) AS numTags
```

The error is:

```console
Neo.DatabaseError.Statement.ExecutionFailed
Tried overwriting already taken variable name p1 as LongSlot(0,false,Node) (was: RefSlot(1,true,Any))
```

Remarks:
* I was originally working on an LDBC dataset but the error can be reproduced in an empty database.
* I tried to trim down the query as much as possible, however, all of the clauses/functions in the query (subquery, `UNWIND`, `count` + `DISTINCT`, `KNOWS*1..2`) are necessary to reproduce this error.
* As the error message suggests, the error occurs in the `slotted` runtime, and putting `CYPHER runtime=interpreted` at the start of the query causes the error to go away. However, the `pipelined` runtime also fails with the same error.

**Comment by sherfert** [comment] 2020-04-06 07:10
We merged a fix for this, which will be available in the 4.0.4 release.

**Closed as completed by sherfert** 2020-04-06 07:10 UTC
Labels: bug, cypher

**Comment by andygout** [comment] 2021-03-30 18:47
I have encountered this error, both using the Neo4j Desktop browser and the [`neo4j-driver`](https://www.npmjs.com/package/neo4j-driver) npm package (as part of a Node.js application).

### Environment
- Neo4j version: 4.2.1 Community, default runtime (`slotted`)
- Neo4j Desktop 1.4.1
- Operating system: macOS Catalina Version 10.15.7

### Steps to reproduce

Clear Neo4j database:
`MATCH (n) DETACH DELETE n RETURN 'done'`

Add a single person node:
`CREATE (p:Person { uuid: 'c771ad24-24ca-4002-ab8f-17719e4c32dc', name: 'John Doe' }) RETURN p`

Set params to use the person's `uuid` value:
`:params { uuid: 'c771ad24-24ca-4002-ab8f-17719e4c32dc' }`

The following query will then fail:
```
MATCH (person:Person { uuid: $uuid })

OPTIONAL MATCH (person)<-[:WRITTEN_BY|USES_SOURCE_MATERIAL*1..2]-(material:Material)

WITH person, COLLECT(DISTINCT(material)) AS materials

UNWIND (CASE materials WHEN [] THEN [null] ELSE materials END) AS material

	OPTIONAL MATCH (person)<-[writerRel:WRITTEN_BY]-(material:Material)

	OPTIONAL MATCH (person)<-[:WRITTEN_BY]-(:Material)<-[sourcingMaterialRel:USES_SOURCE_MATERIAL]-(material)

	RETURN person, material
```

The error is:
```
ERROR Neo.DatabaseError.Statement.ExecutionFailed
Tried overwriting already taken variable name '  material@246' as LongSlot(1,false,Node) (was: RefSlot(1,true,Any))
```

### Remarks:
- For simplicity, the query has been abridged as much as possible from a longer query.
- The error stops appearing once more nodes and relationships are added to the database, although repeating the process of purging the database and re-adding the data in the same order will see the error cease at different stages, i.e. the error is not consistent in terms of being resolved by the presence of specific nodes and/or relationships.
- Runtime:
  - The error occurs in the default `slotted` runtime
  - Putting `CYPHER runtime=interpreted` at the start of the query causes the error to go away
  - Putting `CYPHER runtime=pipelined` fails with the same error, and even fails after sufficient data has been added to the database to stop the error happening on the default `slotted` runtime

Will a fix for this issue be included in a future release?

Let me know if you require further information.

Thank you 👍

**Comment by andygout** [comment] 2021-03-31 07:41
The issue can be fixed by removing the label in this line:
`OPTIONAL MATCH (person)<-[writerRel:WRITTEN_BY]-(material:Material)`

so that it looks like:
`OPTIONAL MATCH (person)<-[writerRel:WRITTEN_BY]-(material)`

The `:Material` label was used in the initial `MATCH` statement used to identify materials that were then collected into `materials`, so it is a given that each `material` in the `UNWIND` statement will have a `:Material` label, meaning it need not be applied again (and in fact causes this error if you do).

Credit to @katsuraku for the solution. 👍
