### ISSUE TITLE
Import via py2neo fails in 2.3.2 with `neostore.counts.db` getting unmapped

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#6787] opened 2016-03-25 01:37 UTC
I am using py2neo 2.0.8 to import my network into neo4j 2.3.2. The network has ~50 thousand nodes and 3 million relationships. I am running into an intermittent error that `File has been unmapped` regarding `graph.db/neostore.counts.db.a`. The error happens in only ~20% of the imports. [Here is my notebook](https://github.com/dhimmel/integrate/blob/e5ebbec3a7b96cc05b7a01a8d5776d6d94ed192a/neo4j-import.ipynb) where I import 6 networks to 6 separate neo4j servers in parallel, with one import failing. The failure happens midway, so the final database is incomplete. Note that I specified `keep_logical_logs=false` in `neo4j.properties` to reduce space.

I believe the `File has been unmapped` error must come from [this line](https://github.com/neo4j/neo4j/blob/6645e641527d32da1aefa61b80bee8c689a43b36/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java#L371) in `community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java`.
## Error in Python

The error that gets thrown in Python is:

```
File has been unmapped: /home/dhimmels/Documents/serg/rephetio/construct/integrate/neo4j/neo4j-community-2.3.2_hetio-ind_perm-2/data/graph.db/neostore.counts.db.a
```
## `messages.log`

The first 3 lines in `messages.log` below are believed to be okay (making up the vast majority of the log). I believe the process starts to derail on line 4. The shutdown is called by my python script due to an error in the py2neo import. The last line before this shutdown registers in the log is `GC Monitor: Application threads blocked for 222ms.`.

```
2016-03-24 08:54:50.600+0000 INFO  [o.n.c.i.CypherCompiler] Discarded stale query from the query cache: Query(None,SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Identifier(n)),List(),None,false)))),List(),Some(Where(And(Equals(Property(Identifier(n),PropertyKeyName(identifier)),Parameter(V)),HasLabels(Identifier(n),List(LabelName(Disease))))))), Return(false,ReturnItems(false,List(AliasedReturnItem(Identifier(n),Identifier(n)), AliasedReturnItem(FunctionInvocation(FunctionName(labels),false,Vector(Identifier(n))),Identifier(labels(n))))),None,None,Some(Limit(SignedDecimalIntegerLiteral(1)))))))
2016-03-24 08:54:50.656+0000 INFO  [o.n.c.i.ServerExecutionEngine] Discarded stale query from the query cache: CYPHER 2.3 MATCH (n:MolecularFunction {identifier:{V}}) RETURN n,labels(n) LIMIT 1
2016-03-24 08:54:50.657+0000 INFO  [o.n.c.i.CypherCompiler] Discarded stale query from the query cache: Query(None,SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(Some(Identifier(n)),List(),None,false)))),List(),Some(Where(And(Equals(Property(Identifier(n),PropertyKeyName(identifier)),Parameter(V)),HasLabels(Identifier(n),List(LabelName(MolecularFunction))))))), Return(false,ReturnItems(false,List(AliasedReturnItem(Identifier(n),Identifier(n)), AliasedReturnItem(FunctionInvocation(FunctionName(labels),false,Vector(Identifier(n))),Identifier(labels(n))))),None,None,Some(Limit(SignedDecimalIntegerLiteral(1)))))))
2016-03-24 08:54:51.093+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Starting check pointing...
2016-03-24 08:54:51.093+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Starting store flush...
2016-03-24 08:54:51.094+0000 INFO  [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 2820 to [/home/dhimmels/Documents/serg/rephetio/construct/integrate/neo4j/neo4j-community-2.3.2_hetio-ind_perm-2/data/graph.db/neostore.counts.db.b], from [/home/dhimmels/Documents/serg/rephetio/construct/integrate/neo4j/neo4j-community-2.3.2_hetio-ind_perm-2/data/graph.db/neostore.counts.db.a].
2016-03-24 08:54:51.099+0000 INFO  [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 2820 to [/home/dhimmels/Documents/serg/rephetio/construct/integrate/neo4j/neo4j-community-2.3.2_hetio-ind_perm-2/data/graph.db/neostore.counts.db.b], from [/home/dhimmels/Documents/serg/rephetio/construct/integrate/neo4j/neo4j-community-2.3.2_hetio-ind_perm-2/data/graph.db/neostore.counts.db.a].
2016-03-24 08:54:51.815+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Store flush completed
2016-03-24 08:54:51.815+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Starting appending check point entry into the tx log...
2016-03-24 08:54:52.041+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Appending check point entry into the tx log completed
2016-03-24 08:54:52.041+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [2820]:  Check pointing completed
2016-03-24 08:54:52.042+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1]:  Starting log pruning.
2016-03-24 08:54:52.042+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1]:  Log pruning complete.
2016-03-24 08:54:52.042+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 222ms.
2016-03-24 08:54:52.058+0000 INFO  [o.n.k.i.f.GraphDatabaseFacade] Shutdown started
2016-03-24 08:54:52.060+0000 INFO  [o.n.k.i.f.CommunityFacadeFactory] Database is now unavailable
2016-03-24 08:54:52.410+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Starting check pointing...
2016-03-24 08:54:52.410+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Starting store flush...
2016-03-24 08:54:53.106+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Store flush completed
2016-03-24 08:54:53.106+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Starting appending check point entry into the tx log...
2016-03-24 08:54:53.553+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Appending check point entry into the tx log completed
2016-03-24 08:54:53.553+0000 INFO  [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [2820]:  Check pointing completed
2016-03-24 08:54:53.555+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1]:  Starting log pruning.
2016-03-24 08:54:53.555+0000 INFO  [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [1]:  Log pruning complete.
2016-03-24 08:54:55.496+0000 INFO  [o.n.k.NeoStoreDataSource] NeoStores closed
2016-03-24 08:54:55.719+0000 INFO  [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics START ---
2016-03-24 08:54:55.720+0000 INFO  [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics END ---
```
## Conclusion

`neostore.counts.db.a` is mentioned in `messages.log` and in the python error. I am thinking the log pruning or cycling leads to a failure in a py2neo command/query/transaction. Unfortunately, I'm not exactly sure where to put error handling wrt py2neo to try again in these instances.

I suspect using the default setting for `keep_logical_logs` may resolve this issue. I can always delete logs after shutting down the server, if I need to reduce the database size. I will try this next as well as upgrading to 2.3.3. Not sure if anyone will be able to help, but thought I'd share in case this can lead to a bugfix.

**Comment by spacecowboy** [comment] 2016-03-29 09:43
Thank you for the detailed report. Unfortunately, the log you posted shows nothing out of the ordinary.
The error you are seeing it not related to logical logs, but to the counts store (as mentioned in the log, and the filename in the error).

The log says that a counts store rotation is triggered, as part of a checkpoint operation, based on the configured timer, and where the latest transaction is number 2820:

```
 Check Pointing triggered by scheduler for time threshold [2820]:  Starting check pointing..
```

The counts store keeps track of some statistics to improve the performance of queries. A rotation of the counts store should not fail a running transaction, so if that is the case, then it's a bug.

A cursory glance of your hetnet code did not reveal any problems on your end, but I'd double check that you don't delete any files from a running database. Once the error has happened, could you open the database directory and actually see if both `neostore.counts.db.a` and `neostore.counts.db.b` are there?

Another thing you can try is to tweak the trigger values for the checkpointing operation:

[dbms.checkpoint.interval.time](http://neo4j.com/docs/stable/configuration-settings.html#config_dbms.checkpoint.interval.time)

[dbms.checkpoint.interval.tx](http://neo4j.com/docs/stable/configuration-settings.html#config_dbms.checkpoint.interval.tx)

Increasing the time interval might reduce your error rate, and reducing it might increase the rate of errors which would help with finding the cause of the problem.

**Comment by spacecowboy** [comment] 2016-03-29 09:55
@dhimmel  Some clarifying questions:
- Are all 6 databases running from the same hard drive?
- Are you running with the default page cache settings? (If not, what do you specify?)
- How much RAM does you machine have?
- What OS are you running? Linux/OS X ?

**Comment by dhimmel** [comment] 2016-03-29 16:05
> I'd double check that you don't delete any files from a running database

@spacecowboy, I only delete logs when the import completes. When I `stat neostore.counts.db*` in `graph.db`, here are the two records:

```
  File: ‘neostore.counts.db.a’
  Size: 4992        Blocks: 32         IO Block: 4096   regular file
Device: 28h/40d Inode: 165807028   Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/dhimmels)   Gid: ( 1000/dhimmels)
Access: 2016-03-24 01:49:55.474605491 -0700
Modify: 2016-03-24 01:49:49.834703152 -0700
Change: 2016-03-24 01:49:49.834703152 -0700
 Birth: -

  File: ‘neostore.counts.db.b’
  Size: 4992        Blocks: 32         IO Block: 4096   regular file
Device: 28h/40d Inode: 165807722   Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/dhimmels)   Gid: ( 1000/dhimmels)
Access: 2016-03-29 08:37:02.772495619 -0700
Modify: 2016-03-24 01:54:51.097485887 -0700
Change: 2016-03-24 01:54:51.097485887 -0700
 Birth: -
```

Note that the timezone here is 7 hours behind the timestamps above. `neostore.counts.db.b` was last modified during the count store rotation preceding the Exception and `neostore.counts.db.a` was last modified 5 minutes prior.

> Are all 6 databases running from the same hard drive?

Yes, all are running from the same hard disk drive.

> How much RAM does you machine have? Are you running with the default page cache settings? (If not, what do you specify?) 

256 GB. I didn't change the default [page memory setting](http://neo4j.com/docs/2.3.2/configuration-io-examples.html), since I assumed the machine would have more than enough RAM. From my recollection, together all 6 instances together were using approximately half of the system RAM. It's definitely possible that due to other processes, all RAM became saturated. Could that cause the issue?

> What OS are you running? Linux/OS X?

Ubuntu 15.10

> Increasing the time interval might reduce your error rate, and reducing it might increase the rate of errors which would help with finding the cause of the problem.

Great point!

## Miscellaneous

Is there a list of essential database files? If I want to send someone only the hetnet (nodes, relationships, and properties), what files are needed?

Finally, paging @antoine-lizee who helped me troubleshoot the issue and may be interested in the discussion.

**Comment by spacecowboy** [comment] 2016-03-31 12:44
@dhimmel Thanks for the details. We'll take a look at it.

The only non-essential files are the counts-store files and possible index files (not legacy index files though), as they are rebuilt on database startup if missing. Except that, you'd basically have to send the entire `graph.db` folder.

**Comment by dhimmel** [comment] 2016-04-04 17:45
I upgraded to 2.3.3, didn't run other memory intensive applications while importing, and increased the trigger values for checkpointing by adding the following two lines to `neo4j.properties`:

```
dbms.checkpoint.interval.time=180m
dbms.checkpoint.interval.tx=10000000
```

All 6 henets [imported successfully](https://github.com/dhimmel/integrate/blob/809e1f837aac4c3b52a144b61b49057b689a2d82/neo4j-import.ipynb). Since the error occurs intermittently, this success is only mild evidence that any of the workarounds are effective.

**Comment by chrisvest** [comment] 2018-02-21 16:33
Closing since #8003 claims to fix this.

**Closed as completed by chrisvest** 2018-02-21 16:33 UTC
Labels: bug, 2.3, team-kernel
