### ISSUE TITLE
Map field cannot handle null object if it is not available in previous WITH projection

### ISSUE THREAD

**Issue by joehmchan** [neo4j/neo4j#9494] opened 2017-06-08 11:58 UTC
I am trying to project the complex nested classes structure with map, using the approach suggested in (https://github.com/Readify/Neo4jClient/issues/214).
I discovered that nested map field cannot handle null object.

### Steps to reproduce
I have several c# classes:
```
public class UnitTestEntityWithNestedEmbedded : BaseEntity
{
	public UnitTestEntityWithEmbedded NestedEmbeddable1 { get; set; }
	public UnitTestEntityWithEmbedded NestedEmbeddable2 { get; set; }
}
public class UnitTestEntityWithEmbedded : BaseEntity
{
	public UnitTestEmbeddable Embeddable1 { get; set; }
	public UnitTestEmbeddable Embeddable2 { get; set; }
}
public class UnitTestEmbeddable : BaseEntity
{
	public string SomeField1 { get; set; }
	public int SomeField2 { get; set; }
	public DateTime SomeField3 { get; set; }
}
public abstract class BaseEntity
{
	public int Id { get; set; }
	public bool IsArchived { get; set; }
}
```

I am able to create the nodes / relationships / child nodes by the following cypher query
```
CREATE (owner:Entity:UnitTestEntityWithNestedEmbedded {
  "id": 5,
  "isArchived": true
})
CREATE (owner)-[:nestedEmbeddable1]->(c0_e0:Embedded:UnitTestEntityWithEmbedded {
  "id": 4,
  "isArchived": true
})
CREATE (c0_e0)-[:embeddable1]->(c1_e0:Embedded:UnitTestEmbeddable {
  "someField1": "I'm embeddable 1",
  "someField2": 1,
  "someField3": "2017-06-07T01:00:00Z",
  "id": 0,
  "isArchived": false
})
```

However, if some of the nested nodes are absent, I am not able to query using map. Here is my query.
```
MATCH (owner:Entity:UnitTestEntityWithNestedEmbedded)
OPTIONAL MATCH (owner)-[owner_e0_r0:nestedEmbeddable1]-(owner_e0:Embedded)
OPTIONAL MATCH (owner_e0)-[owner_e0_e0_r0:embeddable1]-(owner_e0_e0:Embedded)
OPTIONAL MATCH (owner_e0)-[owner_e0_e1_r1:embeddable2]-(owner_e0_e1:Embedded)
OPTIONAL MATCH (owner)-[owner_e1_r1:nestedEmbeddable2]-(owner_e1:Embedded)
OPTIONAL MATCH (owner_e1)-[owner_e1_e0_r0:embeddable1]-(owner_e1_e0:Embedded)
OPTIONAL MATCH (owner_e1)-[owner_e1_e1_r1:embeddable2]-(owner_e1_e1:Embedded)
WITH {someField1:owner_e0_e0.someField1, someField2:owner_e0_e0.someField2, someField3:owner_e0_e0.someField3, id:owner_e0_e0.id, isArchived:owner_e0_e0.isArchived} AS container_c0_c0
WITH {someField1:owner_e0_e1.someField1, someField2:owner_e0_e1.someField2, someField3:owner_e0_e1.someField3, id:owner_e0_e1.id, isArchived:owner_e0_e1.isArchived} AS container_c0_c1
WITH {someField1:owner_e1_e0.someField1, someField2:owner_e1_e0.someField2, someField3:owner_e1_e0.someField3, id:owner_e1_e0.id, isArchived:owner_e1_e0.isArchived} AS container_c1_c0
WITH {someField1:owner_e1_e1.someField1, someField2:owner_e1_e1.someField2, someField3:owner_e1_e1.someField3, id:owner_e1_e1.id, isArchived:owner_e1_e1.isArchived} AS container_c1_c1
WITH {embeddable1:container_c0_c0, embeddable2:container_c0_c1, id:owner_e0.id, isArchived:owner_e0.isArchived} AS container_c0
WITH {embeddable1:container_c1_c0, embeddable2:container_c1_c1, id:owner_e1.id, isArchived:owner_e1.isArchived} AS container_c1
WITH {nestedEmbeddable1:container_c0, nestedEmbeddable2:container_c1, id:owner.id, isArchived:owner.isArchived} AS container
WHERE (owner.id = 5)
RETURN container
```

It seems like not able to handle null object in map, because UnitTestEntityWithEmbedded.NestedEmbeddable1.embeddable2

### Environments
- Neo4j version: 3.2.1 (Docker)
- Operating system: WIndows 10 Pro
- API/Driver: Neo4jClient or Neo4j web browser

### Expected behavior
Should be able to return a map structure

### Actual behavior
```
Variable `owner_e0_e1` not defined (line 9, column 18 (offset: 717))
"WITH {someField1:owner_e0_e1.someField1, someField2:owner_e0_e1.someField2, someField3:owner_e0_e1.someField3, id:owner_e0_e1.id, isArchived:owner_e0_e1.isArchived} AS container_c0_c1"
```

**Comment by jexp** [comment] 2017-06-11 23:16
The problem is that your WITH removes that variable from the scope, for it to be available later you have to pass it on.

Also the many optional matches might increase your cardinality if the relationships are not 1:1
Consider using map-projections within pattern comprehensions instead:
https://neo4j.com/blog/cypher-graphql-neo4j-3-1-preview/

**Comment by sherfert** [comment] 2017-10-20 14:27
I think jexp explained what the problem with the query was. Closing.

**Closed as completed by sherfert** 2017-10-20 14:27 UTC
