### ISSUE TITLE
Neo4jError: Can't coerce `NO_VALUE` to Map

### ISSUE THREAD

**Issue by Brakebein** [neo4j/neo4j#12433] opened 2020-03-21 15:00 UTC
**Neo4j Version:** 4.0.2
**Operating System:** Windows Server 2012 R2
**API:** neo4j-driver 4.0.1 (nodejs)

I found another bug that is very related to #12398 and #12399 . The query also uses `OPTIONAL MATCH` and map projections. And again, the error is thrown after executing the query 10 times. After clearing the query cache it will work another 10 times. The error output is slightly different:

```
Neo.ClientError.Statement.TypeError
Neo4jError: Can't coerce `NO_VALUE` to Map
```

**Cypher query:**

```sql
MATCH (:User:RIVAD {id: $userId})<-[:HAS_OWNER|HAS_MEMBER]-(study:Study {id: $studyId})
    <-[:PART_OF]-(doc:TextDocument {id: $docId})-[:HAS_SEGMENT]->(seg:TextSegment {id: $segId})
    <-[:HAS_INPUT]-(trans:TextTransformation)-[:HAS_OUTPUT]->(gist:Gist)
OPTIONAL MATCH (trans)-[:APPLIES]->(replace:Replacement)-[:CONSISTS_OF]->(snippet:TextSnippet),
               (replace)-[ruRep:CREATED_BY]->(userRep:User)
WITH seg, trans, gist, collect(replace {.*, snippet, meta: {user: userRep.id, userName: userRep.name, timestamp: toString(ruRep.timestamp)}}) AS replacements
OPTIONAL MATCH (trans)-[:APPLIES]->(remove:Removal)-[:CONSISTS_OF]->(snippet:TextSnippet),
               (remove)-[ruRem:CREATED_BY]->(userRem:User)
RETURN trans.id AS id,
       seg.value AS input,
       gist.value AS output,
       replacements,
       collect(remove {.*, snippet, meta: {user: userRem.id, userName: userRem.name, timestamp: toString(ruRem.timestamp)}}) AS removals
```

**Neo4j `query.log`:**

```
2020-03-21 12:29:26.170+0000 ERROR id:408 - 133 ms: bolt-session	bolt	neo4j-javascript/0.0.0-dev		client/127.0.0.1:50693	server/127.0.0.1:7687>	rivad - neo4j - 
		MATCH (:User:RIVAD {id: $userId})<-[:HAS_OWNER|HAS_MEMBER]-(study:Study {id: $studyId})<-[:PART_OF]-(doc:TextDocument {id: $docId})-[:HAS_SEGMENT]->(seg:TextSegment {id: $segId})<-[:HAS_INPUT]-(trans:TextTransformation)-[:HAS_OUTPUT]->(gist:Gist)
		OPTIONAL MATCH (trans)-[:APPLIES]->(replace:Replacement)-[:CONSISTS_OF]->(snippet:TextSnippet),
					   (replace)-[ruRep:CREATED_BY]->(userRep:User)
		WITH seg, trans, gist, collect(replace {.*, snippet, meta: {user: userRep.id, userName: userRep.name, timestamp: toString(ruRep.timestamp)}}) AS replacements
		OPTIONAL MATCH (trans)-[:APPLIES]->(remove:Removal)-[:CONSISTS_OF]->(snippet:TextSnippet),
					   (remove)-[ruRem:CREATED_BY]->(userRem:User)
		RETURN trans.id AS id,
			   seg.value AS input,
			   gist.value AS output,
			   replacements,
			   collect(remove {.*, snippet, meta: {user: userRem.id, userName: userRem.name, timestamp: toString(ruRem.timestamp)}}) AS removals - {studyId: 'study_8m-OOmP47', segId: 'textSegment_mGNyTJzn-', userId: 'user_aH6up2P6j', docId: 'textDocument_5BylXYZDi'} - {} Can't coerce `NO_VALUE` to Map
org.neo4j.exceptions.CypherTypeException: Can't coerce `NO_VALUE` to Map
	at org.neo4j.cypher.operations.CypherCoercions.cantCoerce(CypherCoercions.java:287)
	at org.neo4j.cypher.operations.CypherCoercions.asMapValue(CypherCoercions.java:272)
	at org.neo4j.codegen.Expression9/0x0000000101a61840.evaluate(Unknown Source)
	at org.neo4j.cypher.internal.runtime.slotted.expressions.CompileWrappingExpression.apply(CompiledExpressionConverter.scala:172)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.AggregationOperator$AggregationMapperOperator$State.preAggregate(AggregationOperator.scala:135)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.AggregationOperator$AggregationMapperOperator$State.$anonfun$prepareOutput$1(AggregationOperator.scala:119)
	at org.neo4j.cypher.internal.runtime.pipelined.state.ArgumentStateMap$.$anonfun$map$1(ArgumentStateMap.scala:349)
	at org.neo4j.cypher.internal.runtime.pipelined.state.ArgumentStateMap$.$anonfun$map$1$adapted(ArgumentStateMap.scala:349)
	at org.neo4j.cypher.internal.runtime.pipelined.state.ArgumentStateMap$.foreach(ArgumentStateMap.scala:369)
	at org.neo4j.cypher.internal.runtime.pipelined.state.ArgumentStateMap$.map(ArgumentStateMap.scala:349)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.AggregationOperator$AggregationMapperOperator$State.prepareOutput(AggregationOperator.scala:119)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.AggregationOperator$AggregationMapperOperator$State.prepareOutput(AggregationOperator.scala:96)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.OutputOperatorState.prepareOutputWithProfile(OutputOperator.scala:53)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.OutputOperatorState.prepareOutputWithProfile$(OutputOperator.scala:44)
	at org.neo4j.cypher.internal.runtime.pipelined.operators.AggregationOperator$AggregationMapperOperator$State.prepareOutputWithProfile(AggregationOperator.scala:96)
	at org.neo4j.cypher.internal.runtime.pipelined.PipelineTask.executeOutputOperator(PipelineTask.scala:74)
	at org.neo4j.cypher.internal.runtime.pipelined.PipelineTask.executeWorkUnit(PipelineTask.scala:50)
	at org.neo4j.cypher.internal.runtime.pipelined.Worker.executeTask(Worker.scala:128)
	at org.neo4j.cypher.internal.runtime.pipelined.Worker.workOnQuery(Worker.scala:84)
	at org.neo4j.cypher.internal.runtime.pipelined.execution.CallingThreadExecutingQuery.request(CallingThreadExecutingQuery.scala:30)
	at org.neo4j.cypher.internal.PipelinedRuntime$PipelinedRuntimeResult.request(PipelinedRuntime.scala:326)
	at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:88)
	at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:135)
	at org.neo4j.bolt.runtime.AbstractCypherAdapterStream.handleRecords(AbstractCypherAdapterStream.java:105)
	at org.neo4j.bolt.v3.messaging.ResultHandler.onPullRecords(ResultHandler.java:41)
	at org.neo4j.bolt.v4.messaging.PullResultConsumer.consume(PullResultConsumer.java:42)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:511)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$2.streamResult(TransactionStateMachine.java:355)
	at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.streamResult(TransactionStateMachine.java:92)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processStreamResultMessage(InTransactionState.java:73)
	at org.neo4j.bolt.v4.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:49)
	at org.neo4j.bolt.v4.runtime.InTransactionState.processUnsafe(InTransactionState.java:60)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:143)
	at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:91)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:90)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:151)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:240)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:175)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:165)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:212)
	at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:195)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by shahadp** [comment] 2020-03-23 10:51
Hi,
As per the above
I can see the below issue is still not fixed in 4.0.2. 
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1427
4.0.2 Issue Log Fix
Fixed bug in compiled expressions where a null path from an OPTIONAL MATCH inserted into nested functions lead to an unexpected error.

**Comment by fabio-s-franco** [comment] 2020-03-23 14:05
I can also confirm this has not been fixed in 4.0.2. Also getting it.

**Closed as completed** 2020-03-27 11:24 UTC
Labels: bug, team-cypher

**Comment by fabio-s-franco** [comment] 2020-03-27 20:19
Why is this closed? There is no pull request, no new release in the change logs and the referred commit is just a test scenario.
@sherfert any light on this? When should we expect this to be delivered?

**Comment by sherfert** [comment] 2020-03-30 07:12
Hi @fabio-510 
The bug lived in the closed-source components of neo4j, which is why only the test scenario made it into the publicly visible commit.

The fix missed 4.0.3, but will be included in the 4.0.4 patch release, and will be visible in the changelog.

In the meantime, you should be able to work around it by writing `CYPHER expressionEngine=interpreted ...` in front of your queries.

**Comment by fabio-s-franco** [comment] 2020-06-24 20:30
@sherfert  this bug keeps popping up again and again. We see the issue on 4.0.5 but it relates to path projection. It's going to take a while until I can get a repro working, meanwhile we are using again the "CYPHER expressionEngine=interpreted".

Now I am considering not removing it again, but I still don't understand the impact of it. There is no documentation I could find that explains what it actually means and what is the benefit of the default engine (whichever that is). Would you mind explaining it?

**Comment by sherfert** [comment] 2020-06-25 06:50
@fabio-510 
I am sorry you keep running into this issue, that is really unfortunate.
We have fixed a couple of issues around this area, but apparently we must have missed something. If you find a way to reproduce, please reopen the issue! We want to find and remove the new problem you found as well.

There are two ways of executing expressions (like map-projections) in the `slotted` runtime. The `interpreted` engine has been the standard way for a long time. It executes expressions by interpreting the expression-trees. The `compiled` engine generates dedicated bytecode for each expression, which is faster, especially for large expressions. It was added later and is the new default. We did not document this publicly, because the `compiled` engine should be overall better so that there is no reason for a normal user to decide. That being said, we wanted a way to fallback, so that in cases like yours, you can circumvent bugs.

If you want to disable the compiled engine overall to avoid such problems in the future, you can also set the the setting `unsupported.cypher.expression_engine` to `INTERPRETED`.

**Comment by fabio-s-franco** [comment] 2020-06-25 18:53
Thanks for the clarification @sherfert , appreciate it. As soon as I am able to reproduce it I will create a new issue (I don't have the power to reopen an issue). The reason I do not open the issue right now is that I cannot simply share my database. So I need to create a data model that will trigger it and you can run on your side.

Having that said, it's good to have this as a setting, makes it a lot easier to deploy and does not require code change.

**Comment by byrneciaran** [comment] 2020-06-30 10:00
I have been running into this same issue. I thought if I used COALESCE it would resolve matters but it hasn't. 

I am using the Neo4j.Driver 4.1.0 for my .NET Core Project.

Here is my cypher query:

```
MATCH (p:Plan{id:$id})
WITH p
OPTIONAL MATCH(g)-[:GOAL_ALIGNED_PLAN]->(p)
WITH p,g
OPTIONAL MATCH(at)-[:ACTION_ALIGNED_GOAL]->(g)
WITH p,g,COLLECT(at {.*,createdAt:toString(at.createdAt),
updatedAt:toString(at.updatedAt)})
as actions
RETURN p {.*,createdAt:toString(p.createdAt),
updatedAt:toString(p.updatedAt),
goals:collect(g {.*,createdAt:toString(g.createdAt),
updatedAt:toString(g.updatedAt),
actions: actions})}
as plan
```

It's definitely a show stopper for me, unless there is a workaround ?

**Comment by sherfert** [comment] 2020-06-30 11:19
@byrneciaran 
Could you please share you to setup the database before running the query and which neo4j version your are using?

For a workaround, please find detailed explanations above.
