### ISSUE TITLE
2.3.0 returning 404 after error in a Transaction, change from 2.2x

### ISSUE THREAD

**Issue by cskardon** [neo4j/neo4j#5806] opened 2015-11-02 09:59 UTC
This is related to an issue raised on the .Net `Neo4jClient` page (https://github.com/Readify/Neo4jClient/issues/127)  - all the queries here are run via the `db/data/cypher` endpoint

First, create a constraint:

`CREATE CONSTRAINT ON (n:User) ASSERT n.Name IS UNIQUE`

Then create a user:

Query: `CREATE (n:User {user})`, Params: `{"user":{"Name":"Mike", "Id":1}}`

So far so good - now attempt to create the same user, but within a transaction:

Query: `CREATE (n:User {user})`, Params: `{"user":{"Name":"Mike", "Id":1}}`

This will return a `ConstraintViolation` as you'd expect, and the transaction ID, for the sake of argument, that will be `20`.

Both 2.3.0 and 2.2.x are the same up to this point. The difference occurs when due to the error we decide to `DELETE` the transaction, so we call:

`DELETE http://localhost:7474/db/data/transaction/20`

In 2.2x that returns: `{"results":[],"errors":[]}`

In 2.3.0 that returns:

```
{
    "results":[],
    "errors":[
        {
            "code":"Neo.ClientError.Transaction.UnknownId",
            "message":"Unrecognized transaction id. Transaction may have timed out and been rolled back."
        }
]}
```

All wrapped up in a 404 response. 

Is there a reason the response has changed? Is this expected behaviour? I've executed these via `Neo4jClient` and via `Fiddler` using the composer, so I'm relatively certain it's a change in behaviour from 2.2x to 2.3.0.

**Comment by lutovich** [comment] 2015-11-02 11:11
Hi @cskardon,

I think this PR https://github.com/neo4j/neo4j/pull/5394 is responsible for change of behaviour that you observe. Documentation (http://neo4j.com/docs/2.3.0/status-codes.html) now mentions that `ClientError` has a rollback effect on the transaction.
Previous behaviour was quite inconsistent because it was not possible to commit the transaction after `ClientError` in Cypher statement. So we've just made sure database does the rollback automatically.

Do you think this new change is acceptable and brings any good for you?

**Comment by cskardon** [comment] 2015-11-02 11:45
The problem for me is that the 404 really gives no indication of what's happened it just hides the fact that the rollback has occurred, and from a user point of view, looks a little like something else has happened.

I guess internally I can check for a 404 and treat as a normal 200, but that has problems of it's own - what if it _is_ a genuine timeout?

In my view if you do something like a rollback - it really should be told to the user.

**Comment by lutovich** [comment] 2015-11-02 12:30
After query `CREATE (n:User {user})` with params: `{"user":{"Name":"Mike", "Id":1}}` which violates the constraint and causes transaction rollback, database already has no idea that transaction with id `20` took place. So sending `DELETE` afterwards is not needed. Basically when status code has `ClientError` in it than this is a sign that rollback occurred.
@cskardon what do you think about this?

**Comment by cskardon** [comment] 2015-11-02 15:16
That's only in 2.3.0 though right? In 2.2.x the transaction isn't automatically rolled back?

**Comment by lutovich** [comment] 2015-11-02 15:57
@cskardon no, this change was also released as part of 2.2.6. Thinking behind this was in < 2.2.6 transactions would not be able to commit after `ClientError` so that is effectively a rollback. So that PR makes this behaviour more explicit. But it does break backwards compatibility with 2.2.5 if user code attempts to rollback the tx manually with `DELETE` after `ClientError`.

This is the real problem, I got it :(
Do you think it is possible to work around this problem?

**Comment by jexp** [comment] 2015-11-02 16:36
The problem is that it breaks existing behavior without deprecation and that both users of the api as well as drivers will break. 

Also having to look _into_ the 404 is an awkward means of using an api

**Comment by cskardon** [comment] 2015-11-02 16:39
Well - you _can_ work around any problem :)

Part of my problem is the way Transactions are dealt with in `C#` - because the Tx object is actually for .NET, not just Neo4j, for example:

```
using(var tx = client.BeginTransaction())
{
    tx.Cypher.Match(/*Blah Blah*/)... etc
    AMethodThatThrowsAnException();
    tx.Commit();
}
```

in this case the exception would cause the tx to Rollback, _obviously_ if the cypher code is fine, then there is no issue, as the `DELETE` is valid, and from a dev point of view, it's a nice flow. 

I guess I can attempt to parse the error type, but that seems horribly clunky, but that's just first thoughts - I'll look into it and see what I can do.

**Comment by lutovich** [comment] 2015-11-02 16:44
@jexp this problem is not about 404 per se. Transaction is rolled back on `ClientError` at once so next `DELETE` request is indeed invalid because it refers to an invalid transaction id.

@cskardon I agree that looking at the HTTP response code for `DELETE` is extremely ugly. Feels like reintroducing previous broken behaviour in 2.2.7 would be even worse. I'll talk to other developers about it. Really sorry for this inconvenience!

**Comment by jexp** [comment] 2015-11-02 18:03
Otoh why is the previously existing tx-id inaccessible? After all it existed once in an active state and now its state is rolled-back or aborted. But that the tx as such is no longer there is also inconsistent

**Comment by jexp** [comment] 2015-11-02 18:05
Would also be interesting to see what the behavior is in bolt

**Comment by lutovich** [comment] 2015-11-02 21:15
@jexp previously existing was rolled back that is why it's id is unaccessible. Rollback bit is one that changed. Previously transaction id would be accessible for `DELETE` because transaction was still there opened.

**Comment by ikwattro** [comment] 2015-11-02 21:34
Good catch @cskardon . @lutovich @jexp The problem for driver authors is not really having to look at the http response IMO (this might like an ugly solution but it is internal to the driver, rarely the driver user will deal with it).

It is more than now, there is a condition on the logic we have to implement in the driver's transaction object.

This might not seem so, but this BC change has a huge impact for us, because : 
1. For choosing the logic to use on failure, we need to know now the neo4j version, which requires to send a separate http request to the ReST API (this is for use cases where the users are not using manually transaction objects)
2. If you want to avoid ref1, you need to bump a new major release of the driver being only 2.2.6+ compatible, which means also that you need to backport bug fixes.

On a reminder for driver authors, note that the changelog was mentioning it : https://github.com/neo4j/neo4j/blob/3.0/community/server/CHANGES.txt#L15

**Comment by lutovich** [comment] 2015-11-02 22:51
Here is an example of broken behaviour that PR changed:
1) new transaction started
2) cypher statement is executed and causes `ClientError`, transaction is not rolled back
3) correct cypher statement is executed and response is 200OK
4) transaction is committed and commit fails with `Neo.DatabaseError.Transaction.CouldNotCommit`

After 2) transaction was marked for termination and would never be able to commit. At the same time it was able to accept and 200OK correct cypher statements. At 4) it failed with `DatabaseError` which is quite misleading.

@cskardon, @ikwattro is it true that drivers would just manually rollback with `DELETE` after every client error?
If so than would it simply be possible to ignore 404 only from rollback following the `ClientError`?

**Comment by ikwattro** [comment] 2015-11-02 22:59
In PHP yes it is true, I assume @cskardon is doing the same in .NET .

Yes, you can try/catch the DELETE HTTP Request for a 404 error until the compliance is 2.2.6+.

I just dunno if any of my driver users are using transactions manually and try to issue new statements after one has possibly failed, maybe something to document in our README as warning.

**Comment by ikwattro** [comment] 2015-11-02 23:07
@lutovich  However, you should still treat a 404 as an unexpected exception in <2.2.6, right ?

So this remains the same, you need to know which neo4j version is running.

**Comment by lutovich** [comment] 2015-11-02 23:45
@ikwattro If rollback via `DELETE` results in 404 with status code `Neo.ClientError.Transaction.UnknownId` than it might be safe to not propagate this error to the user if and only if there previously was a `Neo.ClientError` in this transaction.

**Comment by ikwattro** [comment] 2015-11-02 23:50
Yep, so quite a good piece of logic :) We'll manage though because we love that haha :)

**Comment by cskardon** [comment] 2015-11-03 05:48
@lutovich Yes - the .NET driver does auto-call `DELETE` after a failure, and I'm pretty sure @nigelsmall also does the `DELETE` in Py2Neo.

I'm guessing there's gonna be a lot of `if version > 2.2.5` type code appearing in a driver near you! :)

**Comment by jexp** [comment] 2015-11-03 08:51
@lutovich not sure if I see your case as broken behavior. The tx is just the scope of change which can be marked as "rollbackOnly" then the behavior at success + close is specified as "fail". If we just close it I think it will not complain.

It is actually the same behavior as the Java API.

**Comment by lutovich** [comment] 2015-11-03 11:34
@jexp you are right - rollback for such transaction would work fine. At the same time failing with `DatabaseError` on commit does not seem good.
Anyway, this is definitely a BC breaking change in a patch release.
I've wrote an email to the neo4j-ecosystem mailing list to make this issue more visible to driver authors. Let's discuss this problem and possible solutions further there.

**Comment by cskardon** [comment] 2015-11-03 14:36
`Neo4jClient` is now compatible with 2.2.6+ in terms of the way this works.

**Comment by aseemk** [comment] 2015-11-03 14:48
Hi folks,

As the author of the [original issue](https://github.com/neo4j/neo4j/issues/5258) for which this change was made (!), I feel compelled to chime in. :smile: 

I have three things to offer, which I hope will help this situation.

—

Most importantly, the driver I author ([node-neo4j](https://github.com/thingdom/node-neo4j/tree/v2)) is _not_ broken with this change — and I didn't do anything special for it — because of this key [piece of code](https://github.com/thingdom/node-neo4j/blob/951008d41798b806f7c29a0d41462d6a015695b8/lib-new/Transaction.coffee#L154-L160) in the transaction response handler:

``` coffee
if not body.transaction
    # This transaction has been destroyed (either committed or rolled
    # back). ...
    # <code to update this transaction's state to "committed" if a commit
    # was requested and no errors returned, otherwise "rolled back">
     return
```

So that's my suggestion for all drivers: instead of having complex logic based on whether there was previously a ClientError, etc., just use the **presence (or lack thereof) of the `transaction` property** in the response to tell you **whether this transaction still exists or not**.

—

My previous suggestion works because this Neo4j 2.2.6 change kept those semantics: any time a transaction has been committed or rolled back, **the response no longer includes `transaction`**.

E.g. before, with 2.2.3 (assume open transaction with ID `1234`):

``` json
$ http POST localhost:7474/db/data/transaction/1234 statements:='[{"statement":"RETURN {foo}"}]'
HTTP/1.1 200 OK
...
{
    "commit": "http://localhost:7474/db/data/transaction/1234/commit", 
    "errors": [
        {
            "code": "Neo.ClientError.Statement.ParameterMissing", 
            "message": "Expected a parameter named foo"
        }
    ], 
    "results": ["..."],
    "transaction": {
        "expires": "Tue, 03 Nov 2015 14:32:07 +0000"
    }
}
```

And now, with 2.2.6:

``` json
$ http POST localhost:7474/db/data/transaction/1234 statements:='[{"statement":"RETURN {foo}"}]'
HTTP/1.1 200 OK
...
{
    "commit": "http://localhost:7474/db/data/transaction/1234/commit", 
    "errors": [
        {
            "code": "Neo.ClientError.Statement.ParameterMissing", 
            "message": "Expected a parameter named foo"
        }
    ], 
    "results": ["..."]
}
```

Notice no `transaction` object in the response now.

@lutovich: You could probably get rid of `commit` too, for consistency.

—

Finally, for environments where callers still expect to manually/explicitly roll back transactions (e.g. the [C#/.NET example](https://github.com/neo4j/neo4j/issues/5806#issuecomment-153077193) @cskardon posted above), the driver could still accept the rollback call, but no-op it (i.e. make no `DELETE` request) if it knew the transaction had already been rolled back.

Not sure how easy that is to do in every circumstance, but hopefully it's not hard if you're already encapsulating transaction state in a `Transaction` object (as node-neo4j does also).

—

I hope all of this helps! Let me know if I'm missing any points or can provide any more help.

Cheers, and thanks again @lutovich.

**Comment by aseemk** [comment] 2015-11-03 14:53
One addendum for clarification:

If you agree with and follow my suggestions, you should _never_ see a `Transaction.UnknownId` error.

That's because you'll never attempt to rollback (`DELETE`) a transaction that's already been rolled back.

**Comment by cskardon** [comment] 2015-11-03 15:04
Is the lack of `transaction` in the response documented as a fact that is not changeable?

**Comment by aseemk** [comment] 2015-11-03 15:07
That's a very good q. It's _not_ explicitly documented (many REST API things aren't, in my experience); just something I derived from studying all the different cases and examples in the docs:

http://neo4j.com/docs/stable/rest-api-transactional.html

@lutovich or whoever else should chime in.

**Comment by jexp** [comment] 2015-11-03 15:08
I think the absence of a transaction object is pretty _accidental_, if you opted to check for the `commit` property instead (which is still transmitted, even in case of error) then you don't get the same behavior.

Something else I don't really get, is why we roll back the tx on a simple cypher error. I mean there might have been something wrong but it's nothing that the tx is affected by. At least in interactive mode a broken statement is a no-op. E.g. in shell or the browser I don't expect a single broken (e.g. mistyped statement) to break my whole tx.

In non-interactive mode it might be different.

And running operations that result in a 404 as a no-op is kindof weird too.

**Comment by jakewins** [comment] 2015-11-03 15:13
@jexp this was the original thought of the behavior - some errors (like a syntax error) might be recoverable. However, it became really complicated to tell which errors were ok and which ones were not on the impl level.

So, we looked at what others do, and noted that production-hardened dbs we could find would _always_ fail on error, no buts about it. The way they do interactive clients is by bundling a small syntax parser with the client, so they can check for syntax errors before sending the statement. 

I think this is a cleaner approach, and easier to remember. If something goes wrong, the transaction goes away. 

Re: `transaction`/`commit` object keys: That is indeed accidental, but we could cement that behavior in the docs, to make it officially supported. That would be a low-cost way of resolving this.

Overall, and for the record, we have a strict non-breakage policy: Breaking the API like this (in a minor release, with no deprecation) is fundamentally not something we ever want to do. In this particular case, I messed up in the original design, and me and @lutovich felt this was the least bad of many bad options to resolve that hiccup.

**Comment by aseemk** [comment] 2015-11-03 15:21
Good discussion. I just wanted to reply to one thing, @jexp:

> if you opted to check for the commit property instead (which is still transmitted, even in case of error) then you don't get the same behavior

The reason I check `transaction` and not `commit` is purposeful: it's what contains the updated expiry time. The commit URL doesn't change from query to query, but the expiry changes on every query.

**Comment by ikwattro** [comment] 2015-11-05 22:32
Thanks @aseemk for your tips. Unfortunately I think there are drawbacks in all provided suggestions.

While your suggestion is the `easiest` one, I can't be sure it might remain a non-breaking change even at the driver level depending your wrapped Transaction object.

In my case, the Transaction object the user can use, is returning the response object from the Rest API after rollback has been issued (so in <2.2.6). Even the response contains an empty collection of results and an empty collection of errors.

So, for 2.2.6+, The `last` response received is a `ConstraintViolationException`.

**Comment by ikwattro** [comment] 2015-11-09 11:49
@cskardon @lutovich May this issue be closed. It will stay as it is afaik.

**Comment by cskardon** [comment] 2015-11-09 15:43
From my POV it can be closed, I've fixed Neo4jClient, and it only needs to
stay open if Neo want it to...!

**Comment by lutovich** [comment] 2015-11-09 23:34
Hello guys,

Thanks for your input. We indeed can't do much here because 2.2.6 has already been released with this BC breaking change.
Will close this ticket and update it with documentation of `transaction` JSON key a bit later.

**Closed as completed by lutovich** 2015-11-09 23:34 UTC
