### ISSUE TITLE
Empty results at startup with WHERE IN filters

### ISSUE THREAD

**Issue by simondaudin** [neo4j/neo4j#12950] opened 2022-09-29 12:13 UTC
Hello there

I discovered a strange behavior with `WHERE * IN` at startup with neo4j 4.4.11, when making requests in a specific order, a request with `WHERE * IN` would always returns empty. I managed to find a small scenario that seem to reproduces the problem.

- Neo4j version: 4.4.11CE
- Operating system: Ubuntu 22.04

**Steps to reproduce**
1. In a new database (in my environment: `docker run -d --rm  --name=neo4j  -p=7474:7474 -p=7687:7687  --volume=~/neo4j/data:/data --env=NEO4J_AUTH=none neo4j:4.4.11`
2. Execute `CREATE INDEX ON :Attribute(_type);`
3. `CREATE (c:Attribute {_type:'myType',name:'c'});`
4. 
```
CREATE (a:Attribute  {_type:'myType',    name:'a'})
CREATE (b:Attribute  {_type:'myType',    name:'b'})
CREATE (a)-[:Parent {cardinality:'1..1'}]->(b);
```
5. Execute 
```MATCH (a:Attribute {name:'a'})
OPTIONAL MATCH (a)-[l:Parent]->(b:Attribute)
WHERE b._type IN ['myType','otherType']
RETURN a.name,  collect(b.name)
--> return ("a" [])
```
**--> Here is the bug**, expected: `("a" ["b"])`
6. Execute 
```MATCH (a:Attribute {name:'a'})
OPTIONAL MATCH (a)-[l:Parent]->(b:Attribute)
WHERE b._type='myType'
RETURN a.name,  collect(b.name)
--> return ("a" ["b"]) <- it's correct
```
7. Repeat step 5, still wrong response, even after a few minutes.

### Expected behavior
Step 5 should return `("a" ["b"])`

### Actual behavior
Step 5 returns `("a" [])`

**Observations**
- Skip step 2 -> it works
- Skip step 3 -> it works
- Switch steps 5 & 6 -> it works
- neo4j 4.4.10 -> it works
-  If I restart neo4j -> step 5 works

I hope it's clear enough.

**Comment by HannesSandberg** [comment] 2022-10-14 07:21
Thanks for the report! We will investigate and come back to you.

**Comment by arnefischereit** [comment] 2022-10-14 13:32
Hi @simondaudin ,
I tried to reproduce the issue on my machine running neo4j 4.4.11 in docker but without avail. This is my session in cypher-shell:

```
Connected to Neo4j using Bolt protocol version 4.4 at neo4j://localhost:7687 as user neo4j.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
neo4j@neo4j> CREATE INDEX ON :Attribute(_type);
0 rows
ready to start consuming query after 47 ms, results consumed after another 0 ms
Added 1 indexes
neo4j@neo4j> CREATE (c:Attribute {_type:'myType',name:'c'});
0 rows
ready to start consuming query after 84 ms, results consumed after another 0 ms
Added 1 nodes, Set 2 properties, Added 1 labels
neo4j@neo4j> CREATE (a:Attribute  {_type:'myType',    name:'a'})
             CREATE (b:Attribute  {_type:'myType',    name:'b'})
             CREATE (a)-[:Parent {cardinality:'1..1'}]->(b);
0 rows
ready to start consuming query after 86 ms, results consumed after another 0 ms
Added 2 nodes, Created 1 relationships, Set 5 properties, Added 2 labels
neo4j@neo4j> OPTIONAL MATCH (a)-[l:Parent]->(b:Attribute)
             WHERE b._type IN ['myType','otherType']
             RETURN a.name,  collect(b.name);
+--------------------------+
| a.name | collect(b.name) |
+--------------------------+
| "a"    | ["b"]           |
+--------------------------+

1 row
ready to start consuming query after 386 ms, results consumed after another 11 ms
```

If you still can reproduce the issue, can you then please send the output of an `EXPLAIN` of the faulty query?

**Comment by InverseFalcon** [comment] 2022-10-17 18:39
As an additional suggestion, if the problem is still reproducible, see if prefixing the query with `CYPHER runtime=SLOTTED` results in correct behavior. Whether that mitigates this or not may give us a clue for where the problem is.

**Comment by simondaudin** [comment] 2022-10-27 10:07
Hi, unfortunately, I can't reproduce this specific test, even on my environment, I was quite confident at the time I posted the issue :thinking: 
However, in our test environment, at least, we get the error every time. 
4.4.11, 4.4.12 -> Error
4.4.10 -> There is no problem
I tried to trim as much as possible, but needed to run it 10 times to get the error once.
I cannot try `CYPHER runtime=SLOTTED` since I'm using community edition.
However, by trying with `CYPHER runtime=Interpreted`, I got the correct answer. From what I understant, `interpreted` is the default one, so I guess the difference is due to some cache stuff.

Here is my new test
```
CREATE INDEX ON :Attribute(_type);

CREATE (sGlobal:Scope {tag: 'class=scope,scope=global', name:'global'})
CREATE (scopeSP:Scope {tag: 'class=scope,scope=sp', name:'sp'})

CREATE (globalScopeAttribute:Attribute  {_type:'scope',     name:'global',              _internal:true})
CREATE (dWan:Attribute                  {_type:'domain',    name:'iwan',                _internal:true})
CREATE (netCpe:Attribute                {_type:'neType',    name:'cpe',                 requiredProperties : ['vendor']})
CREATE (netSdEdge:Attribute             {_type:'neType',    name:'sdEdge',              requiredProperties : ['vendor']})
CREATE (netSdPath:Attribute             {_type:'neType',    name:'sdPath',              requiredProperties : ['vendor'], networkLayer:'overlay'})
CREATE (netWanLink:Attribute            {_type:'neType',    name:'wanLink',             requiredProperties : ['vendor'], networkLayer:'underlay'})
CREATE (netPe:Attribute                 {_type:'neType',    name:'pe'})
CREATE (netCloudPort:Attribute          {_type:'neType',    name:'cloudPort',           requiredProperties : ['vendor'], _defaultScope:'client'})
CREATE (netCloudEdge:Attribute          {_type:'neType',    name:'cloudEdge'})
CREATE (netViewpoint:Attribute          {_type:'neType',    name:'viewpoint',           requiredProperties : ['vendor']})
CREATE (netApp:Attribute                {_type:'neType',    name:'application',         _overridable:true, _crudable: true})
CREATE (cAppDictionary:Attribute        {_type:'cluster',   name:'dpiDictionary'})
CREATE (cAppGroup:Attribute             {_type:'cluster',   name:'relevance'})
CREATE (cAppCategory:Attribute          {_type:'cluster',   name:'category'})
CREATE (cAppUser:Attribute              {_type:'cluster',   name:'applicationUser',     _crudable: true})

CREATE (cAppDictionary)<-[:Parent {cardinality:'1..1'}]-(netApp)
CREATE (cAppGroup)<-[:Parent {cardinality:'0..1'}]-(netApp)
CREATE (cAppCategory)<-[:Parent {cardinality:'0..1'}]-(netApp)
CREATE (cAppUser)<-[:Parent {cardinality:'0..n'}]-(netApp)
;
```
Then
```
MATCH (a:Attribute) WHERE a._type IN ["neType","toto"]
OPTIONAL MATCH (a)-[l:Parent]->(b:Attribute)
WHERE b._type IN ["neType","cluster","labelType","scope","domain","origin"]
RETURN a.name,  collect(DISTINCT [l, b._type+':'+b.name]) as parents
```
The query with wrong answer
![query_KO](https://user-images.githubusercontent.com/20225932/198253357-04995ee7-ac58-4f74-a3cd-f2e6a4b3cac8.png)

The query with correct answer
![query_OK](https://user-images.githubusercontent.com/20225932/198253346-74019c13-756b-48b4-b0a7-9b1d5a68b4b6.png)

The plan associated to wrong answer
![plan_KO](https://user-images.githubusercontent.com/20225932/198254266-422417f6-f815-4429-bfe6-a790ebd3c242.svg)

The plan associated to correct answer
![plan_OK](https://user-images.githubusercontent.com/20225932/198254338-ab05fb1a-6049-4ce2-9961-abaaf1a5cb9c.svg)

I tried to get it down to something as simple as possible, but it stays quite elusive. I Hope it helps.

**Comment by arnefischereit** [comment] 2022-10-31 14:23
Hi @simondaudin,

Thank you for getting back with some more feedback.

Some comments:
- I ran the first plan ("The plan associated to wrong answer") on the dataset that you described and it did correctly return an answer for the `collect` part of the query.
- As far as I can see, the plan that you describe to be returning the correct answer does not actually test whether `b` has the label `:Attribute`, so I am very surprised that the system uses this plan at all.

Even though we cannot reproduce the issue, its most likely problem is that the index you have installed is not up to date with the entries yet. We therefore generally recommend creating entities first and then the index. That way we either use the index in a fully functional form or we do not use the index, which might be slower but still is correct.

This should solve the issue for you. Otherwise, we would probably need to clarify which plan is connected to which result and possibly also run the query not only with `EXPLAIN` but also with `PROFILE`

**Comment by simondaudin** [comment] 2022-11-02 13:32
Some more info 

> As far as I can see, the plan that you describe to be returning the correct answer does not actually test whether b has the label :Attribute, so I am very surprised that the system uses this plan at 

In the plan, I see `WHERE cache[b._type] IN $autolist_1 AND b:Attribute` -> **AND b:Attribute** this is were the label is tested, right ?

> We therefore generally recommend creating entities first and then the index

I'm not sure to fully understand. We usually create the data structure in the first place, and then populate the data.

> Even though we cannot reproduce the issue, its most likely problem is that the index you have installed is not up to date with the entries yet

Once I run a query that returned the wrong answer, I can wait 10min, it would still be false. Is it some kind of cache issue ?

> Otherwise, we would probably need to clarify which plan is connected to which result and possibly also run the query not only with EXPLAIN but also with PROFILE

I have the profile associated to the "wrong answer"
![profile_KO](https://user-images.githubusercontent.com/20225932/199500013-7d05a330-6a66-40fe-9c35-4640cc0b9206.svg)

the profile associated to the "correct answer"
![profile_OK](https://user-images.githubusercontent.com/20225932/199500590-87ba8dea-e756-47be-b201-840d05a3cd49.svg)

- By changing a little bit my query, it seems to have always the correct answer

Previous query
```
MATCH (a:Attribute) WHERE a._type IN ["neType","toto"]
OPTIONAL MATCH (a)-[l:Parent]->(b:Attribute)
WHERE b._type IN ["neType","cluster","labelType","scope","domain","origin"]
RETURN a.name,  collect(DISTINCT [l, b._type+':'+b.name]) as parents
```
New query
```
MATCH (a:Attribute) WHERE a._type IN ["neType","toto"]
OPTIONAL MATCH (a)-[l:Parent]->(b)
WHERE b._type IN ["neType","cluster","labelType","scope","domain","origin"]
RETURN a.name,  collect(DISTINCT [l, b._type+':'+b.name]) as parents
```

- Just to be clear, this behavior appeared with the version 4.4.11

**Comment by pontusmelke** [comment] 2022-12-14 08:18
Hi @simondaudin 
I have been trying to reproduce this issue but so far I cannot. As @arnefischereit mentioned maybe it is a problem with the indexes? Can you try moving the index creation to after the data has been created, and/or call `CALL db.prepareForReplanning()` just before you run the failing query?

UPDATE: I have looked at this some more and even though I still haven't been able to reproduce, we did a bug fix in 4.4.14 that might be relevant for your case. So if possible please try to update to a version 4.4.14 or later and see if the problem goes away.

Best regards,
Pontus

**Comment by simondaudin** [comment] 2022-12-19 10:36
Hi
Thanks for the reply.
I run my tests many times, it really seems that the problem actually disappears with the 4.4.13, as I could not reproduce it with this version and the next ones.
Thank you for the effort. I guess I would consider it fixed, from my point of view.

**Comment by pontusmelke** [comment] 2022-12-21 08:01
Ok, thanks again for reporting!

I'll close this issue now but don't hesitate to reopen or create a new issue should the problem reappear.

Regards
Pontus

**Closed as completed by pontusmelke** 2022-12-21 08:01 UTC
Labels: bug, team-cypher
