### ISSUE TITLE
[Cypher] Relationship and node is not deleted, when parent node is deleted before in same transaction

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#5981] opened 2015-11-27 14:24 UTC
Hi.

We are using Neo4j 2.3.1.
### What we are doing

First transaction: create 2 nodes and connect them via relationship.

Second transaction: 
1. Delete via Cypher parent node.
2. Delete via Cypher relationship and child node.

When doing same thing via Java API, everything is OK, all data is successfully deleted. 
When doing this via Cypher, nothing is deleted at second step. And no errors are thrown. Then, when transactions is closed exception is thrown, which states that Node can't be deleted, because there are existing relationships for this node (which is true, because nothing was deleted at second step).

If we try to execute second step without first step (delete relationship and child node), data are successfully deleted.

Complete Java example: https://gist.github.com/FylmTM/3c7708c7a5cc3ed6f4a7

Expected result - successful run, and no data in database.

---
### Undefined behaviour

We know that operating with deleted Node is UB. However we are not sure about this case, what is actually happening. Is it UB issues, or just a bug?

**Comment by jexp** [comment] 2015-11-27 14:38
I think as the statement results are committed in order of execution, the deletion of the first node comes first. It is much easier to reproduce:

```
create (:Foo)-[:FOOBAR]->(:Bar)

:POST /db/data/transaction/commit {"statements":[{"statement":"MATCH (f:Foo) DELETE f"},{"statement":"MATCH ()-[r:FOOBAR]->(b:Bar) DELETE r DELETE b"}]}
```

Results in:

```
     "code": "Neo.DatabaseError.Transaction.CouldNotCommit",
      "message": "org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[1,used=false,rel=0,prop=-1,labels=Inline(0x0:[]),light] still has relationships",
      "stackTrace": "java.lang.RuntimeException: org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[1,used=false,rel=0,prop=-1,labels=Inline(0x0:[]),light] still has relationships\n\tat org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.commit(TransitionalTxManagementKernelTransaction.java:87)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.closeContextAndCollectErrors(TransactionHandle.java:279)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:148)\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Node record Node[1,used=false,rel=0,prop=-1,labels=Inline(0x0:[]),light] still has relationships\n\tat org.neo4j.kernel.impl.transaction.state.IntegrityValidator.validateNodeRecord(IntegrityValidator.java:52)\n\tat org.neo4j.kernel.impl.transaction.state.TransactionRecordState.extractCommands(TransactionRecordState.java:170)\n\tat org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:537)\n\tat org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:456)\n\tat org.neo4j.server.rest.transactional.TransitionalTxManagementKernelTransaction.commit(TransitionalTxManagementKernelTransaction.java:83)\n\t... 33 more\n"
```

**Comment by FylmTM** [comment] 2015-11-27 15:16
Thanks @jexp . Exactly our case. I just started with creating example, that is similar to our use-case in Java.

**Comment by jexp** [comment] 2015-11-27 16:59
Sorry, can't reproduce, I had old data in my database, now it works perfectly.

``` json
:POST /db/data/transaction/commit {"statements":[{"statement":"MATCH (f:Foo) DELETE f"},{"statement":"MATCH ()-[r:FOOBAR]->(b:Bar) DELETE r DELETE b"}]}
{
  "results": [
    {
      "columns": [],
      "data": []
    },
    {
      "columns": [],
      "data": []
    }
  ],
  "errors": []
}
```

I also created a test which works in all cases

``` java
package test;

import org.junit.Test;
import org.neo4j.graphdb.*;
import org.neo4j.kernel.GraphDatabaseAPI;
import org.neo4j.kernel.api.DataWriteOperations;
import org.neo4j.kernel.api.Statement;
import org.neo4j.kernel.api.exceptions.EntityNotFoundException;
import org.neo4j.kernel.api.exceptions.InvalidTransactionTypeKernelException;
import org.neo4j.kernel.impl.api.store.RelationshipIterator;
import org.neo4j.kernel.impl.core.ThreadToStatementContextBridge;
import org.neo4j.test.TestGraphDatabaseFactory;

import static java.util.Collections.singletonMap;
import static org.neo4j.graphdb.Direction.BOTH;

/**
 * @author mh
 * @since 27.11.15
 */
public class TransactionDeleteTest {
    @Test
    public void testDeleteInTxKernel() throws InvalidTransactionTypeKernelException, EntityNotFoundException {
        GraphDatabaseService db = new TestGraphDatabaseFactory().newImpermanentDatabase();
        long[] nodes = createData(db);
        ThreadToStatementContextBridge ctx = ((GraphDatabaseAPI) db).getDependencyResolver().resolveDependency(ThreadToStatementContextBridge.class);
        try (Transaction tx = db.beginTx()) {
            Statement statement;

            statement = ctx.get();
            statement.dataWriteOperations().nodeDelete(nodes[0]);
            statement.close();

            statement = ctx.get();
            DataWriteOperations writes = statement.dataWriteOperations();
            RelationshipIterator it = statement.readOperations().nodeGetRelationships(nodes[1], BOTH);
            while (it.hasNext()) {
                writes.relationshipDelete(it.next());
            }
            writes.nodeDelete(nodes[1]);
            statement.close();
            tx.success();
        }
        db.shutdown();
    }

    @Test
    public void testDeleteInTxJava() {
        GraphDatabaseService db = new TestGraphDatabaseFactory().newImpermanentDatabase();
        long[] nodes = createData(db);
        try (Transaction tx = db.beginTx()) {
            db.getNodeById(nodes[0]).delete();
            Node bar = db.getNodeById(nodes[1]);
            for (Relationship rel : bar.getRelationships()) {
                rel.delete();
            }
            bar.delete();
            tx.success();
        }
        db.shutdown();
    }

    @Test
    public void testDeleteInTxCypher() throws InvalidTransactionTypeKernelException, EntityNotFoundException {
        GraphDatabaseService db = new TestGraphDatabaseFactory().newImpermanentDatabase();
        createData(db);
        try (Transaction tx = db.beginTx()) {
            db.execute("MATCH (f:Foo)  DELETE f").close();
            db.execute("MATCH ()-[r:FOOBAR]->(b:Bar) DELETE r DELETE b").close();
            tx.success();
        }
        db.shutdown();
    }
    @Test
    public void testDeleteInTxCypher2() throws InvalidTransactionTypeKernelException, EntityNotFoundException {
        GraphDatabaseService db = new TestGraphDatabaseFactory().newImpermanentDatabase();
        long[] nodes = createData(db);
        try (Transaction tx = db.beginTx()) {
            db.execute("MATCH (n) WHERE id(n) = {id} DELETE n", singletonMap("id",nodes[0])).close();
            db.execute("MATCH (n)-[r]-() WHERE id(n) = {id} DELETE r WITH n MATCH (m) WHERE id(m) = {id} DELETE m", singletonMap("id",nodes[1])).close();
            tx.success();
        }
        db.shutdown();
    }

    private long[] createData(GraphDatabaseService db) {
        try (Transaction tx = db.beginTx()) {
            Node foo = db.createNode(DynamicLabel.label("Foo"));
            Node bar = db.createNode(DynamicLabel.label("Bar"));
            foo.createRelationshipTo(bar, DynamicRelationshipType.withName("FOOBAR"));
            tx.success();
            return new long[] {foo.getId(), bar.getId()};
        }
    }
}
```

**Comment by chrisvest** [comment] 2018-05-09 11:55
Looks like this was fixed in some 3.x version. Closing.

**Closed as completed by chrisvest** 2018-05-09 11:55 UTC
Labels: 2.3, team-kernel
