### ISSUE TITLE
why neo4j-java-driver connecting to neo4j 4.0 using bolt v3 

### ISSUE THREAD

**Issue by leehom** [neo4j/neo4j#13256] opened 2023-07-18 03:09 UTC
client that neo4j-java-driver 5.2.0 connect to neo4j 4.0 using bolt v3，but neo4j 4.0 support bolt v4，how to make neo4j supporting bolt v4

**Comment by robsdedude** [comment] 2023-08-17 08:17
Hi and thanks for reaching out.

That is by design. 5.x.x drivers officially support (and are tested against) Server version 4.4.x and 5.x.x. Everything else might work, might partially work, might work incorrectly or might not work at all. If you want a driver that fully supports server version 4.0 (which is EOL, btw.), please use the latest 4.4.x driver.

See also https://neo4j.com/developer/kb/neo4j-supported-versions/

**Comment by robsdedude** [comment] 2023-08-17 09:44
I will close the issue. Feel free to keep commenting if you have further questions about this.

**Closed as completed by robsdedude** 2023-08-17 09:44 UTC
Labels: team-drivers
