### ISSUE TITLE
MATCH with multiple labels returns node with wrong label in Neo4j 4.1 & 4.2

### ISSUE THREAD

**Issue by cmorgner** [neo4j/neo4j#12704] opened 2021-04-10 09:30 UTC
We are running multiple parallel integration tests against a Dockerized Neo4j database. Each test adds and removes a very similar set of nodes that only differ in one label (a random "tenant identifier"). With Neo4j 4.x we see random test failures that I tracked down to receiving a Neo4j Record with a wrong label coming from the below query.

Neo4j versions: 4.1.8, 4.2.5 (Docker versions 4.1, 4.2, 4.2-enterprise)
Operating System: Ubuntu 20.10
API: Reactive Java Driver versions 4.1.1, 4.2.4

*Note*: we do not create any indexes in our test setup.

### Expected behaviour
```
MATCH (n:NodeInterface:YWRYQFALBS:SchemaNode:NodeInterface) WHERE n.`name` = "Group" RETURN DISTINCT n
```
should return only nodes that match *all* the labels

### Actual behaviour
![Screenshot_2021-04-09 neo4j neo4j 172 17 0 2 7687 neo4j - Neo4j Browser](https://user-images.githubusercontent.com/311577/114264968-5a3ac800-99ee-11eb-90dc-ae6016c23904.png)

The query returns two nodes. One of them does *not* have all the labels present in the query.

- removing the second `NodeInterface` label in the query does not change the result.
- removing the `SchemaNode` label fixes the result

### Steps to reproduce
I was not able to reproduce the issue with a simple set of statemets. It occurs randomly during our integration test suite when different test threads execute multiple statements with random identifiers (NCRLAOJOUF and YWRYQFALBS in this case).

#### Some debugging output that I produced while tracking down the problem:
```
Query:
    MATCH (n:NodeInterface:FEAVTULPKR:SchemaNode:NodeInterface) WHERE n.`name` = $param0 RETURN DISTINCT n, n.`create...
Result (Neo4j Records!):
    Result 1:
        properties: {defaultVisibleToPublic=false, hidden=false, lastModifiedDate=1617998894953, lastModifiedBy=00000...
        labels: [LUCFWEFBAS, SchemaNode, AbstractSchemaNode, Schema, SchemaReloadingNode, AbstractNode, NodeInterface...
    result 2:
        properties: {defaultVisibleToPublic=false, hidden=false, lastModifiedDate=1617998894268, lastModifiedBy=00000...
        labels: [FEAVTULPKR, SchemaNode, AbstractSchemaNode, Schema, SchemaReloadingNode, AbstractNode, NodeInterface...
```

#### Similar output with some more info, but only a screenshot unfortunately:
![neo4j-query-bug](https://user-images.githubusercontent.com/311577/114265232-f5806d00-99ef-11eb-93e7-28b8d6e2dc83.png)

#### Neo4j debug log from the docker container:
[debug.log](https://github.com/neo4j/neo4j/files/6289584/debug.log)

**Comment by loveleif** [comment] 2021-04-20 10:45
Thanks for reporting this @cmorgner and sorry for the inconvenience! We're investigating. Could you provide some details about the creates and removes that you mentioned is part of your testing?

**Comment by cmorgner** [comment] 2021-04-21 15:12
Hi, thank you for investigating the issue!

Here is the full output (with Cypher logging enabled) for the two tests. Each test class is run in a different JVM, and each test class determines a random label string that is added to all queries, working as a kind of a tenant identifier. After each test method, the database is wiped using the following statement:

    MATCH (n:UBNUMLKBWX) DETACH DELETE n

The error first appears in line 9240 of org.structr.test.common.AccessControlTest-output.txt. The lines after 9240 contain the node's ID, the labels and the properties, written out directly from the Neo4j Record object:

    final Node node = v.asNode();
    System.out.println(node.id());
    System.out.println(node.labels());
    System.out.println(node.asMap());

The result of the MATCH query in line 9240 returns two nodes. One has a label that is not known in this JVM (UBNUMLKBWX), and is never seen in the whole file, except in those places where it is returned from a validation query.

The origin of that label is a different test whose output you can see in org.structr.test.common.PermissionResolutionTest-output.txt.

I was hoping to be able to send you the actual database with the error in the data, but I was not able to preserve the data, so it's only visible in the test output. :(

[failing-test-output.tar.gz](https://github.com/neo4j/neo4j/files/6351955/failing-test-output.tar.gz)

**Comment by loveleif** [comment] 2021-04-22 16:25
Hi again @cmorgner, thanks for being so cooperative! We made a quick and naive attempt to reproduce this in our own load testing, but failed. I would like to make a more serious effort and mirror your setup more closely and let that run for a longer period. If you have the time I would greatly appreciate any more information you could provide to increase the chance of reproducing the error.

## Unknowns

- What hardware is used?
- A code snippet how you interact with the driver would be great if possible.
- Are all queries run in a separate transaction?
- Is the database running on the same machine as the tests?
- Are the tests run concurrently on the same machine or across multiple ones? How many machines/threads are used to run the tests? 
- How often do you encounter this?
- Are there any indexes in the database?
- What kind of db user/users are running the test (full access or restricted somehow)?
- I noticed you're using TestNG, is there any specifics about your setup there that could be helpful?

## Test procedure

I imagine something roughly(!) like this, based on what I've seen in the log file. I plan to re-run until failure or stopped (dump database on failure). Run x number of threads concurrently on x machines.

Pseudo/java code:

```java
var randomLabel = generateRandomLabel()
var iterations = ???

for (int i = 0; i < iterations; i++) {
  // Create two node with random label, some other set of labels and some properties:
  var nodeId1 = runQuery("CREATE (n:$randomLabel:... $someProperties) RETURN n")
  var nodeId2 = runQuery("CREATE (n:$randomLabel:... $someMoreProperties) RETURN n")

  // Set some additional properties on the created nodes
  runQuery("MATCH (n:$randomLabel) WHERE ID(n) = $nodeId1 SET n += $additionalProperties")
  runQuery("MATCH (n:$randomLabel) WHERE ID(n) = $nodeId2 SET n += $moreAdditionalProperties")

  // Create a number of relationships between the two nodes and add relationship properties
  runQuery("MATCH (n:$randomLabel), (m:$randomLabel) WHERE ID(n) = $nodeId1 AND ID(m) = $nodeId2 MERGE (n)-[r:$someRelType]->(m) SET r += $someRelProperties RETURN r")
  runQuery("MATCH (n:$randomLabel), (m:$randomLabel) WHERE ID(n) = $nodeId1 AND ID(m) = $nodeId2 MERGE (n)-[r:$someOtherRelType]->(m) SET r += $someRelProperties RETURN r")
  ...

  // Assert that we get the expected node(s) back with correct labels when querying based on labels and properties
  var result = runQuery("MATCH (n:{randomLabel + subset of other labels} WHERE n.name = $name RETURN DISTINCT n")
  assertCorrectResult(result, randomLabel)
}

// Delete all nodes of the random label
runQuery("MATCH (n:{randomLabel}) DETACH DELETE n")
// Go to start
```

**Comment by cmorgner** [comment] 2021-04-22 18:57
Hi @loveleif here are my answers to your questions, and some additional info:

## Answers

### What hardware is used?
We are running our tests on our local machines and our CI server. Mine is an Intel Core i7-5820K, our CI server is an Intel Xeon E5-1620 v3. There are some other machines where the tests run, but those two are the main machines used to run the tests.

### A code snippet how you interact with the driver:
You can see the entire source code of Structr on github, at https://github.com/structr/structr. The driver that we use (and the actual code snippets) can be found here: https://github.com/structr/structr/blob/master/structr-neo4j-bolt-driver/src/main/java/org/structr/bolt/ReactiveSessionTransaction.java

### Are all queries run in a separate transaction?
No, we run many queries in one transaction. Structr is an application platform and we rely heavily on the rollback of all changes when an error occurs etc., hence the transactional context is kind of large.

### Is the database running on the same machine as the tests?
Yes, the whole test suite runs on the same machine, but the Neo4j instance runs in a docker container. See https://github.com/structr/structr/blob/master/structr-test-configuration/pom.xml

### Are the tests run concurrently on the same machine or across multiple ones?
The tests run concurrently on exactly one machine.

### How many machines/threads are used to run the tests?
We use a forkCount of 3, so there are 3 different JVM instances that run queries against the same dockerized Neo4j instance.

### How often do you encounter this?
On my local machine, I have to run the tests about 3 to 7 times to produce the error. On our CI server which is significantly slower, the tests failed almost every time (until we went back to Neo4j 3.5)

### Are there any indexes in the database?
No, we are not creating indexes in the database for most of our tests.

### What kind of db user/users are running the tests?
Full access on Bolt driver level, using the default neo4j/admin user.

### Test NG specifics
I would say that there are no special settings other than the fact that we start Neo4j in a Cocker container. You can find our test setup here: https://github.com/structr/structr/blob/master/structr-test-configuration/pom.xml

## Some more info
- The test class that produces the error can be found here: https://github.com/structr/structr/blob/master/structr-core/src/test/java/org/structr/test/common/AccessControlTest.java
- You should theoretically be able to clone Structr from https://github.com/structr/structr, checkout the branch `neo4j-4.2-label-bug` and run mvn verify to run the tests on your local machine (I'm not sure if that is an option for you at all, or if that really works without all the settings, ymmv)

That's all I have right now, but I'm more than happy to answer questions / make changes to test things etc.. I can reproduce the error on my machine quite easily (but I know that it's a completely different thing than being able to run the tests in one's own dev environment.. :) )

**Comment by cmorgner** [comment] 2021-04-25 14:44
@loveleif I was testing the new 4.3.0-alpha01 Java driver today (it still has the bug), and I managed to capture the erroneous state in the database, so I now have an archive of the data/ folder that shows the bug.

## Steps to reproduce:
- copy the data.tar.gz archive into a newly extracted Neo4j Enterprise 4.2.5 folder
- extract the archive
- start the database
- log in with neo4j/admin
- run the following query: `MATCH (n:NodeInterface:AJSNPSDMWP:SchemaNode:NodeInterface) where n.name = "MailTemplate" return n`
- Result are two nodes, one has the label SMKCPECNKG instead of the requested one AJSNPSDMWP, see screenshot

![Screenshot_2021-04-25 neo4j bolt localhost 7687 neo4j - Neo4j Browser](https://user-images.githubusercontent.com/311577/115997813-d1727d80-a5e4-11eb-8cbd-b19ec8159868.png)

## Database
... I can't upload the file because it has a size of 51 MBs, so I uploaded the file here:
https://structr.com/public/share/data.tar.gz

**Comment by loveleif** [comment] 2021-04-26 07:32
Thank you @cmorgner! We're prioritising this, I will post updates here.

**Comment by loveleif** [comment] 2021-04-26 08:51
The database dump fails our database consistency check (which is no big surprise). The question remains how it ended up in this state. We (the cypher team) have handed the issue to our kernel team for further investigation. Thanks again!

**Comment by tinwelint** [comment] 2021-05-03 10:58
Hi @cmorgner I'm looking into this now. I initially tried to reproduce this and got the tests running and I tried to run two different JVMs, one running AccessControlTest and the other PermissionResolutionTest on and on until failure and they ran for a very long time without failing.

@loveleif previously stated that the database dump you sent had inconsistencies, but that's not true since the inconsistencies were about not cleanly shut down indexes, which might as well be an issue on our side trying to run the checker on a non-clean shutdown after testing out the db in other ways. When I run the consistency check on your database it doesn't report any issues. So I believe what you see is an intermediary state of some sort.

Also I couldn't map your tenant IDs to the actual db. Your initial description (the screenshot) mentions to tenant IDs, the text you're providing talks about _two other_ tenant IDs and none of those four tenant IDs can be found in the database you sent. I would suggest that you try to capture this again and send a new database dump with the relevant tenant IDs and query logs as you did before. I think that'd be the best bet for me to try to find the issue here.

Best,
Mattias

**Comment by cmorgner** [comment] 2021-05-03 11:22
Hi Mattias,

I just downloaded the data.tar.gz from https://structr.com/public/share/data.tar.gz, extracted the archive in a newly extracted neo4j Enterprise 4.2.5, started the database with `bin/neo4j start` and got the following output when executing `MATCH (n:NodeInterface:AJSNPSDMWP:SchemaNode:NodeInterface) where n.name = "MailTemplate" return n`.

![Screenshot_2021-05-03 neo4j bolt localhost 7687 neo4j - Neo4j Browser(1)](https://user-images.githubusercontent.com/311577/116869463-14e67080-ac11-11eb-88a6-57ee5547bd80.png)

The tenant IDs in the initial issue descriptions are not valid any more, since that was from a previous attempt that I didn't save.

Do you see any data at all in the database? You should see 2042 nodes with 9 different tenant-ID style labels (all upper-case random characters) like in the screenshot.

The inconsistency and the wrong query results remain over a restart of the database. Here are the logs:
[logs.tar.gz](https://github.com/neo4j/neo4j/files/6414479/logs.tar.gz)

Can you confirm that you don't see any nodes with labels AJSNPSDMWP or SMKCPECNKG in the database from the data.tar.gz that you downloaded from https://structr.com/public/share/data.tar.gz?

**Comment by cmorgner** [comment] 2021-05-10 07:04
@tinwelint any update on this? I checked the uploaded archive again, and I'm pretty sure that it contains the labels AJSNPSDMWP or SMKCPECNKG, can you confirm or deny that?

**Comment by tinwelint** [comment] 2021-05-10 11:12
Thanks for the tenant IDs there, I haven't had time to work on this, but hopefully some time this week!

**Comment by tinwelint** [comment] 2021-05-17 08:08
Hi again, I believe I've found an issue in our low-level cursors where a node cursor may sometimes incorrectly say "true" for a hasLabel(label) call. Investigating further!

**Comment by tinwelint** [comment] 2021-05-17 09:50
I have a fix and it's confirmed to work on your example database too. I'll ping you on this issue when it's been merged.

**Comment by cmorgner** [comment] 2021-05-17 12:41
That's great news, thank you very much! :)

**Comment by tinwelint** [comment] 2021-05-18 14:33
The PR has now been merged, but not yet sure (nor in control of) when next 4.2.x release comes out

**Comment by cmorgner** [comment] 2021-05-18 14:48
Ok, thanks for the notification! When the next version comes out, I will change our test setup back to 4.2 and let you know the results! :)

**Comment by tinwelint** [comment] 2021-05-18 16:58
OK, and if you wonder 4.1 and 4.3 will also get this fix applied (earlier versions didn't have this issue)

**Closed as completed** 2021-05-24 11:29 UTC
Labels: bug, team-cypher, team-kernel
