### ISSUE TITLE
Cannot install Neo4j 3.0.0 on Xenial Docker images

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#7052] opened 2016-05-03 16:59 UTC
## .deb signature problem

I tried to use the current Debian neo4j repository .deb packages and ran into 2 or 3 different problems with the signatures.

**Neo4j Version:** 3.0.0 
**Operating System:** Ubuntu 16.04 
**API:** .deb Installation
### Steps to reproduce
1. `wget -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add -`
2. `apt-get update && apt-get -y install --no-install-recommends neo4j=3.0.0`
3. `file neotechnology.gpg.key`
### Expected behavior
1. It should install without issues.
2. It should be using a secure form of signature
3. It should use a recent version of a PGP key (file should _not_ identify it is old)

(those may only be 2 issues rather than 3)
### Actual behavior
1. It won't install due to hash sum mismatch
2. It is using sha1 for a signature type
3. File identifies it as a "old" style signature

**Here are the messages from the apt-key add step**

```
2016-05-03 16:39:02--  http://debian.neo4j.org/neotechnology.gpg.key
Resolving debian.neo4j.org (debian.neo4j.org)... 52.0.233.188
Connecting to debian.neo4j.org (debian.neo4j.org)|52.0.233.188|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1679 (1.6K) [application/octet-stream]
Saving to: 'STDOUT'
```

**Here are the messages from the apt-get install step**

```
Ign:1 http://debian.neo4j.org/repo stable/ InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://debian.neo4j.org/repo stable/ Release [1479 B]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [93.3 kB]
Get:5 http://debian.neo4j.org/repo stable/ Release.gpg [819 B]
Get:6 http://debian.neo4j.org/repo stable/ Packages [27.2 kB]
Err:6 http://debian.neo4j.org/repo stable/ Packages
  Hash Sum mismatch
Get:7 http://archive.ubuntu.com/ubuntu xenial-security InRelease [92.2 kB]
Fetched 215 kB in 1s (178 kB/s)
Reading package lists...
W: http://debian.neo4j.org/repo/stable/Release.gpg: Signature by key 66D34E951A8C53D90242132B26C95CF201182252 uses weak digest algorithm (SHA1)
E: Failed to fetch http://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Here is the output from file**

```
neotechnology.gpg.key: PGP public key block Public-Key (old)
```

**Comment by Alan-R** [comment] 2016-05-03 20:55
This is not specific to the 3.0.0 release. I have the same problems when trying to use the 2.3.3 release.

This means I'm dead in the water in terms of putting out a new release until this is fixed. It also means that anyone who uses a Debian-derived release is dead in the water in terms of installing your software.

**Comment by benbc** [comment] 2016-05-05 10:23
Hello Alan. I'm sorry that you're having trouble with this.

I think there are three completely separate problems here, aren't there?
1. **`Packages.gz` hash mismatch:** I cannot reproduce this. Perhaps it was a transient problem with the repo rebuilding it's metadata. Please could you try again.
2. **Warning about use of SHA1:** As I understand it this warning was introduced in Ubuntu 16.04. Attacks against APT's use of SHA1 are still theoretical, but support for it will be turned off next year ([source](https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/)). We shall clearly have to update our repository, but I don't believe that it is critical.
3. **`file` reports key as "old":** Our key is not expired (see [1]). I believe that `file` is reporting that the key uses an "old" (superseded but valid format) ([source](https://github.com/file/file/blob/da42d88766f4a015018d54c91dd9803b905c18ba/magic/Magdir/pgp)).

Please close this issue if you agree with my analysis.

-Ben

[1] Here are the full details of our signing key:

```
> gpg --search-keys 0x66D34E951A8C53D90242132B26C95CF201182252
gpg: searching for "0x66D34E951A8C53D90242132B26C95CF201182252" from hkp server keys.gnupg.net
(1) Neo Technology Admins <admins@neotechnology.com>
      4096 bit RSA key 01182252, created: 2014-10-28, expires: 2019-10-27
```

**Comment by Alan-R** [comment] 2016-05-05 10:50
Hi Ben,

I think the last two are different complaints about the same problem. I didn't mean to say that it was out of date.

The first one was the critical one. That first problem persisted through several attempts. After that I stopped trying and reported it. I'd never seen it before.

I will try again right now (I need to anyway...)

**Comment by Alan-R** [comment] 2016-05-05 11:12
Hi Ben (@benbc),

Looks like its resolved. I agree about the SHA1 attack being more theoretical than practical. I wouldn't have mentioned it if it weren't in the context of the failure. Also where I used the phrase "same problem" above, I meant to say "same issue". It's obviously not a problem worth "solving" at the present time Changing signing keys is disruptive.

It's worth noting that my two recorded observations of the problem were approximately 3 hours apart (according to when I logged it in github). I believe creating the first report took me 15-30 minutes in order to create the report in the proper format, make it look pretty, and so on. So it might have been as much as 4 hours during which time I observed that the repository was unavailable. How long it was actually unavailable is unclear.

**Comment by Alan-R** [comment] 2016-05-05 11:15
Hi Ben,

I missed your source links in your carefully researched reply. I was just all about checking the repository again. Sorry!

Many thanks for your diligence!

  -- Alan

**Comment by Alan-R** [comment] 2016-05-05 13:02
It turns out that the problem only seems to exist for Xenial Xerus (which came out last month).  Here's how to reproduce the problem using Docker. I also tried it with vivid both before and after this, and it works fine each time. Just to make sure I had the good version of Xenial, I deleted my locally cached image and pulled a fresh copy. It made no difference. The relevant Dockerfile is below:

```
FROM ubuntu:xenial
RUN apt-get update && apt-get install -y wget
RUN wget -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add - 
RUN echo "deb http://debian.neo4j.org/repo stable/" > /etc/apt/sources.list.d/neo4j.list
RUN apt-get update && apt-get -y install --no-install-recommends neo4j=3.0.0
```

Here's the resulting error message (apparently the same as before):

```
W: http://debian.neo4j.org/repo/stable/Release.gpg: Signature by key 66D34E951A8C53D90242132B26C95CF201182252 uses weak digest algorithm (SHA1)
E: Failed to fetch http://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Here are the steps to follow to reproduce this:
1. Make an empty directory and cd to it
2. Create a file called Dockerfile in that directory with the contents above
3. Run this command: `docker build .`

Here's the complete output from doing the `docker build .` command (including pulling the fresh copy of Xenial):

```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:xenial
xenial: Pulling from ubuntu
dd25ab30afb3: Pull complete 
a83540abf000: Pull complete 
630aff59a5d5: Pull complete 
cdc870605343: Pull complete 
686477c12982: Pull complete 
Digest: sha256:6b09109fc65866361139420c5582c6c41276731a877c1fb359ef3457286973ca
Status: Downloaded newer image for ubuntu:xenial
 ---> 686477c12982
Step 1 : RUN apt-get update && apt-get install -y wget
 ---> Running in 2e219cbacd49
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [93.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [92.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/main Sources [1103 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [5179 B]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [16.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [40 B]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [1989 B]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [55.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [40 B]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [12.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-security/main Sources [9434 B]
Get:17 http://archive.ubuntu.com/ubuntu xenial-security/restricted Sources [40 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial-security/universe Sources [1491 B]
Get:19 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [42.1 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [40 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [6767 B]
Fetched 22.9 MB in 1min 52s (204 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
The following additional packages will be installed:
  ca-certificates libidn11 libssl1.0.0 openssl
The following NEW packages will be installed:
  ca-certificates libidn11 libssl1.0.0 openssl wget
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2146 kB of archives.
After this operation, 6171 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libidn11 amd64 1.32-3ubuntu1 [45.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.1 [1122 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 openssl amd64 1.0.2g-1ubuntu4.1 [491 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/main amd64 ca-certificates all 20160104ubuntu1 [191 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 wget amd64 1.17.1-1ubuntu1 [297 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2146 kB in 0s (3306 kB/s)
Selecting previously unselected package libidn11:amd64.
(Reading database ... 7253 files and directories currently installed.)
Preparing to unpack .../libidn11_1.32-3ubuntu1_amd64.deb ...
Unpacking libidn11:amd64 (1.32-3ubuntu1) ...
Selecting previously unselected package libssl1.0.0:amd64.
Preparing to unpack .../libssl1.0.0_1.0.2g-1ubuntu4.1_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2g-1ubuntu4.1) ...
Selecting previously unselected package openssl.
Preparing to unpack .../openssl_1.0.2g-1ubuntu4.1_amd64.deb ...
Unpacking openssl (1.0.2g-1ubuntu4.1) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../ca-certificates_20160104ubuntu1_all.deb ...
Unpacking ca-certificates (20160104ubuntu1) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.17.1-1ubuntu1_amd64.deb ...
Unpacking wget (1.17.1-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Setting up libidn11:amd64 (1.32-3ubuntu1) ...
Setting up libssl1.0.0:amd64 (1.0.2g-1ubuntu4.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up openssl (1.0.2g-1ubuntu4.1) ...
Setting up ca-certificates (20160104ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up wget (1.17.1-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for ca-certificates (20160104ubuntu1) ...
Updating certificates in /etc/ssl/certs...
173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 ---> e6a7f35688bc
Removing intermediate container 2e219cbacd49
Step 2 : RUN wget -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
 ---> Running in 50dbd21264fb
--2016-05-05 12:58:23--  http://debian.neo4j.org/neotechnology.gpg.key
Resolving debian.neo4j.org (debian.neo4j.org)... 52.0.233.188
Connecting to debian.neo4j.org (debian.neo4j.org)|52.0.233.188|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1679 (1.6K) [application/octet-stream]
Saving to: 'STDOUT'

     0K .                                                     100% 9.90M=0s

2016-05-05 12:58:23 (9.90 MB/s) - written to stdout [1679/1679]

OK
 ---> edbe4eca99f8
Removing intermediate container 50dbd21264fb
Step 3 : RUN echo "deb http://debian.neo4j.org/repo stable/" > /etc/apt/sources.list.d/neo4j.list
 ---> Running in a63236ce32e3
 ---> 1f671994e09a
Removing intermediate container a63236ce32e3
Step 4 : RUN apt-get update && apt-get -y install --no-install-recommends neo4j=3.0.0
 ---> Running in bc81d5aea48b
Ign:1 http://debian.neo4j.org/repo stable/ InRelease
Get:2 http://debian.neo4j.org/repo stable/ Release [1479 B]
Get:3 http://debian.neo4j.org/repo stable/ Release.gpg [819 B]
Hit:4 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:5 http://debian.neo4j.org/repo stable/ Packages [27.2 kB]
Hit:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Err:5 http://debian.neo4j.org/repo stable/ Packages
  Hash Sum mismatch
Hit:7 http://archive.ubuntu.com/ubuntu xenial-security InRelease
Fetched 29.5 kB in 0s (51.4 kB/s)
Reading package lists...
W: http://debian.neo4j.org/repo/stable/Release.gpg: Signature by key 66D34E951A8C53D90242132B26C95CF201182252 uses weak digest algorithm (SHA1)
E: Failed to fetch http://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
INFO[0134] The command [/bin/sh -c apt-get update && apt-get -y install --no-install-recommends neo4j=3.0.0] returned a non-zero code: 100 

```

**Comment by benbc** [comment] 2016-05-05 13:58
I can confirm that this happens reproducibly using the `ubuntu:xenial` Docker image. However it does not happen with the `ubuntu:wily` Docker image or a clean Ubuntu 16.04 VM on EC2 (AMI ami-d56fe3a6).

**Comment by benbc** [comment] 2016-05-05 14:04
@Alan-R Do you think it would be reasonable to rename this issue for the benefit of other people browsing the issue list?

**Comment by Alan-R** [comment] 2016-05-05 14:19
I renamed it to just now. Please rename it further as you see fit. My laptop is now happily running 3.0.0 from the Xenial repository.

**Comment by moshebeeri** [comment] 2016-05-11 19:37
+1

**Comment by Alan-R** [comment] 2016-05-11 19:40
@mosheberri: Just to be clear - this is a bug in the Xenial Docker image - not a neo4j bug.

**Comment by Alan-R** [comment] 2016-05-11 19:44
@moshebeeri: Just to be clear - this is a bug in the Docker image - not in Neo4j or their web site.  I raised this issue here: https://github.com/tianon/docker-brew-ubuntu-core/issues/51 @mosheberri: Please go +1 it there - since that's where it needs to be fixed...

I'm not 100% certain this was the right place to raise it, but that's how it seemed looking at Docker hub.

**Comment by benbc** [comment] 2016-05-12 07:58
A workaround for some people may be to use the [Neo4j Docker image](https://hub.docker.com/_/neo4j/) itself.

**Comment by Alan-R** [comment] 2016-05-12 11:53
Good point @benbc. Another workaround is to build it for any other version of Ubuntu. I'm pretty sure you already know why those don't work for me (unfortunately) :-(. But it's a good reminder.

**Comment by Alan-R** [comment] 2016-06-08 14:58
FYI @benbc This problem has recurred. I'll have to leave xenial out of my supported releases unless this gets fixed in the next day or so :-(. I haven't yet looked to see if this still works from a VM. My guess is that it does... Details are in https://github.com/tianon/docker-brew-ubuntu-core/issues/51

**Comment by sauravskumar** [comment] 2016-07-16 15:57
@Alan-R were you able to get it working for docker ubuntu 16.04 ... i am facing the same issue.. can you please help... Thank You

**Comment by Alan-R** [comment] 2016-09-01 03:36
This is still broken as of today. Sorry I didn't get back sooner - but it's still broken. I removed absolutely all my docker images, and started fresh. No improvement :-(.

**Comment by Alan-R** [comment] 2016-09-01 03:41
It looks like the error occurs in the apt-get update step. Here's what I get when I run it manually:
apt-get update
Ign:1 http://debian.neo4j.org/repo stable/ InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://debian.neo4j.org/repo stable/ Release [1479 B]  
Get:4 http://debian.neo4j.org/repo stable/ Release.gpg [819 B]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Get:6 http://debian.neo4j.org/repo stable/ Packages [31.3 kB] 
Err:6 http://debian.neo4j.org/repo stable/ Packages  
  Hash Sum mismatch
Get:7 http://archive.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Fetched 224 kB in 2s (112 kB/s)  
Reading package lists... Done
W: http://debian.neo4j.org/repo/stable/Release.gpg: Signature by key 66D34E951A8C53D90242132B26C95CF201182252 uses weak digest algorithm (SHA1)
E: Failed to fetch http://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

Interestingly enough, this only happens with xenial, not any other Ubuntu release :-(.

**Comment by moshebeeri** [comment] 2016-09-01 04:48
As I see this, the issue is with the signature at
http://debian.neo4j.org/repo/stable/Packages.gz, since apt works per Ubuntu
version.
Neo4j should recheck the signature.

**Comment by Alan-R** [comment] 2016-09-01 10:16
@moshebeeri -- It's not a Neo4j issue - since the exact same signature works with every other Docker version of Ubuntu, and also outside of Docker in Xenial - as you noted by @cecilemuller who has no trouble in vagrant, and this is also consistent with my own experience. This is definitely some kind of Docker or Ubuntu docker image bug.

**Comment by hnafar** [comment] 2017-12-21 22:19
Facing the same issue. Steps to reproduce:

Dockerfile:
```
FROM ubuntu:16.04

RUN apt-get update \
	&& apt-get install curl wget -y

RUN apt-get update \
	&& apt-get install apt-transport-https -y

RUN apt-get update \
	&& apt install default-jre default-jre-headless -y

RUN wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add - \
	&& echo 'deb http://debian.neo4j.org/repo stable/' | tee -a /etc/apt/sources.list.d/neo4j.list \
	&& apt-get update \
	&& apt-get install neo4j=3.3.1 -y \

CMD bash

```

Docker build output:
```
--2017-12-21 22:16:53--  https://debian.neo4j.org/neotechnology.gpg.key
Resolving debian.neo4j.org (debian.neo4j.org)... 52.0.233.188
Connecting to debian.neo4j.org (debian.neo4j.org)|52.0.233.188|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4791 (4.7K) [application/octet-stream]
Saving to: 'STDOUT'

     0K ....                                                  100%  586M=0s

2017-12-21 22:16:53 (586 MB/s) - written to stdout [4791/4791]

OK
deb http://debian.neo4j.org/repo stable/
Ign:1 http://debian.neo4j.org/repo stable/ InRelease
Get:2 http://debian.neo4j.org/repo stable/ Release [1479 B]
Get:3 http://debian.neo4j.org/repo stable/ Release.gpg [819 B]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:6 http://debian.neo4j.org/repo stable/ Packages [45.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Err:6 http://debian.neo4j.org/repo stable/ Packages
  Hash Sum mismatch
Get:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 354 kB in 0s (364 kB/s)
Reading package lists...
E: Failed to fetch http://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -        && echo 'deb hturned a non-zero code: 100
...


```

**Comment by craigtaverner** [comment] 2018-11-07 16:46
Since this is not a Neo4j issue, and I've heard no concerns for newer versions of Ubuntu in the discussion above, can we close this issue? I think it can still be found with searches, so the useful content in the discussion above will not be lost.

**Comment by technige** [comment] 2020-02-26 09:01
Closing this issue, as per @craigtaverner's recommendation from Nov 2018. This appears to be unrelated to Neo4j.

**Closed as completed by technige** 2020-02-26 09:01 UTC
Labels: bug, team-packaging
