### ISSUE TITLE
neo4jadmin import is stuck

### ISSUE THREAD

**Issue by alonho** [neo4j/neo4j#12606] opened 2020-10-14 08:03 UTC
Running neo4j-admin gets stuck deterministically. We can see using strace there's no system call running doing IO. All threads are stuck on Mutexes.
I suspect a potential dead lock or a thread dying.

**Neo4j Version:**  4.1.2 (also reproduced on previous two versions)

### Steps to reproduce

neo4j-admin import \
    --database=$DBNAME \
    --delimiter="|" \
    --nodes=REDACTED=${NODE_DIR}/REDACTED.csv,${DATA_DIR}/REDACTED.csv \ # 44 more lines like this 
    --relationships=REDACTED=${EDGE_DIR}/REDACTED.csv,${DATA_DIR}/REDACTED.csv \ # 75 more lines like this
    --skip-bad-relationships=REDACTED \
    --skip-duplicate-nodes=REDACTED \
    --trim-strings=true

Jstack attached:

[jstack_4.1.2.txt](https://github.com/neo4j/neo4j/files/5376298/jstack_4.1.2.txt)

Console output attached:

[console.txt](https://github.com/neo4j/neo4j/files/5376579/console.txt)

The backing store is NFS which we know is not recommended by the documentation but we disabled locking by NFS so the kernel manages them locally as if the application was running locally.

**Comment by rom-burner** [comment] 2020-10-19 14:35
I too suffer neo4j-admin import getting stuck on v4.1.3, although it doesn't make it as far as @alonho .

My csv and neo4j files are on separate XFS volumes and the dataset is larger than the one described above but it gets stuck at prepare node index, the equivalent line 376 of the console log above, ie some way into the SORT stage.  It doesn't make it to DEDUP.

At that stage it's got plenty of headroom with ~160/768GB RAM and 39/96 threads used, it's not crashing but there's no real IO of note and it just does not make any progress (the delta number sporadically goes from 0 to 10k).  Now trying with heap at 30G and pagecache at 730G but stabbing in the dark.  May not be related to the same problem, but it would be nice if it were just a deadlock to fix.

Edit: Failed to make progress at same point again, here's my jstack if it helps: [jstack.txt](https://github.com/neo4j/neo4j/files/5404506/jstack.txt)

**Comment by tinwelint** [comment] 2020-10-20 13:37
@alonho not that I'm sure it causes this issue, but reading the console.txt I see that number of processors is 1. Why is that the case? Could you try to set it to something higher using `--processors=8` or similar?

**Comment by tinwelint** [comment] 2020-10-20 13:42
@rom-burner from that thread dump it looks like it's still running the sorting. Could be some weird case where it gets into some endless loop in the quick sort algo. Would you expect there to be lots of duplicates in your dataset?

**Comment by alonho** [comment] 2020-10-20 14:04
@tinwelint we're going to retry with 8 processors. Anything in the stack trace tells where in the process the import is stuck?
I understand import is used for performance reasons as it's 8 times faster than Cypher. Do you think it's still the case with recent versions?
Are there any flags we can pass to provide more information to make it easier to debug? there are hardly any logs...

**Comment by rom-burner** [comment] 2020-10-20 14:05
> Would you expect there to be lots of duplicates in your dataset?

Yes there are duplicates, probably <1% of the nodes, across 2,000 1MB csv files with strings as node:IDs.  I know it's large but is that likely to be a problem for the quicksort implementation?

**Comment by tinwelint** [comment] 2020-10-20 14:31
@alonho it looks somewhat strange and, as you say as if some thread is missing or something like that. It's in a fairly simple stage where it updates the nodes after it has defragmented the relationship group store. I'll try locally too with processors=1 and see if I can spot anything odd.

**Comment by tinwelint** [comment] 2020-10-20 14:46
And no the performance ratio between Cypher loading and importer shouldn't have changed much in recent versions to my knowledge

**Comment by alonho** [comment] 2020-10-21 08:04
@tinwelint how can we turn on more debug logs to chase down the issue? we're willing to invest efforts as it easily reproduces, just not sure what to do next ):

**Comment by tinwelint** [comment] 2020-10-21 09:21
Oh crap, I now see that one of the threads gets an exception and tries to cry panic to the import as a whole, but there's a problem on that execution path where it gets stuck doing so and therefore no exception gets printed and everything just locks up. I'll devise a fix so that the exception can propagate properly, which is step one of your problem... and we'll just see what comes out and how to solve that when we get there :)

I'll be right back

**Comment by alonho** [comment] 2020-10-21 10:49
Thanks a lot! we'll be testing it as soon as you have the fix.

**Comment by tinwelint** [comment] 2020-10-21 12:09
Alright so I have a fix for this now. Would you be OK with a patched jar file to test on until this is released in the next set of versions? If so, which version would you prefer, 4.1.2?

**Comment by alonho** [comment] 2020-10-21 14:31
I'm fine with a patched jar on 4.1.2.

**Comment by tinwelint** [comment] 2020-10-21 15:08
OK, I've built a jar of the component that has the changes. So replace the `neo4j-record-storage-engine-4.1.2.jar` with this one that I link to below and try the import again. You should now get the real thrown exception, hopefully :)

https://www.dropbox.com/s/xbvumkd7a7fj97s/neo4j-record-storage-engine-4.1.2-deadlock-fix.jar?dl=0

**Comment by alonho** [comment] 2020-10-25 08:59
Thanks @tinwelint we now get a decent report of a corruption. We're debugging the storage layer at this point to find the root cause. The change you made should definitely go to the next version.

**Comment by tinwelint** [comment] 2020-10-25 17:54
Great. Oh and when you say corruption you obviously spark my further interest. What is the error that you see? Or feel free to open another GH issue once you've gathered more information and you've boiled down the problem. Either one is fine by me.

**Comment by alonho** [comment] 2020-11-11 08:51
@tinwelint we see the following error:

`Import error: Node[2240785,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use
Caused by:Node[2240785,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use
org.neo4j.kernel.impl.store.InvalidRecordException: Node[2240785,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use`

can you give us any directions on how to debug the issue please?

**Comment by tinwelint** [comment] 2020-11-11 11:16
Thanks, but please provide the entire stack trace.

**Comment by alonho** [comment] 2020-11-11 12:26
`Write, started 2020-10-22 06:35:46.761+0000                                                                                                                                                                
[*>:26.80MiB/s------------------------------------------------------------------------|v:30.46]1.27M ∆1.27M                                                                                                
Done in 1s 101ms                                                                                                                                                                                           
Node --> Group, started 2020-10-22 06:35:47.921+0000                                                                                                                                                       
[>----------|*FIRST--------------------------------------------------------------|v:??--------] 376K ∆ 376K                                                                                                
Done in 424ms                                                                                                                                                                                              
IMPORT FAILED in 13m 53s 532ms.                                                                                                                                                                            
Imported:                                                                                                                                                                                                  
  97505320 nodes                                                                                                                                                                                           
  156715611 relationships                                                                                                                                                                                  
  465156662 properties                                                                                                                                                                                     
Peak memory usage: 2.090GiB                                                                                                                                                                                
Import error: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use                                                                                                
Caused by:Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use                                                                                                    
org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use                                                          
        at org.neo4j.kernel.impl.store.record.RecordLoad.verify(RecordLoad.java:65)                                                                                                                        
        at org.neo4j.kernel.impl.store.CommonAbstractStore.verifyAfterReading(CommonAbstractStore.java:1103)                                                                                               
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readRecordFromPage(CommonAbstractStore.java:935)                                                                                                
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:888)                                                                                                    
        at org.neo4j.kernel.impl.store.CommonAbstractStore.getRecordByCursor(CommonAbstractStore.java:869)                                                                                                 
        at org.neo4j.internal.batchimport.NodeSetFirstGroupStep.process(NodeSetFirstGroupStep.java:89)                                                                                                     
        at org.neo4j.internal.batchimport.NodeSetFirstGroupStep.process(NodeSetFirstGroupStep.java:39)                                                                                                     
        at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:83)                                                                                                    
        at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)                                                                                         
        Suppressed: java.lang.RuntimeException: org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use          
                at org.neo4j.internal.batchimport.staging.AbstractStep.assertHealthy(AbstractStep.java:156)                                                                                                
                at org.neo4j.internal.batchimport.staging.PullingProducerStep.process(PullingProducerStep.java:51)                                                                                         
                at org.neo4j.internal.batchimport.staging.ProducerStep$1.run(ProducerStep.java:63)                                                                                                         
        [CIRCULAR REFERENCE:org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use]                             
There were bad entries which were skipped and logged into /import/import.report                                                                                                                            
WARNING Import failed. The store files in /data/databases/neo4j are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe i
nconsistent records so start at your own risk or delete the store manually                                                                                                                                 
org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use                                                          
        at org.neo4j.kernel.impl.store.record.RecordLoad.verify(RecordLoad.java:65)                                                                                                                        
        at org.neo4j.kernel.impl.store.CommonAbstractStore.verifyAfterReading(CommonAbstractStore.java:1103)                                                                                               
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readRecordFromPage(CommonAbstractStore.java:935)                                                                                                
        at org.neo4j.kernel.impl.store.CommonAbstractStore.readIntoRecord(CommonAbstractStore.java:888)                                                                                                    
        at org.neo4j.kernel.impl.store.CommonAbstractStore.getRecordByCursor(CommonAbstractStore.java:869)                                                                                                 
        at org.neo4j.internal.batchimport.NodeSetFirstGroupStep.process(NodeSetFirstGroupStep.java:89)                                                                                                     
        at org.neo4j.internal.batchimport.NodeSetFirstGroupStep.process(NodeSetFirstGroupStep.java:39)                                                                                                     
        at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:83)                                                                                                    
        at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:224)                                                                                         
        Suppressed: java.lang.RuntimeException: org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use          
                at org.neo4j.internal.batchimport.staging.AbstractStep.assertHealthy(AbstractStep.java:156)                                                                                                
                at org.neo4j.internal.batchimport.staging.PullingProducerStep.process(PullingProducerStep.java:51)                                                                                         
                at org.neo4j.internal.batchimport.staging.ProducerStep$1.run(ProducerStep.java:63)                                                                                                         
        [CIRCULAR REFERENCE:org.neo4j.kernel.impl.store.InvalidRecordException: Node[26927377,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light] not in use]    `

**Comment by alonho** [comment] 2020-11-14 20:17
@tinwelint  - is the above sufficient?

**Comment by tinwelint** [comment] 2020-11-16 10:01
Thanks for the stack trace @alonho I'll ponder over this.

**Comment by PetrJanouch** [comment] 2020-11-20 08:41
@alonho Hello, I think I know the cause. If I am right it is in a feature that can be disabled, so it is easy to verify. Could you re-run your test with executing `export JAVA_OPTS=-Dorg.neo4j.io.pagecache.impl.SingleFilePageSwapper.PREALLOCATE_MAPPED_FILES=false` before invoking the neo4j-admin?

**Comment by alonho** [comment] 2020-11-23 13:00
I can confirm this fixes the issue!! Thanks @PetrJanouch and @tinwelint.
@PetrJanouch  are you able to shed some light on why this breaks on NFS (version 3) otherwise?
Could it be neo4j uses fallocate to zero out a large region of a file and ignores silently if the FS doesn't support it or something like that?
Also worth adding it to the Neo4J docs.

**Comment by PetrJanouch** [comment] 2020-11-26 09:02
@alonho It is a good guess with fallocate. We use posix_fallocate(3) to extend files. This is the important extract from its man page:
"In the glibc implementation, posix_fallocate() is implemented using
       the fallocate(2) system call, which is MT-safe.  If the underlying
       filesystem does not support fallocate(2), then the operation is
       emulated with the following caveats:

       * The emulation is inefficient.

       * There is a race condition where concurrent writes from another
         thread or process could be overwritten with null bytes."

The cause of the bug is a race condition, which we have not discovered before, because the filesystems we test on implement fallocate(2). We are working on a fix.

We try to make Neo4j run everywhere, but we cannot test every environment and if you run on environment which is not recommended stuff like this can appear, because not recommended also means untested.

**Comment by PetrJanouch** [comment] 2021-01-21 14:16
The fix for this is now included in the most recent 4.1 and 4.2 releases.

**Closed as completed by PetrJanouch** 2021-01-21 14:16 UTC
Labels: bug, team-kernel

**Comment by asad1996172** [comment] 2022-04-08 15:09
Hi @PetrJanouch, @alonho 
I think I am facing a similar issue with neo4j import tool.
I am trying to import a large amount of data but the delta for loading nodes quickly goes to 0 and then very rarely goes up. I am running this on NFS FS as well. Tried to run it with the above mentioned export command as well but it's still getting stuck.

Neo4J version: 4.4.5
![Screen Shot 2022-04-08 at 8 08 09 AM](https://user-images.githubusercontent.com/19806866/162470494-e17ce41a-3047-4677-a09c-e6ae207d6721.png)

Any suggestions?

**Comment by tinwelint** [comment] 2022-04-11 07:56
@asad1996172 If you could provide a couple of thread dumps with a couple of seconds in between, I may be able to infer why this is happening. You can produce a stack trace using either:

`kill -3 <pid>`

or

`jstack <pid>`

and the java pid can easily be spotted using

`jps -lm`

Good luck.
