### ISSUE TITLE
UnknownError when querying the database

### ISSUE THREAD

**Issue by felipebn** [neo4j/neo4j#12058] opened 2018-10-22 18:12 UTC
When querying the database I'm getting the following error:

```
Neo.DatabaseError.General.UnknownError: (n,RefSlot(4,true,Any)) (of class scala.Tuple2)
```

I'm not able right now to provide a small db/query to reproduce it.

Notes:
- Changing the database to run with CYPHER runtime INTERPRETED works fine.

**Neo4j Version:** 3.4.0-enterprise, 3.4.4-enterprise, 3.4.9-enterprise
**Operating System:** Ubuntu 18.04 / Windows 10 / Docker 
**API:** Cypher

Neo4j debug log exception: https://gist.github.com/felipebn/02dafa5b05a82c126e0c7c81958069b2

### Expected behavior
The query should return normally.

### Actual behavior
The query ends with the above error message.

**Comment by sherfert** [comment] 2018-10-23 07:40
Hi @felipebn  and thanks for the report.
Without knowing the query that caused this error, it will be very hard for us to pin it down. Is there any way for you to find the query that led to this error?

**Comment by felipebn** [comment] 2018-10-23 10:04
Hi @sherfert 

Many thanks for the quick reply!

I'm attaching a sample query that fails here https://gist.github.com/felipebn/6db8eac224c20d3354a3b8443894f3d5 .

Hints:

- If I remove the last `OPTIONAL MATCH` the query executes fine.
- Splitting the last `OPTIONAL MATCH` into two also works fine

Let me know if that helps further investigating the issue.

**Comment by sherfert** [comment] 2018-10-23 13:26
@felipebn Thanks. It would be extremely helpful to have a (small) dataset to reproduce the error, since it does work fine on an empty database. Can you make such a dataset available to us?

**Comment by felipebn** [comment] 2018-10-25 16:31
I will prepare a dataset where it happens and share the graph.db folder with you until next week.

thx!

**Comment by sherfert** [comment] 2018-11-06 09:00
@felipebn any news on that?

**Comment by felipebn** [comment] 2018-11-06 11:25
Hey @sherfert !

Sorry for the delay.

I have the same issue with another query, so I'm linking here:

- Query and stacktrace: https://gist.github.com/felipebn/88ccd551781252efa15720fea589e700
- Data set where it's possible to reproduce it: https://we.tl/t-UQCYFWGsXD

Thanks very much for the help!

**Comment by felipebn** [comment] 2018-11-14 20:02
Hey @sherfert !

The sample dataset helped debugging this issue?

**Comment by sherfert** [comment] 2018-11-15 08:37
Hi @felipebn. Yes it did! Thanks a lot for providing it.

A fix is already on its way, and will most likely make it to 3.4.11. I will close the issue as soon as the fix is merged.

**Closed as completed** 2018-11-15 12:03 UTC
Labels: team-cypher
