### ISSUE TITLE
Could not find or load main class org.neo4j.tooling.ImportTool 

### ISSUE THREAD

**Issue by tiaozi0912** [neo4j/neo4j#8558] opened 2016-12-30 01:04 UTC
Got the error `Could not find or load main class org.neo4j.tooling.ImportTool` when using the import tool with neo4j 3.1 installed with the neo4-community_macos_3_1_0.dmg on Mac El Capitan 10.11.6

The cmd I run was `/Applications/Neo4j\ Community\ Edition\ 3.1.0.app/Contents/Resources/app/bin/neo4j-import`

**Comment by spacecowboy** [comment] 2017-01-02 14:57
Thanks for the report. This is a duplicate of https://github.com/neo4j/neo4j/issues/8347 so I'll close this.

**Closed as completed by spacecowboy** 2017-01-02 14:57 UTC
