### ISSUE TITLE
[feat] Allow headers in all neo4j-admin import CSV files

### ISSUE THREAD

**Issue by j6k4m8** [neo4j/neo4j#11989] opened 2018-07-20 00:38 UTC
## Add a command-line flag to optionally ignore headers passed in subsequent CSV-import files.

As per discussion [in Slack](https://neo4j-users.slack.com/archives/C08J7ELUC/p1532041270000195), it would be very helpful to allow CSV headers in every `neo4j-admin import` file. For example, in the (truncated) command:

```shell
./bin/neo4j-admin import --id-type STRING --nodes:Nodes "mynodes-\d+.csv" ...
```

If I have only one file named `mynodes-0.csv`, then all works as planned. But if I have `mynodes-0.csv` and `mynodes-1.csv`, then `mynodes-1.csv` **must not have headers**. This seems a bit silly, since it's easy enough to ignore — and it can be a huge hassle to drop that line from every incoming CSV.

As an example user-story: [Dask's `to_csv`](https://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_csv) function, for example, is a prime candidate source for Neo4j data-import; for data consistency, this API adds a header to _all_ (or, optionally, none) of the output CSVs.

## Potential Short Term Fix

If you found this because you're running into this problem: You can simply remove headers from ALL files, and then pass _ANOTHER_ CSV with just headers; but, of course, this is pretty frustrating :)

## And one more thing:

And one more thing! The documentation currently states:

> **Multiple files will be logically seen as one big file from the perspective of the importer.** The first line must contain the header. Multiple data sources like these can be specified in one import, **where each data source has its own header.** [Emphasis mine.]

This "first line must contain the header" and "each data source has its own header" is, I think, misleading: Each "data source" isn't clearly different (at least to a beginner) than "data file". That suggests that each file may have its own header, but that's not the case!

---

# An end to our sorrows?

Perhaps a `--ignore-firstline` flag (or something more elegant) could be passed to the importer to indicate that every file has a header? **It's probably even possible to do this automatically, since the first line of every file will be the same. That should be easy to detect!** But I appreciate that there might be some corner-case where existing users rely on that, and would suffer if the native behavior were changed.

**Comment by SaschaPeukert** [comment] 2018-10-02 11:28
Hej @j6k4m8 ,

Thanks for your suggestion. I will make sure that it will be considered in the future development of neo4j-admin

Cheers,
Sascha

**Comment by tinwelint** [comment] 2019-12-11 12:56
This is basically a duplicate of https://github.com/neo4j/neo4j/issues/7641 so I'm closing this issue but the feature request remains, cheers

**Closed as completed by tinwelint** 2019-12-11 12:56 UTC
Labels: operability, team-kernel
