### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed is reported when executing the query: MATCH (n0) OPTIONAL MATCH (n1) MATCH (n1) WITH * MATCH (n2) OPTIONAL MATCH (n3) OPTIONAL MATCH (n2) RETURN *

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12833] opened 2022-01-28 05:22 UTC
I discovered that when I executed the following Cypher query, a database error occured.

**Neo4j Version:** 4.1.11 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
Execute the following Cypher query:
MATCH (n0) OPTIONAL MATCH (n1) MATCH (n1) WITH * MATCH (n2) OPTIONAL MATCH (n3) OPTIONAL MATCH (n2) RETURN *

### Expected behavior
Return the result set that satisfy the query.

### Actual behavior
**ERROR: Neo.DatabaseError.Statement.ExecutionFailed**
Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Optional Matches: : ['QueryGraph {Nodes: ['n1']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2'], Arguments: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['n3']}', 'QueryGraph {Nodes: ['n2'], Arguments: ['n2']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Optional Matches: : ['QueryGraph {Nodes: ['n1']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2'], Arguments: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['n2'], Arguments: ['n2']}', 'QueryGraph {Nodes: ['n3']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None)
Plan: ProduceResult(List(n0, n1, n2, n3)) {
  LHS -> Apply() {
    LHS -> Apply() {
      LHS -> AllNodesScan(n0, Set()) {}
      RHS -> Optional(Set(n0)) {
        LHS -> AllNodesScan(n1, Set()) {}
      }
    }
    RHS -> CartesianProduct() {
      LHS -> Apply() {
        LHS -> AllNodesScan(n2, Set(n0, n1)) {}
        RHS -> Optional(Set(n0, n1, n2)) {
          LHS -> Argument(Set(n2)) {}
        }
      }
      RHS -> Apply() {
        LHS -> Argument(Set(n1, n0)) {}
        RHS -> Optional(Set(n1, n0)) {
          LHS -> AllNodesScan(n3, Set()) {}
        }
      }
    }
  }
} 

Differences:
 - Tail
    A: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2'], Arguments: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['n3']}', 'QueryGraph {Nodes: ['n2'], Arguments: ['n2']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))
    B: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2'], Arguments: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['n2'], Arguments: ['n2']}', 'QueryGraph {Nodes: ['n3']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))

**Comment by HannesSandberg** [comment] 2022-01-31 10:34
Thanks for the report! We will take a look.

**Comment by arnefischereit** [comment] 2022-03-02 16:10
Hi @abc123000111,

Thank you for reporting another issue on `OPTIONAL MATCH`.

The issue described here seems to be caused by a bug that was fixed in Neo4j 4.2.
Since December 2021, we no longer support Neo4j 4.1 (see [the list of supported versions](https://support.neo4j.com/hc/en-us/articles/115013134648-Neo4j-Supported-Versions)).

We will therefore close this issue. Please comment, if we can help you with this issue in any other way.

**Closed as completed by arnefischereit** 2022-03-02 16:10 UTC
Labels: bug, team-cypher
