### ISSUE TITLE
1/3 Should be float

### ISSUE THREAD

**Issue by Mintactus** [neo4j/neo4j#13424] opened 2024-03-23 18:17 UTC
Neo4j 5.16
RETURN 1/3 Should return a float, having to write 1/3.0 to make it a float doesn't make any sense

Thanks for noticing

**Comment by InverseFalcon** [comment] 2024-03-23 18:54
Hello,

On the contrary, this is the norm in SQL and various programming languages, to treat integers as integers, and to use integer division when the operands are both integers, and to only use float division when at least one of the operands is explicitly a float. 

For example, with SQL:
https://datalemur.com/sql-tutorial/sql-division

**Comment by Mintactus** [comment] 2024-03-23 20:11
Nothing personnal but...

RETURN 1/2 = 0

I know about the performance reason behind it, java is probably build-in with this behavior, but...
From a logical, mathematical, practical point of view as a programmer, data scientist and human being 1/2 = 1/2 or 0.5.

Neo4j as created massive intuitiveness improvement in data science, 1/2 = 0 is not one of them and is directly conflicting with a high level language like Cypher.

So, I get that a limitation in the core language that Neo4j is build-in, Java, could make it hard or not possible at the moment, BUT an answer like "On the contrary, this is the norm in SQL" should be banned from the language of any dev at Neo4j.

**Comment by InverseFalcon** [comment] 2024-03-23 22:31
I see you have strong feelings here. 

Allow me first to clarify...my prior answer was not made to suggest that choices we make which follow in the footsteps of an existing language are automatically justified by that language's choices. Rather, I was addressing your belief that such behavior "doesn't make any sense" (suggesting unfamiliarity with this behavior) by pointing out that there _is_ an established logic to it (integer division of this kind has a place in computer science), and that such behavior is more common than you may think, as it exists in many other languages, including other popular database query languages. It is not coming out of nowhere, and, strange and unintuitive as it may seem to you, it is not something to be casually viewed as a bug or incorrect. 

Now that said...there _is_ certainly a case to revisit such behavior and consider changes for the future, especially as you point out those making use of Cypher (and later GQL) may come from non-technical backgrounds, and may be more comfortable with more relaxed mathematical logic, and automatic type coercion for certain operations. 

If you do want to pursue such a change, I would suggest creating a separate issue for it, in the form of a feature request. The title and initial take on _this_ one seems to be more from a "this is bug" perspective, given the very specific example, and will not get the traction that a more general feature request might have.

**Comment by InverseFalcon** [comment] 2024-03-23 22:40
Per the above, please submit an issue written out as a feature request if you wish to pursue this.

As this current issue is more in the form of a bug report, and as the "1/3 should be a float" behavior is not a bug but a result of integer division, a common logical behavior present in various programming and query languages (and intentionally present in Cypher), I will close this one up. 

Also, to offer a workaround beyond what you mentioned in your initial comment, you can always cast a value as a float to ensure that the operations on it will produce floating point results: `toFloat(1) / 3`

**Closed as completed by InverseFalcon** 2024-03-23 22:40 UTC
Labels: bug
