### ISSUE TITLE
Error about apoc.load.jdbc. Mysql password with special character. 

### ISSUE THREAD

**Issue by xglreal** [neo4j/neo4j#12855] opened 2022-03-15 01:13 UTC
I use the  query 
**call apoc.load.jdbc('jdbc:mysql://12.13.14.15:3305/test? user=root&password=123456!@# ","table1") yield row**
to connect to mysql for data transfering.
But there is occuring a error when i excurer the query.
**Caused by: java.sql.SQLExceptionL Access denied for user 'root'@''**
It seems that the apoc.load.jdbc don't support password with special character, such as !@#$%^&*.

Is there anyone encounters the proplem？How can I solve this problem?

**Comment by mnd999** [comment] 2022-03-23 16:22
This seems like a duplicate of https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2624 - I think we can deal with this in APOC.

**Closed as completed by mnd999** 2022-03-23 16:22 UTC
Labels: bug
