### ISSUE TITLE
 Beta version of Neo4j 3.0

### ISSUE THREAD

**Issue by nagashi** [neo4j/neo4j#6749] opened 2016-03-21 05:17 UTC
I’m running the beta version of Neo4j 3.0 in the windows 10 environment, 64 bit.  I still have version 2.3.2 installed.  When running 3.0 and then shutting down, I notice a process is still running.  What brought it to my attention is the fact that unless I kill it in task manager, I’m unable to execute 3.0 again.  I tested it with 2.3.2 and after closing down, no process remains.

**Comment by craigtaverner** [comment] 2018-11-07 16:34
I believe this is no longer an issue, so I'm closing the issue. Please re-open if the problem is still there.

**Closed as completed by craigtaverner** 2018-11-07 16:34 UTC
Labels: bug, operability
