### ISSUE TITLE
ExecutionFailed: Index out of bounds

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13144] opened 2023-04-15 10:09 UTC
When running the following query:
```cypher
FOREACH ( n0 IN [] | CREATE ()<-[x:A]-(), ({n1:endNode(x).n2}) )
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Index 3 out of bounds for length 0)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 enterprise version** in a Docker container running **alpine v.3**.
While the error message is similar to the one from #13129, this bug only arises in the enterprise edition, while the one from the mentioned issue only triggers in the community edition.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
FOREACH ( n0 IN [] | CREATE ()<-[x:A]-(), ({n1:endNode(x).n2}) )
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Index 3 out of bounds for length 0)`

**Comment by loveleif** [comment] 2023-04-17 09:24
Thanks @DominicWuest! I've created a ticket in our internal bug tracker for further investigation ([link](https://trello.com/c/qTPjzM4G/4699-executionfailed-index-out-of-bounds)).

**Comment by pontusmelke** [comment] 2023-04-28 12:19
Duplicate of https://github.com/neo4j/neo4j/issues/13094

**Closed as completed by pontusmelke** 2023-04-28 12:19 UTC
Labels: bug, team-cypher
