### ISSUE TITLE
Execution failure when matching multiple labels in cypher

### ISSUE THREAD

**Issue by cornerman** [neo4j/neo4j#5336] opened 2015-09-11 10:01 UTC
So I have a cypher query which matches a relation between two nodes that have multiple labels.

In order to reproduce, first create this:

```
create (n:A:B:C:D:E:F:G:H:I:J:K:L:M)-[:REL]->(m:Z:Y:X:W:V:U) return *
```

and then match the created nodes:

```
match (n:A:B:C:D:E:F:G:H:I:J:K:L:M)-[:REL]->(m:Z:Y:X:W:V:U) return *
```

The matching fails with an `Neo.DatabaseError.Statement.ExecutionFailure` caused by a `java.lang.NumberFormatException` in `java.math.BigDecimal`. You can find the full stacktrace [here](http://sprunge.us/ifYO).

I am using neo4j version 2.2.5

Edit: I tried out previous versions, and the bug is present in neo4j versions 2.2.3, 2.2.4 and 2.2.5.
Version 2.2.2 seems to be the most recent working release.

**Comment by fdietze** [comment] 2015-09-29 21:41
This is still reproducible in `2.3.0-M3`.

**Comment by jexp** [comment] 2015-09-29 21:44
Works for me in 2.3-SNAPSHOT so should be working in the next release.

![plan 17](https://cloud.githubusercontent.com/assets/67427/10179088/fb9716be-6703-11e5-9575-3a638862a3ed.png)

**Comment by pontusmelke** [comment] 2015-10-14 18:01
fixed in https://github.com/neo4j/neo4j/pull/5414

**Closed as completed by pontusmelke** 2015-10-14 18:01 UTC
