### ISSUE TITLE
Incorrect result when indexing and querying on index with a regexp

### ISSUE THREAD

**Issue by lilianaziolek** [neo4j/neo4j#7259] opened 2016-05-30 12:03 UTC
I came across a rather weird issue which seems to be some kind of race condition on indexing a property and I'd appreciate if you could first confirm if you can reproduce it, and then fix it and/or recommend a workaround.
- Neo4j version: 3.0.1
- Operating system: Windows 8.1
- API/Driver: embedded GraphDatabaseService, but this happens also with in-memory instance used for tests
- Steps to reproduce
  please find the following code snippet that shows the problem (at least on my machine it fails virtually every time)
  https://gist.github.com/lilianaziolek/81b1adcdb2c9b3f1c0812952da51cfa9
  The problem goes away if I either remove index (which results in a label-scan on search so obviously not a great idea) or introduce a sleep before the reading step. I tried adding the "await for indexes" as you can see, but that doesn't seem to help either.-It seems that after adding the nodes the index isn't updated on time but instead it's updated with an unknown (quite significant) delay.
- Expected/actual behavior
  I would expect correct result of 3 nodes - either by using index or, in the worst case, a slower result from a scan. Instead I get back all the nodes unless I introduce a sleep.

If I missed some step that would enforce the update of the index please let me know - but I tried looking in the documentation and haven't found anything that would imply that anything special needs to be done for index to be updated within the writing transaction.

**Comment by chrisvest** [comment] 2016-05-30 12:14
This report is a duplicate of #7059, and solved in #7157 

The fix will be part of 3.0.2, so I'm closing this issue.

**Closed as completed by chrisvest** 2016-05-30 12:14 UTC

**Comment by lilianaziolek** [comment] 2016-05-30 12:16
Thank you! I was looking for open issues when searching so didn't find it, super happy it's fixed :) Do you by any chance know if it's in the 3.1.0-M02 build? I'd be happy to use that until 3.0.2 is fully released as it's just for my personal project.

**Comment by chrisvest** [comment] 2016-05-30 12:18
Yeah, looks like it got merged in time for 3.1.0-M2: https://github.com/neo4j/neo4j/commit/b5a20da91233c24b93bcf044c507f0d497ef48c9
