### ISSUE TITLE
Corrupted data after cleaning the database

### ISSUE THREAD

**Issue by Humanitis** [neo4j/neo4j#7906] opened 2016-09-09 14:42 UTC
We have several tests that create data in the neo4j. 
Before each test we delete all data from the database, using the query "MATCH (n) DETACH DELETE n". 
In some cases, after cleaning the base, we get an error "Property [6146, used = false, prev = -1, next = 6145, (blocks not loaded)] not in use". 
After that, the deletion request always returns this error. 
Restarting the server does not help

**Neo4j version:** 3.0.4 (running in the docker container)
**Operating system:** Debian 8
**API/Driver:** Neo4jClient 2.0 (.NET)

**Comment by jexp** [comment] 2016-09-09 16:05
Why don't you just restart the docker container to get a clean state?

Could you share one of the databases that exhibits that error?

Thanks a lot.

**Comment by Humanitis** [comment] 2016-09-13 08:41
Sorry for delay. 

> Why don't you just restart the docker container to get a clean state?

Because we don't want the tests to know about how and where running the database. In the future we will not use docker containers.

> Could you share one of the databases that exhibits that error?

How to send the database to you?

Thanks

**Comment by jexp** [comment] 2016-09-13 13:42
Depending on size send it zipped or a link to dropbox or so via email to michael at neo4j.com

Von meinem iPhone gesendet

**Comment by tinwelint** [comment] 2016-09-19 11:42
Which query is failing and how (stack trace rather)? I tried the db and there's nothing in use in it, so it's hard to know what to look for.

**Comment by tinwelint** [comment] 2016-09-19 12:52
There are no logs (`debug.log`, `console.log`), any chance you could include those?

**Comment by tinwelint** [comment] 2016-09-22 07:31
After investigation of @MishaDemianenko this is caused by the same problem as #7771 of which there's a pending fix for. Will close this ticket

**Closed as completed by tinwelint** 2016-09-22 07:31 UTC
Labels: bug, 3.0, team-kernel
