### ISSUE TITLE
Query fails when using ORDER BY and LIMIT

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#12540] opened 2020-06-28 17:06 UTC
A quite simple query fails to return results, giving a Neo.DatabaseError.Statement.ExecutionFailed 
when combining ORDER BY and LIMIT clauses at the same time in a Q that already uses NOT, CONTAINS

At first I thought it was related to aliases given to return values. Its not. 

[ORDERLIMIT_issue.docx](https://github.com/neo4j/neo4j/files/4842603/ORDERLIMIT_issue.docx)

Attached documents provides the queries and results
technical details,
screen captures of the EXPLAIN of failing q
and output of the check-consistency  neo4j-admin  command

- Neo4j version: 4.0.4  within Desktop 1.2.29
- Operating system: Linux mint 19

Of course, an alike query on other labels works (Smurf, Note) fine even though it combines ORDER BY and LIMIT
as it does since forever
And I have second pair of labels (Smurf, Species) where it fails too.
Smurf is the central label 

Just giving the label names for me to remember.
I have clone the graph so I have a copy in today's state to run any command wanted. 

Its a dev graph, not finished.
The failing Q is an administrative check, not supposed to go to production. So nothing critical here. Just weird.

Is it the combination with CONTAINS ? with NOT ? all four ?

Could be an edge case related to all the events that happened on that graph (like constraints added, removed), or computer put to sleep with graph running ...

**Comment by mnd999** [comment] 2020-07-02 12:46
Thanks for the report, I've had a brief look at this but was unable to reproduce the issue immediately. I have only created a few nodes though and I am getting a very different plan to you so that is likely the reason. I note that you're using enterprise edition, so if you have a support contract in place already please consider raising this via that route as any NDAs etc. we may need to examine your database may already be in place.

I think to investigate further, we would need ideally a simple testcase database that displays this issue, some create statements to produce such a database or database stats via the datacollector procedures ( look at the db.stats.* procedures in https://neo4j.com/docs/operations-manual/current/reference/procedures/ ). If you are not able to provide any of these publicly then we will have to go another route.

**Comment by wadael** [comment] 2020-07-05 22:50
Hello Mark, 

Fortunately, I retrieved the stats before I cleared the QUERIES part, for if I run the failing Q, I get nothing as a result of
CALL db.stats.retrieve('QUERIES')

(no changes, no records)


The CALL db.stats.collect('QUERIES') (I did before) displayed true

I use the enterprise edition with Neo4jDesktop, I have no support contract.
I report to help the project.

I encountered this issue while working for kamusi.org, a NPO, the leader agreed sharing all info needed, even data.

My email is my pseudo, at gmail

**Comment by mnd999** [comment] 2020-07-07 14:39
Can you provide the output of:
*  `call db.stats.retrieve("GRAPH COUNTS")` 
* `call db.stats.retrieve("TOKENS")` 

That would give us something to start from.

**Comment by mnd999** [comment] 2020-07-17 12:57
We had a look into this, and were able to generate the same plan as you. Unfortunately we were not able to reproduce the issue. There are some things you can try:
* Prefix your query with `CYPHER RUNTIME=interpreted`, and `CYPHER RUNTIME=slotted` see if it works with these runtimes. 
* Increase your log level and retry e.g. set `dbms.logs.debug.level=DEBUG` in your neo4j.conf, make sure the query log is enabled with `dbms.logs.query.enabled=VERBOSE`. If you are able to get a full stack trace from the failure, that would be useful.

**Comment by wadael** [comment] 2020-07-17 14:14
Awesome. Thanks Mark
Didnt think about changing the runtime.
The Q works with both slotted and interpreted.

I put an archive on the same gdrive I shared previously with the data.
A NPE occurred in org.neo4j.bolt.packstream.Neo4jPackV1$PackerV1.pack(Neo4jPackV1.java:116)
because of 
ERROR [o.n.b.v.m.BoltResponseMessageWriterV3] Failed to write value null because: null

**Comment by mnd999** [comment] 2020-07-17 14:47
I had to delete that share from my drive without looking, we are not allowed to look at private customer databases without a support contract unfortunately. If you have a full stack trace are you able to add it to this ticket?

**Comment by wadael** [comment] 2020-07-17 14:52
I understand.
It was for helping with the stability of the project. 
I'm a big fan
Here are the logs I previously shared to you. No data here 
[Issue_12540__logs_from_reporter.tar.gz](https://github.com/neo4j/neo4j/files/4938440/Issue_12540__logs_from_reporter.tar.gz)

**Comment by pontusmelke** [comment] 2020-08-13 07:01
Hi @wadael ,
we believe this issue should have been fixed in 4.0.7, if you have the opportunity please try upgrading.

I'll close this issue but don't hesitate to reopen or open a new issue should the problem reappear.

Regards,
Pontus

**Closed as completed by pontusmelke** 2020-08-13 07:01 UTC
Labels: bug, team-cypher

**Comment by wadael** [comment] 2020-08-13 14:51
Confirming the issue is solved with  v4.1.1 
Thank you Mark and Pontus
