### ISSUE TITLE
BOLT: "initializing the session' cannot be done when a session is in the 'IDLE' state."

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#7356] opened 2016-06-09 17:40 UTC
After an INIT failure (e.g. due to invalid credentials) it is not possible to re-attempt INIT. Doing so results in the odd error "initializing the session' cannot be done when a session is in the 'IDLE' state.".

Expected behavior:

--> INIT (invalid credentials)
<-- FAILURE
--> ACK_FAILURE
<-- SUCCESS
--> INIT (valid credentials)
**<-- SUCESS**

Actual behavior:

--> INIT (invalid credentials)
<-- FAILURE
--> ACK_FAILURE
<-- SUCCESS
--> INIT (valid credentials)
**<-- FAILURE (initializing the session' cannot be done when a session is in the 'IDLE' state)**

This behavior prevents interactively prompting a user for credentials, allowing for re-attempts.

**Comment by cleishm** [comment] 2016-06-09 17:43
I suspect this is related to another issue discussed with @igorborojevic, whereby a failure in INIT is leaving the session in IDLE state (rather than UNINITIALIZED).

**Comment by pontusmelke** [comment] 2016-06-10 10:15
Yes you are right, but the connection will be terminated. So you will have to open a new connection and retry init.

https://github.com/neo4j/neo4j/pull/7357

**Comment by cleishm** [comment] 2016-06-10 14:34
@pontusmelke: I recommend against that approach. As already implemented in libneo4j-client, retrying the password and re-init'ing the session should be possible without having to recreate a TCP connection.

```
% ./src/bin/neo4j-client neo4j://localhost
Username: neo4j
Password: 
Authentication failed: Username or password is invalid
Password: 
session initalization failed: 'initializing the session' cannot be done when a session is in the 'IDLE' state.
connection to 'neo4j://localhost' failed: Unexpected error
%
```

**Comment by cleishm** [comment] 2016-06-10 14:37
PS. One additional reason is that the original protocol design is intended for eventually carrying multiple sessions over a single TCP connection, so a failure in INIT at the session level should not affect other concurrent sessions.

**Comment by pontusmelke** [comment] 2016-06-10 22:00
Yes but not in a patch release. Just putting the state to UNINTIALIZED is not enough since that would still not allow you to acknowledge the error, trying to acknowledge an error while in UNINITIALIZED will once again close the connection. I see your pain but the current authentication protocol is not really designed for interactively changing password. We will get there but a patch release is not the place for such a change.

**Comment by cleishm** [comment] 2016-06-10 22:14
Hi @pontusmelke,

I understand your looking for an easy way to deal with this, but closing the connection implicitly assumes that session and connection are synonymous.

Perhaps you can also explain the concern with patch releases here? The current behavior leaves the connection open, and allows for ACK_FAILURE to be sent. Thus it would seem more appropriate to continue to do the same. Changing it to close the connection, and not allowing an ACK_FAILURE, would be changing a surface behavior, with the potential to break implementations.

/c

PS. This isn't about 'changing passwords' - it's about re-trying INIT in the case that it fails (e.g. by substituting credentials).

**Comment by cleishm** [comment] 2016-06-10 22:24
To add some context to this, if you go the route of closing the connection, then the only sensible way to support that in a driver like [libneo4j-client](https://github.com/cleishm/libneo4j-client/) will be to remove the concept of a session entirely. Currently, protocol version negotiation is done when the connection is created, and then INIT is sent later when establishing a connection. In this snippet (from the [libneo4j-client README](https://github.com/cleishm/libneo4j-client/#example)) you can see the two phases:

```
neo4j_connection_t *connection =
        neo4j_connect("neo4j://user:pass@localhost:7687", config, 0);
neo4j_session_t *session =
        neo4j_new_session(connection);
neo4j_result_stream_t *results =
        neo4j_run(session, "RETURN 'hello world'", neo4j_null);
```

The design of BOLT was such that connection and session should be separate concepts, to allow future multiplexing of session over a connection. However, if the creating of the session cannot fail independently of the connection also being destroyed, then it is unhelpful to expose `neo4j_session_t` as a separate concept. It would need to be removed entirely, which is a substantial surface change in the driver (and a lot more work than adding a re-try state in the server state machine).

**Comment by pontusmelke** [comment] 2016-06-10 22:33
Doing what you propose will not lead to the expected behaviour you want. A successful renegotiation  will rather have to be

--> INIT (invalid credentials)
<-- FAILURE (UNINITIALIZED)
--> INIT (valid credentials)
<-- SUCESS

and if you would do what you expect the following will happen

--> INIT (invalid credentials)
<-- FAILURE (UNINITIALIZED)
--> ACK_FAILURE
<-- IGNORE (STOPPED)
--> INIT (valid credentials)
<-- IGNORE (STOPPED)

I don't think the first

**Comment by pontusmelke** [comment] 2016-06-10 22:40
I think I generally agree with you except for making this kind of a change in a point release. It is however way too late to take any good decisions right now :) 

(I didn't intentionally close the issue, I hit the wrong button)

**Comment by cleishm** [comment] 2016-06-10 22:53
That's ok. I did get an email with your previous comment, and yes - it is late over there in Sweden! And it's now the weekend :)

So, when you come back to this on Monday, understand that the flow I'm proposing would simply be `INIT -> FAILURE -> ACK_FAILURE -> SUCCESS -> INIT -> SUCCESS`. The current implementation allows drivers to acknowledge the FAILURE with an ACK_FAILURE (or RESET), which is a mandatory requirement of the protocol. The only surface visible change in this proposal would be that the second INIT would succeed where expected, rather than fail.

On the other hand, I feel that intentionally closing yields a flow like `INIT -> FAILURE <dead connection>`. That's a much larger surface change and probably inappropriate for a point release, as it now prevents the driver from fulfilling the requirement of the protocol that all FAILURE messages must be acknowledged (using ACK_FAILURE or RESET), which could cause problems as it was previously allowed.

**Comment by cleishm** [comment] 2016-06-11 18:20
@pontusmelke: I pushed a commit (629ac14ff40ac419271ade3b11d687edad42a40a) to my branch that resolves the issue with allowing RUN after INIT failure (and consequently this issue as well). It also adds a few more tests for various combinations of init and failure.

**Comment by zhenlineo** [comment] 2016-06-13 15:59
@cleishm I doubt in your commit if the [impl](https://github.com/neo4j/neo4j/blob/629ac14ff40ac419271ade3b11d687edad42a40a/community/bolt/src/main/java/org/neo4j/bolt/v1/runtime/internal/SessionStateMachine.java#L112) for `reset` method in `INIT_ERROR` is correct. If I understand correctly, it should be

```
public State reset( SessionStateMachine ctx )
{
    return UNINITIALIZED;
}
```

WDYT?

**Comment by cleishm** [comment] 2016-06-13 17:05
I think you're absolutely right. And there should be a test using reset also. I'll do that later today for you.

**Comment by cleishm** [comment] 2016-06-14 04:47
Hey @pontusmelke: check out the commit 67700fa2b9676daad83d2a38f30cdd3ad3d2437d. That should also handle reset, and adds a bunch more tests. Indeed, it was a very good catch by you - because it turns out that the code was also allowing RESET to be sent on a new connection, which would move it to IDLE state without ever having received an INIT or any credentials.

**Comment by zhenlineo** [comment] 2016-06-15 14:09
I somehow ended up with this https://github.com/neo4j/neo4j/pull/7391
I found STOPPED might also go to IDLE after a RESET.

**Comment by zhenlineo** [comment] 2016-06-28 16:19
Closing this issue as the fix has been merged. Pls be free to re-open if you find there is still something wrong.

**Closed as completed by zhenlineo** 2016-06-28 16:19 UTC
Labels: bug, bolt server
