### ISSUE TITLE
[neo4j-community-3.3.0] Installation instructions don't work

### ISSUE THREAD

**Issue by stemar87** [neo4j/neo4j#10398] opened 2017-11-08 10:25 UTC
Following installation instructions provided at [here](https://neo4j.com/download-thanks/?edition=community&release=3.3.0&flavour=unix&_ga=2.167900257.1331039344.1510067832-1881734715.1510067832) does not yeld expected results.

### System information

- Neo4j version: 3.3.0
- Operating system: MacOS X 10.12.6
- API/Driver: Java

### Steps to reproduce

1. download Neo4j tar from [here](https://neo4j.com/download/other-releases/)
2. follow instructions at [here](https://neo4j.com/download-thanks/?edition=community&release=3.3.0&flavour=unix&_ga=2.167900257.1331039344.1510067832-1881734715.1510067832)

### Expected behavior

- running command `$NEO4J_HOME/bin/neo4j console` should start Neo4j console
- running command `$NEO4J_HOME/bin/neo4j start` should start Neo4j server

### Actual behaviour

- running command `$NEO4J_HOME/bin/neo4j console` causes log message 

````
Active database: graph.db
Directories in use:
  home:         ~/neo4j-community-3.3.0
  config:       ~/neo4j-community-3.3.0/conf
  logs:         ~/neo4j-community-3.3.0/logs
  plugins:      ~/neo4j-community-3.3.0/plugins
  import:       NOT SET
  data:         ~/neo4j-community-3.3.0/data
  certificates: ~/neo4j-community-3.3.0/certificates
  run:          ~/neo4j-community-3.3.0/run
Starting Neo4j.
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
````

- running command `$NEO4J_HOME/bin/neo4j start` causes log message

````
Active database: graph.db
Directories in use:
  home:         ~/neo4j-community-3.3.0
  config:       ~/neo4j-community-3.3.0/conf
  logs:         ~/neo4j-community-3.3.0/logs
  plugins:      ~/neo4j-community-3.3.0/plugins
  import:       NOT SET
  data:         ~/neo4j-community-3.3.0/data
  certificates: ~/neo4j-community-3.3.0/certificates
  run:          ~/neo4j-community-3.3.0/run
Starting Neo4j.
./bin/neo4j: line 411: ~/neo4j-community-3.3.0/run/neo4j.pid: No such file or directory
./bin/neo4j: line 410: ~/neo4j-community-3.3.0/logs/neo4j.log: No such file or directory
````

**Comment by Baschdl** [comment] 2017-11-08 12:11
@stemar87 #7086 has the solution, you have to change the group and write permissions of the folder

**Comment by stemar87** [comment] 2017-11-08 12:15
@Baschdl I imagine that will work for the latter issue I reported, what about the former? (`Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint`)

[UPDATE] @Baschdl actually it doesn't even solve the latter issue...

**Comment by Artgit** [comment] 2017-11-18 15:48
I got pretty much the same issue https://stackoverflow.com/questions/47367378/neo4j-linux-3-3-0-error-could-not-find-or-load-main-class-org-neo4j-server-comm

**Comment by eebus** [comment] 2017-12-08 14:21
Hello
3.3.1 have just been released, are you having the same problem with it?

**Comment by xenic** [comment] 2018-02-06 19:18
I'm having the problem with 3.3.2

**Comment by jennyowen** [comment] 2018-12-20 11:36
For the `neo4j start No such file or directory` issues, they are fixed by:
https://github.com/neo4j/neo4j/issues/11954

I was not able to reproduce the `neo4j console` error but I've added tests which should hopefully prevent it being an issue in the future.

**Closed as completed by jennyowen** 2018-12-20 11:36 UTC
Labels: operability, team-packaging

**Comment by benrudolph** [comment] 2019-04-24 01:02
I also get this on a fresh install of 3.5.4 (enterprise and community)

**Comment by jennyowen** [comment] 2019-04-24 07:30
@benrudolph Could you file a new issue with more details about error message, reproduction steps, OS and java version installed? Thanks.
