### ISSUE TITLE
Java heap space out of memory error with neo4j 1.9.9 and Oracle java 8

### ISSUE THREAD

**Issue by chiffa** [neo4j/neo4j#5785] opened 2015-10-29 13:01 UTC
I have had a code I have been running in production for two years that has been miserably failing with neo4j 1.9.9 and latest Oracle java 8 on the a new machine

I am performing an inserting of a dataset from python code using bulbflow adapters, it seems that neo4j keeps all the data in the memory (no garbage collection?)

With 4 Gb of RAM allocated to neo4j java process, this amount of data saturates the machine and leads to failure:

25 k nodes
35 k relationships
122k properties. 

We are nowhere near 100 M nodes limit claimed by the doc for that amount of allocated RAM. 
What steps could I perform to figure out where is the problem and debug it?

**Comment by chrisvest** [comment] 2015-10-29 13:42
Transaction state is kept in memory, so if your dataset insertion is in a single transaction, then that may be the cause of your troubles. Try breaking the transaction up into smaller batches.

**Comment by chiffa** [comment] 2015-10-29 14:28
I reproduced the problem with Java 7. I perform transnational insertions of a single node/relationship at a time via a Gremlin Groovy interface (the only one available for bulblfow from Python).

The problem has been introduced since the 1.9.6 update (the latest version I can have access to and that runs fine) and beyond the "Perm Gen heap out of memory" error, the overall speed of transactions is slower by an order of magnitude.

I tried to pushing the heap space up to 6 Gb, all gets consumed by JVM that runs neo4j 1.9.9. The problem is absent in neo4j 1.9.6, that loads the entire dataset without ever getting over 300 MB.

**Comment by jexp** [comment] 2015-10-30 06:25
Perhaps its related to the gremlin interpreter

Do you have a repeatable test project that you can make available?

**Comment by chiffa** [comment] 2015-10-30 14:29
Sure: https://github.com/chiffa/PolyPharma

To reproduce the error, install the project, (MongoDB, python-Levenshtein, pymongo, scikits.sparse, click not required to reproduce the problem)
from project root execute 

> python- m PolyPharma.Utils.ConfigsIO
> Python -m PolyPharma.neo4j_Importers.Import_commander

the error should occur within first couple hundreds operation with default parameters and within a thousand for -Xmx1g option.

In case the installation is too complex for you, I could extract a gist and post it.

**Comment by jexp** [comment] 2015-11-02 01:39
It would be cool if you could try to run a profiler with your project, e.g. jvisualvm
Or if you need sth simpler jvmtop --profile <pid> https://github.com/patric-r/jvmtop

Are you using Neo4j Community or enterprise?

A minimal gist that reproduces it wold be very appreciated. Also with a profiler you could create and share a heap-dump.

**Comment by chiffa** [comment] 2015-11-02 01:50
Community.
I will extract and post gist tomorrow. 
To make sure I understand well: I start neo4j process, launch jvmtop in detailed mode on the neo4j process and run it until it crashes. At what point would you want me to collect the data from the process? Start-up? Midway? as close to crash as possible?

**Comment by chiffa** [comment] 2015-11-02 22:38
here is the python code gist:
https://gist.github.com/chiffa/0d2befe746fba3806019

in order to run this gist only requires bulbflow installation: 

> pip install bulbs 

in order to  run the test, I edited the `neo4j-wrapper.conf` in both the 1.9.9 and 1.9.6:

> wrapper.java.initmemory=128
> wrapper.java.maxmemory=256

The gist was executed on a ubuntu 14.04 with Oracle Java 7. database was launched via shell without changing the user

> $NEO4J_HOME/bin/$ ./neo4j start

Both problems with 1.9.9 persists:
- the insert is slower by an order of magnitude
- the memory consumption is stable in 1.9.6 around 256 Mb, whereas in 1.9.9 grows linearly, up to 700+ Mb

I did not replicate the out-of-memory crash. It most likely will require insertion of relations and node parameters.

**Comment by jakewins** [comment] 2015-12-05 05:04
@chiffa according to the Bulbs documentation they should work with the latest version of Neo4j, where this should not be an issue. I would try with Neo4j 2.3.1, in terms of memory management the two are two completely different databases.

**Comment by chiffa** [comment] 2015-12-06 00:46
@jakewins Bulbs relies on Gremlin and gremlin support was removed in the neo4j 2.x versions. Bulbflow documentation was written before neo4j 2.0 and haven't been updated since, despite it working well. I could try to set up maven to patch neo4j 2.x to support gremlin, but if possible I would like to avoid it.

**Comment by jakewins** [comment] 2015-12-06 00:56
@chiffa understood. I'll mark this as a potential bug. 

Meanwhile; while Neo4j no longer ships with gremlin, the gremlin plugin for the server is community maintained and works at least up to Neo4j 2.1.x: https://github.com/neo4j-contrib/gremlin-plugin Might be worth trying?

**Comment by chiffa** [comment] 2015-12-06 01:01
I am using neo4j as a back-end in a bioinformatics tool I have an intention to distribute to the end users. Anything that is more than an `apt-get install` or "click twice here" I fear would be asking too much from my end users. I also don't want to package a separate version of database either, since I would like the it to be compatible with other tools using neo4j as back-end. So a working neo4j 1.9.x branch would be really the best thing for me.

**Comment by chrisvest** [comment] 2017-11-13 11:23
Since it's a "Perm Gen heap out of memory" error, I am also suspecting that the problem is with the Gremlin plugin. We don't support 1.9 or the Gremlin plugin anymore, so if Bulbs still relies on those then you probably have to stick with 1.9.6. At this point, we will not be making any more 1.9 releases, so I'm going to close this issue. If you are, however, able to upgrade to a more recent version, and the problem is still there, then feel free to reopen this issue (or create a new one) and post updated information.

**Closed as completed by chrisvest** 2017-11-13 11:23 UTC
Labels: bug, team-kernel
