### ISSUE TITLE
`MATCH (x) DELETE x RETURN x` should be handled differently.

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#8673] opened 2017-01-23 12:31 UTC
- Neo4j version: 3.1.1
- Operating system: Debian Testing
- API/Driver: any

When executing a query of the form `MATCH (x) DELETE x RETURN x`, the result is an empty node with its previously existing node ID. However, this should not happen; instead, such queries should return an error.

**Comment by chrisvest** [comment] 2017-01-23 13:11
It is useful to get the id back if you have manual indexes that need maintenance after a delete, though.

**Comment by jexp** [comment] 2017-01-26 00:36
if you look at the returned metadata the node is marked as deleted entity

**Comment by spacecowboy** [comment] 2017-01-26 09:10
Working as intended. Closing.

**Closed as completed by spacecowboy** 2017-01-26 09:10 UTC
Labels: wontfix
