### ISSUE TITLE
building neo4j from source where much time is consume for running test cases

### ISSUE THREAD

**Issue by nareshk355** [neo4j/neo4j#7803] opened 2016-08-25 06:11 UTC
please let us know what is normal build time for neo4j where i'm working on ubuntu16.04.

**Comment by spacecowboy** [comment] 2016-09-15 10:33
@MishaDemianenko this is not docker related, could you confirm if it is intended behavior that we never remove this file?

**Comment by MishaDemianenko** [comment] 2016-09-15 11:15
@spacecowboy @nareshk355 that is normal behaviour - write.lock will be created for locking purposes if it does not exist, and soon as lock will be released it will just be there and will be reused for future locking. Presence of lock file by itself does not mean anything and should not be rely on.
So, observed behaviour is expected and correct and is not a problem

**Comment by chrisvest** [comment] 2016-09-15 11:40
@MishaDemianenko @spacecowboy Sounds like you have been discussing the Example Bug Report from our issue template. I have cleaned up the description.

**Comment by MishaDemianenko** [comment] 2016-09-15 11:41
@chrisvest 😆

**Comment by spacecowboy** [comment] 2016-09-15 12:41
@chrisvest great

@nareshk355 in answer to your actual question then, it depends on your hardware. a build time between 1.5 and 4 hours can be expected.

**Closed as completed by spacecowboy** 2016-09-15 12:41 UTC
Labels: question
