### ISSUE TITLE
Feature request: Automatic handling of lock contentions 

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6586] opened 2016-03-03 01:02 UTC
In neo4j 2.3.2, when I use multiple threads to write to the same parts of a graph, there are lock contentions and neo4j throws a bunch of Java exceptions. The manual suggests resolving this by writing my own retry loop:

http://neo4j.com/docs/stable/transactions-deadlocks.html

However, I feel this is clunky, and low numbers or high numbers of retries both seem potentially problematic. If it's set to (say) one retry per second for twenty seconds, then if another thread spends ten minutes entering data, the locked-out data might just get dropped and that would be very bad. However, if it's set to retry forever, then if anything went wrong the server might spend unlimited CPU time on retrying bad writes.

I'm not a database expert, but it seems like one could resolve this by having an internal "cache" of pending Cypher transactions. One could build, say, a hash map from lock IDs (however those are defined) to a linked list of Cypher statements. When a statement comes in that conflicts with a lock, it's added to the corresponding hash map value; and when a lock is released, the hash map is checked to see if any statements need to be popped off the stack. That way, all valid Cypher queries would be guaranteed to get executed eventually, given enough time. I've never worked on database code before, though, so this might be a bad idea for reasons I'm not aware of.

Relevant Hacker News comment: https://news.ycombinator.com/item?id=9699964

**Comment by chrisvest** [comment] 2016-03-03 08:58
If two transactions take locks in the same order, then one will wait for the other to finish, and both will complete without throwing exceptions.

The problem is when their lock orderings differ. This can lead to dead locks, which are resolved by killing one of the transactions by throwing an exception. We cannot automatically retry failed transactions, because we don't know what state and business logic exist outside of our transaction state. This is because we support long-running transactions rather than unit-of-work transactions.

**Comment by rationalism** [comment] 2016-03-03 09:27
Thanks for the explanation, but I'm still kind of confused. With manual retrying, since the program calling neo4j doesn't know the state of the locks, the code has to blindly retry after a fixed period of time, regardless of whether the lock lasts 0.001 seconds or 1,000 seconds. If there were a RETRY switch that told neo4j to do things automatically, neo4j could keep track of the conflicting locks, and call retry as soon as the other locks were lifted. It seems like this would do exactly the same thing as manual retrying, except faster and more efficiently. Is there something I'm missing? (Please do tell me if I just don't understand this properly.)

**Comment by chrisvest** [comment] 2016-03-22 17:24
@rationalism A deadlock happens when two transactions wants the same locks but take them in a different order. Say T1 (transaction one) has lock A and wants lock B, and T2 has lock B and wants lock A. This is a deadlock, and the lock manager will fail one of the transactions. Say, for instance, that it fails T2. Then T1 can get the lock on B. Then T2 is restarted as T2' and wants to retake its lock on B and A. In this case, T1 will already have grabbed the locks on both B and A, so T2' will simply wait for T1 to complete, and then take its locks.

Since the Cypher queries are not individual transactions, but rather participating in long running transactions, we cannot automatically re-run them when a deadlock happens. There can be many other queries and side-effects involved in a long-running transactions that the database has no control of. Therefor, the only safe way that we can deal with a deadlock is by failing one of the offending transactions by throwing an exception.

**Closed as completed by chrisvest** 2016-03-22 17:24 UTC
Labels: feature, team-kernel
