### ISSUE TITLE
Jaccard Similarity Result Returning Infinity for Certain Relationships - doubt

### ISSUE THREAD

**Issue by eduardogoncalo** [neo4j/neo4j#13335] opened 2023-11-09 18:54 UTC
I am encountering an unexpected issue with the Jaccard Similarity in my Neo4j graph. My graph structure involves nodes labeled as Customer and Category, connected by the relationship ORDER_CATEGORY. The problem arises when attempting to calculate the Jaccard Similarity between certain nodes. Surprisingly, the similarity results are returning as "infinity," which is an unexpected behavior for my dataset.

To provide some context, my graph consists of a considerable scale, with approximately 1.4 million Customer nodes and 17 million relationships. However, despite the substantial volume, this is the first instance where the Jaccard Similarity has yielded such infinite results, leaving me puzzled about the underlying cause.

I have thoroughly reviewed the data and the implementation, yet I have not been able to identify the specific reason behind this unexpected behavior. I have also cross-verified the parameters and configurations to ensure that they align with the standard practices for calculating Jaccard Similarity.

I would highly appreciate any insights, suggestions, or potential solutions from the community to help me resolve this issue and gain a better understanding of why this anomaly is occurring.

**Comment by jamthief** [comment] 2024-10-28 10:28
Hi Eduardo,

Thanks for taking the time to post this interesting question here!

Since this github issues space is exclusively for reporting bugs in Neo4j, we would require more specific details around the problem you are having before being able to investigate it. If you have a specific bug you would like to report, it would be helpful if you could provide some of the following so we can investigate further:

- stacktraces / logs showing the nature of the error
- example data and/or a zipped database store with a query that can reliably reproduce the problem

Otherwise, here are some resources that you can use to get answers to more qualitative questions:

- [Neo4j community forums](https://community.neo4j.com/)
- [Neo4j discord servers](https://discord.com/invite/neo4j)
- [Neo4j Aura support](https://support.neo4j.com/s/), if your question relates to an issue with an Aura database
- [Neo4j docs](https://neo4j.com/docs/) can be useful if you prefer to research the problem yourself

I'll close this question for now, but please reopen it if you want to provide more information for a specific bug you've found.

**Closed as completed by jamthief** 2024-10-28 10:28 UTC
Labels: need-more-info
