### ISSUE TITLE
Unable to execute Neo4j 2.2 Cypher Queries from Scala

### ISSUE THREAD

**Issue by anindya-saha** [neo4j/neo4j#4465] opened 2015-04-20 00:04 UTC
Hello Experts

Recently I upgraded to Neo4j 2.2 and I am trying to run Neo4j's examples JavaQuery.java from the reference manual http://neo4j.com/docs/stable/tutorials-cypher-java.html I am getting the below exception. All necessary jars are in classpath.

I could run cypher queries from Java very well in 2.1.7. Please suggest a workaround. I have already upgraded my graph database and cannot go back to 2.1.7. I am running on Windows 7.

Exception in thread "main" java.lang.UnsupportedOperationException: No query engine installed.
at org.neo4j.kernel.impl.query.NoQueryEngine.noQueryEngine(NoQueryEngine.java:56)
at org.neo4j.kernel.impl.query.NoQueryEngine.executeQuery(NoQueryEngine.java:33)
at org.neo4j.kernel.InternalAbstractGraphDatabase.execute(InternalAbstractGraphDatabase.java:953)
at org.neo4j.kernel.InternalAbstractGraphDatabase.execute(InternalAbstractGraphDatabase.java:944)
at JavaQuery.run(JavaQuery.java:67)
at JavaQuery.main(JavaQuery.java:47)

**Comment by cleishm** [comment] 2015-04-20 00:42
Hi @anindya-saha,

You've likely not got the correct jars in the classpath - make sure the cypher compilers are present for 2.2.

Also, this issue tracker is for reporting and tracking source code issues in the Neo4j code base. For questions on usage, please refer to the [google group](http://groups.google.com/group/neo4j) or to [stackoverflow](http://stackoverflow.com/questions/tagged/neo4j) for community support.

Cheers,
Chris

**Comment by TheCreativeMind** [comment] 2015-10-12 14:37
I have a similar Issue with the 2.2.5 Version. All the cypher dependencies are in the class path. Compiling and starting the db leads to no error, however if I try to query it, I get the following error:

Caused by: java.lang.UnsupportedOperationException: No query engine installed.
    at org.neo4j.kernel.impl.query.NoQueryEngine.noQueryEngine(NoQueryEngine.java:56) ~[neo4j-kernel-2.2.5.jar:2.2.5]
    at org.neo4j.kernel.impl.query.NoQueryEngine.executeQuery(NoQueryEngine.java:33) ~[neo4j-kernel-2.2.5.jar:2.2.5]
    at org.neo4j.kernel.InternalAbstractGraphDatabase.execute(InternalAbstractGraphDatabase.java:966) ~[neo4j-kernel-2.2.5.jar:2.2.5]

**Comment by jexp** [comment] 2015-10-12 21:08
The only thing you need to have as dependency is : `org.neo4j:neo4j:2.2.5`.

With that it should work out of the box.

**Comment by TheCreativeMind** [comment] 2015-10-13 12:41
Unfortunately the problem remains. I am still not able to query the db, I get the same error message as before.

**Comment by jexp** [comment] 2015-10-13 14:50
Can you share a sample project on GitHub?

What is the output of mvn dependency:tree ?

**Comment by TheCreativeMind** [comment] 2015-10-14 11:29
I just saw that it states java in the title not scala...

However here is my minimal example:

`build.sbt`

```
name := "DBTest"

version := "1.0"

scalaVersion := "2.11.7"

libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.4" % "test"

libraryDependencies += "com.michaelpollmeier" %% "gremlin-scala" % "3.0.1a-incubating"
libraryDependencies += "org.apache.tinkerpop" % "neo4j-gremlin" % "3.0.1-incubating"
libraryDependencies += "org.neo4j" % "neo4j-tinkerpop-api-impl" % "0.1-2.2"
libraryDependencies += "org.neo4j" % "neo4j" % "2.2.5"
```

`Hello.scala`

```
import gremlin.scala._
import org.apache.commons.configuration.BaseConfiguration
import org.apache.tinkerpop.gremlin.neo4j.structure.Neo4jGraph

object Hello {
  def main(args: Array[String]): Unit = {

    val conf = new BaseConfiguration()
    conf.setProperty("gremlin.neo4j.directory" , "tmpDB/")

    val graph: Neo4jGraph = Neo4jGraph.open(conf)
    val gs = graph.asScala
    val sg = ScalaGraph(graph)

    println(graph.cypher("Match (n:Label) return count(n)"))

  }
}
```

**Comment by jexp** [comment] 2015-10-14 14:25
What does the dependency tree look like if you list it with sbt?

Similar to `mvn depdendency:tree`

**Comment by TheCreativeMind** [comment] 2015-10-14 15:23
```
Dependencies
com.carrotsearch:hppc:0.7.1:jar
com.chuusai:shapeless_2.11:2.2.5:jar
com.fasterxml.jackson.core:jackson-annotations:2.5.0:jar
com.fasterxml.jackson.core:jackson-core:2.5.3:jar
com.fasterxml.jackson.core:jackson-databind:2.5.3:jar
com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4:jar
com.jcabi:jcabi-log:0.14:jar
com.jcabi:jcabi-manifests:1.1:jar
com.michaelpollmeier:gremlin-scala_2.11:3.0.1a-incubating:jar
com.michaelpollmeier:macros_2.11:3.0.1a-incubating:jar
commons-configuration:commons-configuration:1.10:jar
commons-lang:commons-lang:2.6:jar
jline:jline:2.12:jar
net.sf.opencsv:opencsv:2.3:jar
org.apache.commons:commons-lang3:3.3.1:jar
org.apache.ivy:ivy:2.3.0:jar
org.apache.lucene:lucene-core:3.6.2:jar
org.apache.tinkerpop:gremlin-core:3.0.1-incubating:jar
org.apache.tinkerpop:gremlin-groovy:3.0.1-incubating:jar
org.apache.tinkerpop:gremlin-shaded:3.0.1-incubating:jar
org.apache.tinkerpop:neo4j-gremlin:3.0.1-incubating:jar
org.apache.tinkerpop:tinkergraph-gremlin:3.0.1-incubating:jar
org.codehaus.groovy:groovy-console:2.4.1:jar
org.codehaus.groovy:groovy-groovysh:2.4.1:indy:jar
org.codehaus.groovy:groovy-json:2.4.1:indy:jar
org.codehaus.groovy:groovy-jsr223:2.4.1:indy:jar
org.codehaus.groovy:groovy-swing:2.4.1:jar
org.codehaus.groovy:groovy-templates:2.4.1:jar
org.codehaus.groovy:groovy-xml:2.4.1:jar
org.codehaus.groovy:groovy:2.4.1:indy:jar
org.javatuples:javatuples:1.2:jar
org.mindrot:jbcrypt:0.3m:jar
org.neo4j:neo4j-consistency-check:2.2.5:jar
org.neo4j:neo4j-csv:2.2.5:jar
org.neo4j:neo4j-cypher-compiler-1.9:2.0.4:jar
org.neo4j:neo4j-cypher-compiler-2.0:2.0.4:jar
org.neo4j:neo4j-cypher-compiler-2.1:2.1.8:jar
org.neo4j:neo4j-cypher-compiler-2.2:2.2.5:jar
org.neo4j:neo4j-cypher:2.2.5:jar
org.neo4j:neo4j-graph-algo:2.2.5:jar
org.neo4j:neo4j-graph-matching:2.2.5:jar
org.neo4j:neo4j-io:2.2.5:jar
org.neo4j:neo4j-jmx:2.2.5:jar
org.neo4j:neo4j-kernel:2.2.5:jar
org.neo4j:neo4j-lucene-index:2.2.5:jar
org.neo4j:neo4j-primitive-collections:2.2.5:jar
org.neo4j:neo4j-tinkerpop-api-impl:0.1-2.2:jar
org.neo4j:neo4j-tinkerpop-api:0.1:jar
org.neo4j:neo4j-udc:2.2.5:jar
org.neo4j:neo4j-unsafe:2.2.5:jar
org.neo4j:neo4j:2.2.5:jar
org.parboiled:parboiled-core:1.1.7:jar
org.parboiled:parboiled-scala_2.10:1.1.7:jar
org.scala-lang.modules:scala-xml_2.11:1.0.4:jar
org.scala-lang:scala-library:2.11.7:jar
org.scala-lang:scala-reflect:2.11.7:jar
org.scalatest:scalatest_2.11:2.2.4:jar
org.slf4j:jcl-over-slf4j:1.7.12:jar
org.slf4j:slf4j-api:1.7.12:jar
org.yaml:snakeyaml:1.15:jar
```

**Comment by jexp** [comment] 2015-10-14 23:03
Probably some classloader issue (probably for META-INF/services/*), I remember that the tinkerpop guys had that in the past, but I don't remember the solution.

**Comment by jexp** [comment] 2015-10-14 23:03
Otherwise your dependency tree looks ok to me.

**Comment by geosmart** [comment] 2016-05-09 12:01
I use neo4j 2.2.3 ,and face the same exception today, I solve it like this
1. delete the `{loacalRepository}/org/scala-lang` dirctionary in maven local repository
2. redowload the jars
and everything is ok!

**Comment by Mats-SX** [comment] 2016-10-20 12:49
This is not really a topic for an issue here (and a solution has been presented). Closing.

**Closed as completed by Mats-SX** 2016-10-20 12:49 UTC
Labels: bug, cypher, 2.2
