### ISSUE TITLE
Infinite loop during initial startup by systemctl

### ISSUE THREAD

**Issue by rito-mg** [neo4j/neo4j#11958] opened 2018-06-29 19:51 UTC
## Bug report

Unless `~neo4j/bin/neo4j start` is run manually, the first time you launch a newly installed neo4j it infinite loops. For example, if you run `systemctl start neo4j` directly after installation (or indirectly if you had run `systemctl enable neo4j` and rebooted), the service loops with the `debug.log` giving no indication of what the problem is.

The problem appears to be that running `neo4j-admin set-initial-password` creates `/var/lib/neo4j/data/dbms/auth.ini` (on Debian/Ubuntu), but the loop occurs unless `/var/lib/neo4j/data/dbms/auth` (note the missing `.ini`) is present. Starting it manually (outside of `systemctl`) with `~neo4j/bin/neo4j start` appears to create the `auth` file.

I'm reporting the bug for Ubuntu (Debian package installed) but it is possible the bug could occur on any Linux that uses Systemd, although I haven't tested that.

**Neo4j Version:** 3.4.1
**Operating System:** Ubuntu 16.04

#### Prepare to install.

    root# u1=root; u2=neo4j; printf "%s\tsoft\tnofile\t60000\n%s\thard\tnofile\t60000\n%s\tsoft\tnofile\t60000\n%s\thard\tnofile\t60000\n" "$u1" "$u1" "$u2" "$u2" >> /etc/security/limits.conf
    root# shutdown -r now

#### Log back in and verify ulimit for number of files has increased to 60000.

    root# ulimit -n

#### Install the neo4j repository.

    root# wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -

#### Make sure local hostname resolves before proceeding.

    root# echo 'deb https://debian.neo4j.org/repo stable/' | tee -a /etc/apt/sources.list.d/neo4j.list
    root# apt-get update && apt-get install -y neo4j=1:3.4.1

#### Install the neo4j package from the repository.

    root# apt-get update && apt-get install -y neo4j=1:3.4.1

#### Customize the main neo4j.conf file.

    root# cp -i -p /etc/neo4j/neo4j.conf /etc/neo4j/neo4j.conf.orig
    root# neo4j-admin memrec >> /etc/neo4j/neo4j.conf
    root# ${EDITOR-vi} /etc/neo4j/neo4j.conf

#### Set initial password.

Use the `set-initial-password` command of `neo4j-admin` to define the password for the native user neo4j. This must be performed before starting up the database for the first time.

    root# /usr/bin/neo4j-admin set-initial-password abc123

Note that this step apparently creates `/var/lib/neo4j/data/dbms/auth.ini` via the java `org.neo4j.commandline.admin.AdminTool` and is the likely cause of the bug.

#### Launch neo4j service using systemctl.

Truncate and set ACLs on logs, then startup the service for the first time:

    root# :> /var/log/neo4j/debug.log && :> /var/log/neo4j/neo4j.log && chown neo4j:neo4j /var/log/neo4j/*.log && systemctl start neo4j && tail -n ${LINES-25} -f /var/log/neo4j/debug.log

### Expected behavior

`set-initial-password` (`org.neo4j.commandline.admin.AdminTool`) probably needs to create `/var/lib/neo4j/data/dbms/auth` instead of `/var/lib/neo4j/data/dbms/auth.ini` on Linux.

I also expect to see an error message in `debug.log`, rather than silently terminating and restarting forever.

After startup, expect that the service is listening on ports designated in `neo4j.conf`:

```
root# netstat -tanlp | sed -n -r '1,2p; /(3637|7473|7474|7687).*LISTEN/p;'
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::7687                 :::*                    LISTEN      1369/java
tcp6       0      0 :::7474                 :::*                    LISTEN      1369/java
```

### Actual behavior

`set-initial-password` (`org.neo4j.commandline.admin.AdminTool`) creates `/var/lib/neo4j/data/dbms/auth.ini`.

### Workaround

Do this after you run `set-initial-password`, but before `systemctl start neo4j`:

    root# cp -p /var/lib/neo4j/data/dbms/auth.ini /var/lib/neo4j/data/dbms/auth

**Comment by sswartzl** [comment] 2018-07-18 19:06
I can confirm this occurs on RHEL 7.5. Infinite loop on initial startup with systemctl. Rename the referenced auth.ini to auth, then neo4j starts successfully.

**Comment by frank-zsy** [comment] 2018-09-10 08:20
I also encounter this bug on CentOS 7.5 and rename the file makes another problem.

After run `systemctl start neo4j`, I still got infinite restart all the time with different log content like this,

```
2018-09-10 08:02:58.571+0000 INFO [o.n.k.i.DiagnosticsManager]   store_lock: 2018-09-10T15:18:49+0800 - 0.00 B
2018-09-10 08:02:58.571+0000 INFO [o.n.k.i.DiagnosticsManager] Storage summary:
2018-09-10 08:02:58.571+0000 INFO [o.n.k.i.DiagnosticsManager]   Total size of store: 113.51 kB
2018-09-10 08:02:58.571+0000 INFO [o.n.k.i.DiagnosticsManager]   Total size of mapped files: 112.00 kB
2018-09-10 08:02:58.572+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for KernelDiagnostics:StoreFiles END ---
2018-09-10 08:03:08.737+0000 INFO [o.n.k.i.f.CommunityEditionModule] No locking implementation specified, defaulting to 'community'
2018-09-10 08:03:09.222+0000 INFO [o.n.k.AvailabilityGuard] Requirement makes database unavailable: Database available
2018-09-10 08:03:09.247+0000 INFO [o.n.k.i.DiagnosticsManager] --- INITIALIZED diagnostics START ---
2018-09-10 08:03:09.247+0000 INFO [o.n.k.i.DiagnosticsManager] Neo4j Kernel properties:
```

After the `KernelDiagnostics.StoreFiles` ended, it seems that the server is started but several seconds later, got a message about locking implementation and something about requirement and the server restart with `diagnostics` all over again.

Please help me with that. My Neo4j version is 3.4.7.

**Comment by jennyowen** [comment] 2018-09-11 15:04
Thanks for writing such detailed reproduction steps @rito-mg !

There are a few different things to unpack here.

## infinite service restarts
The neo4j service is set to retry on failure, this is behaviour we don't want to change since it's likely lots of automated systems rely on that working. 
The downside to that is that if something consistently prevents Neo4j from starting up, it'll restart, then fail, then restart, then fail forever.

There's not a lot we can do about the service infinitely restarting, which wouldn't break Neo4j in other ways.

## `set-initial-password` creates `auth.ini` file
This is supposed to happen. The *initial* password hash for the `neo4j` user is stored in a file called `auth.ini`. On startup, neo4j will read in `auth.ini`, check it doesn't have a `requires password reset` flag, and create the `auth` file from `auth.ini`.

## Neo4j is consistently failing to start
OK, so here's what the problem is:

1. When you install Neo4j it does not create the `/var/lib/neo4j/data/dbms` folder.
2. When you run `sudo neo4j-admin set-initial-password PASSWORD` it creates the `auth.ini` file and the `/var/lib/neo4j/data/dbms` folder, BUT! it's running as `root`, so the folder is owned by `root`.
3. When you start neo4j, it checks the `auth.ini` file. This involves writing some temporary files into `/var/lib/neo4j/data/dbms`. Neo4j runs under the `neo4j` user, who doesn't have permission to write to the `dbms` folder, so it fails during the check.

Your workaround works because renaming `auth.ini` to `auth` bypasses the checks which fail.

## How to fix
The best solution is to run `set-initial-password` as the `neo4j` user:
`sudo -u neo4j neo4j-admin set-initial-password PASSWORD`
That way the `dbms` folder is created with the correct permissions.

I'll see if editing our debian and yum installer to create `/var/lib/neo4j/data/dbms` (along with all the other folders it makes on installation) will fix this. 
If that doesn't work I'll update the documentation to mention that `set-initial-password` should be run as `neo4j`.

**Comment by jennyowen** [comment] 2018-09-11 15:06
@Frankzhaopku There could be any number of different things causing Neo4j to not start and it sounds like the cause for you is unrelated to this specific issue. 

If you're making a bug report, could you please make a new github issue and include reproduction steps and the systemd log? You can get the log by running:
`sudo journalctl -u neo4j -n 100`

If you need help getting Neo4j to work, https://community.neo4j.com/ is the best place to ask.

**Comment by jennyowen** [comment] 2018-09-12 14:22
As of Neo4j 3.4.8, the installation will also create the `/var/lib/neo4j/data/dbms` folder, so that these permissions errors shouldn't come up again.

Closing the issue as fixed. Thanks for reporting the bug!

**Closed as completed by jennyowen** 2018-09-12 14:22 UTC
Labels: operability, 3.4

**Comment by jotadepicas** [comment] 2019-07-13 01:05
This startup loop error is still happening to me with version 3.4.12 and ubuntu 16.04

**Comment by jotadepicas** [comment] 2019-07-15 23:00
Hi again, it turned out my start loop was due to a permissions issue (neo4j was not the owner of the graph.db directory, added to a misconfiguration in the dbms path in neo4j.conf).
