### ISSUE TITLE
Consistent growth of lucene_native-1.0 index

### ISSUE THREAD

**Issue by klichukb** [neo4j/neo4j#12053] opened 2018-10-17 08:26 UTC
- Neo4j version: 3.4.6
- Operating system: Docker (based on official ` neo4j:3.4.6-enterprise` image).
- API/Driver: Spring Neo4j OGM

Steps:
1. Create HA cluster of 1 master and 2 slaves.
  Each instance: 
 AWS m5.large. Overall RAM available: 7.5GB.
 DB size after boot - around 800MB. 1 mil nodes.
SSD size of data volume - 20GB.

2. Connect with Neo4j OGM from a Spring microservices, write/read different data for 1-2 weeks.
3. Day after day compare storage size taken by data volumes on master and slaves.
4. Observe that master's data volume is growing approx 2% per day. While slaves are NOT.
   This is what's taking all space: `graph.db/schema/index/lucene_native-1.0`.
   Specifically subdirs of this template: `graph.db/schema/index/lucene_native-1.0/31/lucene-1.0/1`.
   They have tons of small files:

```
-rw-r--r--    1 root     root           425 Oct  2 10:11 _qj61.si
-rw-r--r--    1 root     root           305 Oct  2 18:26 _qmj2.cfe
-rw-r--r--    1 root     root         90905 Oct  2 18:26 _qmj2.cfs
-rw-r--r--    1 root     root           425 Oct  2 18:26 _qmj2.si
-rw-r--r--    1 root     root           305 Oct  2 18:41 _qmk6.cfe
-rw-r--r--    1 root     root         91781 Oct  2 18:41 _qmk6.cfs
-rw-r--r--    1 root     root           425 Oct  2 18:41 _qmk6.si
-rw-r--r--    1 root     root           305 Oct  2 18:56 _qmna.cfe
-rw-r--r--    1 root     root         94023 Oct  2 18:56 _qmna.cfs
-rw-r--r--    1 root     root           425 Oct  2 18:56 _qmna.si
-rw-r--r--    1 root     root           305 Oct  2 19:11 _qmq0.cfe
-rw-r--r--    1 root     root         95877 Oct  2 19:11 _qmq0.cfs
```
5. Observe master stop serving requests with lots of different errors due to "out of space". The original error in neo4j logs is indeed "out of disk space" (sorry, I don't have stack trace for this).
6. If you simply failover master to other slave, after boot previous master's storage size will suddenly return to normal. So basically reboot drops the lucene index size to normal and overall db directory is again under 1 GB.

I want to understand whether it's some kind of leak on Lucene index side or is this growth fine? Especially with reboot fixing this..

Also when this happens master doesnt seem to be able to failover on it's own which is bad. It can't serve requests properly but still is master. Some systems autoheal by failing over when they see problems on master's side, but maybe I misconfigured the cluster.

Configuration:
```
dbms.jvm.additional=-Dunsupported.dbms.udc.source=tarball
wrapper.java.additional=-Dneo4j.ext.udc.source=docker
ha.tx_push_strategy=fixed_ascending
ha.tx_push_factor=0
ha.server_id=523
ha.pull_interval=2s
ha.join_timeout=2m
ha.initial_hosts=10.0.0.132:5001,10.0.2.11:5001
ha.host.data=ip-10-0-2-11:6001
ha.host.coordination=ip-10-0-2-11:5001
dbms.tx_log.rotation.retention.policy=100M size
dbms.tx_log.rotation.retention_policy=100M size
dbms.security.procedures.unrestricted=apoc.*
dbms.security.ha_status_auth_enabled=false
dbms.mode=HA
dbms.memory.pagecache.size=3000m
dbms.memory.heap.max_size=3000m
dbms.memory.heap.initial_size=3000m
dbms.connectors.default_listen_address=0.0.0.0
dbms.connector.https.listen_address=0.0.0.0:7473
dbms.connector.http.listen_address=0.0.0.0:7474
dbms.connector.bolt.listen_address=0.0.0.0:7687
dbms.backup.address=0.0.0.0:6362
dbms.allow_upgrade=false
causal_clustering.transaction_listen_address=0.0.0.0:6000
causal_clustering.transaction_advertised_address=ip-10-0-2-11:6000
causal_clustering.raft_listen_address=0.0.0.0:7000
causal_clustering.raft_advertised_address=ip-10-0-2-11:7000
causal_clustering.discovery_listen_address=0.0.0.0:5000
causal_clustering.discovery_advertised_address=ip-10-0-2-11:5000
apoc.export.file.enabled=true
```

**Comment by chrisvest** [comment] 2018-10-17 09:35
Lucene cannot remove old segments that may still be accessed by active index readers. Index readers are closed when their enclosing transaction is closed. So you should double-check that do not leak open transactions somewhere.

**Comment by klichukb** [comment] 2018-10-17 16:00
Thanks @chrisvest.
Would my `:sysinfo` report show me a lot of open transactions? I always get maximum 2 (mostly 1). Not really sure where to start though, I'm using OGM.

`@Transactional` for services which use Neo4j repositories, not handling transactions manually at all. Anything I can share to get some help tracking this down?

**Comment by klichukb** [comment] 2018-10-17 21:54
At least to keep production safe, I started using `lucene_native-2.0`. Since my indexes used are all strings, native index in 2.0 would support them, without need to use regular lucene ones. Tried and I don't seem to be getting increasing amount of files in test environment. Tempted to try on production.

Still, just avoiding the issue, I believe.

**Comment by chrisvest** [comment] 2018-10-18 10:24
As long as you don't index arrays or booleans, don't use composite indexes, and don't use `contains` or `ends with` queries, or need to index strings with more than 4.000 or so characters, then `lucene+native-2.0` should be fine. There might be a bug with how Lucene is integrated in those index providers.

**Comment by MishaDemianenko** [comment] 2018-10-18 12:43
Hi @klichukb 

First of all thanks for the detailed report.

In case if you have only one transaction open for most of the time leaking transaction and related index readers should not be the root cause of the described behaviour.

Also, it sounds like you have a test environment where you can easily reproduce the problem.
In that case, would it be possible to start affected test environment with something like http://file-leak-detector.kohsuke.org/ to capture stack traces of parties that open those index files?
That should help us a lot in finding the root cause.

**Comment by MishaDemianenko** [comment] 2019-02-13 15:45
@klichukb 3.4.12 or 3.5.2 includes the fix that closing leaked index readers that were causing exactly described behaviour. I'm pretty sure, so far, that you were facing the same issue. So as soon as you will upgrade indexes growth should be under control. It should be easy to verify new behaviour by checking the number of files in a particular index. Now it should be _reasonable_.

I will gonna close the issue since I believe it's solved. Please feel free to reopen the issue if that is not the case.

**Closed as completed by MishaDemianenko** 2019-02-13 15:45 UTC
Labels: team-kernel
