### ISSUE TITLE
Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: java.lang.IllegalArgumentException: There is no such fulltext schema index:

### ISSUE THREAD

**Issue by ben749l** [neo4j/neo4j#12609] opened 2020-10-17 14:01 UTC
Hello, I'm trying to use full text search functionality in GRANDstack but I have an error.

 Important details:

- Neo4j version: Desktop, 4.1.0
- APOC version: 4.1.0.1
- Operating system: Windows 10

In Neo4j Desktop, in my db I did this: `CALL db.index.fulltext.createNodeIndex("articleIndex", ["ARTICLE"],["title"])`

Next, still in Desktop I tried a request and it works: `CALL db.index.fulltext.queryNodes("articleIndex", "tiktok")`

So I added a cypher directive in my graphql schema:

```
type Query {
  # fulltext search query
  fuzzyArticleByTitle(searchString: String): [ARTICLE] @cypher(statement:" CALL db.index.fulltext.queryNodes('articleIndex', $searchString+'~') YIELD node, score RETURN node.title, score")
}
```
I tried a request in GraphQL Playground:

```
{
  fuzzyArticleByTitle(searchString:"tiktok"){
    title
  }
}
```
And I have the following error:  `"message": "Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: java.lang.IllegalArgumentException: There is no such fulltext schema index: articleIndex"`

I don't how I can fix this bug

**Comment by emmaholmbergohlsson** [comment] 2020-10-22 10:13
Hi @ludoben974 
Does the request in Desktop still work after you get the error in GraphQL Playground? Or does that also get `There is no such fulltext schema index: articleIndex`?

My guess would be that the setup of your GRANDstack application includes a call to `apoc.schema.assert` with dropExisting true.
If dropExisting is true only the indexes/constraints provided in that call will exist afterwards. Since your index was created in Desktop your graphQL schema doesn't include it.

Try to create the index again, start your application and see if the index still exist.
Then if the index is gone try to instead start your application first, then create the index and see if that works.
This should tell you if the problem is in your setup.
If the problem is in the setup, a change to do `apoc.schema.assert` with dropExisting false should work.

**Comment by burqen** [comment] 2020-11-24 09:57
Closing this issue since fix has been provided and further questions has been raised.

**Closed as completed by burqen** 2020-11-24 09:57 UTC
Labels: bug, team-kernel

**Comment by jaedag** [comment] 2020-12-12 23:17
What's the fix? I'm not seeing it, and I'm having the exact same issue

**Comment by burqen** [comment] 2020-12-13 20:46
@jaedag As described by @emmaholmbergohlsson:

> Does the request in Desktop still work after you get the error in GraphQL Playground? Or does that also get `There is no such fulltext schema index: articleIndex`?
> 
> My guess would be that the setup of your GRANDstack application includes a call to `apoc.schema.assert` with dropExisting true.
> If dropExisting is true only the indexes/constraints provided in that call will exist afterwards. Since your index was created in Desktop your graphQL schema doesn't include it.
> 
> Try to create the index again, start your application and see if the index still exist.
> Then if the index is gone try to instead start your application first, then create the index and see if that works.
> This should tell you if the problem is in your setup.
> If the problem is in the setup, a change to do `apoc.schema.assert` with dropExisting false should work.

**Comment by jaedag** [comment] 2021-05-07 04:23
Thanks @burqen that was exactly the issue. Sorry it has taken so long for me to respond.
