### ISSUE TITLE
CREATE UNIQUE not working with IN

### ISSUE THREAD

**Issue by Gorgia666** [neo4j/neo4j#5303] opened 2015-09-08 10:59 UTC
MATCH n,m where id(n) = {id}
                AND id(m) IN {ids}
                CREATE UNIQUE (n)–[r:HAS_AS_FRIEND]->(m) return r

Continue creating new relationship of label "HAS_AS_FRIEND" between the same nodes in Neo4j 2.2.5, at least if queried from REST

**Comment by jexp** [comment] 2015-09-11 10:19
Can't reproduce:

on an empty database

create (:Foo);
create (:Bar);

MATCH n,m
WHERE id(n)= 0 AND id(m) IN [1,1,1,1,1]
CREATE UNIQUE (n)–[r:HAS_AS_FRIEND]->(m)
RETURN r, id(r);

returns the same relationship (with the same id)

**Comment by jakewins** [comment] 2015-12-05 18:15
@Gorgia666 closing this as unreproducible - if this issue persists for you, please re-open this ticket with a runnable code example that shows the issue.

**Closed as completed by jakewins** 2015-12-05 18:15 UTC
