### ISSUE TITLE
Attempting to create a uniqueness constraint causes Neo4J to hang.

### ISSUE THREAD

**Issue by TomGroves** [neo4j/neo4j#10276] opened 2017-10-12 20:26 UTC
Attempting to create a uniqueness constraint causes Neo4J to hang.

**Neo4j Version:** 3.2.6
**Operating System:** Ubuntu 16.04
**API:** Cypher in web interface, also occurs from Py2Neo

### Steps to reproduce
1. With new, empty graph, enter in web interface
`CREATE CONSTRAINT ON (book:Book) ASSERT book.isbn IS UNIQUE`
### Expected behavior
Constraint should be created

### Actual behavior
Neo4J server hangs, apparently while trying to create an index. The request, and all other requests in the web interface, are just met with a spinner.
From debug.log:

`2017-10-12 13:29:17.245+0000 INFO [o.n.k.i.DiagnosticsManager] --- SERVER STARTED END ---
2017-10-12 13:29:56.701+0000 INFO [o.n.k.i.a.i.IndexPopulationJob] Index population started: [:Book(isbn) [provider: {key=lucene, version=1.0}]]
2017-10-12 13:29:57.088+0000 INFO [o.n.k.i.a.i.IndexPopulationJob] Completed node store scan. Flushing all pending updates.
BatchingMultipleIndexPopulator{activeTasks=0, executor=java.util.concurrent.ThreadPoolExecutor@1cf9354b[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], batchedUpdates = [], queuedUpdates = 0}
2017-10-12 13:29:57.088+0000 INFO [o.n.k.i.a.i.IndexPopulationJob] Shutting down executor.
BatchingMultipleIndexPopulator{activeTasks=0, executor=java.util.concurrent.ThreadPoolExecutor@1cf9354b[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], batchedUpdates = [], queuedUpdates = 0}
2017-10-12 13:51:15.551+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [4]:  Starting check pointing...
2017-10-12 13:51:15.552+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [4]:  Starting store flush...`

Discussed on [stackoverflow](https://stackoverflow.com/questions/46710894/uniqueness-constraint-causes-neo4j-to-hang)

**Comment by sherfert** [comment] 2017-10-20 14:09
Duplicate of #10251

**Comment by burqen** [comment] 2017-11-17 08:58
Actually I think this is a different issue. This involves a uniqueness constraint and db ends up hanging. This is not what we see in #10251
Re-opening

**Comment by ragadeeshu** [comment] 2017-11-21 14:58
@TomGroves I am unable to reproduce. Are you still facing this issue? If so, could you please provide additional details of your setup?

**Comment by TomGroves** [comment] 2017-11-21 15:16
Sadly not; I had to remove and reinstall Neo4J, which fixed it. Sorry.

**Comment by ragadeeshu** [comment] 2017-11-24 13:52
We have been unable to reproduce this. This issue might be because of a half-applied constraint left over form previous interactions, and might also have something to do with the fact that you deleted the db without deleting the logs. If you crash while creating a constraint, recreating it should work fine. Please do notify us if you run into this again.

**Closed as completed by ragadeeshu** 2017-11-24 13:52 UTC
Labels: team-kernel
