### ISSUE TITLE
执行mvn test 失败

### ISSUE THREAD

**Issue by dabao1990** [neo4j/neo4j#13468] opened 2024-06-06 12:16 UTC
Neo4j Version: 5.19.0 and 5.20.0
Operating System: centos8 aarch64
API: maven@3.8.2 and openjdk@17.0.2

unset JAVA_TOOL_OPTIONS;
ulimit -n 1048576;
mvn test -fn -Duser.timezone=UTC"

报错信息

--------------------< org.neo4j.community:dbms-it >---------------------
[INFO] Building Neo4j - Community DBMS Integration Tests 5.20.0-SNAPSHOT [115/141]
[INFO] --------------------------------[ jar ]---------------------------------

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
WARNING: Using incubator modules: jdk.incubator.vector
WARNING: Using incubator modules: jdk.incubator.vector
WARNING: Using incubator modules: jdk.incubator.vector
[INFO] Running org.neo4j.commandline.dbms.AdminToolTest
[INFO] Running org.neo4j.commandline.dbms.MemoryRecommendationsCommandTest
[INFO] Running org.neo4j.commandline.dbms.MigrateConfigCommandTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.324 s -- in org.neo4j.commandline.dbms.AdminToolTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.221 s <<< FAILURE! -- in org.neo4j.commandline.dbms.MigrateConfigCommandTest
[ERROR] org.neo4j.commandline.dbms.MigrateConfigCommandTest.suggestedJvmAdditionalsShouldMatchTemplate -- Time elapsed: 0.016 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
        at org.neo4j.commandline.dbms.MigrateConfigCommandTest.suggestedJvmAdditionalsShouldMatchTemplate(MigrateConfigCommandTest.java:392)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.73 s -- in org.neo4j.commandline.dbms.MemoryRecommendationsCommandTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MigrateConfigCommandTest.suggestedJvmAdditionalsShouldMatchTemplate:392 NullPointer Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
[INFO]
[ERROR] Tests run: 31, Failures: 0, Errors: 1, Skipped: 0

**Comment by dabao1990** [comment] 2024-06-06 12:29
754_233tmp' 'surefire_81-20240606191534754_247tmp'
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] org.neo4j.collection.trackable.HeapTrackingConcurrentLongObjectHashMapTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$null$3(ForkStarter.java:350)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project neo4j-cypher: There are test failures.
[ERROR]
[ERROR] Please refer to /home/stage/root/spack-stage-neo4j-5.20.0-z2ue6bsl2pp2ci5k75ip2ul4yvbgjxez/spack-src/community/cypher/cypher/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 2]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project neo4j-kernel-test: There are test failures.
[ERROR]
[ERROR] Please refer to /home/stage/root/spack-stage-neo4j-5.20.0-z2ue6bsl2pp2ci5k75ip2ul4yvbgjxez/spack-src/community/kernel-test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 2]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project dbms-it:
[ERROR]
[ERROR] Please refer to /home/stage/root/spack-stage-neo4j-5.20.0-z2ue6bsl2pp2ci5k75ip2ul4yvbgjxez/spack-src/community/community-it/dbms-it/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :neo4j-collections

**Comment by mnd999** [comment] 2024-06-06 14:52
Possibly related to https://github.com/neo4j/neo4j/issues/13375

**Comment by pontusmelke** [comment] 2024-06-11 07:42
Hi @dabao1990 
Thanks for reporting, I tried it out and it looks like https://github.com/neo4j/neo4j/issues/13375 indeed fixed the issue. So please try with a later version.

I'll close this issue, please reopen or open a new one in case the issue isn't resolved.

Regards,
Pontus

**Closed as completed by pontusmelke** 2024-06-11 07:42 UTC
Labels: bug
