### ISSUE TITLE
NullPointerException @ CloseableThreadLocal.set (2.2.0-M4)

### ISSUE THREAD

**Issue by cdshines** [neo4j/neo4j#4066] opened 2015-02-24 14:40 UTC
During the stress testing of our application this bug appears under a highly concurrent number of requests involving neo4j: 

		java.lang.NullPointerException
		at org.apache.lucene.util.CloseableThreadLocal.set(CloseableThreadLocal.java:98)
		at org.apache.lucene.index.TermInfosReader.getThreadResources(TermInfosReader.java:164)
		at org.apache.lucene.index.TermInfosReader.get(TermInfosReader.java:184)
		at org.apache.lucene.index.TermInfosReader.get(TermInfosReader.java:172)
		at org.apache.lucene.index.SegmentReader.docFreq(SegmentReader.java:539)
		at org.apache.lucene.search.TermQuery$TermWeight$1.add(TermQuery.java:56)
		at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:81)
		at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:87)
		at org.apache.lucene.util.ReaderUtil$Gather.run(ReaderUtil.java:70)
		at org.apache.lucene.search.TermQuery$TermWeight.<init>(TermQuery.java:53)
		at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:199)
		at org.apache.lucene.search.Searcher.createNormalizedWeight(Searcher.java:168)
		at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:664)
		at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:319)
		at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:305)
		at org.neo4j.kernel.api.impl.index.PageOfRangesIterator.fetchNextOrNull(PageOfRangesIterator.java:67)
		at org.neo4j.kernel.api.impl.index.PageOfRangesIterator.fetchNextOrNull(PageOfRangesIterator.java:35)
		at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
		at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
		at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongConcatingIterator.fetchNext(PrimitiveLongCollections.java:194)
		at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongBaseIterator.hasNext(PrimitiveLongCollections.java:54)
		at org.neo4j.kernel.InternalAbstractGraphDatabase$PropertyValueFilteringNodeIdIterator.fetchNext(InternalAbstractGraphDatabase.java:1360)
		at org.neo4j.collection.primitive.PrimitiveLongCollections$PrimitiveLongBaseIterator.hasNext(PrimitiveLongCollections.java:54)
		at org.neo4j.collection.primitive.PrimitiveLongCollections$13.hasNext(PrimitiveLongCollections.java:708)
		at org.neo4j.helpers.collection.ResourceClosingIterator.hasNext(ResourceClosingIterator.java:61)
		at ontrack.bush.util.stream.TxSpliterator.tryAdvance(TxSpliterator.java:51)
		at ontrack.bush.util.stream.TxSpliterator.forEachRemaining(TxSpliterator.java:35)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
		at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
		at dnet.controller.services.files.Allocate.rpc(Allocate.java:41)
		at fw.network.BeeServiceInvoker.invokeRpc(BeeServiceInvoker.java:70)
		at fw.network.BeeServiceInvoker.invoke(BeeServiceInvoker.java:46)
		at fw.network.BeeServiceInvoker.invoke(BeeServiceInvoker.java:36)
		at fw.hive.invoker.InvocationChain.submit(InvocationChain.java:114)
		at fw.network.server.BeeNetworkMessageProcessor.process(BeeNetworkMessageProcessor.java:103)
		at fw.network.server.BeeNetworkMessageProcessor.handlePayload(BeeNetworkMessageProcessor.java:69)
		at fw.network.server.AbstractNetworkMessageProcessor.run(AbstractNetworkMessageProcessor.java:134)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

The code is something like this (not exactly, just the gist), so there is really not so much place to fail for me:

		try (Transaction tx = db.beginTx()) {
			long sum = 0L;
			for (Node node : loop(db.findNodes(label, key, value))) {
				sum += node.getProperty("prop", 0L);
			}
			return sum;
		}

We also experience periodic index misses from time to time (I believe this has something to do with 'eventual' consistency). If there is anything I can do to help to resolve this issue, I'd be glad to.

**Comment by jexp** [comment] 2015-02-24 19:28
Thanks a lot for reporting it, we'll get back to you when we know more about the cause.

**Comment by rickardoberg** [comment] 2015-03-02 06:17
@cdshines I would like to have some extra info to investigate this.

Which JDK version are you using?

Are you using embedded or server?

Is this single instance or clustered?

**Comment by rickardoberg** [comment] 2015-03-02 08:02
@cdshines so, in general, to get that particular error the database has to be shutdown while you are doing the code you outlined. Which should be impossible, as the database on shutdown waits for transactions to finish. However, there is a timeout for that wait, so the only scenario I can see is that the database is shutting down, the transactions you are doing take too long time, and so in the end you'll be accessing the database in a shutdown state, yielding exceptions. Is that possible in your case?

**Comment by cdshines** [comment] 2015-03-02 18:34
~|⇒ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
    ~|⇒ javac -version
    javac 1.8.0_31

This is an embedded HA database running a single instance (yeah, I know, kind of silly).

And no, the database can't be possibly shutting down since this is just a 1 per roughly 10-100K calls to the service that fails, and there are other succeeding calls to that very service after this exception.

By the way, can you address another question I have? Basically, if I obtained an iterator from `db.findNodes()` and closed the transaction, but then I open another one and try to iterate through that iterator, it fails. I suppose that's a normal behavior? What's the motivation behind it? If I'm not asking too much :)

**Comment by chrisvest** [comment] 2015-03-02 19:56
@cdshines Technically: The iterator is lazy, so we don't exhaust it unless you do. Saves memory. When you make use of indexes, your Neo4j transaction acquires a Lucene transaction as well. Because we use Lucene for indexes. When you close a transaction, all resources attached to it are closed and released as well. This includes that Lucene transaction that your iterator was feeding from.

Logically: Each transaction have their own "scope" for atomicity, consistency, isolation and durability. The iterator belongs to the scope of a particular transaction, and can't be used in any other. I guess the lines can sometimes seem blurred when you are using embedded mode, but they're still there.

Did you get this exception by using an iterator from a closed transaction? If so, then we could look into providing a better error message.

**Comment by cdshines** [comment] 2015-03-02 20:48
@chrisvest, @rickardoberg 
I got rid of that piece of code, but IIRC that had to do something with periodically closing/opening the transaction (I knew beforehand that traversal will return ~100K elements and I didn't need the atomicity of a single transaction, so I decided to optimise prematurely, I guess), and now that I think about it - yes, it might've been happening right in that place.
I got your point and now I think that my idea of 'chunked transactions' was really not that good :)

**Comment by rickardoberg** [comment] 2015-03-03 08:32
@cdshines it is absolutely possible for the single instance to be shutting down. Basically, what might be happening is that you get a long GC pause, this causes a timeout where the instances thinks that it is dead (in the HA sense), tries a new election, and does an down-up maneuver to recover, at which point the database is temporarily unavailable for transactions. Can you try with plain embedded without HA, to see if that fixes it?

**Comment by cdshines** [comment] 2015-03-03 16:27
@rickardoberg, just to be clear - does what you said hold even for a single node setup?

**Comment by rickardoberg** [comment] 2015-03-04 05:43
@cdshines double-checked, and no, you're right, for single node there is no heartbeat, so can't happen. Still, the reason the exception happens is because that index reader has been closed. Was this one of the places where an iterator was reused from another transaction? If so, there you have the issue.

**Comment by cdshines** [comment] 2015-03-04 12:53
@rickardoberg Yes, I guess it was. Thank you for your time. 

P.S. Would be nice to have a more explanatory exception though :)

**Comment by rickardoberg** [comment] 2015-03-05 04:51
@cdshines ok, good to know! And yes, the exception should have been translated into a "not in transaction" error or somesuch, agreed!

**Closed by rickardoberg** 2015-03-05 04:51 UTC
Labels: 2.2, bug, kernel
