### ISSUE TITLE
Write Transaction Interfering with Reads

### ISSUE THREAD

**Issue by Hoekz** [neo4j/neo4j#12250] opened 2019-07-24 15:18 UTC
### Summary
We started seeing an issue in our applications where data was sometimes not returned from API calls. While investigating, it appeared to be an issue where write transactions happening in one application that destroys and recreates a node in the database interfere with the read transactions from the APIs. This seems to violate the expectation that the write transaction should be self-contained and not affect the read of the same node.

We've setup a simplified version of this problem occurring. We first create a node and spin up a separate instance of the application to simply continually query for that node. We then continually run a write transaction that first deletes the node and then recreates the node with a configurable delay in between those two steps (however, the same transaction is still used in both steps).

### Setup

- Neo4j: (Enterprise) v3.5.3 (also tried v3.5.6)
- OS: MacOS Mojave (Neo in Docker), Ubuntu 14 (Servers)
- Driver: Java v1.7.3
- Language: Scala v2.13.0

### Steps to Reproduce
[Linked Repo](https://github.com/Hoekz/NeoTransactionInvestigation). Run twice at the same time, once in write mode, and once in read mode.

`sbt "run 0"` - runs in write mode with 0ms delay between delete and create in same transaction.
`sbt "run read-mode"` - runs in read mode with a constant read of the same node and reports when the node is either found or not found.

These two commands should be run at the same time in two different terminals (better to kick off the write first, but should be very little delay between starting the read).

### Expected

No matter the delay used, the read should always see a node.

### Actual

With no or very little delay (<= 10ms), the read intermittently fails to find the node.
With a longer delay (1s), the read always finds the node.

**Comment by Hoekz** [comment] 2019-07-26 14:05
To pull the context of the repo into this conversation: The write app continually runs this transaction:

```scala
def deleteAndCreateNode(tx: Transaction) = {
    deleteNode(tx) // MATCH (a:Investigation { id: '1234567890' }) DELETE a
    Thread.sleep(delay)
    createNode(tx) // CREATE (a:Investigation { id: '1234567890', name: 'test' }) RETURN a
  }
```

The read node continually runs this transaction (underlying query alter slightly from original to return whole node rather than just the name property):
```scala
  def readNameFromNode(tx: Transaction) = {
    val result: StatementResult = tx.run("MATCH (a:Investigation { id: '1234567890' }) RETURN a")

    val maybeName: util.List[Record] = result.list()

    if (maybeName.isEmpty) None else Some(maybeName.get(0).get(0))
  }
```

When running these two in concurrent/parallel apps, we see `None` get returned from the read transaction intermittently when the delay for the write transaction was set to anything under 10ms. When the delay was set to 1s however, we never see `None` returned by the read transaction.

The deletion and creation of the node is reflective of what we have in our real world scenario, just greatly simplified, and the consistent running of the write node is also reflective of our scenario, but the nodes/relationships being deleted changes virtually every run in our real apps, so the collision rate is much lower, but has been observed.

**Comment by InverseFalcon** [comment] 2019-07-29 14:40
This is an odd thing and bears some investigation. Neo4j should be read committed, so reads should only be seeing the committed state and not an in-between state from another transaction in-flight.

If you do need full exclusion between reading and writing then you may want to synchronize on a separate node made explicitly for that purpose. Since your use case involves deleting the node in question, we cannot synchronize on that, as it may not be present at the time of the read. This will have to be a different node as the synchronizer.

You can explicitly take locks on a node by either making use of [APOC locking procedures](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#locking) or by setting and then removing a label on the node which will engage the write lock. Note that this will make your query into a write operation, which if run on a cluster should use the writeTransaction() function to route it to the cluster leader.

Alternatively, if you know this node will always be recreated, you might instead just clear out its properties (with `SET n = {}`) and delete its relationships (if it has any) such that the node remains in the graph, which will let you lock on the node from your read queries, with no need for a separate node as a synchronizer.

**Comment by sherfert** [comment] 2019-07-29 16:27
Hi @Hoekz 

I think what you observe is a non-repeatable read anomaly. That means that the read transaction can happen to read the node id before the node was deleted, but then when it tries to return the node (and therefore read its properties), the node does not exist any longer. It is more likely to happen the more write transactions you have, which is why you see the anomaly more often with lower delays.

@InverseFalcon 's suggestion with setting and removing a Label should unfortunately not solve the problem, since it can still happen that the node is read in `MATCH` but then when we try to take a lock for `SET`, the node does not exist.

We have a naive version of executing a query on a snapshot. This option can be enabled through a configuration option and should solve your problem: Set `unsupported.dbms.query.snapshot` to `true`. Can you try that and see if it works for your case?

**Comment by Hoekz** [comment] 2019-07-29 17:38
Hi @sherfert,

We tried running with the snapshot flag and while it lessened the frequency of the observed issue, it was still present. What you're describing sounds like Neo4j does not meet ACID compliance (specifically Isolation).

Our situation in the real world is far more complex than the simple example. It's a cluster of 5 core nodes and 3 read nodes with several ingestion apps writing data and many more APIs reading data. We're ingesting data from a pipeline and end up deleting and recreating both nodes and relationships during reingestion. We're seeing these deletes/creates interfere with at least 2 locations in our system and in multiple ways (both from referencing the original node and referencing nodes attached to the entry node). We've implemented some logic to mitigate this by retrying queries in situations that we recognize as being invalid, but it by no means covers all our edge cases. Because of this, we'd really like to be able to avoid rewriting our ingestion transaction as it would be a pretty substantial rewrite.

I guess I'm left with 2 questions at this point:
1) Does this mean that Neo4j is not ACID compliant?
2) For the `unsupported.dbms.query.snapshot`, should we choose to enable this on our servers, what sort of performance impact might we see? It does seem to make the situation better, but it might not be worth it if we lose performance.

**Comment by sherfert** [comment] 2019-07-30 13:50
Hi @Hoekz 

I tried reproducing your issue. If I set `unsupported.dbms.query.snapshot` to `true`, the reason that we still see `*****NOT FOUND*****` is because of the test setup. I [made some modifications](https://github.com/Hoekz/NeoTransactionInvestigation/pull/1) so that we create the node in a separate setup step and don't delete it after the 30 seconds. After that, I got `Missing 0 / 27298 times`.

With respect to your questions:

1. We provide the [read-committed isolation level](https://en.wikipedia.org/wiki/Isolation_(database_systems)#Read_committed). Non-repeatable read (which is the issue you are seeing) is an anomaly that can appear with that isolation level. The snapshot flag solves this anomaly.
2. The implementations uses a retry-loop and checks for dirty reads. The number of retries can be configured with `unsupported.dbms.query.snapshot.retries` and defaults to 5. You can observe overhead from
  * running your queries more than once in the retry-loop, and
  * having to eagerly consume the result on the server side to check if dirty reads occurred.

**Comment by Hoekz** [comment] 2019-07-30 15:41
Ok, thank you for the explanation, it feels a little weird that a `MATCH` and a `RETURN` are considered separate reads though (If I'm understanding you correctly).

We will try using the snapshot flag in our test environments to see if it solves our issue enough without too much of a performance hit.

**Comment by chrisvest** [comment] 2019-07-30 18:09
> 2. The implementations uses a retry-loop and checks for dirty reads.

Sorry for being pedantic, but it's non-repeatable reads. A "dirty read" is seeing writes from _uncommitted_ transactions, which is not what is happening. Just wanted to make that clear.

**Comment by sherfert** [comment] 2019-07-31 06:25
@Hoekz the reason that the `MATCH` and the `RETURN` are separate reads is because in the `MATCH` we only fetch the node id, nothing else. Since you are returning the node, we need to "populate" it with all its properties and labels (which we look up by node id), and that happens in the `RETURN`. Moreover you also have a `WHERE a.id = '1234567890'` hidden in your `MATCH`, and that property read is also by node id. If the other transaction commits anywhere between these reads, the node with that id cannot be found any longer.

If you create an index on `:Investigation(id)`, then we can find the node with the correct property with just one read. If you then also change `RETURN a` to `RETURN id(a)`, so you only return the internal node id without populating the node, there can be no non-repeatable reads. I confirmed that as well with the test setup. I hope this explanation helps.

**Closed as completed by sherfert** 2019-07-31 06:25 UTC
Labels: bug

**Comment by InverseFalcon** [comment] 2019-07-31 21:01
Just to note, the proposal to use a separate node as a synchronizer is still viable, though you will need to ensure both reads and writes of the node(s) in question first take locks on the separate synchronizer node to ensure mutual exclusion for all operations on the node, including the reads from a MATCH.

As previously mentioned, if it's at all possible to avoid deleting the node entirely, and instead doing only a delete/overwrite of properties (except id) and possibly deleting relationships from it (if needed), that would allow the node to always be visible for matches on the node by id, and may circumvent the race condition.
