### ISSUE TITLE
Is the heap not being released?

### ISSUE THREAD

**Issue by TonyHenrique** [neo4j/neo4j#12719] opened 2021-05-08 16:08 UTC
I am having a problem with Neo4j:

I start the neo4j database and it looks good, handles all the queries with no apparent problem:
![image](https://user-images.githubusercontent.com/6307623/117547093-227e6a80-b004-11eb-80da-a3ce1a26c203.png)

But the heap usage keeps growing. The minimum on the chart of the used Heap grows slowly every time; After some hours the graph looks like this:
![image](https://user-images.githubusercontent.com/6307623/117595576-952c3a80-b117-11eb-9d95-9c047ffedb49.png)

Then after some hours, keeping receiving those requests / queries the database start to reach the maximum Heap space:

![image](https://user-images.githubusercontent.com/6307623/118346820-993fca00-b514-11eb-9939-1859380369ee.png)

Then it fails and I receive this e-mail:

> We're reaching out to let you know that your database was automatically restarted at 13:58 UTC, March 28 due to an Out of Memory(OOM) issue.
> Please do profile your requests to make sure your lookups are indexed and to identify potential expensive queries that could result in Neo4j running out of memory. 
> 

I already created all the relevant Indexes, checked the queries. I can not find what is causing this issue.

**Neo4j Version:** Neo4j Community version 4.2.4

### Steps to reproduce
1. Start the server
2. Let it running
3. Run thousands connections / Cypher queries

### Expected behavior
Database should release Heap (completely to the same amount it had when database was restarted).

### Actual behavior
Heap usage keeps growing until database hits OOM Out of Memory and stops responding.

**Comment by InverseFalcon** [comment] 2021-05-19 01:18
As of Neo4j 4.2.x, I believe, the community edition should allow you to use `:queries`, `CALL dbms.listQueries()`, and `CALL dbms.listTransactions()`. If you use those, can you see if the transactions linger or build up as the memory appears to leak? If so, then there's an issue here on either long-running queries (likely requiring tuning) or on properly consuming the results and closing resources.

Also check your debug logs. If you are seeing frequent and spiking stop-the-world pauses, with positive gcCounts, then this may be an issue of query tuning, some bad queries eating up your heap. 

You may also want to take a look at some of the configuration properties for controlling the amount of heap queries are allowed to use. Take a look at the `dbms.memory.transaction` prefixed config options.

**Comment by TonyHenrique** [comment] 2021-05-19 01:26
After all day today, right now I ran this

`CALL dbms.listTransactions()`

```
╒════════════════════════════╤═══════════╤═══════════════════════════════════════════════════╤══════════════════════════╤══════════╤══════════════════╤═════════════════╤════════════════╤══════════════════════════════╤═════════════════╤═════════╤═════════════════════╤═══════════════════╤═══════════════╤════════════════╤════════════════╤════════════════╤══════════════════════╤══════════╤════════════╤══════════════╤══════════════════════════╤══════════╤═════════════════════════╕
│"transactionId"             │"username" │"metaData"                                         │"startTime"               │"protocol"│"clientAddress"   │"requestUri"     │"currentQueryId"│"currentQuery"                │"activeLockCount"│"status" │"resourceInformation"│"elapsedTimeMillis"│"cpuTimeMillis"│"waitTimeMillis"│"idleTimeMillis"│"allocatedBytes"│"allocatedDirectBytes"│"pageHits"│"pageFaults"│"connectionId"│"initializationStackTrace"│"database"│"estimatedUsedHeapMemory"│
╞════════════════════════════╪═══════════╪═══════════════════════════════════════════════════╪══════════════════════════╪══════════╪══════════════════╪═════════════════╪════════════════╪══════════════════════════════╪═════════════════╪═════════╪═════════════════════╪═══════════════════╪═══════════════╪════════════════╪════════════════╪════════════════╪══════════════════════╪══════════╪════════════╪══════════════╪══════════════════════════╪══════════╪═════════════════════════╡
│"graph.db-transaction-62638"│"[omitted]"│{"type":"user-direct","app":"neo4j-browser_v4.2.5"}│"2021-05-19T01:22:39.236Z"│"bolt"    │"172.28.0.1:46670"│"172.28.0.2:7475"│"query-63655"   │"CALL dbms.listTransactions()"│0                │"Running"│{}                   │36                 │0              │0               │36              │0               │0                     │0         │0           │"bolt-9774"   │""                        │"graph.db"│152                      │
└────────────────────────────┴───────────┴───────────────────────────────────────────────────┴──────────────────────────┴──────────┴──────────────────┴─────────────────┴────────────────┴──────────────────────────────┴─────────────────┴─────────┴─────────────────────┴───────────────────┴───────────────┴────────────────┴────────────────┴────────────────┴──────────────────────┴──────────┴────────────┴──────────────┴──────────────────────────┴──────────┴─────────────────────────┘
```

`CALL dbms.listQueries()`

```
╒═════════════╤═══════════╤═══════════════════════════════════════════════════╤═════════════════════════╤════════════╤═════════╤═════════════╤═════════╤══════════════════════════╤══════════╤══════════════════╤═════════════════╤═════════╤═════════════════════╤═════════════════╤═══════════════════╤═══════════════╤════════════════╤════════════════╤════════════════╤══════════╤════════════╤══════════════╤══════════╕
│"queryId"    │"username" │"metaData"                                         │"query"                  │"parameters"│"planner"│"runtime"    │"indexes"│"startTime"               │"protocol"│"clientAddress"   │"requestUri"     │"status" │"resourceInformation"│"activeLockCount"│"elapsedTimeMillis"│"cpuTimeMillis"│"waitTimeMillis"│"idleTimeMillis"│"allocatedBytes"│"pageHits"│"pageFaults"│"connectionId"│"database"│
╞═════════════╪═══════════╪═══════════════════════════════════════════════════╪═════════════════════════╪════════════╪═════════╪═════════════╪═════════╪══════════════════════════╪══════════╪══════════════════╪═════════════════╪═════════╪═════════════════════╪═════════════════╪═══════════════════╪═══════════════╪════════════════╪════════════════╪════════════════╪══════════╪════════════╪══════════════╪══════════╡
│"query-63546"│"[omitted]"│{"type":"user-direct","app":"neo4j-browser_v4.2.5"}│"CALL dbms.listQueries()"│{}          │"idp"    │"interpreted"│[]       │"2021-05-19T01:21:30.719Z"│"bolt"    │"172.28.0.1:46664"│"172.28.0.2:7475"│"running"│{}                   │0                │7                  │null           │0               │null            │0               │0         │0           │"bolt-9773"   │"graph.db"│
└─────────────┴───────────┴───────────────────────────────────────────────────┴─────────────────────────┴────────────┴─────────┴─────────────┴─────────┴──────────────────────────┴──────────┴──────────────────┴─────────────────┴─────────┴─────────────────────┴─────────────────┴───────────────────┴───────────────┴────────────────┴────────────────┴────────────────┴──────────┴────────────┴──────────────┴──────────┘
```
Right now the Halin shows me this Heap usage, is not getting below 1.2G. If I restart the Database then the Heap starts to getting to minimum about 300MB

![image](https://user-images.githubusercontent.com/6307623/118743387-a7e5f400-b828-11eb-90f0-425d64c39c5f.png)


About the (bad) queries: Right now, the database usage is low, users use it more on daytime. But Heap still not get lower value as it does when restart database. Can the Bad Queries prevent the Heap from being released?

**Comment by TonyHenrique** [comment] 2021-05-19 14:17
Today, the Database was Restarted the Heap minimum was about 200 and 300MB and now, under user load, this is the Heap chart, with minimum between 400 and 500 MB
![image](https://user-images.githubusercontent.com/6307623/118828464-adc4ef00-b893-11eb-87cd-837408419b29.png)

By my experience I know that after about 30 hours under this load, the Heap will grow until it gets OOM.

**Comment by TonyHenrique** [comment] 2021-05-20 15:40
I had to put a scheduled task to restart the database every day at dawn. 
I would like a solution on this because it is requiring to have a instance with too much RAM to handle those requests, but based on the heap usage incrementally not being released I guess that when this get fixed I could have much lower memory requirement.

**Comment by TonyHenrique** [comment] 2021-05-20 23:24
How can I export the data so I can import into neo4j 3.x again?  
Is there a way using the neo4j browser to download the whole data as a TXT file with all the Cypher commands that we could use to recreate the whole graph data in a blank database? 
I was using neo4j 3.x and upgraded to 4.x . I believe that downgrading the database would allow me to have more Heap available, because I suspect that this problem worsened after I upgraded to version 4.x

**Comment by mnd999** [comment] 2021-05-21 10:19
You could certainly try `db.clearQueryCaches` to see if that helps, otherwise it may be a case of taking a heap dump and seeing what is filling up the heap.

**Comment by TonyHenrique** [comment] 2021-05-21 13:04
Hey!
`CALL db.clearQueryCaches();`
It looks like this solved the issue! Now the Heap looks good.
I will put it as a scheduled task and monitor for the next day and see if this solution stabilizes.

Thank you very much! Now it is looking good! Graphs are awesome.
![image](https://user-images.githubusercontent.com/6307623/119141315-7a14d100-ba1b-11eb-8719-4951fe711baf.png)

**Comment by TonyHenrique** [comment] 2021-05-22 02:07
I tried it all day, but it does not seems to solve the issue.
I make a lot of requests using JMeter, then `CALL db.clearQueryCaches` but the Heap never returns to the initial levels. So in about 30 hours the Database would hit an Out of Memory.
This would require a bigger RAM, but I would like a way to the Heap to return to initial levels so I do not need to have increase the RAM just because the Heap is not being released.

I tried this same data on neo4j Aura and got even worse results on the 1GB Aura it got OOM on a few tests I did. 

I would like to use neo4j on all my future projects, but these memory requirements force to use a too costly VM, for example, the ideal for me would be $60 for a 4GB RAM offering. that seems to be the minimal for it to 4.x work at least one entire day without having to restart the database during day time operation.

Here is the chart for this database I restarted under a 2GB RAM  1 vCPU, applied about 400 queries in a few seconds. Then even after `CALL db.clearQueryCaches` you can note that the Heap did not return to initial values.

![image](https://user-images.githubusercontent.com/6307623/119211413-5045c380-ba88-11eb-8991-e987de23022b.png)

After some minutes:
![image](https://user-images.githubusercontent.com/6307623/119212173-feec0300-ba8c-11eb-8ac3-e1b188b7f1d6.png)

Notice that the Heap that initially had lower of 100MB now it does not fall below 200MB. 

EDIT:
After more minutes that I ran the clear query caches command, then it returned to the 100MB level on this machine...

![image](https://user-images.githubusercontent.com/6307623/119212366-36a77a80-ba8e-11eb-9e8b-138bf0ad76d3.png)

Sorry for the confusing trajectory, but that is what I observed as a newbie.

**Comment by TonyHenrique** [comment] 2021-05-23 00:09
Well after some hours running, today is saturday and we have few users and queries, even after `CALL db.clearQueryCaches` a few times, the Heap does not fall to original levels about 100MB anymore. So to run safely (requiring a restart every dawn), I will have to increase RAM. I would like a solution for this Heap issue.

![image](https://user-images.githubusercontent.com/6307623/119243931-ba6e6f00-bb41-11eb-953f-b19131837d0b.png)

A few hours later after I cleared the Query Caches, I checked again, and the Heap is back to the "normal levels" with minimum about 100MB

![image](https://user-images.githubusercontent.com/6307623/119247699-4bedd900-bb62-11eb-891b-8b815760a192.png)

**Comment by TonyHenrique** [comment] 2021-05-26 16:46
I put a scheduled task to clear the Query Cache every 15 minutes and then all requests got working well with no Heap issues or Database Out of Memory errors. This allowed me to use a smaller and more viable machine for the same database.
Thank you very much for your help, Mark @mnd999  !

**Comment by mnd999** [comment] 2021-05-27 07:24
If the query caches are filling up, it might be worth examining your queries to see if you can make better use of parameters, this may also reduce the amount of work the planner has to do and make things faster overall.

**Comment by klaren** [comment] 2021-05-31 07:28
You can also lower the configuration value `dbms.query_cache_size` so neo4j will cache fewer queries. Default is 1000.

**Comment by mnd999** [comment] 2021-06-01 08:07
Will close this one for now as it seems like the problem is resolved, please feel free to reopen if you're still having issues.

**Closed as completed by mnd999** 2021-06-01 08:07 UTC
Labels: bug
