### ISSUE TITLE
neo4j-admin import stuck at Relationships counts

### ISSUE THREAD

**Issue by whwang1996** [neo4j/neo4j#12240] opened 2019-07-04 14:03 UTC
## Guidelines

- Neo4j version: 3.5.6
- Operating system: Windows 10, 64G RAM, AMD R1700
- API/Driver: neo4j-admin import
- **Steps to reproduce**
I tried to import 40M nodes, 260M nodes properties and 300M relationships. 
The number of node labels is about 40,000, and a node may have more than one label. 
The number of relationship types is about 1,100, and a relationship haves only one type. 

The command I ran:
```
neo4j-admin import  
--nodes=C:\Whole\nodes\nodes_0.csv (71 files in total)
--relationships=relationships.csv (only 1 file)
--array-delimiter=";"
```
The previous steps were completed in an hour. But it stuck at `Relationship Counts` for 21h already and it doesn't seem to be finished:

```
******** DETAILS 2019-07-04 12:48:10.330+0000 ********
        Relationship counts
        [*>(10)==========================================|COUNT(9)====================================] 299M
        I/O throughput: 746.40 MB/s
        VM stop-the-world time: 51m 11s 967ms
        Duration: 21h 18m 29s 433ms
        Done batches: 29924
```
The CPU it uses is about 0%, and RAM use is about 14G

Thanks for your help!
------------------------------------------------------
Finally, I succeeded by importing the nodes first, which took me about 30 minutes. Then I import the relationships by APOC manually, which took me about 4 hours.
Thank you anyway!

**Comment by tinwelint** [comment] 2019-11-21 09:09
Hi, sorry for the delay. Did this work out in the end? If not what's your machine specs w/ regards to memory and number of CPUs. Also, have you tried the latest 3.5.x version?

**Comment by tinwelint** [comment] 2019-11-21 10:15
What was the I/O numbers during that time of virtually no CPU work? By the looks of it it's fairly high. I'd guess since you have so many labels it will cause node labels in the store to be stored less efficiently and in the importer there's only a small page cache and will therefore cause lots of page eviction over and over.

Yup, this case where there are lots and lots of labels isn't handled very well in the importer and could probably be improved. I'll sketch out some ideas around it.

**Comment by tinwelint** [comment] 2019-11-22 07:59
@whwang1996 When reproducing this locally I could also see relationship counts stage taking a very very long time in the very end. This is when it would build the counts store. And due to how the counts store updating works in 3.5 it would be very inefficient to do and require lots of heap... but it would eventually complete. In 4.0 this counts store building problem is fixed already. This is of course assuming that this is the problem you saw. A thread dump when it happened for you would have been helpful.

Given that you worked around this and likely 4.0 has this fixed, unless you have more information on the matter I'd suggest closing this issue. Would that be OK?

**Comment by whwang1996** [comment] 2019-11-23 04:03
> @whwang1996 When reproducing this locally I could also see relationship counts stage taking a very very long time in the very end. This is when it would build the counts store. And due to how the counts store updating works in 3.5 it would be very inefficient to do and require lots of heap... but it would eventually complete. In 4.0 this counts store building problem is fixed already. This is of course assuming that this is the problem you saw. A thread dump when it happened for you would have been helpful.
> 
> Given that you worked around this and likely 4.0 has this fixed, unless you have more information on the matter I'd suggest closing this issue. Would that be OK?

Thanks for your detailed explanation. And since it has been fixed, just close it.

**Closed as completed** 2019-11-24 15:34 UTC
Labels: bug, team-kernel
