### ISSUE TITLE
Warnings about "Illegal reflective access" are printed on startup (4.0) 

### ISSUE THREAD

**Issue by eastlondoner** [neo4j/neo4j#12279] opened 2019-08-25 15:50 UTC
- Neo4j version: 4.0
- Operating system: Official Docker Container on Linux

**Steps to reproduce**
- Start neo4j docker container

## Report

Neo4j 4.0 prints warnings about illegal reflexive access on startup (see below)

### Steps to reproduce
1. Start Neo4j Docker container

### Expected behaviour
Scary warnings about illegal access should not be routine (I hope).

### Actual behavior
```
Starting Neo4j.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.commons.lang3.reflect.FieldUtils (file:/var/lib/neo4j/lib/commons-lang3-3.9.jar) to field sun.nio.ch.FileChannelImpl.fd
WARNING: Please consider reporting this to the maintainers of org.apache.commons.lang3.reflect.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by chrisvest** [comment] 2019-08-25 19:28
Duplicate of #12277, and yeah, they are pretty much routine at this point. They _should_ all have work-arounds, though, so it would be a bug if stuff broke with `--illegal-access=deny`.

**Closed as completed by chrisvest** 2019-08-25 19:28 UTC
Labels: bug

**Comment by eastlondoner** [comment] 2019-08-25 23:13
@chrisvest what do you think about setting `--illegal-access=deny` by default in the docker packaging ?

**Comment by chrisvest** [comment] 2019-08-26 07:11
@eastlondoner Why is the docker packaging special?

**Comment by MishaDemianenko** [comment] 2019-08-26 07:14
@eastlondoner speaking of being special: why do we have this issue/discussion here and not in trello?

**Comment by eastlondoner** [comment] 2019-08-26 19:02
Currently (3.5 etc.) when you run the neo4j docker container and it's working correctly _nothing_ is output to `stderr`. In 4.0 these warnings are output to `stderr`. I'd be much happier if these warnings were sent to neo4j.log or debug.log rather than stderr. 

@chrisvest where stdout and stderr logs/warnings are sent is packaging-dependent. But I do think this is something that would be better handled in the core product. However if it isn't I will probably make a PR to change the docker packaging because I can do that.

I don't think it's a good principle in general to print warnings somewhere highly visible if they're expected and we don't want the user to do anything about them. Imagine if your car had a warning light on the dash that was always on.

@MishaDemianenko I'm on parental leave for a year - this is me with my "neo4j hobby user" hat, not my "neo4j employee" hat.
