### ISSUE TITLE
List concatenation causes unexpected type conversion

### ISSUE THREAD

**Issue by tcfritchman** [neo4j/neo4j#11242] opened 2018-03-13 17:57 UTC
Experiencing an issue with list concatenation in Cypher where using the '+' operator on lists of strings causes some unexpected type conversion.

This issue was introduced for us when upgrading from neo4j 3.2.3 to 3.3.3.

**Neo4j Version:** 3.3.3
**API:** Cypher

### Steps to reproduce
Run the following in Neo4j Browser:
`:params {skus: ['123', '234'], styles:['567'], pid:'3'}`
```
UNWIND $skus+$styles AS sku
MERGE (pts:Pts {pk: $pid+'_'+sku})
ON CREATE SET pts.color=split(sku, ':')[1]
```

### Expected result
The transaction should succeed as it does in version 3.2.3

### Actual result
Fails with the following error:
```
Type mismatch: expected String but was Any, Boolean or Float (line 3, column 31 (offset: 93))
"ON CREATE SET pts.color=split(sku, ':')[1]"
                               ^
```

**Comment by sherfert** [comment] 2018-03-16 12:05
Hey. I just tried reproducing it and I am quite sure this bugfix https://github.com/neo4j/neo4j/pull/11161 also fixed your issue. This fix is included in 3.3.4.

That being said, your query will set `pts.color` to `null`, since `split('123', ':')` (and the likes) has only size 1.

**Closed as completed by sherfert** 2018-03-16 12:05 UTC
Labels: team-cypher
