### ISSUE TITLE
non-fatal NPE on JMX websocket handshake from HTTP browser running on BOLT in wrapped EnterpriseBootstrapper around embedded mode EnterpriseGraphDatabase

### ISSUE THREAD

**Issue by obriensystems** [neo4j/neo4j#8548] opened 2016-12-26 23:15 UTC
- Neo4j version: 3.1.0
- Operating system: MacOS (10.12.1) running Tomcat 8.0.28, Redhat RHEL 7.2 running 8.0.28 and Amazon Linux 4.4.23 running Tomcat 8.0.36 (ElasticBeanstalk)
- API/Driver: java 8 embedded

I get this regardless of tomcat version, OS and where it runs (locally, AWS beanstalk)
When we run the http browser (7575) over bolt (7688) we get a nonfatal NPE on JMX handshake.
This error does not look to affect functionality - it just pollutes the logs every x seconds

```
2016-12-24 16:28:19.005+0000 INFO  [REQUEST] [AsyncLog @ 2016-12-24 16:28:19.004+0000]  179.99.99.99 -  [Sat Dec 24 16:28:19 UTC 2016] "/?null" 200 -1 "http://biometric-nbi.us-east-1.elasticbeanstalk.com:7575/browser/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36" 5


2016-12-24 16:29:19.742+0000 DEBUG [io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder] Decoding WebSocket Frame length=40
2016-12-24 16:29:19.752+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Exception invoking method writeBufSize. See debug.log for more details, reference 0926f32f-a363-4e29-81b4-38a2fabdb51f.
2016-12-24 16:29:19.753+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Exception invoking method writeBufSize, reference 0926f32f-a363-4e29-81b4-38a2fabdb51f. Exception invoking method writeBufSize
javax.management.RuntimeOperationsException: Exception invoking method writeBufSize
	at org.apache.tomcat.util.modeler.BaseModelMBean.getAttribute(BaseModelMBean.java:196)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at org.neo4j.kernel.builtinprocs.JmxQueryProcedure.toNeo4jValue(JmxQueryProcedure.java:131)
	at org.neo4j.kernel.builtinprocs.JmxQueryProcedure.toNeo4jValue(JmxQueryProcedure.java:119)
	at org.neo4j.kernel.builtinprocs.JmxQueryProcedure.lambda$apply$0(JmxQueryProcedure.java:91)
	at org.neo4j.collection.RawIterator$2.fetchNextOrNull(RawIterator.java:84)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.api.OperationsFacade$1.hasNext(OperationsFacade.java:1583)
	at org.neo4j.cypher.internal.spi.v3_1.TransactionBoundQueryContext$$anon$2.hasNext(TransactionBoundQueryContext.scala:633)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply$mcZ$sp(ExceptionTranslationSupport.scala:47)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:47)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$$anon$1$$anonfun$hasNext$1.apply(ExceptionTranslationSupport.scala:47)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
	at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContextFor3_1.translateException(ExceptionTranslatingQueryContextFor3_1.scala:34)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$$anon$1.hasNext(ExceptionTranslationSupport.scala:47)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.neo4j.cypher.internal.spi.v3_1.ExceptionTranslationSupport$$anon$1.foreach(ExceptionTranslationSupport.scala:46)
	at org.neo4j.cypher.internal.compiler.v3_1.executionplan.procs.ProcedureExecutionResult.accept(ProcedureExecutionResult.scala:69)
	at org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor3_1.accept(CompatibilityFor3_1.scala:402)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply$mcV$sp(ClosingExecutionResult.scala:169)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$1.apply(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_1$runSafely$.apply(CompatibilityFor3_1.scala:190)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:168)
	at org.neo4j.cypher.internal.javacompat.ExecutionResult.accept(ExecutionResult.java:317)
	at org.neo4j.bolt.v1.runtime.cypher.CypherAdapterStream.accept(CypherAdapterStream.java:69)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter$ResultHandler.onRecords(BoltMessageRouter.java:131)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.lambda$pullAll$0(BoltStateMachine.java:451)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:211)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:450)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:233)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$6(BoltMessageRouter.java:99)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:136)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:123)
	at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:94)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.tomcat.util.net.SocketProperties.getTxBufSize(SocketProperties.java:300)
	at org.apache.tomcat.util.net.NioEndpoint.getWriteBufSize(NioEndpoint.java:504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.getAttribute(BaseModelMBean.java:189)
	... 38 more
2016-12-24 16:29:19.756+0000 DEBUG [io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder] Encoding WebSocket Frame opCode=2 length=3795
```

reproduction is on the standard POC at

github example project for wrapped embedded DB
https://github.com/obrienlabs/nbi-neo4j-embedded-aws-war

endpoints
http://neo4j.ca-central-1.elasticbeanstalk.com/FrontController?action=graph 
(bolt enabled) http browser - user:neo4j pass:password 
http://neo4j.ca-central-1.elasticbeanstalk.com:7575/browser

some more config state
```
24-Dec-2016 16:13:59.283 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.36
24-Dec-2016 16:13:59.289 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 12 2016 18:14:42 UTC
24-Dec-2016 16:13:59.289 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.36.0
24-Dec-2016 16:13:59.289 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
24-Dec-2016 16:13:59.290 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.23-31.54.amzn1.x86_64
24-Dec-2016 16:13:59.290 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
24-Dec-2016 16:13:59.290 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre
24-Dec-2016 16:13:59.291 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_101-b13
```

**Comment by obriensystems** [comment] 2016-12-28 15:19
Reproduction
sorry that test page should have a call to start the db.

The spring bean that injects the graphdatabase starts on the first crud operation. 
Exercise the db by writing a node via an action=graph call on the FrontController servlet (very basic ui) - to populate it (should not affect the exception though - as it is the websocket channel)

http://localhost:8080/nbi-neo4j-embedded-aws-war.web-0.0.11-SNAPSHOT/FrontController?action=graph

then connect to the browser to cause the exception (non-fatal)

/michael

http://localhost:7575

The exception should be periodic about every 10 sec on the javascript websocket heartbeat

**Comment by obriensystems** [comment] 2016-12-29 16:46
I'll also verify Tomcat's 8.5 support of Websocket - as it may be their implementation in 8.0 (which changed twice)

**Comment by maxsumrall** [comment] 2017-01-20 10:24
Hello obriensystems,

Thanks for providing details to reproduce the issue. This is indeed a very strange issue that we're looking at. I see you also concurrently opened an internal support ticket. Since this issue seems to be very specific to your application, I'll close this issue and we can continue the discussion on zendesk.

**Closed as completed by maxsumrall** 2017-01-20 10:24 UTC
Labels: bug, operability

**Comment by obriensystems** [comment] 2017-01-20 16:09
Sounds good - I will continue to provide reproduction code here.
The use case is all customers that need Neo browser 7474 access to an embedded Neo4j 3.x server.
