### ISSUE TITLE
Cypher query error - unknown function ID(n)

### ISSUE THREAD

**Issue by sezerdulger** [neo4j/neo4j#7027] opened 2016-04-25 18:31 UTC
I have a query works on neo4j server that is in another machine but does not work in my machine

Unknown function 'ID' (line 1, column 87 (offset: 86)) "UNWIND {rows} as row CREATE (n:`User`) SET n=row.props RETURN row.nodeRef as nodeRef, ID(n) as nodeId"

**Comment by sezerdulger** [comment] 2016-04-25 19:38
id(n) working

**Comment by Mats-SX** [comment] 2016-06-16 09:02
Hello @sezerdulger and thanks for reporting this.

Functions in Cypher should all be case insensitive, meaning that any case combination of `id()` should work (`id()`, `iD()`, `Id()`, and `ID()`). I am unable to reproduce this problem on the latest milestone `3.1.0-M03`. Which version of Neo4j were you using when you encountered this issue?

**Comment by nmervaillie** [comment] 2017-03-16 13:58
Maybe this can help : http://stackoverflow.com/questions/42831063/neo4j-ogm-org-neo4j-ogm-exception-cypherexception-unknown-function-id?noredirect=1#comment72779883_42831063

**Comment by Lojjs** [comment] 2017-10-04 12:23
@sezerdulger I know this is a very late replay, we are sorry about that. In order to help you we would like to know which Neo4j version you were running and if possible also the exact query that you ran. As far as we know this is not an issue in newer releases.
Best regards the Cypher team through Louise

**Comment by Lojjs** [comment] 2017-10-20 13:31
Since we have asked for more information but haven’t received any reply, I will close this issue for now. Feel free to reopen it or create a new one if you still have troubles. 
Best regards Louise, Neo4j Cypher Team

**Closed as completed by Lojjs** 2017-10-20 13:31 UTC
Labels: cypher, question, team-cypher
