### ISSUE TITLE
possible bug: broken indexing?

### ISSUE THREAD

**Issue by chiffa** [neo4j/neo4j#6342] opened 2016-02-02 16:56 UTC
I think I have neo4j index failing to properly to match the key:value pair:

![image](https://cloud.githubusercontent.com/assets/1384395/12756855/93b75a88-c9a3-11e5-8a1c-180bb764116c.png)

I only got this error on a substantial amount of data. For the reasons related to a separate issue (#5785), I can only use neo4j 1.9.6.
Does anyone know where this error might come and how it can be mediated?

**Comment by chrisvest** [comment] 2017-11-13 11:28
Hi @chiffa, sorry for the late reply. It is not clear to me from the picture, what exactly is wrong. Can you explain a bit more what we're looking at? Did you see an exception or a stack trace somewhere?

**Comment by chiffa** [comment] 2017-11-13 15:13
When I was using the built-in administration panel and looking for a specific type of nodes through an index (the command), a lot of nodes with other types were in the return results (`element_type` column). 

Best,

Andrei

**Comment by chrisvest** [comment] 2017-11-15 15:50
I wasn't able to reproduce the problem in a 1.9.9 installation. The image above says that only 1 row was returned, even though it is clearly displaying more than one row. If this is still relevant I would suggest trying to query through the console, directly to the REST API, to verify that the index only returns one row. If that's the case, then it must be the webadmin that's playing tricks, which is annoying but at least doesn't break anything else that integrates via the REST or embedded APIs.

So if it looks like the problem is with the webadmin, then we can close this because the console should do as a work-around, and we don't have the webadmin anymore in supported versions. If it is _not_ just the webadmin playing tricks, then we'll have to try and recreate the issue in a newer version, and see where that leads us.

**Closed as completed** 2018-02-21 16:31 UTC
Labels: bug, 1.9, team-kernel
