### ISSUE TITLE
Unique constraint not getting respected

### ISSUE THREAD

**Issue by lazywizar** [neo4j/neo4j#5528] opened 2015-10-03 23:52 UTC
I have created a neo4j DB locally and assigned some indices and unique constraint.
Here is the :schema
Indexes
  ON :Actor(social_id) ONLINE (for uniqueness constraint) 
  ON :Category(name)   ONLINE (for uniqueness constraint) 
Constraints
  ON (actor:Actor) ASSERT actor.social_id IS UNIQUE
  ON (category:Category) ASSERT category.name IS UNIQUE
Additionally I do a createIfNotFound() in my java code, where I first do a find and then create if not found.

Inspite of these two checks I still see multiple nodes of Label category and same name existing in the DB.

 MATCH (n:Category) WHERE n.name='garden' RETURN n
name    garden
name    garden
name    garden
name    garden
Returned 4 rows in 49 ms.

After a lot of debugging and restarting the server, I see a different error for another node which should be unique.

MATCH (n:Category) where n.name='garden' RETURN n;

More than one item in org.neo4j.helpers.collection.IteratorUtil$12@20c98f24, first:2, second:450

Am i going wrong somewhere conceptually? Please help.

**Comment by jexp** [comment] 2015-10-04 05:18
How did you create the nodes in the first place?
Did you create the constraints before/after ?
Which Neo4j version do you use?

Would you be able to send us the db? To michael at neo4j.com

**Comment by lazywizar** [comment] 2015-10-04 14:44
- I created the nodes using Java API. 

```
        public Node createNodeIfNotExists(GraphNode graphNode) {
        Node node = null;
        Transaction tx = graphDb.beginTx();
        try {
            node = findNode(graphNode);

            if (node == null) {
                node = graphDb.createNode(graphNode.getLabel());
                for (String propertyName : graphNode.getProperties().keySet()) {
                    if (graphNode.getProperties().get(propertyName) != null) {
                        node.setProperty(propertyName, graphNode
                                .getProperties().get(propertyName));
                    }
                }
            }
            tx.success();
        } catch (Exception e) {
            logger.error("Exception while finding the node.. ", e);
        } finally {
            tx.close();
        }
        return node;
    }
```
-  Yes I created the index and unique constraint right in the beginning. 
- neo4j version is : neo4j-community-2.2.5
- I have cleared all the data in the DB and recreated it. This time, I did not see the duplicated being created. However there was one note which got multiple instance. I wrote a small code to delete it. 
  Thats when I noticed the delay, that might be the root cause.

When I deleted the node, next run of findAll still returned multiple nodes, but accessing the second node threw error. After 5 minutes findAll returned just 1 entry. So my theory is that I am calling createNodeIfNotExists() too fast, hence at times it thinks that there is no element with the given property name and Label. But once the flush/sync happens it messes up the DB. 

Does that sound like something which is possible? Can you recommend the best practice/solution for it.

Thanks a lot for looking into it!

**Comment by jexp** [comment] 2015-10-04 15:59
Hi, this should not be possible at all. Could you provide us with a full unit test which reproduces the issue, that would help us a lot in determining the root cause.

Thanks so much!

**Comment by jexp** [comment] 2015-10-04 20:56
And this is the normal, embedded API?

**Comment by lazywizar** [comment] 2015-10-05 00:25
Sure will do. Its not constant repro, but let me try to have all same variables and come back.

Thanks

**Comment by lazywizar** [comment] 2015-10-05 00:26
Ya its the normal embedded API. I am using maven dependency for neo4j.

**Comment by thobe** [comment] 2015-10-07 14:02
We have found (and implemented a fix for) one issue that could lead to symptoms that look very much like the ones you are describing. The steps to reproduce would be:
1. Start Neo4j and create the constraint as well as at least one node that matches the constraint.
2. Wait a while for the background thread to flush the changes to disk.
3. Kill the Neo4j JVM process.
4. Start up Neo4j again. Since the last run was a crash, recovery will take place.
5. The very first transaction is now able to violate the constraint. Subsequent transactions will not be able to do so.

@lazywizar does that sound like something that could have happened in your case?

**Comment by lazywizar** [comment] 2015-10-07 19:11
Hey  Tobias,
That just sounds like what I was doing. Multiple kills and restart of
server from console and then java code.
I am a starter and was taking my first stab at neo4j to create a prototype
and present it to my leadership.

I was starting the server from console and exploring the graph from
Browser. And then killing it to start it from the code (Java code)
I was getting error that server already started if I started at both
places. Also I was not able to find out how can I connect to existing
running server instead of starting from java code.

Thanks a lot, I will try to repro this again this weekend.
To pull in your fixes which version/branch should I pull?

Thanks
varun

On Wed, Oct 7, 2015 at 7:02 AM, Tobias Lindaaker notifications@github.com
wrote:

> We have found (and implemented a fix for) one issue that could lead to
> symptoms that look very much like the ones you are describing. The steps to
> reproduce would be:
> 1. Start Neo4j and create the constraint as well as at least one node
>    that matches the constraint.
> 2. Wait a while for the background thread to flush the changes to disk.
> 3. Kill the Neo4j JVM process.
> 4. Start up Neo4j again. Since the last run was a crash, recovery will
>    take place.
> 5. The very first transaction is now able to violate the constraint.
>    Subsequent transactions will not be able to do so.
> 
> @lazywizar https://github.com/lazywizar does that sound like something
> that could have happened in your case?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5528#issuecomment-146204389.

## 

Varun Kumar

**Comment by jexp** [comment] 2015-10-07 19:39
Hi, just FYI to connect from Java code you can use something along these lines:

http://neo4j.com/developer/java
- jdbc driver
- neo4j-ogm
- spring-data-neo4j
- http-client via http://neo4j.com/docs/stable/rest-api-transactional.html

**Comment by lazywizar** [comment] 2015-10-07 20:20
Thanks Michael. Will try it.

On Wed, Oct 7, 2015 at 12:39 PM, Michael Hunger notifications@github.com
wrote:

> Hi, just FYI to connect from Java code you can use something along these
> lines:
> 
> http://neo4j.com/developer/java
> - jdbc driver
> - neo4j-ogm
> - spring-data-neo4j
> - http-client via
>   http://neo4j.com/docs/stable/rest-api-transactional.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5528#issuecomment-146305567.

## 

Varun Kumar

**Comment by thobe** [comment] 2015-10-08 07:31
@lazywizar if you are willing to build from source, the current `HEAD` of [the 2.2 branch](https://github.com/neo4j/neo4j/tree/2.2) contains the fix, as does [the 2.3 branch](https://github.com/neo4j/neo4j/tree/2.3) branch.

**Comment by lazywizar** [comment] 2015-10-08 18:04
Will do that. Thanks!

On Thu, Oct 8, 2015 at 12:32 AM, Tobias Lindaaker notifications@github.com
wrote:

> @lazywizar https://github.com/lazywizar if you are willing to build
> from source, the current HEAD of the 2.2 branch
> https://github.com/neo4j/neo4j/tree/2.2 contains the fix, as does the
> 2.3 branch https://github.com/neo4j/neo4j/tree/2.3 branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5528#issuecomment-146443474.

## 

Varun Kumar

**Comment by thobe** [comment] 2015-10-14 20:01
@lazywizar what were the conclusions from your testing? Can I close this issue?

**Comment by lazywizar** [comment] 2015-10-14 20:27
Hey Tobias,
Sorry for I didn't get change to post here.
Yes you can close it, with the version you gave I am not able to repro the
issue using the same set up I had. So it works! thanks!

Thanks
varun

On Wed, Oct 14, 2015 at 1:01 PM, Tobias Lindaaker notifications@github.com
wrote:

> @lazywizar https://github.com/lazywizar what were the conclusions from
> your testing? Can I close this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5528#issuecomment-148179241.

## 

Varun Kumar

**Closed as completed** 2015-10-14 20:32 UTC
