### ISSUE TITLE
Indexed WHERE clause comparing properties of two nodes in MATCH clause being ignored in Query?

### ISSUE THREAD

**Issue by yourpalal** [neo4j/neo4j#8534] opened 2016-12-20 17:36 UTC
A relatively simple query is causing me some major headaches! It's easy enough to rewrite this query to get it to work, but I cannot figure out why it's returning the wrong results in the first place.

- Neo4j version: 3.0.1-enterprise (via Docker)
- Ubuntu 14.04
- cypher query via browser interface

# Steps to reproduce

Unfortunately, this doesn't actually reproduce the issue :( I have no clue why not

```sql
CREATE p=(n:Titled {matchable_title: "left"})-[:of_group]->(g:Group)<-[:of_group]-(m:Titled {matchable_title: "right"})
RETURN p;

CREATE p=(n:Titled {matchable_title: "same"})-[:of_group]->(g:Group)<-[:of_group]-(m:Titled {matchable_title: "same"})
RETURN p;

CREATE INDEX ON :Titled(matchable_title);
```

```sql
MATCH p=(n:Titled)-[:of_group]-(g)-[:of_group]-(m:Titled)
WHERE m.matchable_title = n.matchable_title
RETURN m.matchable_title, n.matchable_title, p LIMIT 25;
```

# Expected behavior

For each row of results, m.matchable_title will be the same as n.matchable_title

# Actual behavior

n.matchable_title and m.matchable_title do not match. According to PROFILE, the query starts with a NodeIndexScan to find `m`. There are multiple different values for m.matchable_title across different rows (as expected). Some of the returned nodes should be in the result set (although the row is wrong, n/m should appear in rows in the correct results) but some m/n nodes would not appear in the correct results.

Interestingly, although the query plan is not the same, the rows are returned in the same order as when the WHERE clause is removed.

It seems like n is found by an index scan, but the index values are not being checked, or something like that. If I remove the index on matchable_title, then the query starts with a NodeByLabelScan and then proceeds correctly. Adding the index back again results in incorrect rows. If I try to specify to use the matchable_title index, neo4j complains that this is not allowed.

The query can be corrected in many different ways. One example is to add  a WITH clause:

```sql
MATCH p=(n:Titled)-[:of_group]-(g)-[:of_group]-(m:Titled)
WITH p, n, m
WHERE m.matchable_title = n.matchable_title
RETURN m.matchable_title, n.matchable_title, p LIMIT 25;
```

This causes the query plan to change, starting with NodeByLabelScan, then expanding and filtering. This query produces correct results.

**Comment by yourpalal** [comment] 2016-12-20 17:39
Here are some real query results that result from this problem. (.json.txt because github wouldn't let me upload .json)

[real-incorrect-query-results.json.txt](https://github.com/neo4j/neo4j/files/664357/real-incorrect-query-results.json.txt)


indexes from `:schema ls -l HumanPhenomena::Concept` (this is the real label in the database)

```sql
Indexes
  ON :HumanPhenomena::Concept(title)                    ONLINE                             
  ON :HumanPhenomena::Concept(matchable_title)          ONLINE                             
  ON :HumanPhenomena::Concept(duplicate_check_required) ONLINE                             
  ON :HumanPhenomena::Concept(uuid)                     ONLINE (for uniqueness constraint) 
  ON :HumanPhenomena::Concept(accession_numbers)        ONLINE (for uniqueness constraint) 

Constraints
  ON (humanphenomena::concept:HumanPhenomena::Concept) ASSERT humanphenomena::concept.uuid IS UNIQUE
  ON (humanphenomena::concept:HumanPhenomena::Concept) ASSERT humanphenomena::concept.accession_numbers IS UNIQUE
```

**Comment by yourpalal** [comment] 2016-12-20 17:40
oh, also it's probably good to note that consistency checks on this database come back clean

**Comment by yourpalal** [comment] 2016-12-20 17:58
Here's a screenshot of the offending query plan ![query-plan](https://cloud.githubusercontent.com/assets/763936/21361901/0b5ab126-c6b4-11e6-8ce0-c271d0159c53.png)

**Comment by jexp** [comment] 2016-12-21 07:14
Can you share your actual query?

**Comment by jexp** [comment] 2016-12-21 07:21
@yourpalal It seems to be fixed in later versions of Neo4j, could you upgrade to 3.0.8 ? And check.

**Comment by jexp** [comment] 2016-12-21 07:22
Btw. thanks a lot for the very detailed issue reporting.

**Comment by jexp** [comment] 2016-12-21 07:23
To reproduce it with your sample, you have to create another 1000 (or so nodes) to trigger the index usage, e.g. with `unwind range(1,1000) as id CREATE p=(n:Titled {matchable_title: "left"+id});`

**Comment by yourpalal** [comment] 2016-12-21 16:02
Thanks, @jexp, it looks like you don't need it any more, but the query that matches that json was

```sql
MATCH p=(n:`HumanPhenomena::Concept`)-[:of_group]-(g)-[:of_group]-(m:`HumanPhenomena::Concept`)
WHERE m.matchable_title = n.matchable_title
RETURN m.matchable_title, n.matchable_title, p LIMIT 25;
```

I'll upgrade my local instance and try it out. For now I've added a workaround in our app, which adds in the `WITH` statement. Assuming it works out in 3.0.8, then I expect we will be able to upgrade our production database to 3.0.8 as well.

**Closed as completed** 2017-10-04 12:26 UTC
Labels: bug, cypher, 3.0
