### ISSUE TITLE
Change in response from the transactional cypher endpoint in 2.2.5 when a transaction could not be committed

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#5262] opened 2015-09-01 08:32 UTC
Assume the following cypher statement:

```
{"statements":[{"statement":"CREATE (_0:`User`:`Person`{_0_props}) RETURN id(_0) AS _0","parameters":{"_0_props":{"name":"Michal"}},"resultDataContents":["row"],"includeStats":false}]}
```

posted to http://localhost:7474/db/data/transaction/1

If a transaction cannot be committed (assume a transaction event handler throws an exception), in versions prior to 2.2.5, the response contained an empty `results`.

```
{
    "results": [],
    "errors": [
        {
            "code": "Neo.DatabaseError.Statement.ExecutionFailure",
            "message": "Could not create token",
            "stackTrace": "org.neo4j.graphdb.TransactionFailureException: Could not create token\n\tat org.neo4j.kernel.impl.core.TokenHolder.getOrCreateId(TokenHolder.java:121)\n\tat
...
       }
    ]
}
```

In 2.2.5, the response includes the id of the node that was supposed to be created but was not:

```
{
    "results": [
        {
            "columns": [
                "_0"
            ],
            "data": [
                {
                    "row": [
                        0
                    ]
                }
            ]
        }
    ],
    "errors": [
        {
            "code": "Neo.DatabaseError.Transaction.CouldNotCommit",
            "message": "org.neo4j.kernel.api.exceptions.TransactionFailureException: ",
            "stackTrace": "java.lang.RuntimeException: org.neo4j.kernel.api.exceptions.TransactionFailureException: \n\tat
...
        }
     ]
}
```

This is quite unexpected- no node with ID 0 exists, yet it's returned!

**Comment by jexp** [comment] 2015-09-01 08:44
The response is written in a streaming fashion, i.e. when the error occurs the first part of the response is already on the wire.

When you get an error in a response from that endpoint, then you can safely discard all transactional state that you expected to happen as part of this

**Comment by davidegrohmann** [comment] 2015-09-14 09:32
Hi @luanne,

I have been trying to reproduce this issue with the following test (with a simplified query):

```
@Test
    public void shouldNotStreamResultsIfTransactionFails() throws Exception
    {
        graphdb().registerTransactionEventHandler( new TransactionEventHandler<Object>()
        {
            @Override
            public Object beforeCommit( TransactionData data ) throws Exception
            {
                throw new RuntimeException( "boom!" );
            }

            @Override
            public void afterCommit( TransactionData data, Object state )
            {
            }

            @Override
            public void afterRollback( TransactionData data, Object state )
            {

            }
        } );

        // execute
        Response response = http.POST( "/db/data/transaction/commit", quotedJson(
                "{'statements':[{" +
                "'statement':'CREATE (n) RETURN id(n) AS n'," +
                "'resultDataContents':['row']," +
                "'includeStats':false" +
                "}]}" ) );

        System.out.println( response );

        assertEquals( 200, response.status() );
        assertTrue( response.get( "errors" ).size() > 0 );
        assertTrue( response.get( "results" ).size() == 0 );
    }
```

but in all 2.2.x versions I see the same response, i.e., the second one listed in your report.

Can you please verify that the test above matches your use case? If not can you please add more details on how reproduce?

Thanks in advance.

**Comment by ikwattro** [comment] 2015-09-14 21:25
Hi @davidegrohmann 

Thanks for your effort to reproduce. @luanne is currently offline for a couple of time. 

Here is a simple debugged http request using `httpie` and the provided query in the initial comment : 

```
cw@graphaware-2 ~/d/g/bugs> http POST 'http://localhost:8474/db/data/transaction' < cypher.json -v
POST /db/data/transaction HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 185
Content-Type: application/json
Host: localhost:8474
User-Agent: HTTPie/0.9.2

{
    "statements": [
        {
            "includeStats": false,
            "parameters": {
                "_0_props": {
                    "name": "Michal"
                }
            },
            "resultDataContents": [
                "row"
            ],
            "statement": "CREATE (_0:`User`:`Person`{_0_props}) RETURN id(_0) AS _0"
        }
    ]
}

HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Content-Length: 193
Content-Type: application/json
Date: Mon, 14 Sep 2015 21:23:45 GMT
Location: http://localhost:8474/db/data/transaction/2026
Server: Jetty(9.2.4.v20141103)

{
    "commit": "http://localhost:8474/db/data/transaction/2026/commit",
    "errors": [],
    "results": [
        {
            "columns": [
                "_0"
            ],
            "data": [
                {
                    "row": [
                        9359
                    ]
                }
            ]
        }
    ],
    "transaction": {
        "expires": "Mon, 14 Sep 2015 21:24:45 +0000"
    }
}
```

**Comment by ikwattro** [comment] 2015-09-14 21:28
Hi @davidegrohmann Thanks for your report for trying to reproduce the issue.

@luanne is currently online for a couple of days. I tried with a debugged http response using `httpie` and the results are the same than yours : 

```
cw@graphaware-2 ~/d/g/bugs> http POST 'http://localhost:8474/db/data/transaction' < cypher.json -v
POST /db/data/transaction HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 185
Content-Type: application/json
Host: localhost:8474
User-Agent: HTTPie/0.9.2

{
    "statements": [
        {
            "includeStats": false,
            "parameters": {
                "_0_props": {
                    "name": "Michal"
                }
            },
            "resultDataContents": [
                "row"
            ],
            "statement": "CREATE (_0:`User`:`Person`{_0_props}) RETURN id(_0) AS _0"
        }
    ]
}

HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Content-Length: 193
Content-Type: application/json
Date: Mon, 14 Sep 2015 21:23:45 GMT
Location: http://localhost:8474/db/data/transaction/2026
Server: Jetty(9.2.4.v20141103)

{
    "commit": "http://localhost:8474/db/data/transaction/2026/commit",
    "errors": [],
    "results": [
        {
            "columns": [
                "_0"
            ],
            "data": [
                {
                    "row": [
                        9359
                    ]
                }
            ]
        }
    ],
    "transaction": {
        "expires": "Mon, 14 Sep 2015 21:24:45 +0000"
    }
}
```

I'll ask @vince-bickers to check the behavior on the Java application level of sdn4/ogm

**Comment by bachmanm** [comment] 2015-09-14 21:37
@davidegrohmann try using a label on the node you're creating. I suspect it _might_ be a change in the way transaction handlers are called....

**Comment by jexp** [comment] 2015-09-14 22:42
Esp. if it is a new label that didn't exist before.

**Comment by tinwelint** [comment] 2015-09-15 13:17
Transaction event handlers have been changed to only be invoked on write transactions where there are any changes made that is actually accessible in `TransactionData`, so for example handlers aren't invoked for token transactions (e.g. the mini-transactions that create property keys, labels and relationship types) anymore.

**Comment by davidegrohmann** [comment] 2015-09-16 08:36
I can reproduce the problem, the behavior change happened between 2.2.3 and 2.2.4 and the reason is exactly what @tinwelint explained above.

**Comment by davidegrohmann** [comment] 2015-09-16 11:46
@luanne @bachmanm As @tinwelint explained above the latest behavior is correct and expected. I am going to close this issue. Please feel free to reopen it if you think this is still an issue.

**Closed as completed by davidegrohmann** 2015-09-16 11:46 UTC
