### ISSUE TITLE
Transaction Isolation Problems in Neo4j 2.1.3

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#2677] opened 2014-07-14 16:44 UTC
We're experiencing transactions seeing other transactions' uncommitted data. Please refer to the test below. Some threads are creating a linked list with a single root (head), they are doing just fine. The threads reading the data sometimes encounter a node without the "sequence" property, which is only possible if they're seeing a node just being created in another transaction that hasn't been committed yet.

    /**
     * Created by Luanne (GraphAware) on 14/07/14.
     */
    public class TestLinkedList {

    Node root; //root of the linked list

    private GraphDatabaseService database;

    private AtomicInteger sequence = new AtomicInteger(0);

    @Before
    public void setUp() {
        database = new TestGraphDatabaseFactory().newImpermanentDatabase();
        try (Transaction tx = database.beginTx()) {
            root = database.createNode(DynamicLabel.label("Head"));
            tx.success();
        }
    }

    @After
    public void tearDown() {
        database.shutdown();
    }

    @Test
    public void verifyConcurrentInsertsAndFetchesFromTheLinkedList() throws InterruptedException {
        ExecutorService createExecutor = Executors.newFixedThreadPool(50);
        ExecutorService getExecutor = Executors.newFixedThreadPool(50);
        int noRequests = 100; //change this to 1000 if you don't see the issue
        final AtomicBoolean success = new AtomicBoolean(true);

        for (int i = 0; i < noRequests; i++) {
            createExecutor.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        insert();
                    } catch (Exception e) {
                        success.set(false);
                        e.printStackTrace();
                    }
                }
            });
            createExecutor.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        System.out.println("get(5) = " + get(5));
                    } catch (Exception e) {
                        success.set(false);
                        e.printStackTrace();
                    }
                }
            });
        }

        long start = System.currentTimeMillis();

        createExecutor.shutdown();
        getExecutor.shutdown();
        createExecutor.awaitTermination(30, TimeUnit.SECONDS);
        getExecutor.awaitTermination(30, TimeUnit.SECONDS);

        System.out.println("Took " + (System.currentTimeMillis() - start) + " ms");

        assertTrue("At least one insert or read failed", success.get());
    }

    private void insert() {
        try (Transaction tx = database.beginTx()) {
            //Create the new node to be inserted at the head of the list
            Node itemNode = database.createNode(DynamicLabel.label("Item"));
            itemNode.setProperty("sequence", sequence.incrementAndGet());
            itemNode.setProperty("timestamp", new Date().getTime());

            //Acquire a lock on the head of the list
            tx.acquireWriteLock(root);

            Relationship firstItemRel = root.getSingleRelationship(DynamicRelationshipType.withName("NEXT"), Direction.OUTGOING);
            if (firstItemRel != null) {
                //Get the first item in the list
                Node firstItem = firstItemRel.getEndNode();
                //Create a relationship from the new item to the old first item
                itemNode.createRelationshipTo(firstItem, DynamicRelationshipType.withName("NEXT"));
                //Delete the relationship from the head to the old first item
                firstItemRel.delete();
            }
            //Create a relationship from the head to the new first item
            root.createRelationshipTo(itemNode, DynamicRelationshipType.withName("NEXT"));

            tx.success();
            System.out.println("Inserted");
        }
    }

    private List<Integer> get(int limit) {
        int count = 0;
        List<Integer> list = new ArrayList<>();

        try (Transaction tx = database.beginTx()) {
            // tx.acquireWriteLock(root);   //uncommenting this fixes the problem, but that's a bit harsh since we're not modifying the db at all, read lock isn't good enough

            Relationship nextRel = root.getSingleRelationship(DynamicRelationshipType.withName("NEXT"), Direction.OUTGOING);

            while (count < limit && nextRel != null) {
                Node itemNode = nextRel.getEndNode();
                list.add((Integer) itemNode.getProperty("sequence"));   //sometimes fails here with org.neo4j.graphdb.NotFoundException: NODE[XXX] has no property with propertyKey="sequence"
                count++;

                nextRel = itemNode.getSingleRelationship(DynamicRelationshipType.withName("NEXT"), Direction.OUTGOING);
            }
            tx.success();
            System.out.println("Fetched");
        }

        return list;
    }

}

**Comment by fdietze** [comment] 2015-02-10 18:29
My queries can still see data from uncommitted transactions in Neo4j 2.1.7.
This is very easy to reproduce:

https://gist.github.com/fdietze/559c9f6fc4a9a95152cd [bash]
https://gist.github.com/fdietze/70d11beb69d723b13e12 [ruby]

**Comment by cdshines** [comment] 2015-02-10 20:06
@bachmanm, I realize it's pretty late to say this, but anyway, since this thread just popped up in a tracker, I couldn't help but notice that your test declares a couple of pools but actually uses just one (even for reading), so the issue here might be that since transactions are bound to threads, it's a normal behaviour for them to see into each other in this case? I mean, you have 100 (or 1000) requests and 50 threads, so some of them are definitely bound to collide.
Again, I didn't run the test myself and I might be completely wrong, but this strange trifle is bothering me a little.

**Comment by davidrapin** [comment] 2015-03-27 09:13
Same here. We had this bug with the following sequence of requests (Neo4j 2.1.7):
 1. cypher: add a new node with no label 
 2. cypher: add a label to the node
 3. cypher: get the node (by id) : the label is not added (Neo4j returns a cached from before `2`)

**Comment by jakewins** [comment] 2015-12-06 04:24
This cache poisoning issue has been resolved in 2.2, and the cache has been removed in its entirety in 2.3. Sorry this took so long.

**Closed by jakewins** 2015-12-06 04:24 UTC

**Comment by bachmanm** [comment] 2015-12-06 12:49
Thanks guys, part of the problem fixed. There seems to be a (use-case-wise) related issue though that seems to have been introduced: https://github.com/neo4j/neo4j/issues/6036
