### ISSUE TITLE
Multiline fields with a line starting with an escaped quote break CSV importer

### ISSUE THREAD

**Issue by timmytofu** [neo4j/neo4j#4439] opened 2015-04-15 22:56 UTC
```
LOAD CSV WITH HEADERS FROM
  "https://gist.githubusercontent.com/timmytofu/ba39ae1bf3669bd36ba3/raw/3be7510f487c50b64259bb3e0c1e68ace9f6af69/bad-neo-import.csv"
  AS csv
CREATE (:Foo {fid: toInt(csv.id), thetext: csv.thetext});
```

Strangely, if I add 0xD (the carriage return Windows puts before newlines) to the line above that starting with "" it works:

```
LOAD CSV WITH HEADERS FROM
  "https://s3.amazonaws.com/vfiles-sandbox/good-neo.csv"
  AS csv
CREATE (:Foo {fid: toInt(csv.id), thetext: csv.thetext});
```

(I had to put that on S3, gist scrubs the carriage return)

This happens on 2.2.1, but not 2.2.0. Tested on Ubuntu 14.04.

**Comment by cleishm** [comment] 2015-04-15 23:20
Duplicate of #4434

**Closed as completed by cleishm** 2015-04-15 23:20 UTC

**Comment by ernestoe** [comment] 2015-07-24 07:57
Both this #4434 and #4439 are failing again.
