### ISSUE TITLE
Cypher parser doesn't accept escaped backticks

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#7175] opened 2016-05-19 13:20 UTC
Neo4j version: any
OS: any

Steps to reproduce:
1.From e.g. Java API:

```
Node n0 = db().createNode();
Node n1 = db().createNode();
n0.createRelationshipTo(n1, RelationshipType.withName("`RelType`"));  // note the _`_
```

2.Open the browser, open UI, open entity explorer. In the relationship list you'll see 

```
`RelType`  // note the explicit '`' 
```

3.The following will be the output resulting from clicking on the `RelType` button:

```
$MATCH p=()-[r:``RelType``]->() RETURN p LIMIT 25          // one ` is a part of rel type and another ` is inserted by the browser, unescaped
Errors
Code
 Invalid input 'R': expected '`', whitespace, '|', a length specification, a property map or ']' (line 1, column 17 (offset: 16))
"MATCH p=()-[r:``RelType``]->() RETURN p LIMIT 25"
                 ^
```

Expected: either of:
- don't allow '`' in relationship types, labels, etc.
- escape '`' in the browser and accept them in parser

**Comment by oharlem** [comment] 2016-05-19 13:53
@tkroman 
Hi, my workaround (Go):
`
        Statement: `
        MERGE (:Event:` + "`" + e.Type + "`" + ` {title:{title}, eventId:{eventId}, created:{created}, start:{start}, type:{type}, end:{end}, urlPath:{urlPath}, userId:{userId}})
        `,
`

Note the "`" around e.Type above.

**Comment by tkroman** [comment] 2016-05-19 14:22
@mpmlj, this bug report is about the inconsistency in the handling of the '`' symbol by the browser module and the native API rather than request for workarounds. Good to know they exist though.

**Comment by rishabhjain08** [comment] 2016-05-29 00:19
Cyper parser accepts backticks. Backticks have to be escaped using another backtick so your query will become
MATCH p=()-[r:```RelType```]->() RETURN p LIMIT 25
This query will work well on both the shell and the browser.
Looks like Java driver automatically takes care of escaping backticks. 
Also, it seems like the issue is with the browser not escaping backticks when constructing a query when a user clicks on a relationship name with backticks in it.  
The issue should be renamed to something like - "Browser does not escape backticks when automatically creating queries."

Rule - Any string which cannot be represented as a java identifier (http://www.tutorialspoint.com/java/lang/character_isjavaidentifierstart.htm) has to be escaped by putting the string inside backticks. Additionaly if the string contains backticks, backticks have to be escaped by putting a backtick before each occurent of backtick. So for eg. rel`10 will become `rel``10`

**Comment by rishabhjain08** [comment] 2016-05-29 00:32
On a somewhat related note -
The browser cannot handle " in the relationship type. Try creating a relationship with " in it. Notice that browser wont be able to load relationships under "database information" reason being that the response from the server doesnt escape " in relation types before sending them.

**Comment by rishabhjain08** [comment] 2016-05-29 02:49
@spacecowboy I have created an issue for this in neo4j-browser https://github.com/neo4j/neo4j-browser/issues/174
I think this one can be closed.

**Comment by spacecowboy** [comment] 2016-05-30 07:51
Agree. Closing since the issue has been opened against the browser repo.

**Closed as completed by spacecowboy** 2016-05-30 07:51 UTC
Labels: bug, browser
