### ISSUE TITLE
Unable to restart replica

### ISSUE THREAD

**Issue by mahaveer123** [neo4j/neo4j#10657] opened 2017-12-19 11:28 UTC
Hi , 
Read replica became unresponsive during write, because of disk full issue.
I cleared some disk and restarted. but it was unable to start was throwing exception. had to delete data and restart.

```
2017-12-14 08:11:18.872+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1c807b1d' was successfully initialized, but failed to start.
 Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10". Starting Neo4j failed: Component 'org.neo4j.server.database.Lifecy
cleManagingDatabase@1c807b1d' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry vers
ion V3_0_10".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1c807b1d' was successfully initialized, but failed to start. Please see the a
ttached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1c807b1d' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, read_replica_01_neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
        at org.neo4j.causalclustering.readreplica.CommercialReadReplicaGraphDatabase.<init>(CommercialReadReplicaGraphDatabase.java:35)
        at org.neo4j.causalclustering.readreplica.CommercialReadReplicaGraphDatabase.<init>(CommercialReadReplicaGraphDatabase.java:26)
        at org.neo4j.server.enterprise.CommercialNeoServer.lambda$static$1(CommercialNeoServer.java:34)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.causalclustering.readreplica.ReadReplicaStartupProcess@22680f52' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
        ... 10 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@77b21474' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10".
        at org.neo4j.causalclustering.readreplica.ReadReplicaStartupProcess.start(ReadReplicaStartupProcess.java:153)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 12 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@77b21474' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
        at org.neo4j.causalclustering.catchup.storecopy.LocalDatabase.start(LocalDatabase.java:104)
        at org.neo4j.causalclustering.readreplica.ReadReplicaStartupProcess.start(ReadReplicaStartupProcess.java:148)
        ... 13 more
Caused by: java.lang.NegativeArraySizeException: null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readLongs(PhysicalLogCommandReaderV3_0_2.java:626)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyBlock(PhysicalLogCommandReaderV3_0_2.java:601)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyRecord(PhysicalLogCommandReaderV3_0_2.java:566)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.visitPropertyCommand(PhysicalLogCommandReaderV3_0_2.java:183)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.read(PhysicalLogCommandReaderV3_0_2.java:76)
        at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:49)



Caused by: java.lang.NegativeArraySizeException: null. At position LogPosition{logVersion=1189, byteOffset=79802344} and entry version V3_0_10
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readLongs(PhysicalLogCommandReaderV3_0_2.java:626)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyBlock(PhysicalLogCommandReaderV3_0_2.java:601)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyRecord(PhysicalLogCommandReaderV3_0_2.java:566)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.visitPropertyCommand(PhysicalLogCommandReaderV3_0_2.java:183)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.read(PhysicalLogCommandReaderV3_0_2.java:76)
        at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:49)
        at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:34)
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_3$2.parse(LogEntryParsersV2_3.java:70)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:82)
        at org.neo4j.kernel.impl.transaction.log.LogEntryCursor.next(LogEntryCursor.java:54)
        at org.neo4j.kernel.impl.transaction.log.LogTailScanner.update(LogTailScanner.java:88)
        at org.neo4j.kernel.impl.transaction.log.LogTailScanner.getTailInformation(LogTailScanner.java:240)
        at org.neo4j.kernel.impl.transaction.log.LogVersionUpgradeChecker.check(LogVersionUpgradeChecker.java:47)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:431)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 17 more
2017-12-14 08:11:18.873+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by klaren** [comment] 2018-03-12 12:40
Hi and thanks for reporting!

This is a known issue, where running out of disk space might cause the transaction log to be corrupt. It has already been addressed by #9956 and will make the database more resilient when running out of space. So this should already be fixed 3.4-alpha releases, what version are you running?

**Comment by burqen** [comment] 2018-06-25 09:12
Problem has been addressed. Closing issue. Feel free to open it again if you disagree.

**Closed as completed by burqen** 2018-06-25 09:12 UTC
Labels: team-kernel

**Comment by sonali1192** [comment] 2018-10-26 12:46
Hello All ,

I have installed latest version of neo4j but while starting I am getting following error in log file 


2018-10-26 12:28:56.956+0000 WARN  WARNING! Deprecated configuration options used. See manual for details
2018-10-26 12:28:56.959+0000 WARN  dbms.allow_format_migration has been replaced with dbms.allow_upgrade.
2018-10-26 12:28:56.983+0000 INFO  ======== Neo4j 3.4.9 ========
2018-10-26 12:28:57.026+0000 INFO  Starting...
2018-10-26 12:29:00.642+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@79c5636f' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@79c5636f' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@79c5636f' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@79c5636f' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@341a8659' was successfully initialized, but failed to start. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:100)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
        ... 9 more
Caused by: java.lang.RuntimeException: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@56bc3fac' failed to initialize. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:531)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 14 more

		Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery@56bc3fac' failed to initialize. Please see the attached cause exception "null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:515)
        ... 15 more
Caused by: java.lang.RuntimeException: Error reading transaction logs, recovery not possible. To force the database to start anyway, you can specify 'unsupported.dbms.tx_log.fail_on_corrupted_log_files=false'. This will try to recover as much as possible and then truncate the corrupt part of the transaction log. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead.
        at org.neo4j.kernel.recovery.Recovery.throwUnableToCleanRecover(Recovery.java:155)
        at org.neo4j.kernel.recovery.LogTailScanner.findLogTail(LogTailScanner.java:147)
        at org.neo4j.kernel.recovery.LogTailScanner.getTailInformation(LogTailScanner.java:260)
        at org.neo4j.kernel.recovery.RecoveryStartInformationProvider.get(RecoveryStartInformationProvider.java:89)
        at org.neo4j.kernel.recovery.DefaultRecoveryService.getRecoveryStartInformation(DefaultRecoveryService.java:61)
        at org.neo4j.kernel.recovery.Recovery.init(Recovery.java:68)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
        ... 18 more
Caused by: java.io.IOException: java.lang.NegativeArraySizeException: null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:115)
        at org.neo4j.kernel.impl.transaction.log.LogEntryCursor.next(LogEntryCursor.java:54)
        at org.neo4j.kernel.recovery.LogTailScanner.findLogTail(LogTailScanner.java:99)
        ... 23 more
Caused by: java.lang.NegativeArraySizeException: null. At position LogPosition{logVersion=27, byteOffset=94199720} and entry version V3_0_10
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readDynamicRecord(PhysicalLogCommandReaderV3_0_2.java:499)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readDynamicRecords(PhysicalLogCommandReaderV3_0_2.java:513)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyBlock(PhysicalLogCommandReaderV3_0_2.java:617)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.readPropertyRecord(PhysicalLogCommandReaderV3_0_2.java:566)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.visitPropertyCommand(PhysicalLogCommandReaderV3_0_2.java:189)
        at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV3_0_2.read(PhysicalLogCommandReaderV3_0_2.java:76)
        at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:49)
        at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:34)
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_3$2.parse(LogEntryParsersV2_3.java:70)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:82)
        ... 25 more
2018-10-26 12:29:00.644+0000 INFO  Neo4j Server shutdown initiated by request



please help me with that. I am unable to proceed further.

Thanks in advance.
