### ISSUE TITLE
index not working when combine multiply fields using and operator

### ISSUE THREAD

**Issue by forestlcoder** [neo4j/neo4j#13269] opened 2023-08-02 03:41 UTC
Neo4J:5.10.0

Index create sql:
CREATE INDEX composite_IdxCompanyFilter FOR (n:`企业`) ON(n.city, n.province, n.district);

Query Sql:
explain MATCH (n:`企业`) where n.city = '重庆市' and n.province = '重庆市' and n.district = '万州区' RETURN n LIMIT 25

Expect:
all index filed can hit, but only city field is hitted
![image](https://github.com/neo4j/neo4j/assets/26137810/f672ae8e-c8e1-4b23-b236-395372f2266e)

**Comment by blouerat** [comment] 2023-08-02 17:14
Hi @forestlcoder,

Would it be possible for you to tell us a bit more about the data in your database?
Could you perhaps give us the output of `CALL db.stats.retrieve("GRAPH COUNTS")`, that would give us the stats used by the planner?

Thank you for your report and for the additional info.

**Comment by forestlcoder** [comment] 2023-08-03 02:27
{
  "relationships": [
    {
      "count": 164331018
    },
    {
      "relationshipType": "拥有",
      "count": 12394919
    },
    {
      "relationshipType": "拥有",
      "count": 1887925,
      "endLabel": "专利"
    },
    {
      "relationshipType": "拥有",
      "count": 1498985,
      "endLabel": "资质证书"
    },
    {
      "relationshipType": "拥有",
      "startLabel": "企业",
      "count": 12394919
    },
    {
      "relationshipType": "拥有",
      "count": 3577284,
      "endLabel": "专利附表"
    },
    {
      "relationshipType": "拥有",
      "count": 682550,
      "endLabel": "软件著作"
    },
    {
      "relationshipType": "拥有",
      "count": 4163728,
      "endLabel": "商标"
    },
    {
      "relationshipType": "拥有",
      "count": 584447,
      "endLabel": "作品著作"
    },
    {
      "relationshipType": "拥有",
      "startLabel": "产品企业",
      "count": 1355933
    },
    {
      "relationshipType": "法人",
      "count": 40464286
    },
    {
      "relationshipType": "法人",
      "count": 10317493,
      "endLabel": "企业"
    },
    {
      "relationshipType": "法人",
      "startLabel": "个人",
      "count": 40464286
    },
    {
      "relationshipType": "法人",
      "count": 383243,
      "endLabel": "产品企业"
    },
    {
      "relationshipType": "法人",
      "count": 30146793,
      "endLabel": "个体"
    },
    {
      "relationshipType": "分类",
      "count": 299
    },
    {
      "relationshipType": "分类",
      "startLabel": "产品",
      "count": 299
    },
    {
      "relationshipType": "分类",
      "count": 299,
      "endLabel": "产品"
    },
    {
      "relationshipType": "上游",
      "count": 89
    },
    {
      "relationshipType": "上游",
      "startLabel": "产品",
      "count": 89
    },
    {
      "relationshipType": "上游",
      "count": 89,
      "endLabel": "产品"
    },
    {
      "relationshipType": "有属性",
      "count": 64292261
    },
    {
      "relationshipType": "有属性",
      "startLabel": "企业属性",
      "count": 22523045
    },
    {
      "relationshipType": "有属性",
      "count": 64292261,
      "endLabel": "企业属性"
    },
    {
      "relationshipType": "有属性",
      "startLabel": "企业",
      "count": 25097764
    },
    {
      "relationshipType": "有属性",
      "startLabel": "产品企业",
      "count": 683519
    },
    {
      "relationshipType": "有属性",
      "startLabel": "个体",
      "count": 16671452
    },
    {
      "relationshipType": "经营范围",
      "count": 1481144
    },
    {
      "relationshipType": "经营范围",
      "startLabel": "企业",
      "count": 793210
    },
    {
      "relationshipType": "经营范围",
      "count": 1481144,
      "endLabel": "产品"
    },
    {
      "relationshipType": "经营范围",
      "startLabel": "产品企业",
      "count": 1431870
    },
    {
      "relationshipType": "经营范围",
      "startLabel": "个体",
      "count": 687934
    },
    {
      "relationshipType": "有",
      "count": 4117658
    },
    {
      "relationshipType": "有",
      "startLabel": "专利",
      "count": 3314691
    },
    {
      "relationshipType": "有",
      "startLabel": "企业",
      "count": 802967
    },
    {
      "relationshipType": "有",
      "count": 3314691,
      "endLabel": "专利附表"
    },
    {
      "relationshipType": "有",
      "count": 108612,
      "endLabel": "专利数量"
    },
    {
      "relationshipType": "有",
      "count": 83459,
      "endLabel": "软件著作数量"
    },
    {
      "relationshipType": "有",
      "count": 573331,
      "endLabel": "商标数量"
    },
    {
      "relationshipType": "有",
      "count": 37565,
      "endLabel": "作品著作数量"
    },
    {
      "relationshipType": "有",
      "startLabel": "产品企业",
      "count": 17569
    },
    {
      "relationshipType": "包含",
      "count": 20
    },
    {
      "relationshipType": "包含",
      "startLabel": "行业",
      "count": 20
    },
    {
      "relationshipType": "包含",
      "count": 20,
      "endLabel": "产品"
    },
    {
      "relationshipType": "分支机构",
      "count": 1010910
    },
    {
      "relationshipType": "分支机构",
      "startLabel": "企业",
      "count": 1010910
    },
    {
      "relationshipType": "分支机构",
      "count": 1010795,
      "endLabel": "企业"
    },
    {
      "relationshipType": "分支机构",
      "startLabel": "产品企业",
      "count": 32266
    },
    {
      "relationshipType": "分支机构",
      "count": 23204,
      "endLabel": "产品企业"
    },
    {
      "relationshipType": "分支机构",
      "count": 115,
      "endLabel": "个体"
    },
    {
      "relationshipType": "参股",
      "count": 20236668
    },
    {
      "relationshipType": "参股",
      "startLabel": "企业",
      "count": 632626
    },
    {
      "relationshipType": "参股",
      "count": 20236668,
      "endLabel": "企业"
    },
    {
      "relationshipType": "参股",
      "startLabel": "个人",
      "count": 19431422
    },
    {
      "relationshipType": "参股",
      "startLabel": "其他",
      "count": 172614
    },
    {
      "relationshipType": "参股",
      "startLabel": "产品企业",
      "count": 15390
    },
    {
      "relationshipType": "参股",
      "count": 273647,
      "endLabel": "产品企业"
    },
    {
      "relationshipType": "参股",
      "startLabel": "个体",
      "count": 6
    },
    {
      "relationshipType": "主要成员",
      "count": 20332764
    },
    {
      "relationshipType": "主要成员",
      "count": 20332764,
      "endLabel": "企业"
    },
    {
      "relationshipType": "主要成员",
      "startLabel": "个人",
      "count": 20332764
    },
    {
      "relationshipType": "主要成员",
      "count": 347222,
      "endLabel": "产品企业"
    }
  ],
  "nodes": [
    {
      "count": 218632435
    },
    {
      "count": 1849254,
      "label": "专利"
    },
    {
      "count": 16247044,
      "label": "acc"
    },
    {
      "count": 94479405,
      "label": "企业属性"
    },
    {
      "count": 5,
      "label": "行业"
    },
    {
      "count": 1498789,
      "label": "资质证书"
    },
    {
      "count": 10317493,
      "label": "企业"
    },
    {
      "count": 399,
      "label": "产品"
    },
    {
      "count": 70494154,
      "label": "个人"
    },
    {
      "count": 11083628,
      "label": "scc"
    },
    {
      "count": 172614,
      "label": "其他"
    },
    {
      "count": 3442890,
      "label": "专利附表"
    },
    {
      "count": 108612,
      "label": "专利数量"
    },
    {
      "count": 679493,
      "label": "软件著作"
    },
    {
      "count": 83460,
      "label": "软件著作数量"
    },
    {
      "count": 4163730,
      "label": "商标"
    },
    {
      "count": 573332,
      "label": "商标数量"
    },
    {
      "count": 584447,
      "label": "作品著作"
    },
    {
      "count": 37565,
      "label": "作品著作数量"
    },
    {
      "count": 383243,
      "label": "产品企业"
    },
    {
      "count": 30146793,
      "label": "个体"
    }
  ],
  "indexes": [
    {
      "updatesSinceEstimation": 0,
      "indexType": "LOOKUP",
      "totalSize": 0,
      "indexProvider": "token-lookup-1.0",
      "properties": [],
      "labels": [],
      "estimatedUniqueSize": 0
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "LOOKUP",
      "totalSize": 0,
      "indexProvider": "token-lookup-1.0",
      "relationshipTypes": [],
      "properties": [],
      "estimatedUniqueSize": 0
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "TEXT",
      "totalSize": 10317493,
      "indexProvider": "text-2.0",
      "properties": [
        "city"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 10317493
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "TEXT",
      "totalSize": 10317493,
      "indexProvider": "text-2.0",
      "properties": [
        "province"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 10317493
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "TEXT",
      "totalSize": 10317493,
      "indexProvider": "text-2.0",
      "properties": [
        "district"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 10317493
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "name"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 10271482
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "legalPerson"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 2924299
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 0,
      "indexProvider": "range-1.0",
      "properties": [
        "CompanyType"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 0
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "stdRegCapital"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 57605
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "city",
        "province",
        "district"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 756
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 0,
      "indexProvider": "range-1.0",
      "properties": [
        "stdRealCapital"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 0
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 0,
      "indexProvider": "range-1.0",
      "properties": [
        "insuredNumber"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 0
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "registerStatus"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 10
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "typeList"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 46
    },
    {
      "updatesSinceEstimation": 0,
      "indexType": "RANGE",
      "totalSize": 10317493,
      "indexProvider": "range-1.0",
      "properties": [
        "establishDate"
      ],
      "labels": [
        "企业"
      ],
      "estimatedUniqueSize": 17681
    }
  ],
  "constraints": []
}

**Comment by blouerat** [comment] 2023-08-03 07:42
Wonderful, thank you, we'll have a look and report back 👍

**Comment by inmost-light** [comment] 2023-08-03 13:38
Hello @forestlcoder, thank you for reporting.

This is a known issue with `TEXT` indexes using `text-2.0` index provider. They have difficulty with estimating the number of unique items in the index (`estimatedUniqueSize` field below):

```json
{
  "updatesSinceEstimation": 0,
  "indexType": "TEXT",
  "totalSize": 10317493,
  "estimatedUniqueSize": 10317493
  "indexProvider": "text-2.0",
  "properties": ["city"],
  "labels": ["企业"],
},
{
  "updatesSinceEstimation": 0,
  "indexType": "TEXT",
  "totalSize": 10317493,
  "estimatedUniqueSize": 10317493
  "indexProvider": "text-2.0",
  "properties": ["province"],
  "labels": ["企业"],
},
{
  "updatesSinceEstimation": 0,
  "indexType": "TEXT",
  "totalSize": 10317493,
  "estimatedUniqueSize": 10317493
  "indexProvider": "text-2.0",
  "properties": ["district"],
  "labels": ["企业"],
},
{
  "updatesSinceEstimation": 0,
  "indexType": "RANGE",
  "totalSize": 10317493,
  "estimatedUniqueSize": 756
  "indexProvider": "range-1.0",
  "properties": ["city", "province", "district"],
  "labels": ["企业"],
},
```

As you can see, both `totalSize` and `estimatedUniqueSize` for the three TEXT indexes are set to 10317493, which is probably incorrect for you data. This mis-estimation makes the planner avoid using the composite index.

There are a few workarounds you can try:

- Add an index hint to your query:

```cypher
explain
MATCH (n:企业)
USING INDEX n:企业(city, province, district)
where n.city = '重庆市' and n.province = '重庆市' and n.district = '万州区'
RETURN n
LIMIT 25
```

- For the `TEXT` indexes listed above, do you have queries with `CONTAINS` or `ENDS WITH` that use them? If not, consider using `RANGE` indexes for those properties instead.
- If you _do_ have such queries, you can also try using `text-1.0` index provider for them instead, e.g. `CREATE TEXT INDEX FOR (n:企业) ON (n.city) OPTIONS { indexProvider: 'text-1.0' }`.

Hope this helps.

**Comment by forestlcoder** [comment] 2023-08-04 01:59
> Thanks, I have a try with creating range index ,  but execute this sql still slowly.
MATCH (n:企业)
USING INDEX n:企业(city, province, district)
where n.city = '重庆市' and n.province = '重庆市' and n.district = '万州区'
RETURN count(n)
I guess count(n) aggs may causing index does not working, or it does not take effect as mysql

**Comment by inmost-light** [comment] 2023-08-04 08:07
@forestlcoder 
You can run the query with `PROFILE` prefix and then get the text output from the browser (see the attached screenshot).
If there's a lot of misses in `Page Cache Hits/Misses` column, the query might be slow because it's the first run.

<img width="937" alt="export_txt" src="https://github.com/neo4j/neo4j/assets/1788612/d2380de6-3e35-4bd8-a29f-fe37893a8430">

**Comment by forestlcoder** [comment] 2023-08-04 09:20
> @forestlcoder You can run the query with `PROFILE` prefix and then get the text output from the browser (see the attached screenshot). If there's a lot of misses in `Page Cache Hits/Misses` column, the query might be slow because it's the first run.
> 
> <img alt="export_txt" width="937" src="https://user-images.githubusercontent.com/1788612/258361100-d2380de6-3e35-4bd8-a29f-fe37893a8430.png">

Planner COST

Runtime SLOTTED

Runtime version 5.10

+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| Operator          | Id | Details                                          | Estimated Rows | Rows    | DB Hits | Memory (Bytes) | Page Cache Hits/Misses |
+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +ProduceResults   |  0 | `count(n)`                                       |              1 |       1 |       0 |                |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +Limit            |  1 | 25                                               |              1 |       1 |       0 |                |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +EagerAggregation |  2 | count(n) AS `count(n)`                           |              1 |       1 |       0 |             24 |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +Filter           |  3 | n.province = $autostring_1                       |         103755 | 2547943 | 2547943 |                |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +NodeIndexSeek    |  4 | TEXT INDEX n:企业(city) WHERE city = $autostring_0 |         518773 | 2547943 | 2547944 |                |                    0/0 |
+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+

Total database accesses: 5095887, total allocated memory: 88


first query and second query both slowly

**Comment by inmost-light** [comment] 2023-08-04 09:27
@forestlcoder The composite index is not used because you don't have predicates on all three properties. Only non-null properties are indexed, so you need to add `AND n.district IS NOT NULL` to be able to use the composite index for this query.

**Comment by forestlcoder** [comment] 2023-08-09 01:17
I find it will be very slowly if using function count for the result,  whether using index or not.
![image](https://github.com/neo4j/neo4j/assets/26137810/fc571218-f27e-4363-afb5-8fdc2a293ee1)
![image](https://github.com/neo4j/neo4j/assets/26137810/e6a05e2d-8231-43da-afea-1341577bc6f0)

**Comment by inmost-light** [comment] 2023-08-09 08:53
@forestlcoder I can't reproduce this. What does `PROFILE` output?

**Comment by forestlcoder** [comment] 2023-08-10 07:48
Planner COST

Runtime SLOTTED

Runtime version 5.10

+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| Operator          | Id | Details                                          | Estimated Rows | Rows    | DB Hits | Memory (Bytes) | Page Cache Hits/Misses |
+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +ProduceResults   |  0 | `count(n)`                                       |              1 |       1 |       0 |                |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +EagerAggregation |  1 | count(n) AS `count(n)`                           |              1 |       1 |       0 |             24 |                    0/0 |
| |                 +----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+
| +NodeIndexSeek    |  2 | TEXT INDEX n:企业(city) WHERE city = $autostring_0 |         517836 | 6793464 | 6793465 |                |                    0/0 |
+-------------------+----+--------------------------------------------------+----------------+---------+---------+----------------+------------------------+

Total database accesses: 6793465, total allocated memory: 88

**Comment by inmost-light** [comment] 2023-08-10 08:26
- Try creating a RANGE index for  `n:企业(city)`. You can then add `USING RANGE INDEX n:企业(city)` hint to the query.
- Are you using Neo4j community edition? Try with enterprise.

**Comment by inmost-light** [comment] 2023-08-18 07:58
Closing, since the original issue is not a bug.

If you need help with tuning queries or the Neo4j server, ask https://community.neo4j.com/

**Closed as completed by inmost-light** 2023-08-18 07:58 UTC
Labels: bug, team-cypher
