### ISSUE TITLE
Apache Commons Text package needs to be updated

### ISSUE THREAD

**Issue by verydemo** [neo4j/neo4j#12962] opened 2022-10-26 07:14 UTC
![image](https://user-images.githubusercontent.com/29354679/197959042-4ae67dea-1b7a-4b00-a7c2-4e600b6be1b2.png)
Hi, Apache Commons Text package needs to be updated. Thanks.

**Comment by jennyowen** [comment] 2022-10-26 08:01
closing because it's a duplicate of #12961

**Closed as completed by jennyowen** 2022-10-26 08:01 UTC
