### ISSUE TITLE
The query hang if the result contains circle?

### ISSUE THREAD

**Issue by ninaqms** [neo4j/neo4j#11114] opened 2018-02-27 11:00 UTC
**Operating System: win64, 
Run the following query in the  neo4j browser, and it hangs: 

**MATCH (g:GROUP) WHERE g.SamAccountName="ABC" 
WITH g   
MATCH (sg:GROUP)<-[r*]-(user:User)  
WHERE sg.SamAccountName = g.SamAccountName   
RETURN user, r, sg**

This model describes the relationship between groups and users. For group ABC,
ABC <- DEF <- user1  (DEF is memberOf ABC, user1 is memberOf DEF)
ABC <- DEF <- user2 (DEF is memberOf ABC, user2 is memberOf DEF)
ABC -> DEF  (ABC is memberOf DEF)

- Expected behavior
Above query will return (user1, ABC <- DEF <- user1,  ABC), (user2, ABC <- DEF <- user2, ABC)

- Actual behavior
The above query will keep running and not return any result.

I know this should be caused by the circle between ABC and DEF. Return any one path between ABC and user1/user2 is acceptable for me, but not hang there. I do not want use shortestPath since it's much slower.

**Comment by Lojjs** [comment] 2018-03-05 08:28
@ninaqms In order to help you we need to know which version of neo4j are you using.

Best regards Louise, Neo4j Cypher team

**Comment by InverseFalcon** [comment] 2018-03-05 22:42
@ninaqms You aren't using variable-length relationships in your query, so it couldn't be an infinite loop issue (additionally, the mode of expansion that Cypher uses wouldn't allow that anyway...a relationships can ever only be traversed once in a matched path).

I would guess that this probably has to do with non-indexed lookup of your nodes. Can you tell us the indexes in your db for :GROUP nodes? Also if you could add the PROFILE plan of the query (after all elements of the plan are expanded) that could help point out where the problem is.

**Comment by Lojjs** [comment] 2018-03-19 13:09
@ninaqms we need the above requested info about neo4j version in order to help you. As @InverseFalcon wrote, also eventual indexes and PROFILE could be helpful. If I don't hear back from you within a couple of days I will close this issue for now. Feel free to re-open it or create a new one if you still have problems.

**Closed as completed** 2018-04-09 07:49 UTC
Labels: team-cypher
