### ISSUE TITLE
Neo4j Vector Index - Increase dimension limit to 8192

### ISSUE THREAD

**Issue by HollowMan6** [neo4j/neo4j#13512] opened 2024-08-25 17:10 UTC
Something similar to #13406

I'm using https://huggingface.co/dunzhang/stella_en_1.5B_v5 sentence transformer, it creates 8192 dimension vector arrays and I believe the limit on the index is 4096.

Any chance we can get support in the vector index for larger vectorized embeddings, maybe up to 8192?

I'm also aware that starting from Neo4j 5.23 (vector-2.0), `vector.dimensions` is no longer required, but it would still be great to increase the limit so that additional checks can be done. https://neo4j.com/release-notes/database/neo4j-5/

**Comment by HollowMan6** [comment] 2024-08-25 21:09
Looks like it can be caused by some bugs from vllm. They do use the size of 4096, so will investigate and close this for now.

**Comment by parnmatt** [comment] 2024-08-26 13:08
Hi @HollowMan6 thanks for reaching out.

It is important to note that there still is an upper limit of 4096 dimensions in Neo4j 5.23 for indexed vectors. The index config setting itself is no longer mandatory for the creation of the index, and now only enforces strict checking. It is still _recommended_ to use the setting for those checks.
Vectors of the incorrect dimensionality (if specified), or larger than supported (if not) will not be indexed.

In regards to increasing the maximum supported dimensions, this is a feature request, not a bug, so I have relabelled the issue and the product team will review the request.

---

In the past, the team has increased the limit based on what the major model vendors in the space are doing. Currently, 4096 is still above most major model vendors are doing.

It seems a lot of vendors have been focusing more on the quality of their models over dimensions, and large vectors take up a lot of space. Take OpenAI, their gen 1, they had 16k-dimensional vectors as its largest, but I believe their gen2 1536-dimension vectors were better. The current gen3 "large" model output 3k-dimensional vectors, but they (effectively) sort them in importance allowing for a reduction in dimensions (by the API, but can be done manually); the "large" model reduced to 256-dimensions outperforms the gen2 1536, and is 6x smaller!

**Comment by parnmatt** [comment] 2024-09-02 10:59
Hi @HollowMan6 just thought I'd get back to you with an update that perhaps can unblock you in this project using this model
(sorry I was on leave last week).

The product team are discussing the potential increase in some future version of Neo4j. I can say from an engineering perspective that with how indexing works in Neo4j, and the consistency of indexes between upgrades, such a change would likely need to be tied to another index provider (think `vector-1.0` vs the current default `vector-2.0`).
This requirement would be due to the allowance of no longer specifying dimensions in Neo4j 5.23.
Such work is a little more involved than bumping a number and adding a few protections; thus _**if**_ it is planned, it will likely be merged with other work requiring a new index provider version.

---

However, I do have some good news regarding the model you are using. After reading a little about it, we noticed they are Matryoshka embeddings. This uses the same technique OpenAI uses, discussed above. 

From the model page:
> The models are finally trained by [MRL](https://arxiv.org/abs/2205.13147), so they have multiple dimensions: 512, 768, 1024, 2048, 4096, 6144 and 8192.
> The higher the dimension, the better the performance. Generally speaking, 1024d is good enough. The MTEB score of 1024d is only 0.001 lower than 8192d.

You likely do not need 8k dimensions; they've noted that the 1k dimensional vectors are good enough, barely making too much difference (MTEB score). You should therefore be able to use the reduced dimensional representations of these embeddings as they are now, and arguably save a tonne of disk space and/or handle _more_ vectors than you could before.

You could check this for yourself to find the dimensionality that provides the accuracy you find acceptable by doing an exhaustive search (pair-wise, not using an index, thus creating a ground truth) with a known query on a subset of embeddings, perhaps <10k.
Once using 8k dimensions, another using a smaller dimensionality, and compare the results, and the difference in similarity. You hopefully would see a small variance.

If the model has a preferred procedure for reducing the dimensions, it would be best to use that.
However, it is _"likely"_ they are ordered, and you can discard the tails yourself; though I'd only suggest that if you have already generated a large number of these embeddings. If that's the case, I would specifically test the output between their preferred procedure and simply discarding the tail. I would check using the similarity between them rather than entry-wise.

**Comment by HollowMan6** [comment] 2024-09-02 11:21
Hi @parnmatt! Thank you so much for your reply in great detail! I actually have already switched to another model that fits within the 4096 limit, but I guess we can still leave this issue open, as so other people may find this helpful. Anyway, it's not in a hurry, so thanks again!

**Comment by parnmatt** [comment] 2024-09-02 12:46
Glad you were able to move forward.
As this is a feature request in discussion I am happy to keep this open until some resolution.

**Comment by parnmatt** [comment] 2024-10-02 13:06
For now, it has decided not to add this feature request to the roadmap.

However, we do keep our eyes on the market, and on the frequency of certain feature requests; it may be added to the roadmap in the future.

**Closed as completed by parnmatt** 2024-10-02 13:06 UTC
Labels: feature, team-kernel
