### ISSUE TITLE
Transaction error documentation incorrect/misleading

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#5258] opened 2015-09-01 03:23 UTC
http://neo4j.com/docs/2.2.3/status-codes.html#_classifications

This page still says that both `ClientError`s and `TransientError`s have no effect on transactions.

While that may technically be considered correct (if you don't specify `/commit`, then the transaction still appears open, not rolled back), it's definitely misleading: the transaction will _not_ ultimately commit.

—

Easy repro:

```
$ http POST localhost:7474/db/data/transaction statements:='[{"statement":"RETURN {foo}"}]'
```

``` js
{
    "commit": "http://localhost:7474/db/data/transaction/13448/commit", 
    "errors": [
        {
            "code": "Neo.ClientError.Statement.ParameterMissing", 
            "message": "Expected a parameter named foo"
        }
    ], 
    // ...
}
```

```
$ http POST localhost:7474/db/data/transaction/13448/commit
```

``` js
{
    "errors": [
        {
            "code": "Neo.DatabaseError.Transaction.CouldNotCommit", 
            "message": "org.neo4j.kernel.api.exceptions.TransactionFailureException: Transaction rolled back even if marked as successful", 
            "stackTrace": "java.lang.RuntimeException: org.neo4j.kernel.api.exceptions.TransactionFailureException: Transaction rolled back even if marked as successful\n\t..."
        }
    ], 
    // ...
}
```

—

This is something we at @FiftyThree discussed with the Neo4j team in depth, and it seems this is by design (for better or for worse). The only solution then, and what we do, is to roll the transaction back manually, and retry the whole thing again.

So at the very least, the documentation should be improved. (But I also wonder then: should Neo4j just go ahead and roll the transaction back in every case then?)

**Comment by digitalstain** [comment] 2015-09-16 10:17
@aseemk The issue is being worked on here: https://github.com/neo4j/neo4j/pull/5353 - your feedback is welcome.

**Comment by lutovich** [comment] 2015-09-18 08:48
@aseemk We've actually realised that not only docs change is required here. Behaviour of `ClientError`s was unexpected and slightly inconsistent. Here is a new PR with the fix: https://github.com/neo4j/neo4j/pull/5390

**Comment by lutovich** [comment] 2015-09-18 12:21
@aseemk attempt number 3 https://github.com/neo4j/neo4j/pull/5394 :)
We realised that it is not safe to not rollback on ClientError because subsequent reads might see dirty transaction state. Now behaviour would be in sync with docs.

**Comment by lutovich** [comment] 2015-09-30 16:41
Mentioned PR merged. Issue should be fixed in next 2.2 and 2.3 releases. With this fix transaction will be rolled back on ClientError by the database.

**Closed as completed by lutovich** 2015-09-30 16:41 UTC

**Comment by aseemk** [comment] 2015-10-12 17:08
Awesome, thank you @lutovich!

**Comment by aseemk** [comment] 2015-10-12 17:08
And great tests.
