### ISSUE TITLE
Unintended JSON string conversion in property values

### ISSUE THREAD

**Issue by yashagw** [neo4j/neo4j#13525] opened 2024-09-18 12:54 UTC
Neo4j is automatically converting certain JSON-like strings into native data types when setting node properties. For example, a string value of '[{"AWS": ""}]' is being stored as {"AWS": ""} in the database. The desired behavior is to store these JSON-like strings exactly as they are provided, without any automatic type conversion. This is crucial for maintaining the integrity of the original data, especially in cases where the string representation is significant. Current workarounds like using json.dumps() or manually escaping strings are not feasible due to the scale of the application and the inability to predict which properties might contain JSON-like strings. Is there a global configuration or a driver-level solution that can prevent this automatic conversion for all queries without requiring changes to individual Cypher statements or extensive code modifications?

Neo4j Version: 5.23.0
Linux Environment

**Comment by mnd999** [comment] 2024-09-18 13:49
Can you give us a bit more information about what you are doing? I tried `CREATE (j:Json { json:  '[{"AWS": ""}]' });` in cypher-shell and it seems okay. But I'm guessing you're doing something with the python driver? A code example might help to find out where the issue is so we can pass this to the correct team.

**Comment by mnd999** [comment] 2024-10-01 07:15
Will close this for now as it's not had a response. If you are still having problems, please feel free to reopen.

**Closed as completed by mnd999** 2024-10-01 07:15 UTC
Labels: bug
