### ISSUE TITLE
db.schema.visualization() displays nonexistent relationships

### ISSUE THREAD

**Issue by numericOverflow** [neo4j/neo4j#12417] opened 2020-03-03 19:48 UTC
- Neo4j Server version: 4.0.0 (community)
- Operating system: Windows server 2012R2
- API/Driver: Cypher console web browser (Neo4j Browser version: 4.0.1)

**NOTE**:  Neo4j Browser version: 4.0.3/Neo4j Server version: 4.0.1 (community) (latest version as of right now) also exhibits the same behavior described below.

1. Load data
2. Run call db.schema.visualization()
The example DB at neo4j console:  https://console.neo4j.org/r/nt3sgc

```
create (l1a:Level1 {name:'l1a'})
,(l1b:Level1 {name: 'l1b'})
,(l1c:Level1 {name: 'l1c'})
,(l1d:Level1 {name: 'l1d'})
,(l2a:Level2 {name: 'l2a'})
,(l2b:Level2 {name:'l2b'})
,(l3a:Level3 {name:'l3a'})
,(l1a)-[:OWNED_BY]->(l2a)
,(l1b)-[:OWNED_BY]->(l2a)
,(l1c)-[:OWNED_BY]->(l2b)
,(l1d)-[:OWNED_BY]->(l2b)
,(l2a)-[:OWNED_BY]->(l3a)
,(l2b)-[:OWNED_BY]->(l3a)
;

match (n1:Level1)-[:OWNED_BY]->(:Level1)
RETURN count(n1) as cnt, 'count_L1_to_L1' as description
UNION
match (n2:Level2)-[:OWNED_BY]->(:Level2)
RETURN count(n2) as cnt, 'count_L2_to_L2' as description
UNION
match (n3:Level3)-[:OWNED_BY]->(:Level3)
RETURN count(n3) as cnt, 'count_L3_to_L3' as description
UNION
match (n4:Level1)-[:OWNED_BY]->(:Level2)
RETURN count(n4) as cnt, 'count_L1_to_L2' as description
UNION 
match (n5:Level2)-[:OWNED_BY]->(:Level3)
RETURN count(n5) as cnt, 'count_L2_to_L3' as description
;

call db.schema.visualization()
```

Here is the database contents as loaded.  It's a simple tree type hierarchy where level 3 is the top node, and level 1 is the most detailed level.  Each level's nodes points upward to a single parent, and there are no links across nodes in the same level.
The match query included above proves that there are relationships shown in the viz that do not exist in the DB.
![expected_db_schema_viz_2020-03-03](https://user-images.githubusercontent.com/3429424/75811826-beeb1400-5d52-11ea-9f40-7de11c697ef0.jpg)

- Expected behavior
Viz should only show relationships between nodes where that type of relationship actually exists in the DB
![DB_Viz_as_expected](https://user-images.githubusercontent.com/3429424/75812118-46d11e00-5d53-11ea-9f89-0cf93369ffd8.jpg)

- Actual behavior
The viz shows inter-node links between *ALL* nodes that have the same relationship type instead of just those that actually exist in the DB.
![DB_Viz_is_wrong](https://user-images.githubusercontent.com/3429424/75811839-c4e0f500-5d52-11ea-9d85-4e0da98d6162.jpg)

**Comment by sherfert** [comment] 2020-03-09 07:49
Duplicate of https://github.com/neo4j/neo4j/issues/9726

**Closed as completed by sherfert** 2020-03-09 07:49 UTC
Labels: bug
