### ISSUE TITLE
Inconsistent result when deleting unrelated node in same statement

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13142] opened 2023-04-14 16:33 UTC
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
CREATE ({x:0})<-[y:A]-() CREATE ({x:endNode(y).x})
-
RETURN COUNT { ({x:0}) } AS n
```
Produces:
```
╒═══╕
│"n"│
╞═══╡
│1  │
└───┘
```

---
2:
```cypher
CREATE ({x:0})<-[y:A]-() CREATE (z) DELETE z CREATE ({x:endNode(y).x})
-
RETURN COUNT { ({x:0}) } AS n
```
Produces:
```
╒═══╕
│"n"│
╞═══╡
│2  │
└───┘
```
---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.
The only difference between them is the `CREATE (z) DELETE z` part which shouldn't have any impact on the query, especially on properties that it doesn't reference.

I encountered this issue when testing queries against the **neo4j:5.6.0** Docker container.

### Steps to reproduce
1.
	<details>

	<summary>Run the Docker Container</summary>

	```
	docker run \
	    -p 7474:7474 -p 7687:7687 \
	    --name neo4j-apoc \
	    -e apoc.export.file.enabled=true \
	    -e apoc.import.file.enabled=true \
	    -e apoc.import.file.use_neo4j_config=true \
	    -e NEO4J_PLUGINS=\[\"apoc\"\] \
	    -e NEO4J_AUTH=none
	    --rm \
	    neo4j:5.6.0
	```

	</details>

1. Navigate to the browser interface on [localhost:7474](http://localhost:7474)

1. Run the aforementioned queries and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The first query returns `1`, whereas the second query returns `2`.

**Comment by InverseFalcon** [comment] 2023-04-14 22:32
This doesn't look like correct syntax:

```
RETURN COUNT { (x:0) } AS n
```

This would be interpreted as a node with variable `x` and label `:0`, but labels cannot start with a number, so this errors out.

You may have missed brackets within the node parenthesis for the node's properties. This looks like correct syntax:

```
RETURN COUNT { ({x:0}) } AS n
```

This would be a count nodes without a variable, without any restriction on label, where its `x` property is 0.

__________

Let's look now to behavior and a possible bug.

I can see differing results, when running just the creation query on an empty db, between SLOTTED and PIPELINED runtime, so there's definitely a bug in play here.

With PIPELINED runtime, 3 nodes are created, two of these nodes have the property `x` set to 0, which makes sense: we created a pattern where the end node of the rel has x set to 0, then we created a new node where its x should be set to the same value, as it's taking its value from the rel's end node's x property.

However, when run with SLOTTED runtime, we see incorrect results. Only one of the nodes (the endnode of the relationship) has its x property set to 0. The node created last, without any relationships, does not have any properties set, and that's incorrect.

Even though there are two CREATE statements, I only see one Create operation in the plan. My guess is that the internal execution of the create operation is wrong with SLOTTED runtime so that the evaluation of the endnode's x property happens in the wrong order, such that it gets the value prior to the value being set.

This actually explains why the correct creation behavior results if we place the CREATE and DELETE of a node in between, because instead of one Create operation handling the creation of the nodes in question, it is now handled by two Create operations (we are ignoring the one in the middle that gets created and deleted), and with 2 Create operations we get expected behavior with a correct result of 2.

Looks like even a simple WITH clause between them will result in 2 Create operations in the query plan and produce correct results, regardless of runtime:

```
CREATE ({x:0})<-[y:A]-() 
WITH y 
CREATE ({x:endNode(y).x})
```

**Comment by CelineWuest** [comment] 2023-04-14 22:43
Thanks a lot for the in-depth analysis @InverseFalcon!
The syntax error you pointed out was just a typo on my side, I fixed it in the report.

Interesting how this bug only occurs in the SLOTTED runtime, I would have expected the opposite, judging by their complexity.

**Comment by InverseFalcon** [comment] 2023-04-14 22:50
@DominicWuest 

Yes, and that has historically been the case throughout Neo4j 4.x, with PIPELINED bugs being more numerous, and SLOTTED being relatively stable with only a few.

It will be interesting to see how many of these recently reported issues end up being SLOTTED runtime bugs, and to see if there's a single common bug underlying them, or several different ones.

**Comment by loveleif** [comment] 2023-04-17 09:01
Thanks again @DominicWuest, very clear report as always! I've created a ticket in our internal bug tracker for further investigation ([link](https://trello.com/c/2CUVlwFQ/4697-inconsistent-result-when-deleting-unrelated-node-in-same-statement)).

**Comment by pontusmelke** [comment] 2023-04-28 12:28
Duplicate of https://github.com/neo4j/neo4j/issues/13094

**Closed as completed by pontusmelke** 2023-04-28 12:28 UTC
Labels: bug, team-cypher
