### ISSUE TITLE
neo4j-import does not correctly recognize Excel-type CSV wrt. double quotes and backslash

### ISSUE THREAD

**Issue by dsevilla** [neo4j/neo4j#8472] opened 2016-12-03 09:17 UTC
neo4j-import does not correctly recognize Excel-type CSV wrt. double quotes and backslash

- Neo4j version: 3.1
- Operating system: Arch Linux
- API/Driver: None
- **Steps to reproduce**

The following CSV parsed correctly under MongoDB and MySQL, but it is failing in Neo4j:

http://neuromancer.inf.um.es:8080/es.stackoverflow/Posts.csv.gz

- Expected behavior

CSV read correctly with default parameters, as neo4-import is supposed to convert "" to " within a field.

- Actual behavior

neo4j-import fails reporing early termination of a field. The example error is the following:

For an imput line with the following characters:

abcdef\\""ghi

The parser interprets the first \" as *one* double quotes, and then the next double quote is used to end the field early. I think quoting of backslash should be avoided if backslask is not specified explicitly as the quote character. The above text should produce the following complete field (using the conventions of Excel-CSV):

abcdef\\"ghi

(that is, one backslash and one quote).

**Comment by spacecowboy** [comment] 2016-12-05 12:54
If I understand you correctly, you want a string composed of the three characters `\`, `"`, `"`, to result in the string of two characters `\`, `"`.

This is not what [the default options](https://neo4j.com/docs/operations-manual/current/import/import-tool-usage/#import-tool-options) will give you.

Since you have  backslash in the value, you'd need to escape it (double backslash).

Backslash is typically used as a character to escape other values. Changing this behavior would surprise a great deal of users. For that reason I am closing this as working as intended.

**Comment by dsevilla** [comment] 2016-12-05 16:14
Oh, that's infortunate. Of course you're free of implementing your product as you like, but I think it is much better to stick to standards than to "surprise users", as they may (as I was) expecting the import process to be correct according to, at least, the RFC that specifies CSV with double quoting:

[https://tools.ietf.org/html/rfc4180](https://tools.ietf.org/html/rfc4180)

If you look at the grammar, there is no trace of backquote used for quoting. 

Backquote is a de facto standard for quoting string with special characters *inside* literals of programming languages. But CSV is not a program, it is *data*, and you don't have to quote anything *apart from* the quotes themselves, that are used to delimit fields in case they have commas or carriage return characters.

I don't *want* a string composed of \\, " and " to result in two characters, \\ and ". It is as the RFC says, as Excel itself exports CSV, and as I have used it to import CSV to MySQL and MongoDB. The same files that now I have to tweak to be read by Neo4j in what appears to me to be a broken implementation of the CSV reader.

**Comment by spacecowboy** [comment] 2016-12-05 23:16
Oh I wasn't aware of there being an RFC for this. Then I think there is value in keeping this open as a possible improvement in the future

**Comment by RXminuS** [comment] 2017-01-31 16:18
Just ran into this behaviour as well. Annoying thing is that our system produces perfect CSV and when I tried importing it into Neo4J using ```LOAD CSV```it gave me ```there's a field starting with a quote and whereas it ends that quote there seems to be characters in that field after that ending quote.```  finally after lots of headscratching figured out that Neo indeed doesn't adhere to the RFC where ```"this is a string with a quote\"""``` should be read as  ```this is a string with a quote\"``` Definetly a bug in my eyes, not an enhancement

**Comment by dsevilla** [comment] 2017-01-31 16:55
@RXminuS exactly, that was the idea initially. That case you don't see it very often, but when you find it, it is really difficult to debug, and it would be nice to be fixed.

**Comment by RXminuS** [comment] 2017-01-31 16:59
Ok update: I've found the responsible code it's in ```/neo4j/community/csv/src/main/java/org/neo4j/csv/reader/BufferedCharSeeker.java``` line ```157```. I was going to make a pull request but this was the comment on the responsible line: 

```"// Legacy concern, support java style quote encoding". ```

And indeed looking through the tests it seems that it's specifically coded to support this weird 'legacy' feature. Annoyingly though it's nearly impossible to combine the two behaviours because you would have to go down two separate control paths. In my opinion the best solution would be to make legacy behaviour explicitly configurable...not the default. Especially because it doesn't conform with CSV standards. @spacecowboy what's your thoughts, then I can submit the PR.

**Comment by dsevilla** [comment] 2017-01-31 17:03
I ended up duplicating the backquote. In my opinion, bringing here Java has no meaning, as we're talking about CSV, not Java... (Even in the source code, the file refers to CSV import, so it won't affect any other conversion inside the database).

**Comment by RXminuS** [comment] 2017-01-31 17:06
Yeah that's what I think too. But if it's a legacy feature they need to support I can understand. But it shouldn't be default behaviour

**Comment by spacecowboy** [comment] 2017-02-01 10:26
@RXminuS I agree with your general opinion - this is CSV and not Java. And I further fully agree that the default should be what makes sense for CSV (the RFC spec) and not "whatever was the default in Java".

Having said that though, the current behavior has been the default for a long time and we cannot change the default behavior in a patch/minor release. We'd have to wait until `4.0.0` for that which is not scheduled at this time.

So I think the only thing we can do right now is add a config option (in 3.2) to adhere to the spec, which by default (for 3.x) would be off. Then in 4.0, once that comes around, we can flip the default value.

If you want, you can open a PR which adds a test and changes the default behavior and I can have a look at adapting it to be a configuration option instead.

**Comment by RXminuS** [comment] 2017-02-01 10:31
Makes sense. I'll have to add some functionality to make LOAD CSV
configurable from the ui (currently only cli supports setting things like
seperator char etc.) Or do you reckon it's better to go with an overall
config that can be edited from a config file?

**Comment by spacecowboy** [comment] 2017-02-01 10:43
@RXminuS Hmm, are the two in conflict? Can we support both at the same time, or does supporting the RFC make some strings which are supported now fail on import?

If we can support both at the same time, we don't need to add a config option. We should not add stuff to LOAD CSV ui.

**Comment by RXminuS** [comment] 2017-02-07 13:54
@spacecowboy We can't both support \\"" java escaping and RFC \\"" escaping at the same time. So there will have to be a config of supporting either RFC spec or Legacy Java style...which until v4.0.0 has to be set to Legacy Java Style by default. The problem is that LOAD CSV isn't at all configurable atm. in the ui (but the load shell script is). This means that either we need to make the "UI" version configurable (which would be nice anyways, so that you can customise separator character etc.) or there needs to be a system wide config option for which spec to follow.

My preference would be to extend the LOAD CSV with a way to configure but haven't looked into how practical that is yet...any suggestions?

**Comment by tinwelint** [comment] 2017-02-08 12:03
I think this makes sense. To sum up what I've understood and what seems to be the conclusion (with which I agree):

- Ability in `BufferedCharSeeker` to configure whether or not `\"` is interpreted as `"`, i.e. whether or not to treat `\` with any more context than just another character
- Expose configuration option through various surfaces for this option
- Default option is to have it work as it does now ("legacy"-style)
- For next major version (4.0) this default changes to (proper RFC style)

This change could and probably should go back to 3.0 or so, btw

**Comment by RXminuS** [comment] 2017-02-08 16:44
@tinwelint Yes that sounds about how I envisioned it :-)

**Comment by tinwelint** [comment] 2017-02-15 12:52
@RXminuS this has now been merged, although the surface for configuring this isn't complete yet.

**Comment by craigtaverner** [comment] 2017-02-28 14:25
@RXminuS Support for neo4j.conf control over this behaviour has now been merged into 3.0 (and later) and so will come out in the next 3.0.x, 3.1.x and 3.2.0 release. For 3.0 and 3.1 the legacy behaviour is default. It is possible that 3.2 might use the standard as default instead.

See https://github.com/neo4j/neo4j/pull/8903

**Closed as completed by craigtaverner** 2017-02-28 14:25 UTC
Labels: enhancement

**Comment by craigtaverner** [comment] 2017-02-28 14:28
#8903
