### ISSUE TITLE
java.sql.SQLException: Neo.ClientError.Request.Invalid: 'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state.

### ISSUE THREAD

**Issue by brucejee** [neo4j/neo4j#8320] opened 2016-11-08 02:07 UTC
My test code is:
1. The first cypher, I add a '。' for p2 property deliberately.
2. The second cypher i delete the '。' character, i want reuse this connection, but i got a exception too.
3. I debug this exception, found that this error is neo4j server response.
4. I use neo4j jdbc 3.0.1 and server is neo4j 3.0.6 community version.

![image](https://cloud.githubusercontent.com/assets/5820173/20084334/917bcd3c-a59c-11e6-9151-1417b4d10245.png)

And i met an exception like this:
java.sql.SQLException: Neo.ClientError.Statement.SyntaxError: Invalid input '。': expected whitespace or a property key name (line 1, column 48 (offset: 47))
"CREATE(n:TEST{Name:'TEST'}) SET n.p1 = 'A1', n.。p2 = 'A2';"
                                                ^
	at org.neo4j.jdbc.bolt.BoltStatement.wrapException(BoltStatement.java:91)
	at org.neo4j.jdbc.bolt.BoltStatement.executeUpdate(BoltStatement.java:103)
	at org.neo4j.jdbc.bolt.BoltStatement.execute(BoltStatement.java:112)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at com.emotibot.kgoff.mappers.UpdateNeo4jMapper.main(UpdateNeo4jMapper.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.neo4j.driver.v1.exceptions.ClientException: Invalid input '。': expected whitespace or a property key name (line 1, column 48 (offset: 47))
"CREATE(n:TEST{Name:'TEST'}) SET n.p1 = 'A1', n.。p2 = 'A2';"
                                                ^
	at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:129)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:108)
	at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:136)
	at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:157)
	at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:110)
	at org.neo4j.jdbc.bolt.BoltStatement.executeInternal(BoltStatement.java:68)
	at org.neo4j.jdbc.bolt.BoltStatement.executeUpdate(BoltStatement.java:96)
	... 9 more

java.sql.SQLException: Neo.ClientError.Request.Invalid: 'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state.
	at org.neo4j.jdbc.bolt.BoltStatement.wrapException(BoltStatement.java:91)
	at org.neo4j.jdbc.bolt.BoltStatement.executeUpdate(BoltStatement.java:103)
	at org.neo4j.jdbc.bolt.BoltStatement.execute(BoltStatement.java:112)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at com.emotibot.kgoff.mappers.UpdateNeo4jMapper.main(UpdateNeo4jMapper.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.neo4j.driver.v1.exceptions.ClientException: 'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state.
	at org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:68)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
	at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
	at org.neo4j.driver.internal.connector.socket.SocketClient.receiveAll(SocketClient.java:124)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.receiveAll(SocketConnection.java:129)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.sync(SocketConnection.java:108)
	at org.neo4j.driver.internal.connector.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:136)
	at org.neo4j.driver.internal.pool.PooledConnection.sync(PooledConnection.java:157)
	at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:110)
	at org.neo4j.jdbc.bolt.BoltStatement.executeInternal(BoltStatement.java:68)
	at org.neo4j.jdbc.bolt.BoltStatement.executeUpdate(BoltStatement.java:96)
	... 9 more

**Comment by chrisvest** [comment] 2016-11-08 09:19
You have a syntax error in your Cypher query. Specifically, `。` is not a valid identifier character. You can work around that problem by enclosing the property name with back-ticks, though:

```
"CREATE(n:TEST{Name:'TEST'}) SET n.p1 = 'A1', n.`。p2` = 'A2';"
```

**Comment by jexp** [comment] 2016-11-08 10:41
@chrisvest that was not the actual issue, the cypher syntax error was there deliberately to have one statement execution fail, and then demonstrate that a second statement fails.

as he states here:
1. The first cypher, I add a '。' for p2 property **deliberately.**
2. The second cypher i delete the '。' character, i want reuse this connection, **but i got a exception too.**

this one is the actual issue:

```
java.sql.SQLException: Neo.ClientError.Request.Invalid: 'beginning implicit transaction' cannot be done when a session is in the 'IN_TRANSACTION' state.
at org.neo4j.jdbc.bolt.BoltStatement.wrapException(BoltStatement.java:91)
at org.neo4j.jdbc.bolt.BoltStatement.executeUpdate(BoltStatement.java:103)
at org.neo4j.jdbc.bolt.BoltStatement.execute(BoltStatement.java:112)
at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
```

**Comment by inserpio** [comment] 2016-11-08 10:51
@jexp @chrisvest isn't it a JDBC Driver issue, to close here and open in https://github.com/neo4j-contrib/neo4j-jdbc?

**Comment by jexp** [comment] 2016-11-08 10:53
Let me try to reproduce it with the regular bolt java driver.

**Comment by brucejee** [comment] 2016-11-08 13:31
Thanks a lot.

**Comment by jexp** [comment] 2016-11-08 13:56
seems to be something in the JDBC driver @inserpio 
perhpas we don't consume the StatementResults in case of error ?

https://gist.github.com/jexp/6da03a94522d5692ae5fefc56d7fd24b

```
Ich:neo-test mh$ ~/Downloads/groovy-2.3.7/bin/groovy tx-bug.groovy 
1 Invalid input 'o': expected 'r/R' (line 1, column 3 (offset: 2))
"foo"
   ^
Caught: org.neo4j.driver.v1.exceptions.ClientException: Cannot run more statements in this transaction, because previous statements in the transaction has failed and the transaction has been rolled back. Please start a new transaction to run another statement.
org.neo4j.driver.v1.exceptions.ClientException: Cannot run more statements in this transaction, because previous statements in the transaction has failed and the transaction has been rolled back. Please start a new transaction to run another statement.
    at org.neo4j.driver.internal.InternalTransaction.ensureNotFailed(InternalTransaction.java:189)
    at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:158)
    at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:132)
    at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:138)
    at org.neo4j.driver.v1.StatementRunner$run.call(Unknown Source)
    at tx-bug.run(tx-bug.groovy:20)
Ich:neo-test mh$ ~/Downloads/groovy-2.3.7/bin/groovy tx-bug3.groovy 
Invalid input 'o': expected 'r/R' (line 1, column 3 (offset: 2))
"foo"
   ^
1
Ich:neo-test mh$ ~/Downloads/groovy-2.3.7/bin/groovy tx-bug3.groovy 
Invalid input 'o': expected 'r/R' (line 1, column 3 (offset: 2))
"foo"
   ^
1
Ich:neo-test mh$ ~/Downloads/groovy-2.3.7/bin/groovy tx-bug2.groovy 
Invalid input 'o': expected 'r/R' (line 1, column 3 (offset: 2))
"foo"
   ^
1
```

**Comment by sherfert** [comment] 2017-10-04 12:50
@inserpio @jexp Has this been moved to the JDBC issue list?

**Comment by inserpio** [comment] 2017-10-04 15:34
Hi @sherfert, no. We haven't opened it on the other repo, but it should be solved from the jdbc side.
Are you still experiencing the issue?

**Comment by inserpio** [comment] 2017-10-04 15:35
We just forgot to close this one...

**Comment by craigtaverner** [comment] 2017-10-04 15:37
Thanks @inserpio

**Closed as completed by craigtaverner** 2017-10-04 15:37 UTC
Labels: cypher, question
