### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13185] opened 2023-05-12 01:48 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Community
operating system: windows 10
API：Cypher version 9
query:unwind [p=(c{k:1})-[]->()|p] as c create ({k:exists{return max(length(c))}}) return 1 
error message:
Neo.DatabaseError.Statement.ExecutionFailed
A bug has occurred in the slotted runtime: The target slotted execution context cannot hold the data to copy
From : SlotConfiguration1972514466(longs=1, refs=4, discarded=0,1,2, markedDiscarded=0,1,2, slots=HashMap(VariableSlotKey(  c@4) -> RefSlot(1,false,Any), VariableSlotKey(  UNNAMED6) -> RefSlot(0,false,List<Any>), VariableSlotKey(1) -> RefSlot(3,true,Any), VariableSlotKey(  UNNAMED2) -> LongSlot(0,false,Node), VariableSlotKey(  UNNAMED7) -> RefSlot(2,false,Boolean)))
To :   SlotConfiguration1099173514(longs=0, refs=3, discarded=, markedDiscarded=, slots=HashMap(VariableSlotKey(  c@4) -> RefSlot(1,false,Any), VariableSlotKey(  UNNAMED6) -> RefSlot(0,false,List<Any>), VariableSlotKey(max(length(c))) -> RefSlot(2,true,Any)))

Expected behavior:
The query should run successfully or at least it should not give such confusing error message.

Actual behavior:
The query failed.

**Comment by ncordon** [comment] 2023-05-12 09:12
Hey @ljhhuxiaoba! Thanks for reporting 😄 

Unfortunately I am unable to reproduce with an OSX operating system, but we'll try to reproduce on a Windows machine and keep you posted on progress solving this.

**Comment by JonasHolgersson** [comment] 2023-06-01 09:05
@ljhhuxiaoba Thanks again for reporting, this has been fixed and will be included in the 5.9 release.

**Closed as completed by JonasHolgersson** 2023-06-01 09:05 UTC
Labels: bug, team-cypher
