### ISSUE TITLE
Unable to install as a service under windows 7

### ISSUE THREAD

**Issue by mijujoel** [neo4j/neo4j#597] opened 2013-03-07 16:50 UTC
Here's the command in "Services" under Windows:

C:\Program Files (x86)\Java\jre\bin\java.exe -Djava.util.logging.config.file=conf\windows-wrapper-logging.properties -DworkingDir=C:\NEO4J-~1.M05\bin.. -DconfigFile=conf\neo4j-wrapper.conf -DserverClasspath=lib/_.jar;system/lib/_.jar;plugins/_.jar;system/coordinator/lib/_.jar;./conf\* -DserverMainClass=org.neo4j.server.Bootstrapper -Dorg.neo4j.cluster.logdirectory=C:\NEO4J-~1.M05\bin..\data\log -jar C:\NEO4J-~1.M05\bin\windows-service-wrapper-*.jar Neo4j-Server

The Neo4J directory is not correct in this command - ~1.M05 - I was trying to install 1.9.M05.  I changed the directory name since I couldn't find a config file that let me set the directory.  Neo4J_Home and Java_Home seem to be okay.  I have a 64-bit OS and both 32-bit and 64-bit java are installed, but I set Java_Home to the 32-bit version and listed the 32-bit version first in my Path.  The service installs but says it can't start in a timely manner.  Any suggestions?

**Comment by chrisvest** [comment] 2017-06-22 12:14
This is a duplicate of an already closed issue.

**Closed by chrisvest** 2017-06-22 12:14 UTC
Labels: bug, operability
