### ISSUE TITLE
Possible bug: EntityNotFound exception

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6823] opened 2016-03-31 01:25 UTC
My program runs many Cypher queries of the form "MATCH (root)-[:body]->(b) WHERE ID(root) = XXXXXX DETACH DELETE b", for varying values of XXXXXX. This query should either delete the b node (if it exists), or do nothing (if either the root node, the relationship, or the b node don't exist). However, when I switch the program to multithreaded mode, which involves running these queries plus a bunch of other types of queries in parallel, I sometimes get the exception:

Error: [{:code "Neo.ClientError.Statement.EntityNotFound", :message "Unable to load RELATIONSHIP with id XXXXXX."}]

When I force everything to be single-threaded, the errors go away. Unfortunately, I'm not sure how to reproduce this, as the behavior is multithreaded and nondeterministic, and at any given moment there are dozens of transactions going and I'm not sure which ones might conflict. Is there a type of logging within neo4j, or other tool, which might help me track this down? Thanks a lot.
- Neo4j version: 2.3.3 Enterprise
- Operating system: Ubuntu 15.10
- API/Driver: Neocons 3.1.0

**Comment by rationalism** [comment] 2016-03-31 01:56
OK, it looks like there's also another error occurring, although much less frequently. On the query:

MATCH (root)-[:body]->(b) WHERE ID(root) = 1169871 DETACH DELETE b

it returned:

https://gist.github.com/rationalism/200df6befa590d917433b3b5c0e366ee

**Comment by rationalism** [comment] 2016-04-02 08:16
OK! Took a little while, but I think I've succeeded in tracking this down. To reproduce:

 - Start with a blank database

 - Run CREATE CONSTRAINT ON (root:person_name) ASSERT root.val IS UNIQUE

 - Run CREATE (n:person) RETURN ID(n) ten times, and record the IDs (since it's a blank DB, in my case they're just 0 through 9)

 - For each of the ten IDs above, run MATCH (a) WHERE ID(a) = <ID HERE> MERGE (b:person_name {val:'Bob Smith'}) CREATE (a)-[r:name]->(b)

 - For each of the ten IDs, run a transaction with the two queries:

MATCH (root)-[:name]->(b:person_name) WHERE ID(root) = <ID HERE> DETACH DELETE b

MATCH (a) WHERE ID(a) = <ID HERE> MERGE (b:person_name {val: 'Bob Smith'}) CREATE (a)-[r:name]->(b)

Run all of these transactions in parallel, each on a separate thread. You should get a bunch of error messages of the form:

Transaction failed and rolled back. Error: [{:code "Neo.ClientError.Statement.EntityNotFound", :message "Unable to load RELATIONSHIP with id 9."}]

I'm not sure how to run parallel transactions in Java, but in Clojure I do:

(defn bug-query [id]
  (cypher-combined-tx 
    [(str "MATCH (root)-[:name]->(b:person_name) WHERE ID(root) = " id " DETACH DELETE b")
     (str "MATCH (a) WHERE ID(a) = " id " MERGE (b:person_name {val: 'Bob Smith'}) CREATE (a)-[r:name]->(b)")]))

(->> (range 10) (pmap bug-query) dorun)

where pmap = parallel map, meaning each function call is run on its own thread. If I instead run:

(->> (range 10) (map bug-query) dorun)

which removes the parallelism, everything runs perfectly and the graph is unchanged (as expected).

**Comment by rationalism** [comment] 2016-04-02 08:38
OK! Took a little while, but I think I've succeeded in tracking this down. To reproduce:
- Start with a blank database
- Run CREATE CONSTRAINT ON (root:person_name) ASSERT root.val IS UNIQUE
- Run CREATE (n:person) RETURN ID(n) ten times, and record the IDs (since it's a blank DB, in my case they're just 0 through 9)
- For each of the ten IDs above, run MATCH (a) WHERE ID(a) = (ID HERE) MERGE (b:person_name {val:'Bob Smith'}) CREATE (a)-[r:name]->(b)
- For each of the ten IDs, run a transaction with the two queries:

MATCH (root)-[:name]->(b:person_name) WHERE ID(root) = (ID HERE) DETACH DELETE b

MATCH (a) WHERE ID(a) = (ID HERE) MERGE (b:person_name {val: 'Bob Smith'}) CREATE (a)-[r:name]->(b)

Run all of these transactions in parallel at the same time, each on a separate thread. You should get a bunch of error messages of the form:

Transaction failed and rolled back. Error: [{:code "Neo.ClientError.Statement.EntityNotFound", :message "Unable to load RELATIONSHIP with id 9."}]

I'm not sure how to run parallel transactions in Java, but in Clojure I do:

(->> (range 10) (pmap bug-query) dorun)

(definition of the bug-query function at https://gist.github.com/rationalism/14ee4f0aa341c22e25f416a1fa783646)

where pmap = parallel map, meaning each function call is run on its own thread. If I instead run:

(->> (range 10) (map bug-query) dorun)

which removes the parallelism, everything runs smoothly and the graph is unchanged. I'm actually not sure if that itself counts as a bug - if the transactions run serially, should we expect that the Bob Smith node is deleted every time and only one relationship is re-created (since all of them are deleted in each transaction)?

**Comment by rationalism** [comment] 2016-04-02 08:47
Potentially related issues?

http://stackoverflow.com/questions/27380491/neo-clienterror-statement-entitynotfound-when-deleting-and-then-creating-nodes-i

http://stackoverflow.com/questions/33628993/how-to-fix-random-npe-and-neo-clienterror-statement-entitynotfound-when-doing

https://jira.spring.io/browse/DATAGRAPH-785

**Comment by tkroman** [comment] 2016-04-02 12:57
I can reproduce this exactly like described, too:

```
    @Test
    public void name() throws Exception {
        try (Transaction tx = db().beginTx()) {
            db().execute("CREATE CONSTRAINT ON (root:person_name) ASSERT root.val IS UNIQUE");
            tx.success();
        }

        List<Long> ids;
        try (Transaction tx = db().beginTx()) {
            ids = LongStream.range(0, 10).boxed()
                    .map(id -> db().execute("CREATE (n:person) RETURN ID(n) as id").<Long>columnAs("id").next())
                    .collect(toList());
            tx.success();
        }

        try (Transaction tx = db().beginTx()) {
            for (long id : ids) {
                db().execute("MATCH (a) WHERE ID(a) = " + id + " MERGE (b:person_name {val:'Bob Smith'}) CREATE (a)-[r:name]->(b)");
            }
            tx.success();
        }

        ids.parallelStream().forEach(id -> {
            try (Transaction tx = db().beginTx()) {
                db().execute("MATCH (root)-[:name]->(b:person_name) WHERE ID(root) = " + id + " DETACH DELETE b");
                db().execute("MATCH (a) WHERE ID(a) = " + id + " MERGE (b:person_name {val: 'Bob Smith'}) CREATE (a)-[r:name]->(b)");
                tx.success();
            }
        });
    }
```

I believe this is due to the fact that the pipe is constructed in a from-inside-out fashion (starting at DefaultExecutionResultBuilderFactory.scala:94), which leads to (non-locking) reads from first from the e.g. `NodeByLabelScanPipe`, which binds variables to actual nodes (proxies with established ids). 
Then it doesn't matter if we lock during the deletion or not since reads were concurrent and each thread got its node/relationship. 
I imagine the solution would be something based on the query type (the one derived from `PipeInfo`) and deriving the necessity of early lock acquisition depending on is the type R or RW or W or whatever else. 
This will certainly affect the performance, though, so the less performance-harmful fix would be obviously to ignore exceptions like this one in relevant pipes.

**Comment by tkroman** [comment] 2016-04-09 01:44
Wow, I just found out that this issue is (kind of) known since 2012! I'm talking about #37

**Comment by rationalism** [comment] 2016-06-02 06:42
Happy to report that this looks fixed in 3.0.1, at least for the Java driver. The above code no longer works as-is, because a separate session is now required for each parallel transaction. But once separate sessions are added, it works fine, with no weird errors or glitches or race conditions. 

Not sure if I should close this out, is 2.3.x still officially supported?

**Comment by spacecowboy** [comment] 2016-06-02 08:01
Yes, it is supported.

**Comment by Sahasrara** [comment] 2016-06-02 17:07
Can somebody confirm this is fixed in the latest version of neo?

**Comment by spacecowboy** [comment] 2016-06-03 07:51
It is not. As #37 describes, this is not a bug, it is a consequence of the underlying design of Neo4j. In multi-threaded scenarios you can run into this, and so you must plan for getting failed transactions (so retry on failure).

**Comment by chrisvest** [comment] 2018-05-08 13:06
Closing this because the specific error condition was fixed, even though the isolation level remain the same. A stronger isolation level can be reached with the experimental flag `unsupported.dbms.query.snapshot=true`. We'll close #37 once we have a productised and fully supported stronger isolation level.

**Closed as completed by chrisvest** 2018-05-08 13:06 UTC
Labels: enhancement, team-kernel

**Comment by elR1co** [comment] 2020-03-06 14:21
Hello.
Do you have an idea when the fully supported stronger isolation level is expected ?
Thanks.
