### ISSUE TITLE
Move org.neo4j.test.Digests so dependency on test-jar is no longer needed

### ISSUE THREAD

**Issue by diversit** [neo4j/neo4j#8523] opened 2016-12-19 10:16 UTC
Neo4j version: <= 3.1.0

When testing with Neo4j by using Neo4j's test harness, it is needed to include a dependency on the org.neo4j:neo4j-io test-jar because the AbstractInProcessServerBuilder depends on org.neo4j.test.Digests which is a neo4j-io test class.

As a developer,
I would like the Digest class to be moved so it is no longer a test class, or copied into the test harness project,
So the test harness is no longer depending on a test class from another project
And test-time ClassNotFound exceptions no longer occur since it is not very logical to have to include a test-jar from neo4j-io to be able to run tests.

### Steps to reproduce
1. Create a project including the Neo4j test harness dependency (do not include dependencies on test-jars)
2. Create a test using Neo4j test harness
3. Run the test

### Expected behavior
The test should run normally

### Actual behavior
ClassNotFoundException : org.neo4j.test.Digests

**Comment by spacecowboy** [comment] 2016-12-19 10:49
Thanks for the input. We'll look into improving this.

To be clear, I am interpreting your first line to mean this is a regression in 3.1.0 and it worked before, correct?

**Comment by spacecowboy** [comment] 2016-12-19 10:56
This issue seems surprising because when reviewing the pomfile: 
<https://github.com/neo4j/neo4j/blob/3.2/community/neo4j-harness/pom.xml#L89>

the dependence to `neo4j-io`'s test-jar was added in 2014 during the early 2.x development. It also has several other neo4j test dependencies.

You wouldn't happen to have conflicting versions on your dependencies by any chance?

**Comment by diversit** [comment] 2016-12-19 10:59
Thanks.
No, as far as I understand this issue exists in Neo4j 3.1.0 and all earlier versions.

We're using Neo4j in a Scala/Sbt project. Maybe Sbt is not resolving the test-jar dependencies?
But anyway, having a project pulling in test-jar from other projects is not very nice. If a class is needed in a non-test environment, that class should also not be a test-class, right?

**Comment by spacecowboy** [comment] 2016-12-19 13:04
I can see your point, with the caveat that the test harness is designed for testing, so depending on a test-jar doesn't sound that problematic.

**Comment by chrisvest** [comment] 2016-12-19 13:08
Maven (and tools built on it) does not transitively resolve test-jar dependencies, so you have to add your own dependency to them. `Digests` is in `neo4j-io` because the tests in that module needs it. It is in the test sources because we only use it as part of our test infrastructure. What we could look into is making `neo4j-harness` work without needing that test-jar. It looks like it only has a single use of the `Digests` class from the `neo4j-io` test-jar.

**Comment by chrisvest** [comment] 2018-05-23 12:59
We no longer have the `org.neo4j.test.Digests`, so I'm closing this. We use Apache Commons Codecs instead.

**Closed as completed by chrisvest** 2018-05-23 12:59 UTC
Labels: enhancement
