### ISSUE TITLE
Bolt erroneously accepts unencrypted connection

### ISSUE THREAD

**Issue by mcolburn** [neo4j/neo4j#10475] opened 2017-11-17 15:58 UTC
**Neo4j Version:** 3.3 (Community)
**Operating System:** Ubuntu 16.04 

### Goal
To confirm that the neo4j database instance is correctly configured to reject bolt connections that are not encrypted.  In this case, neo4j is running in the cloud on a server, and a local workstation is being used to connect via bolt using cypher-shell.

### Steps to reproduce
1. On the server, edit neo4j.conf by setting `dbms.connector.bolt.tls_level=REQUIRED`
2. Start neo4j and confirm that the log shows the tls_level = REQUIRED
2. On another different machine, cd to the neo4j bin directory.
3. `./neo4j cypher-shell -a hostname --encryption false` (where hostname is the IP address or domain name of the server that hosts the neo4j database)
4. Enter username and password

### Expected behavior
The neo4j server should reject the cypher-shell connection since it was invoked with the --encryption false parameter, which is in conflict with the `dbms.connector.bolt.tls_level=REQUIRED` setting in the neo4j.conf.

### Actual behavior
The neo4j server erroneously accepts the cypher-shell connection.

**Comment by technige** [comment] 2018-02-19 10:59
Thanks @mcolburn we'll have a look at this and try to recreate it.

**Comment by ali-ince** [comment] 2018-02-22 16:04
Hi @mcolburn,

We were unable to reproduce the behavior you described with any of the `3.3.0`, `3.3.1` and `3.3.3` versions.

What we get when we invoke `bin/cypher-shell -a <IP Address> --encryption false` is the error `Connection terminated while receiving data. This can happen due to network instabilities, or due to restarts of the database. Expected 4 bytes, received none.`. We get asked for username & password only if either we did not specify `--encryption` option or we set it explicitly by `--encryption true`.

If this is still reproducable on your side, could you please send us your neo4j.conf file and your exact neo4j version including its patch level?

Thanks.

**Comment by mcolburn** [comment] 2018-02-23 17:26
I believe you can close this.  I suspect the problem was that I have multiple Neo4j instances on cloud services and apparently I was connecting to one that had  dbms.connector.bolt.tls_level=OPTIONAL. Sorry to trouble you.

**Comment by ali-ince** [comment] 2018-02-23 21:14
No worries @mcolburn, closing the issue.

**Closed as completed by ali-ince** 2018-02-23 21:14 UTC
Labels: team-drivers
