### ISSUE TITLE
Cypher: OR index lookups should work

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#861] opened 2013-06-06 22:09 UTC
You guys might already be working on this, but this is a somewhat common use case that was easy with the old index syntax, and entirely too inefficient with the new indexes. Index hinting on this type of query returns an error, and the query without an index hint does a label scan for horrid performance.

Query:
match a:Crew using index a:Crew(name) 
where a.name="Neo" or a.name="Cypher" 
return a;
Error: org.neo4j.cypher.IndexHintException: Can't use an index hint without an equality comparison on the correct node property label combo.
Label: `Crew`
Property name: `name`

**Comment by zmarty** [comment] 2016-11-15 18:36
Is there any progress on this issue?

It is **astounding** that Neo4j still cannot do simple queries that use two indices at the same time such as WHERE x.field1 = 'A' OR x.field2='B' after several years.

**Comment by systay** [comment] 2016-11-16 09:17
@zmarty That feature has been implemented: https://github.com/neo4j/neo4j/pull/8214

It will make it into the Neo4j 3.2 release

**Comment by zmarty** [comment] 2017-05-11 18:06
neo4j 3.2 is out. If this is really really fixed please close this item.

**Comment by zmarty** [comment] 2017-05-19 18:09
I can confirm this works for our use case as of neo4j 3.2. The query below used to take 1700ms, now it takes less than 1ms. All fields below have indexes on them.

PROFILE MATCH (person:Person)
WHERE 
(person.firstNameLower = "tom brady"
OR person.middleNameLower = "tom brady"
OR person.lastNameLower = "tom brady"
OR person.fullNameLower = "tom brady"
OR person.fullNameNoMiddleNameLower = "tom brady")
RETURN distinct person
ORDER BY person.staticRankScore DESC
LIMIT 60

**Comment by craigtaverner** [comment] 2017-05-19 20:49
Thanks @zmarty for confirming this works on your data with your query. Fantastic that you experienced such a huge performance improvement.

**Closed by craigtaverner** 2017-05-19 20:49 UTC
Labels: cypher, feature

**Comment by zmarty** [comment] 2017-05-22 21:18
@craigtaverner I unfortunately found some sort of regression with the OR operator. I don't know enough about the query planner to tell if it's related to this change or not.

Here is a query that works correctly in 3.0.6:

```
MATCH (u2:User)-[:HAS_SCOREBOARD]->(s2:UserScoreboard) 
WHERE ((s2.triviaGameMonthlyRank >= 1 AND s2.triviaGameMonthlyRank <= 5) OR (s2.triviaGameMonthlyRank >= 10 AND s2.triviaGameMonthlyRank <= 12))
RETURN u2 AS User, s2 AS Standing
ORDER BY s2.triviaGameMonthlyRank
```

Notice it has a **WHERE ((X AND Y) **OR** (A AND B))**

This does not work anymore in 3.2 and fails with: Neo.DatabaseError.Statement.ExecutionFailed Expected [...] Instead, got: [...]

It only works if I remove one of the branches of the OR (which obviously I don't want to do):

```
MATCH (u2:User)-[:HAS_SCOREBOARD]->(s2:UserScoreboard) 
WHERE (s2.triviaGameMonthlyRank >= 1 AND s2.triviaGameMonthlyRank <= 5)
RETURN u2 AS User, s2 AS Standing
ORDER BY s2.triviaGameMonthlyRank
```

**Comment by craigtaverner** [comment] 2017-05-25 21:08
@zmarty It looks like what is specific about your query that is not being handled well is the existence of inequality predicates. We have tests that work well with `WHERE ((X AND Y) OR (A AND B))` when all the predicates are equality predicates, but when inequalities are involved, it fails. We are looking into this. Thanks for reporting it.

**Comment by systay** [comment] 2017-05-29 09:31
FYI - This should solve the problems: https://github.com/neo4j/neo4j/pull/9438
