### ISSUE TITLE
Neo4j 2.2 Cypher - Poor query performance with multiple OPTIONAL MATCH statements

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#4402] opened 2015-04-09 19:26 UTC
I'm running into an issue with quickly degrading performance on queries that use multiple OPTIONAL MATCH statements, especially with the COST planner.

If the query only has a single OPTIONAL MATCH statement, the query planner creates an appropriate `OptionalExpand(All)` query term.  However, when multiple OPTIONAL MATCH statements are used the query planner starts creating `NodeByLabelScan` query terms with large parallel branches that then get merged.  I would have expected that the multiple OPTIONAL MATCH statement query would have looked more similar to the single OPTIONAL MATCH query with just multiple `OptionalExpand(All)` terms.

I believe that this issue exists in previous versions of Neo4j as well, but I'm only noticing it now as my database grows in size (30k nodes and 100k relationships, not even that large).  Queries that used to take 100ms are now taking 2+ minutes to complete.

The following query concerns 670 contacts that are associated with approximately 1800 phone, address, tag, and invite nodes.  I'm trying to create a query that will return the contacts along with the associated nodes if any exist.

**Example 1:  Query with a single OPTIONAL MATCH STATEMENT**

```
  PROFILE
  MATCH (:user { id:"foobar" })-[:CONTACT]->(uc:contact)-[:CONTACT]->(ur:role)
  WHERE HAS(ur.teamid)
  WITH uc, ur

  MATCH (c:contact {teamid: uc.teamid})
  WITH DISTINCT c, {accessedby: uc.id, accessedrole: ur.name} AS r

  OPTIONAL MATCH (c)-[:TAG]->(t:tag)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: r.isinvited,
    tags: EXTRACT(x IN COLLECT(t) | {id: x.id, object: x.object, name: x.name})
    } AS r

  RETURN c, r LIMIT 10
```

**Result:** Cypher version: CYPHER 2.2, planner: COST. 8364 total db hits in 70 ms.
Full plan available at http://i.imgur.com/QAPvO39.png.

**Example 2:  Query with a multiple OPTIONAL MATCH STATEMENTs**

```
  PROFILE
  MATCH (:user { id:"foobar" })-[:CONTACT]->(uc:contact)-[:CONTACT]->(ur:role)
  WHERE HAS(ur.teamid)
  WITH uc, ur

  MATCH (c:contact {teamid: uc.teamid})
  WITH DISTINCT c, {accessedby: uc.id, accessedrole: ur.name} AS r

  OPTIONAL MATCH (c)-[:INVITE]->(i:invite)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: NOT i IS NULL
    } AS r

  OPTIONAL MATCH (c)-[:PHONE]->(p:phone)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: r.isinvited,
    phones: EXTRACT(x IN COLLECT(p) | { id: x.id, object: x.object })
    } AS r

  OPTIONAL MATCH (c)-[:ADDRESS]->(a:address)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: r.isinvited, phones: r.phones,
    addresses: EXTRACT(x IN COLLECT(a) | { id: x.id, object: x.object, street: x.street, locality: x.locality,
        region: x.region, postcode: x.postcode, country: x.country, description: x.description, neighborhood: x.neighborhood, latlnglocation: x.latlnglocation
      })
    } AS r

  OPTIONAL MATCH (c)-[:TAG]->(t:tag)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: r.isinvited, phones: r.phones, addresses: r.addresses,
    tags: EXTRACT(x IN COLLECT(t) | {id: x.id, object: x.object, name: x.name})
    } AS r

  RETURN c, r LIMIT 10
```

**Result:** Cypher version: CYPHER 2.2, planner: RULE. 99988 total db hits in 731 ms.
Full expanded query plan available at http://i.imgur.com/dvvEt48.png.

**Result:** Cypher version: CYPHER 2.2, planner: COST. 5620191 total db hits in 4821 ms.
Full expanded query plan available at http://i.imgur.com/L0nAJlB.png.

**Comment by jexp** [comment] 2015-04-10 23:01
_Try to use more descriptive variable/identifier names_

I think the biggest problem is that your are creating cross products.

Make sure your have an index on `:contact(teamid)` so that can be used instead of a label scan.

Also you check for WHERE HAS(ur.teamid) but then use uc.teamid for the lookup which seems wrong to me.

If you don't get the cardinalities down each optional match adds a new cartesian product.

```
 PROFILE
  MATCH (:user { id:"foobar" })-[:CONTACT]->(uc:contact)-[:CONTACT]->(ur:role)
  WHERE HAS(uc.teamid)
  WITH uc, collect(ur.name) as accessedroles
  // todo index on :contact(teamid)
  MATCH (c:contact {teamid: uc.teamid}) 
   // get cardinality down
  WITH c, collect({accessedby: uc.id, accessedroles: accessedroles}) AS access
  OPTIONAL MATCH (c)-[:TAG]->(t:tag)
  // get cardinalitiy down again
  RETURN c, access, COLLECT({id: t.id, object: t.object, name: t.name}) as tags
  LIMIT 10
```

**Comment by jexp** [comment] 2015-04-10 23:01
Btw. GitHub is uses for bug tracking. Please direct performance discussion to StackOverflow or the Google Group. Thanks a lot

**Comment by bunkat** [comment] 2015-04-11 04:25
Nobody in the Google Group or StackOverflow can help because the query planner is not working as intended for OPTIONAL MATCH statements.  For example, adding in one additional OPTIONAL MATCH (that doesn't even match anything) can cause a query to require 100x the database accesses.  Adding in a single OPTIONAL MATCH in an otherwise performant query can cause a 10x slowdown (see https://groups.google.com/forum/#!topic/neo4j/eR2wYaMLFL8).  I've had discussions with a few more experienced Neo4j users and they agree that the results I'm seeing are unexpected.

Cardinality is not the problem. I've spent the last couple of days eliminating all use of OPTIONAL MATCH but keeping the same query structure (store results in a MAP to reduce cardinality).  If my structure was causing a problem and OPTIONAL MATCH statements worked similar to MATCH statements then I should still see similar results.  Instead I'm able to get 10x to 100x better performance.

Bugs:
- OPTIONAL MATCH statements generate NodeByLabelScan queries that touch the entire database.  An OPTIONAL MATCH rooted at a node should never touch the entire database. I'm trying to express `return any connected nodes if they exist, if not, that's okay continue with the query` and not `please look for anything in my database that looks sort of like this`.  I think this is where the primary confusion is.
- NodeByLabelScan queries as part of OPTIONAL MATCH statements produce nonsensical PROFILE results.  A NodeByLabelScan query for a node label with 1000 total nodes will produce a PROFILE result of 500,000 database hits.
- PROFILE view displays NaN for OPTIONAL MATCH statements that did not have any matches, but yet still required hundreds of thousands of database hits to determine.
- PROFILE view displays estimated rows that make no sense with values in the quintillions for a database with 30k nodes.
- OPTIONAL MATCH statements often do not use indexes correctly even when they exist.  USE INDEX does not work with OPTIONAL MATCH statements in order to provide hints to Neo4j.  I do have an index on :contact(teamid) and it does nothing.

I understand I'm not on a support contract and am not asking for somebody here to fix my problems for me.  I just thought you might want to know that the query planner is not working correctly in a bunch of different scenarios.  You're obviously free to do whatever you want with these reports.

**Comment by boggle** [comment] 2015-04-11 10:22
Thank you for reporting these issues. This is very helpful; we will investigate them immediately.

In the mean time, you might want to consider prefixing queries that suffer from these issues with "PLANNER RULE" to use the old query planner.  Alternatively, you could try to force treating the optional match separately by separating it with "UNWIND [1] AS ignored". This is of course only a temporary workaround.

Regarding estimated rows: Cardinality estimation is difficult; these numbers are allowed to be off by multiple orders of magnitude in various situations as that usually still leads to the right plans (even if not in this case).

**Comment by jexp** [comment] 2015-04-11 10:26
What you could also try is to use a pattern expression as a workaround:

Instead of:

```
OPTIONAL MATCH (c)-[:TAG]->(t:tag)
```

use:

```
WITH c, [p in (c)-[:TAG]->(:tag) | last(nodes(p))] as tags
```

E.g. 

```
explain
  MATCH (:user { id:"foobar" })-[:CONTACT]->(c:contact)
  OPTIONAL MATCH (c)-[:TAG]->(t:tag)
  return c, EXTRACT(x IN COLLECT(t) | {id: x.id, object: x.object, name: x.name}) as tags
```

![plan 10](https://cloud.githubusercontent.com/assets/67427/7101104/a686d838-e046-11e4-909a-b2306f8f2421.png)

becomes:

```
explain
  MATCH (:user { id:"foobar" })-[:CONTACT]->(c:contact)
  with c, [p in (c)-[:TAG]->(:tag) | last(nodes(p))] as tags
return c, [x in tags| {id: x.id, object: x.object, name: x.name}] as tag
```

![plan 11](https://cloud.githubusercontent.com/assets/67427/7101117/6b74eedc-e047-11e4-9621-ac47efcf06a2.png)

**Comment by neemah** [comment] 2015-04-13 17:36
We also use a lot of OPTIONAL MATCH in queries, and with upgrade to 2.2 such queries result in Java Heap Space (as of 2.1.7 there was no exceptions and was much faster).

This is +1 for initial message.

**Comment by davidegrohmann** [comment] 2015-04-17 13:57
Hi @bunkat,

thanks a lot for pointing out this bug, we are gonna fix it soon.

I can suggest the following workaround until the bug is fixed:

```
PROFILE
  MATCH (:user { id:"foobar" })-[:CONTACT]->(uc:contact)-[:CONTACT]->(ur:role)
  WHERE HAS(ur.teamid)
  WITH uc, ur SKIP 0

  MATCH (c:contact {teamid: uc.teamid})
  WITH DISTINCT c, {accessedby: uc.id, accessedrole: ur.name} AS r

  OPTIONAL MATCH (c)-[:TAG]->(t:tag)
  WITH c, {
    accessedrole: r.accessedrole, accessedby: r.accessedby,
    isinvited: r.isinvited,
    tags: EXTRACT(x IN COLLECT(t) | {id: x.id, object: x.object, name: x.name})
    } AS r

  RETURN c, r LIMIT 10
```

Please note the `SKIP 0` on the first `WITH` clause.

I hope this is helpful.

Cheers,
Davide

**Comment by bunkat** [comment] 2015-04-17 18:17
Thanks David.  What does the SKIP 0 indicate to the planner?  How does that help the issue with OPTIONAL MATCH statements?

**Comment by boggle** [comment] 2015-04-17 19:49
@bunkat this is a workaround that forces building an Apply-based plan which then does not suffer from the bug you found.  You should only use this to circumvent this problem for the time being and remove it again from your queries as soon as there's a fix and you've upgraded your installation.

**Comment by ghost** [comment] 2015-10-30 10:33
What is the current status of this issue? Our team is also experiencing performance problems related to the use of OPTIONAL MATCH.

**Comment by jexp** [comment] 2015-10-31 11:38
Can you try to reproduce it with 2.3.0? Or 2.2.6?

**Comment by panthershark** [comment] 2015-11-03 17:10
I can reproduce this on 2.3.0.  Here are my queries:

This one is fast: ~100ms

```
MATCH
  (:person)<-[created_date:CREATED_BY]-(d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
WHERE g.key in ['uuid1','uuid2','uuid3']
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

This one ends up on constant GC and does not return for a couple hundred seconds b/c the query plan shows that a NodeByLabelScan of `:person` which seems to be the culprit.  

```
MATCH
  (d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
OPTIONAL MATCH (:person)<-[created_date:CREATED_BY]-(d)
WHERE g.key in ['uuid1','uuid2','uuid3']
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

Notice that the only difference between these queries is that the `CREATED_BY` edge is moved to OPTIONAL MATCH in the 2nd one.

**graph.db** is 1G on disk 

```
$ du -hs /usr/local/Cellar/neo4j/2.3.0/libexec/data/graph.db/
1.0G    /usr/local/Cellar/neo4j/2.3.0/libexec/data/graph.db/
```

**Memory settings are**
`dbms.pagecache.memory=6g`
`wrapper.java.initmemory=8192`
`wrapper.java.maxmemory=8192`

**Comment by jexp** [comment] 2015-11-03 17:42
Please move your where statement after the match

Otherwise you match all possible paths and only filter all of them after the optional match

**Comment by panthershark** [comment] 2015-11-03 19:36
@jexp - Thanks.  I just tried both above queries on 2.2.6 with the same data and they both come back in 50ms-80ms.  Could 2.3.0 have a regression in it?

**Comment by jexp** [comment] 2015-11-03 19:43
@tommymessbauer 
Do you have an index on `:user_group(key)` ?
Can you share the query plan in both versions ? (i.e. prefix your query with `PROFILE`) 

Did you try it with this one?

```
MATCH
  (d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
WHERE g.key in ['uuid1','uuid2','uuid3']
OPTIONAL MATCH (:person)<-[created_date:CREATED_BY]-(d)
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

**Comment by panthershark** [comment] 2016-01-18 05:11
Sorry for delay on this.  I needed to finish pushing a project to production before I could get back to this.  We were able to go live with Neo4J 2.2.6, but I want to upgrade.  I kept the data set that was being slow untouched so I could come back to it.  

It looks like the query planner simply does not try to optimize the order of operations.. which makes sense b/c changing the order could change the results.  It is weird that 2.2.6 did not seem to have this issue.

I attached the queries and the query plans below and it looks obvious that the problem is that the slow query plan is executing the OPTIONAL MATCH before the WHERE clause which degenerates into a much larger query.  

As you suggested, moving WHERE above OPTIONAL MATCH chose the more optimal query plan.

## No Optional Match

```
MATCH
  (:person)<-[created_date:CREATED_BY]-(d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
WHERE g.key in ['uuid1','uuid2','uuid3']
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

![query_plan_no_optional_match](https://cloud.githubusercontent.com/assets/1046102/12379842/4a4ed6d2-bd28-11e5-9595-48ed1c0fc10c.png)

## WITH OPTIONAL MATCH ABOVE THE WHERE

```
MATCH
  (d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
OPTIONAL MATCH (:person)<-[created_date:CREATED_BY]-(d)
WHERE g.key in ['uuid1','uuid2','uuid3']
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

![query_plan_with_optional_match_before_where_clause](https://cloud.githubusercontent.com/assets/1046102/12379952/5332249a-bd2b-11e5-8ec8-aa56044317cd.png)

## WITH OPTIONAL MATCH BELOW WHERE

```
MATCH
  (d:document)<-[:PERMISSION_GRANTED {read:true}]-(g:user_group)
WHERE g.key in ['uuid1','uuid2','uuid3']
OPTIONAL MATCH (:person)<-[created_date:CREATED_BY]-(d)
RETURN d.key
ORDER BY created_date.date DESC
SKIP 0 LIMIT 10
```

![query_plan_optional_match_after_where_clause](https://cloud.githubusercontent.com/assets/1046102/12379852/a0ef93d2-bd28-11e5-8f66-6a4a232e4542.png)

**Comment by diversit** [comment] 2016-11-24 07:48
Is this issue still not solved? I have read in multiple comments people were going to look at this.
We have this same issue with Neo4j 3.0.6 where the result set 'explodes' after a second Optional Match.

**Comment by bunkat** [comment] 2016-11-24 09:17
What I've learned is to pretty much never use OPTIONAL MATCH, it doesn't seem to do what everyone thinks it does.  I always thought it meant 'try to match this path, if not, that's cool just continue' when really it means 'match everything you possibly can that looks sort of like this thing'. That's where they explosion comes from.

If you want to the former type of query, then this works better:

```
MATCH (t:Team {id: "123"})-[:CONTAINS]->(p:Project)
WITH t, p
  HEAD([x IN (p)-[:CREATED]->(:Activity) | LAST(NODES(x))]) AS create,
  HEAD([x IN (p)-[:EDITED]->(:Activity) | LAST(NODES(x))]) AS edit
```

This query gets a team node and all of the contained projects. It also optionally gets the create and edit activities associated with each project if they exist, but if they don't exist that's okay.  Doing things like this with OPTIONAL MATCH results in queries that run for 100's of milliseconds in the simplest of cases.  Doing it this way instead often returns for me in under 10ms.  In fact, I have queries that fetch 10's of optional nodes like this that are still able to return in under 10ms.

**Comment by jexp** [comment] 2016-12-02 23:23
OPTIONAL MATCH is the equivalent of LEFT/RIGHT OUTER JOIN, that's what it it documented and advertised for

In 3.1(RC1) you can actually use pattern comprehensions for this, which are really nice.

```
MATCH (t:Team {id: "123"})-[:CONTAINS]->(p:Project)
WITH t, p
  [(p)-[:CREATED]->(created:Activity) | created][0] AS create,
  [(p)-[:EDITED]->(edited:Activity) | edited][0] AS edit
```
Or better as map

```
MATCH (t:Team {id: "123"})-[:CONTAINS]->(p:Project)
WITH t, p { .*, create: [(p)-[:CREATED]->(c) | c ], edit:[(p)-[:EDITED]->(e) | e] }
```

**Comment by bunkat** [comment] 2016-12-02 23:45
I think you should have called it MATCH OUTER JOIN instead of MATCH OPTIONAL.  OPTIONAL is seen as an adjective on MATCH and not a noun specifying the type of query.

Do you expect there to be any performance difference between any of the new methods available in 3.1 RC1?  Or do they all compile down to roughly the same query?

**Comment by jexp** [comment] 2016-12-02 23:55
The problem that was reported here was that the planner wrongly did a label scan when encountering an optional match.

At least that's not happenign (for me) anymore.
@bunkat could you try that for me ? with RC1 ?

```

profile
match (m:Movie {title:"The Matrix"})
optional match (m)<-[:ACTED_IN]-(p:Person)
RETURN *
```

![plan 25](https://cloud.githubusercontent.com/assets/67427/20854288/d1ad9142-b8f2-11e6-8c61-5ec4caf16ea3.png)

this query, turns the pattern comprehensions into nested normal matches

```
MATCH (t:Team {id: "123"})-[:CONTAINS]->(p:Project)
WITH t, p { .*, create: [(p)-[:CREATED]->(c) | c ], edit:[(p)-[:EDITED]->(e) | e] }
```
![plan 26](https://cloud.githubusercontent.com/assets/67427/20854316/21b931e6-b8f3-11e6-9834-d4034ded710b.png)

**Comment by panthershark** [comment] 2016-12-03 15:29
My original issue was around the query planner. In 3.x, we've been better. Honestly, I'm not sure if 3.x fixed it or we rewrote the query with our OPTIONAL MATCH statements in different places.. Probably some of both.

**Comment by jexp** [comment] 2016-12-05 10:34
@bunkat your 2nd Example query from the first comment should world much better now, as you explicitely aggregate correctly at each step. (Just change `has`  to `exists`).

Would you by chance have an example dataset of yours that I could run this query on?

**Comment by bunkat** [comment] 2016-12-05 10:52
I provided a sample dataset to Neo4j last year along with sample queries of this type that I was told was going to be put into the test matrix.  I don't have a setup to generate a new one at the moment unfortunately.

I tried similar queries to the one that started this issue on 3.0 and did see improvement but saw even greater improvement by removing OPTIONAL MATCH statements completely.  Moving to the new pattern that I commented on led to a 10x improvement on 3.0 over using OPTIONAL MATCH with aggregations.  Execution times went from 250ms - 350ms on average to consistently under 25ms.  Plus I don't have to deal with all of that aggregation madness anymore :) At this point I have about 7500 lines of Cypher code and not a single OPTIONAL MATCH statement so it will be hard for me to test this out any further.

**Comment by jexp** [comment] 2016-12-05 11:14
Thanks a lot @bunkat I'll find it. 

As your pattern is something that's handled more nicely now with pattern comprehensions, you should benefit from those.
see: https://neo4j.com/blog/cypher-graphql-neo4j-3-1-preview/

**Comment by bunkat** [comment] 2016-12-05 11:21
I'll definitely take a look at the pattern comprehensions and see how they compare to what I'm doing currently.  Overall, I'm really impressed with 3.1.  Even doing things the 'old' way it is leaps and bounds above the performance I saw in 2.1.7 and 2.3.  My VM sitting on a single SSD, single CPU with 6GB of memory running 3.1 is now an order of magnitude faster than my production server that was running 2.1.7 18 months ago.  Kudos to the whole team!

**Comment by systay** [comment] 2016-12-05 12:22
FWIW - your use case (@bunkat) and this ticket was the reason I worked on pattern comprehensions in the first place. We had bounced around the idea for a while, but your query really drove home the fact that we needed something better. 

Thanks for sharing!

**Comment by chanep** [comment] 2016-12-06 15:45
I have my whole app using OPTIONAL MATCH's  and im realizing  about the very poor performance. The excution plan is crazy and has not any sense. This point is a critical bug as @bunkat commented: 

OPTIONAL MATCH statements generate NodeByLabelScan queries that touch the entire database. **An OPTIONAL MATCH rooted at a node should never touch the entire database**. I'm trying to express return any connected nodes if they exist, if not, that's okay continue with the query and not please look for anything in my database that looks sort of like this. I think this is where the primary confusion is.

I'm using version 3.0.7

**Comment by sherfert** [comment] 2017-10-03 13:56
@chanep Can you provide a (concise) QUERY with a small dataset, that behaves poorly for you, by creating the non-optimal plan?

**Comment by sherfert** [comment] 2018-09-24 08:39
> The problem that was reported here was that the planner wrongly did a label scan when encountering an optional match.
> 
> At least that's not happenign (for me) anymore.
> @bunkat could you try that for me ? with RC1 ?
> 
> ```
> 
> profile
> match (m:Movie {title:"The Matrix"})
> optional match (m)<-[:ACTED_IN]-(p:Person)
> RETURN *
> ```
> ![plan 25](https://cloud.githubusercontent.com/assets/67427/20854288/d1ad9142-b8f2-11e6-8c61-5ec4caf16ea3.png)
> 
> this query, turns the pattern comprehensions into nested normal matches
> 
> ```
> MATCH (t:Team {id: "123"})-[:CONTAINS]->(p:Project)
> WITH t, p { .*, create: [(p)-[:CREATED]->(c) | c ], edit:[(p)-[:EDITED]->(e) | e] }
> ```
> ![plan 26](https://cloud.githubusercontent.com/assets/67427/20854316/21b931e6-b8f3-11e6-9834-d4034ded710b.png)

Th original issue should have been resolved (long ago). Also we didn't get any more concrete queries on recent versions that resulted in a bad plan. I am closing this now, and feel free to reopen if I missed something.

**Closed as completed by sherfert** 2018-09-24 08:39 UTC
Labels: bug, cypher, 3.0, team-cypher
