### ISSUE TITLE
Unexpected DatabaseException: Exception closing multiple resources

### ISSUE THREAD

**Issue by YuanchengJiang** [neo4j/neo4j#12968] opened 2022-10-31 06:04 UTC
Neo4j version: 4.4.12
Operating system: Ubuntu 20.04
API/Driver: Cypher
Dataset: Pole(Crime analysis), https://github.com/neo4j-graph-examples/pole.

I am using `cypher-shell --debug` to get exception logs

Bug:

`OPTIONAL MATCH p=(n)-->()--()-->()--()--()-->()<--(n) RETURN id(n) SKIP 2 LIMIT 1;` worksed.
However, changing the symbol from `n` to `a`:
`OPTIONAL MATCH p=(a)-->()--()-->()--()--()-->()<--(a) RETURN id(a) SKIP 2 LIMIT 1;` throwed exception.

Logs:
```
neo4j@neo4j> OPTIONAL MATCH p=(n)-->()--()-->()--()--()-->()<--(n) RETURN id(n) SKIP 2 LIMIT 1;
+-------+
| id(n) |
+-------+
| 0     |
+-------+

1 row
ready to start consuming query after 1 ms, results consumed after another 5 ms
```

Exception logs:
```
neo4j@neo4j> OPTIONAL MATCH p=(a)-->()--()-->()--()--()-->()<--(a) RETURN id(a) SKIP 2 LIMIT 1;
org.neo4j.driver.exceptions.DatabaseException: Exception closing multiple resources.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
	at org.neo4j.driver.internal.InternalResult.blockingGet(InternalResult.java:107)
	at org.neo4j.driver.internal.InternalResult.hasNext(InternalResult.java:53)
	at org.neo4j.shell.prettyprint.TableOutputFormatter.take(TableOutputFormatter.java:69)
	at org.neo4j.shell.prettyprint.TableOutputFormatter.formatResultAndCountRows(TableOutputFormatter.java:81)
	at org.neo4j.shell.prettyprint.TableOutputFormatter.formatAndCount(TableOutputFormatter.java:63)
	at org.neo4j.shell.prettyprint.PrettyPrinter.format(PrettyPrinter.java:54)
	at org.neo4j.shell.CypherShell.lambda$executeCypher$0(CypherShell.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.neo4j.shell.CypherShell.executeCypher(CypherShell.java:136)
	at org.neo4j.shell.CypherShell.execute(CypherShell.java:112)
	at org.neo4j.shell.cli.InteractiveShellRunner.runUntilEnd(InteractiveShellRunner.java:114)
	at org.neo4j.shell.Main.runShell(Main.java:178)
	at org.neo4j.shell.Main.startShell(Main.java:132)
	at org.neo4j.shell.Main.main(Main.java:110)
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:82)
		at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:107)
		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.unpackFailureMessage(CommonMessageReader.java:75)
		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.read(CommonMessageReader.java:53)
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:81)
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:37)
		at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
		at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:42)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by HannesSandberg** [comment] 2022-10-31 08:08
Thank you for your report! We will investigate this and report back to you.

**Comment by pontusmelke** [comment] 2022-11-08 14:30
Thanks @YuanchengJiang 

We have investigated the issue and a fix will be provided in an upcoming release.

Best Regards,
Pontus

**Comment by YuanchengJiang** [comment] 2022-11-15 10:03
> Thanks @YuanchengJiang
> 
> We have investigated the issue and a fix will be provided in an upcoming release.
> 
> Best Regards, Pontus

Hi,

It would be helpful if the fix commit can be linked here.

**Comment by yoni333** [comment] 2023-06-26 06:36
neo4j version 5.8.0 this bug came again......

**Comment by pontusmelke** [comment] 2023-07-03 12:45
@yoni333 I just tried on a 5.8.0 db and I couldn't reproduce. What I did was

- create a db from the polestar dump on 5.8
- run the above queries
- No errors observed.

Could you share more details about the errors you are seeing in 5.8.0?

Best regards,
Pontus

**Comment by pontusmelke** [comment] 2023-07-03 12:51
> > Thanks @YuanchengJiang
> > We have investigated the issue and a fix will be provided in an upcoming release.
> > Best Regards, Pontus
> 
> Hi,
> 
> It would be helpful if the fix commit can be linked here.

Sorry I missed this message. This is the commit, https://github.com/neo4j/neo4j/commit/a7e7bc7d1c3cb88b45449e2909fbae77ca62f3c1.

Best regards,
Pontus

**Comment by pontusmelke** [comment] 2023-07-10 07:17
@yoni333 
Could you provide more details about the failure you see in 5.8? I am so far unable to reproduce the issue in 5.8 or later.

Regards,
Pontus

**Comment by pontusmelke** [comment] 2023-08-14 07:05
Since I am no longer able to reproduce this issue I will close it. @yoni333 if you are indeed still hitting this issue please provide some more details and I will revisit this issue.

**Closed as completed by pontusmelke** 2023-08-14 07:05 UTC
Labels: bug, team-cypher
