### ISSUE TITLE
Misinformative exception when disk is full during an import

### ISSUE THREAD

**Issue by tonicebrian** [neo4j/neo4j#12194] opened 2019-04-08 09:51 UTC
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.
To help us understand your issue, please specify important details, primarily:

- Neo4j version: 3.5.3
- Operating system: Ubuntu 16.04
- API/Driver: neo4j-import
- **Steps to reproduce**
- Import CSVs using neo4j-import that result in a DB bigger than the available space in disk. It will fail with a hard to understand exception `java.io.IOException: Exception in the page eviction thread`

```
(1/4) Node import 2019-04-05 09:35:13.031+0000
Estimated number of nodes: 908.68 M
Estimated disk space usage: 209.37 GB
Estimated required memory usage: 12.17 GB
.......... .......... .......... .......... .......... 5% ∆4m 45s 884ms
.......... .......... .......... .......... .......... 10% ∆4m 46s 228ms
.......... .......... .......... .......... .......... 15% ∆4m 40s 372ms
.......... .......... .......... .......... .......... 20% ∆11m 44s 147ms
.......... .......... .......... .......... .......... 25% ∆17m 29s 999ms
.......... .......... .......... .......... .......... 30% ∆17m 56s 545ms
.......... .......... .......... .......... .......... 35% ∆17m 17s 782ms
.......... .......... .......... .......... .......... 40% ∆17m 19s 990ms
.......... .......... .......... .......... .......... 45% ∆17m 17s 178ms
.......... .......... .......... .......... .......... 50% ∆17m 21s 299ms
.......... .......... .......... .......... .......... 55% ∆17m 14s 424ms
.......... .......... .......... .......... .......... 60% ∆17m 29s 184ms
.......... .......... .......... .......... .......... 65% ∆17m 14s 392ms
.......... .......... .......... .......... .......... 70% ∆19s 492ms
.......... .......... .......... .......... .......... 75% ∆1ms
.......... .......... .......... .......... .......... 80% ∆1ms
.......... .......... .......... .......... .......... 85% ∆0ms
.......... .......... .......... .......... .......... 90% ∆1ms
.......... .......... .......... .......... .......... 95% ∆0ms
.......... .......... .......... .......... .......... 100% ∆0ms

IMPORT FAILED in 3h 5m 37s 826ms.
Data statistics is not available.
Peak memory usage: 0.00 B
Error in input data
Caused by:ERROR in input
data source: BufferedCharSeeker[source:/var/lib/neo4j/import/outputs/outputs-000000000227.csv.gz, position:2711786, line:12085]
in field: spending_tx_hash:string:9
for header: [:ID(Output-ID), tx_hash:string, output_index:int, required_signatures:string, type:string, value:long, is_spent:boolean, input_index:int, spending_tx_hash:string]
raw field value: d9be3d33b842ae49815356b7583ee87f7c47c6bef13d9d33c4d7b8bc60191f52
original error: java.io.IOException: Exception in the page eviction thread

WARNING Import failed. The store files in /var/lib/neo4j/data/databases/bitcoin.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
unexpected error: ERROR in input
data source: BufferedCharSeeker[source:/var/lib/neo4j/import/outputs/outputs-000000000227.csv.gz, position:2711786, line:12085]
in field: spending_tx_hash:string:9
for header: [:ID(Output-ID), tx_hash:string, output_index:int, required_signatures:string, type:string, value:long, is_spent:boolean, input_index:int, spending_tx_hash:string]
raw field value: d9be3d33b842ae49815356b7583ee87f7c47c6bef13d9d33c4d7b8bc60191f52
original error: java.io.IOException: Exception in the page eviction thread
```

**Comment by chrisvest** [comment] 2019-04-09 09:50
Can you try running it again with the `NEO4J_DEBUG=1` environment variable set? That should make it include the stack trace in the console output. You might also be able to find a stack trace in the log files you have already.

**Comment by tonicebrian** [comment] 2019-04-09 09:53
Sorry, I resized disks and then the whole import ran without any issues. I cannot reproduce the problem now because it was solved just by adding more space.

**Comment by kcrimson** [comment] 2019-05-07 14:32
@tonicebrian I am closing this issue because it cannot be reproduced

**Closed as completed by kcrimson** 2019-05-07 14:32 UTC
