### ISSUE TITLE
Queries against indexed properties fail on null value comparison after clean upgrade from 2.1.7 to 2.2.2

### ISSUE THREAD

**Issue by CharlieDigital** [neo4j/neo4j#4673] opened 2015-05-21 20:38 UTC
Hello,

Today, I updated my data store from 2.1.7 to 2.2.2 and some queries are failing with a 400 error.

I followed the upgrade procedure for the database and set the `allow_store_upgrade=true` for the database.  Upgrade completed without error to the UI and no error that I can see in any logs.

Please note that I do not believe this to be a case of query incompatibility as we have another environment using the same queries already on 2.2.2.

The full exception is as follows:

```
"Received an unexpected HTTP status when executing the request.The response status was: 400 Bad Request
The response from Neo4j (which might include useful detail!) was: {  "exception" : "NullPointerException",  "fullname" : "java.lang.NullPointerException",  "stackTrace" : [ "org.neo4j.kernel.api.impl.index.LuceneDocumentStructure$ValueEncoding$2.canEncode(LuceneDocumentStructure.java:90)", "org.neo4j.kernel.api.impl.index.LuceneDocumentStructure.newQuery(LuceneDocumentStructure.java:219)", "org.neo4j.kernel.api.impl.index.LuceneIndexAccessorReader.lookup(LuceneIndexAccessorReader.java:96)", "org.neo4j.kernel.impl.api.store.DiskLayer.nodesGetFromIndexLookup(DiskLayer.java:601)", "org.neo4j.kernel.impl.api.store.CacheLayer.nodesGetFromIndexLookup(CacheLayer.java:349)", "org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodesGetFromIndexLookup(StateHandlingStatementOperations.java:591)", "org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodesGetFromIndexLookup(ConstraintEnforcingEntityOperations.java:210)", "org.neo4j.kernel.impl.api.OperationsFacade.nodesGetFromIndexLookup(OperationsFacade.java:172)", "org.neo4j.cypher.internal.spi.v2_2.TransactionBoundQueryContext.exactIndexSearch(TransactionBoundQueryContext.scala:131)", "org.neo4j.cypher.internal.compiler.v2_2.spi.DelegatingQueryContext.exactIndexSearch(DelegatingQueryContext.scala:82)", "org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$super$exactIndexSearch(ExceptionTranslatingQueryContext.scala:92)", "org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:92)", "org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:92)", "org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$translateException(ExceptionTranslatingQueryContext.scala:182)", "org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.exactIndexSearch(ExceptionTranslatingQueryContext.scala:92)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$2$$anonfun$apply$2.apply(NodeIndexSeekPipe.scala:47)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$2$$anonfun$apply$2.apply(NodeIndexSeekPipe.scala:47)", "org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:53)", "org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:51)", "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)", "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)", "scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)", "scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)", "scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)", "scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)", "org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$.apply(indexQuery.scala:50)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.internalCreateResults(NodeIndexSeekPipe.scala:55)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.Pipe$class.createResults(Pipe.scala:58)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.createResults(NodeIndexSeekPipe.scala:33)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:35)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:32)", "scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)", "scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)", "scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)", "scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)", "scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)", "scala.collection.Iterator$class.foreach(Iterator.scala:727)", "scala.collection.AbstractIterator.foreach(Iterator.scala:1157)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:79)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:122)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)", "org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:92)", "org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:64)", "org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:121)", "org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:105)", "org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anon$1.run(ExecutionPlanBuilder.scala:69)", "org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:173)", "org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:173)", "org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:105)", "org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.run(CompatibilityFor2_2.scala:172)", "org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:28)", "org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:108)", "org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:102)", "org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:61)", "org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:118)", "java.lang.reflect.Method.invoke(Unknown Source)", "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)", "java.lang.Thread.run(Unknown Source)" ],  "errors" : [ {    "message" : null,    "code" : "Neo.DatabaseError.General.UnknownFailure",    "stackTrace" : "java.lang.NullPointerException
  at org.neo4j.kernel.api.impl.index.LuceneDocumentStructure$ValueEncoding$2.canEncode(LuceneDocumentStructure.java:90)
  at org.neo4j.kernel.api.impl.index.LuceneDocumentStructure.newQuery(LuceneDocumentStructure.java:219)
  at org.neo4j.kernel.api.impl.index.LuceneIndexAccessorReader.lookup(LuceneIndexAccessorReader.java:96)
  at org.neo4j.kernel.impl.api.store.DiskLayer.nodesGetFromIndexLookup(DiskLayer.java:601)
  at org.neo4j.kernel.impl.api.store.CacheLayer.nodesGetFromIndexLookup(CacheLayer.java:349)
  at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodesGetFromIndexLookup(StateHandlingStatementOperations.java:591)
  at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodesGetFromIndexLookup(ConstraintEnforcingEntityOperations.java:210)
  at org.neo4j.kernel.impl.api.OperationsFacade.nodesGetFromIndexLookup(OperationsFacade.java:172)
  at org.neo4j.cypher.internal.spi.v2_2.TransactionBoundQueryContext.exactIndexSearch(TransactionBoundQueryContext.scala:131)
  at org.neo4j.cypher.internal.compiler.v2_2.spi.DelegatingQueryContext.exactIndexSearch(DelegatingQueryContext.scala:82)
  at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$super$exactIndexSearch(ExceptionTranslatingQueryContext.scala:92)
  at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:92)
  at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:92)
  at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$translateException(ExceptionTranslatingQueryContext.scala:182)
  at org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.exactIndexSearch(ExceptionTranslatingQueryContext.scala:92)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$2$$anonfun$apply$2.apply(NodeIndexSeekPipe.scala:47)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$2$$anonfun$apply$2.apply(NodeIndexSeekPipe.scala:47)
  at org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:53)
  at org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:51)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
  at org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$.apply(indexQuery.scala:50)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.internalCreateResults(NodeIndexSeekPipe.scala:55)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.Pipe$class.createResults(Pipe.scala:58)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.createResults(NodeIndexSeekPipe.scala:33)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:35)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:32)
  at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
  at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
  at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
  at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
  at scala.collection.Iterator$class.foreach(Iterator.scala:727)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:79)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:122)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)
  at org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:92)
  at org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:64)
  at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:121)
  at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:105)
  at org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anon$1.run(ExecutionPlanBuilder.scala:69)
  at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:173)
  at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:173)
  at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:105)
  at org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.run(CompatibilityFor2_2.scala:172)
  at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:28)
  at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:108)
  at org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:102)
  at org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:61)
  at org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:118)
  at sun.reflect.GeneratedMethodAccessor219.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)
  at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
  at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
  at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
  at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)
  at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
  at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
  at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
  at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
  at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
  at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
  at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
  at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
  at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
  at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
  at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
  at org.eclipse.jetty.server.Server.handle(Server.java:497)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
  at java.lang.Thread.run(Unknown Source)
  "  } ]}"
```

From messages.log, I see the following:

```
2015-05-21 19:40:37.401+0000 INFO  [o.n.s.CommunityNeoServer]: Setting startup timeout to: 120000ms based on 120000
2015-05-21 19:40:37.401+0000 INFO  [o.n.s.CommunityNeoServer]: Setting startup timeout to: 120000ms based on 120000
2015-05-21 19:40:37.415+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Starting upgrade of database store files
2015-05-21 19:40:37.415+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Starting upgrade of database store files
2015-05-21 19:40:37.859+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Finished upgrade of database store files
2015-05-21 19:40:37.859+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Finished upgrade of database store files
2015-05-21 19:40:38.280+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Migration completed in 0 s

2015-05-21 19:40:38.280+0000 INFO  [o.n.k.i.s.StoreMigrationTool]: Migration completed in 0 s
```

Did I miss a step?  Is there some corrective action I can take?

**Comment by CharlieDigital** [comment] 2015-05-22 01:15
Well, I've done more testing with one of the failing queries and found that the issue occurs when there is a `null` comparison.

In this case, there is a property on the relationship between two nodes that references another node

Consider a graph like the following:

```
(jake:User {Name: 'Jake'})-[:FRIENDS_WITH { From: 'Harvard' }]->(arthur:User {Name: 'Arthur'})
(harvard:Context { Name: 'Harvard', Type: 'University' })
(alice:User {Name: 'Alice'})-[:FRIENDS_WITH]->(sam:User {Name: 'Sam'})
```

With a `CREATE INDEX ON :Context(Name)`

A match like this:

```
MATCH (u0:User)-[f:FRIENDS_WITH]->(u1:User)
WITH u0, u1, f.From AS contextName
OPTIONAL MATCH (c:Context)
WHERE c.Name = contextName
RETURN u0, u1, c.Name
```

Will fail if the `f.From` is `null` valued as is the case with Alice and Sam

If we return at the first `WITH`, it works:

```
MATCH (u0:User)-[f:FRIENDS_WITH]->(u1:User)
RETURN u0, u1, f.From AS contextName
```

If the query is changed to coalesce the `null` into an empty string:

```
MATCH (u0:User)-[f:FRIENDS_WITH]->(u1:User)
WITH u0, u1, coalesce(f.From, '') AS contextName
OPTIONAL MATCH (c:Context)
WHERE c.Name = contextName
RETURN u0, u1, c.Name
```

It works.  

This query definitely works in 2.1.7 and for data created in 2.2.2, we don't seem to have an issue.  But when a store upgrade is performed (seemingly without error), this issue occurs.

We've tested with the specific example as outlined above and unfortunately, we are unable to replicated it using JUST this data as provided in the example, but our production data is structured the exact same way (just more of it and with different node names, etc.).

Further testing revealed additional observations: 
- If we drop the index, the query will **work**.  
- If we re-add the index, the query will **fail**.
- If we use a non-indexed field for the `OPTIONAL MATCH ... WHERE` (`Type` instead of `Name`), the query will **work**.
- If we use a non-existent field for the `OPTIONAL MATCH ... WHERE` (such as `BlahBlah` instead of `Name`), the query will **work**.
- If we add an index on `:Context(Type)` and then try to use it against a null comparison, it will **fail**.
- If we change the `WHERE` to  `WHERE contextName IS NOT NULL AND c.Name = contextName`, it will **fail**.
- If we `MATCH (c:Context) WHERE c.Name IS NULL SET c.Name = ''` the query will **work**
- If we revert that and execute `MATCH (c:Context) WHERE c.Name = '' SET c.Name = null` the query will **fail**

So it seems pretty clear that there is an issue here regarding the indexes on migrated data.

Aside from `DROP INDEX ON`, is there another way to clean up the indexes and force them to be regenerated?

**Comment by CharlieDigital** [comment] 2015-05-28 17:46
Well, we've now observed the issue with fresh 2.2.2 installs as well on Windows with Java 1.7.0_79.

**Comment by CharlieDigital** [comment] 2015-05-28 23:59
Consistency check on the database shows all clear:

```
c:\Neo4j>java -cp "lib/*;system/lib/*" org.neo4j.consistency.ConsistencyCheckTool d:/innovograph
Full consistency check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Checking node and relationship counts
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
```

**Comment by jexp** [comment] 2015-05-29 06:25
Hi, thanks so much for the detailed feedback, I reported it to the engineering team and will update you when we know more. Would it perhaps be possible to share that upgraded store (and the backup of the original) with us?

**Comment by CharlieDigital** [comment] 2015-05-29 07:51
Yes, a small sample database from a clean 2.2.2 environment is available (200KB)

**Comment by jexp** [comment] 2015-05-30 01:39
Thanks a lot, investingating ...

**Comment by jexp** [comment] 2015-06-27 10:00
It's a query planning issue, not related to the upgrade of the store

You can change you query to 

Where c.name = coalesce(contextName,'')

It should work

The issue is that index lookups currently don't deal with null values

**Comment by lutovich** [comment] 2015-08-06 08:43
Hello @CharlieDigital,

I believe this issue is fixed by https://github.com/neo4j/neo4j/pull/5080 and should be available with next release.
Please feel free to reopen this ticket if you experience any related problems.

**Closed as completed by lutovich** 2015-08-06 08:43 UTC
Labels: 2.2, team-kernel
