### ISSUE TITLE
hasRelation method returns wrong result

### ISSUE THREAD

**Issue by horak90** [neo4j/neo4j#12345] opened 2019-11-14 12:34 UTC
Hello,

I am getting a not consistent behavior of the hasRelation method when used by my custom stored procedure.

`Stream<Node> filterNodesByRelationType(List<Node> nodes) {
        return nodes.stream().filter(node -> node.hasRelationship(Direction.OUTGOING, RelationshipType.withName("myRelation")));
    }`

The problem is that at some point the hasRelation method returns true for a node that does not have this type of relationship.

By debugging, I found out that true is returned only the first time, the other calls of the same method return false for the same node.

By entering the innerHasRelationships method in NodeProxy class, I saw that the iterator contains a relationship that belongs to a previously checked node ( from the list ). So it seems like the method returns a value of the previous call for the first time.

If I replace the hasRelationship method by `getRelationships(Direction.OUTGOING, RelationshipType.withName("myRelation")).iterator().hasNext()` everything works as expected.

- Neo4j version: 3.5.12
- Operating system: MacOS Catalina

**Comment by tinwelint** [comment] 2019-11-18 10:37
That is indeed very strange because (also looking at the code) both `hasRelationships` and `getRelationships(Direction)` delegates to `getRelationshipSelectionIterator` and so what ever happens in one also happens in the other. Would it be possible for you to provided a reproducible test case showing this problem?

**Comment by horak90** [comment] 2019-11-18 13:14
I just sent you an email with all the data to reproduce the issue.

**Comment by tinwelint** [comment] 2019-11-18 14:34
Thanks

**Comment by chrisvest** [comment] 2019-11-19 15:53
@horak90 Thank you for the material you sent us. We have identified a bug and are working on a fix.

**Comment by aijcoa** [comment] 2019-11-20 10:40
just pointing out that the issue # is 12345.

**Comment by tinwelint** [comment] 2019-11-20 22:55
@f7n my word, how could we have missed that. Quite notable, cheers

**Comment by chrisvest** [comment] 2019-11-21 14:48
We have merged a fix for this, which will be out in the next 3.5 release.

**Closed as completed by chrisvest** 2019-11-21 14:48 UTC
Labels: bug, team-kernel
