### ISSUE TITLE
UnknownError in a DuplicatedSlotKey

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13440] opened 2024-04-04 19:20 UTC
When running the following query:
```cypher
UNWIND 0 AS n0
RETURN null AS n1
	UNION
MATCH ()
OPTIONAL MATCH ()-[n2]->(n3)--(n4)-[aZvD]->(n5)
OPTIONAL MATCH
	(:!n6)-[{y:0, y:aZvD.x, x:0, x:0}]->(ex),
	(),
	({x:0, y:0}),
	()<--(),
	()
RETURN null AS n1
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.General.UnknownError ((DuplicatedSlotKey(RuntimeKey(aZvDy,PropertyKeyName(x),RELATIONSHIP_TYPE),2),RefSlot(2,false,Any)) (of class scala.Tuple2))
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.18.0 community version** in a Docker container running **alpine v.3**.
When testing the query against the enterprise version, no error is thrown, unless the slotted runtime is forced.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
UNWIND 0 AS n0 RETURN null AS n1 UNION MATCH () OPTIONAL MATCH ()-[n2]->(n3)--(n4)-[aZvD]->(n5) OPTIONAL MATCH (:!n6)-[{y:0, y:aZvD.x, x:0, x:0}]->(ex), (), ({x:0, y:0}), ()<--(), () RETURN null AS n1
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.General.UnknownError ((DuplicatedSlotKey(RuntimeKey(aZvDy,PropertyKeyName(x),RELATIONSHIP_TYPE),2),RefSlot(2,false,Any)) (of class scala.Tuple2))`

**Comment by LinneaAndersson** [comment] 2024-04-05 06:35
@DominicWuest Thanks for reporting this bug, I was able to reproduce it. 

We will have a look at the issue and get back to you once we have more information

**Comment by JonasHolgersson** [comment] 2024-06-10 14:04
Duplicate of https://github.com/neo4j/neo4j/issues/13426

**Closed as completed by JonasHolgersson** 2024-06-10 14:04 UTC
Labels: bug, cypher, team-cypher
