### ISSUE TITLE
Unknown expression UnaryAdd in neo4j 3.5

### ISSUE THREAD

**Issue by hagen666** [neo4j/neo4j#12942] opened 2022-09-14 03:45 UTC
Semantic analysis error when executing cypher query: with +1 as p return p

- Neo4j version: 3.5.16, 3.5.35-SNAPSHOT
- Operating system: windows 10
- API/Driver: Cypher

### Steps to reproduce
1. Run Neo4j
2. Open Neo4j Browser
3. execute cypher query: with +1 as p return p

### Expected behavior
return 1 or other values.

### Actual behavior
Error in semantic analysis: Unknown expression UnaryAdd(SignedDecimalIntegerLiteral(1))
![image](https://user-images.githubusercontent.com/9511148/190054820-0119a455-e829-4b12-9857-25db94c8e735.png)

**Comment by HannesSandberg** [comment] 2022-09-15 05:30
Thanks for your report. We will investigate and report back to you!

**Comment by arnefischereit** [comment] 2022-09-21 06:55
Hi @hagen666,

It seems like this is a bug in the version that you have specified.

Unfortunately, [we do not support version 3.5 any longer since May](https://support.neo4j.com/hc/en-us/articles/115013134648-Neo4j-Supported-Versions). We tested this query in later versions and it succeeded for us.

Beyond that, it seems like the query can easily be adapted to succeed: `with 1 as p return p`.

I will close this issue now. If you find that your problem can be reproduced in later versions of the product or you have any questions to this, please feel free to comment on this issue or open a new one.

Regards,

Arne

**Closed as completed by arnefischereit** 2022-09-21 06:55 UTC
Labels: bug, team-cypher
