### ISSUE TITLE
BUG : neo4j looses triples, running partial commits leads to errors 

### ISSUE THREAD

**Issue by AnkurArohi** [neo4j/neo4j#13039] opened 2023-02-09 11:18 UTC
After the neo4j starts properly and the inital CYPHER queries are worked upon there is a partial transaction rolled back issue and the tuples are getting lost.

This leads to the exception and the task which the neo4j was configured to do is incomplete.

With the version 4.4.4 we didnt face this issue

- Neo4j version: 5.3.0
- Operating system: (for example Windows 95/Ubuntu 16.04) linux fedora
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)  Docker

## **Steps to reproduce**

Start the docker container with the correct settings for the neo4j DB and the following plugins 

Neo4j-Apoc: 5.3.1-extended, 
apoc-5.3.0-core.jar,
neosemantics-5.1.0.0.jar

and the following environment vars 

server.directories.data=/dbdata
server.jvm.additional=-Dlog4j2.formatMsgNoLookups=true
server.jvm.additional=-Dlog4j2.disable.jmx=true
server.jvm.additional=-XX:+ExitOnOutOfMemoryError
server.directories.plugins=/plugins
server.config.strict_validation.enabled=false

server.bolt.advertised_address=:7687
server.bolt.listen_address=:7687

dbms.security.procedures.unrestricted=algo.,apoc.

db.tx_log.rotation.retention_policy=false

server.memory.heap.initial_size=10g
server.memory.heap.max_size=10g
server.memory.pagecache.size=4g

## Expected behavior

 - Simply load and persist the tuples

## Actual behavior
Tuples are being lost and exception is being raised

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

2023-02-09 08:30:54.523+0000 ERROR Problems when running partial commit. Partial transaction rolled back. 3887 triples lost.                                                                                    │
│ org.neo4j.kernel.DeadlockDetectedException: ForsetiClient[transactionId=676, clientId=20] can't acquire UpdateLock{owners=ForsetiClient[transactionId=676, clientId=20], ForsetiClient[transactionId=650, clien │
│  Wait list:SharedLock[                                                                                                                                                                                          │
│ Client[676] waits for [ForsetiClient[transactionId=650, clientId=22]],                                                                                                                                          │
│ Client[650] waits for [ForsetiClient[transactionId=676, clientId=20]]]                                                                                                                                          │
│     at org.neo4j.kernel.impl.locking.forseti.ForsetiClient.waitFor(ForsetiClient.java:839) ~[neo4j-lock-5.3.0.jar:5.3.0]                                                                                        │
│     at org.neo4j.kernel.impl.locking.forseti.ForsetiClient.tryUpgradeToExclusiveWithShareLockHeld(ForsetiClient.java:787) ~[neo4j-lock-5.3.0.jar:5.3.0]                                                         │
│     at org.neo4j.kernel.impl.locking.forseti.ForsetiClient.tryUpgradeSharedToExclusive(ForsetiClient.java:750) ~[neo4j-lock-5.3.0.jar:5.3.0]                                                                    │
│     at org.neo4j.kernel.impl.locking.forseti.ForsetiClient.acquireExclusive(ForsetiClient.java:339) ~[neo4j-lock-5.3.0.jar:5.3.0]                                                                               │
│     at org.neo4j.kernel.impl.api.parallel.ParallelAccessCheck$1.acquireExclusive(ParallelAccessCheck.java:62) ~[neo4j-kernel-5.3.0.jar:5.3.0]                                                                   │
│     at org.neo4j.internal.recordstorage.RecordStorageLocks.acquireNodeLabelChangeLock(RecordStorageLocks.java:174) ~[neo4j-record-storage-engine-5.3.0.jar:5.3.0]                                               │
│     at org.neo4j.kernel.impl.newapi.Operations.nodeAddLabel(Operations.java:382) ~[neo4j-kernel-5.3.0.jar:5.3.0]                                                                                                │
│     at org.neo4j.kernel.impl.core.NodeEntity.addLabel(NodeEntity.java:317) ~[neo4j-kernel-5.3.0.jar:5.3.0]                                                                                                      │
│     at n10s.rdf.load.DirectStatementLoader.lambda$runPartialTx$1(DirectStatementLoader.java:63) ~[neosemantics-5.1.0.0.jar:5.1.0.0]                                                                             │
│     at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]                                                                                                                                                      │
│     at

**Comment by klaren** [comment] 2023-02-13 08:08
Hello @AnkurArohi and thanks for reporting!

The exceptions are thrown by the `neosemantics` plugin so you should open an issue there instead: https://github.com/neo4j-labs/neosemantics.

As of Neo4j 5, the community edition now uses the same locking implementation that the enterprise edition has been using for a long time. This implementation allows higher throughput, at the cost of occasionally false positive deadlocks. This might be what you are observing since the problem was not present in 4.4.4.

`DeadlockDetectedException` should be seen as transient errors and the queries should be retried. The Neo4j drivers automatically do the retries so this is generally not an issue, but I suspect that there are a few places where `neosemantics` don't do this properly. 

When you open the issue in the `neosemantics` repository you can reference this issue. I'll close this issue for now, but if it turns out the problem is not caused by `neosemantics`, please feel free to reopen it.

**Closed as completed by klaren** 2023-02-13 08:08 UTC
Labels: bug, team-kernel
