### ISSUE TITLE
Constraint creation is not idempotent operation

### ISSUE THREAD

**Issue by tomocesnik** [neo4j/neo4j#13208] opened 2023-06-09 08:56 UTC
### Steps to reproduce

1. Create a Neo4j instance with enough nodes (>20M) so that population of their index takes relatively long time. For this example, use nodes with label X and property x.
2. Run: `CREATE CONSTRAINT c IF NOT EXISTS ON (n:X) ASSERT n.x IS UNIQUE`. Use the label and property name of the created nodes. Query will block.
3. Kill the query before it finishes (simulates also broken connection to the DB for example).
4. Use: `CALL db.indexes()` to check the status of the constraint. Observe that the index for that constraint will keep populating until it is on 100%. Afterwards its status will keep saying "POPULATING" (after DB restart, this status will be “ONLINE”). Its uniqueness field will be "UNIQUE", even though the constraint was never fully created.
5. Running the query for constraint creation again will fail, even though there is a guard that should prevent failure if the constraint does not exist. Failure message will be: There already exists an index called 'c'.
6. Dropping the constraint will not work: `DROP CONSTRAINT c`. It will report that constraint does not exist.
7. Index should be dropped first, before the constraint can be re-created successfully: `DROP INDEX c`

This was reproduced on Neo4j 4.3.15. It can be reproduced (with appropriate Cypher commands changed) also on 5.8.0. There the index status will just be set to "FAILED", but will still exist, which makes the issue still problematic.

### Expected behavior

Constraint creation succeeds and the index that is created in the background is auto-cleaned up, so that the constraint creation operation can be retried if the connection to DB is dropped in-between.

### Actual behavior

Constraint creation fails and cannot be relied on for idempotent behavior.

**Comment by HannesSandberg** [comment] 2023-06-09 13:42
Thanks, we will investigate this

**Comment by emmaholmbergohlsson** [comment] 2023-07-14 09:03
Hello @tomocesnik , thank you for reporting and describing the problem so thoroughly 
Yes and no :grin: 
Constraint creation is an idempotent operation, you will end up with either a constraint and its index, or none of them. That's the intention and it is nearly true - it is true unless the dbms crashes (query is killed) during a very specific time span during the constraint creation. It only applies to index-backed constraints and it only happens if you are unlucky to have your constraint creation crash after starting to populate the index but before before finishing the constraint. Just as you describe, you don't end up with a constraint but just the index that should have belonged to the constraint, and to get out of this you have to drop the index to be able to retry. There are no other side-effects, the database is healthy it just has an extra index.

I can't say that this is by design (even though it is because of a design decision taken a very long ago) or that it is intended behaviour, but it is a known problem and it behaves the same in all the supported versions.
There is talk of some work in this area to improve this experience and make it possible to retry the constraint creation without dropping the index first. No decision has been made on which version this will be targeted for so I can't give you a timeline right now

**Comment by emmaholmbergohlsson** [comment] 2023-07-14 12:45
Actually thinking a bit more about it, killing the query shouldn't have the same behaiviour as a crash. We do not kill the running query directly, it should be cleaning up after itself. I'll see if I can reproduce it and see if it is missing something for that case

**Comment by emmaholmbergohlsson** [comment] 2023-07-21 12:22
Hello @tomocesnik an update for you
I have been able to reproduce the behaviour you are seeing when killing the query (`TERMINATE TRANSACTION`). We will look into it more and see what we can do

**Comment by tomocesnik** [comment] 2023-07-22 20:53
> 

Thanks for checking this out, even though it is not a high-priority item, since the workaround is rather straight-forward.

**Comment by emmaholmbergohlsson** [comment] 2023-09-12 07:47
Hello again @tomocesnik . We have now had time to look at this more - sorry for the delay. A fix has been merged and will be available in version 5.13
Thank you for reporting it

**Comment by tomocesnik** [comment] 2023-09-12 09:49
Awesome, thanks! :)

**Comment by emmaholmbergohlsson** [comment] 2023-10-24 07:02
Hello again @tomocesnik , 5.13 has now been released with the fix. Closing this issue since the fix is out, but of course feel free to reopen or open a new issue if you find that the problem you were seeing isn't completely solved.

**Closed as completed by emmaholmbergohlsson** 2023-10-24 07:02 UTC
Labels: bug, team-cypher
