### ISSUE TITLE
Writing blocks to neo4j stopped abruptly with org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by Vaibhav1587** [neo4j/neo4j#10598] opened 2017-12-06 19:56 UTC
- Neo4j version: 3.3.0
- Operating system: Ubuntu 16.04
- API/Driver: Java API

Trying to read the blocks from node and writing it to Neo4j. Following is the Java code snippet to create the block. 
`						StatementResult res = session.writeTransaction(new TransactionWork<StatementResult>() {
							public StatementResult execute(org.neo4j.driver.v1.Transaction tx) {
								StatementResult result = tx.run(query);
								return result;
							};
						});
`
After some 45K blocks insertion Neo4j Halts with exception,

> 2017-12-06 09:55:21.603+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [TransactionStartFailed]: Database has encountered some problem, plea$
org.neo4j.graphdb.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:198)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:610)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:405)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI.beginTransaction(TransactionStateMachineSPI.java:102)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:207)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:398)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
**Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)**
        at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:63)
        at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:94)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:190)
        ... 16 more
**Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: Error performing check point
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.constructCombinedFailure(CheckPointScheduler.java:100)**
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        ... 4 more
        **Suppressed: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.IOException: Permission denied**
                at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.force(NativeLabelScanStore.java:263)
                at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:460)
                at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:160)

Neo4j browser is not responsive after above exception. Tried start and stop. 
Show status as 

>  neo4j.service - Neo4j Graph Database
>    Loaded: loaded (/lib/systemd/system/neo4j.service; disabled; vendor preset: enabled)
>    Active: active (running) since Wed 2017-12-06 12:13:56 MST; 39min ago
>  Main PID: 43547 (java)
>     Tasks: 27
>    Memory: 249.6M
>       CPU: 1min 15.866s
>    CGroup: /system.slice/neo4j.service
>            └─43547 /usr/bin/java -cp /var/lib/neo4j/plugins:/etc/neo4j:/usr/share/neo4j/lib/*:/var/lib/neo4j/plugins/* -server -XX:+UseG1GC -XX:-OmitStackTraceInFastThr
> 
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
> Dec 06 12:14:16 blockchainhost neo4j[43547]:         at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
>  
>

**Comment by chrisvest** [comment] 2017-12-07 15:32
> Trying to read the blocks from node and writing it to Neo4j.

What does this mean? What is a block in this context?

> java.io.IOException: Permission denied

Does the user that the Neo4j database process run as, have the necessary access rights to write to the store files? Have any permissions on the database files been changed at some point? Is there more of this stack trace? It looks truncated.

**Comment by Vaibhav1587** [comment] 2017-12-07 15:53
Thanks for the reply..

Its a blockchain block. I'm storing blockchain2graph.

All permission's are given. That has been checked. Exception is happening in between the insertion. 
Complete stack is as follows,

> 2017-12-06 09:55:21.603+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [TransactionStartFailed]: Database has encountered some problem, plea$
> org.neo4j.graphdb.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
>         at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:198)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:610)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:405)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI.beginTransaction(TransactionStateMachineSPI.java:102)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:207)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:77)
>         at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:398)
>         at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:200)
>         at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
>         at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:134)
>         at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
>         at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:109)
> Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
>         at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.neo4j.kernel.internal.DatabaseHealth.assertHealthy(DatabaseHealth.java:63)
>         at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:94)
>         at org.neo4j.kernel.impl.factory.ClassicCoreSPI.beginTransaction(ClassicCoreSPI.java:190)
>         ... 16 more
> Caused by: org.neo4j.kernel.impl.store.UnderlyingStorageException: Error performing check point
>         at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.constructCombinedFailure(CheckPointScheduler.java:100)
>         at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:81)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         ... 4 more
>         Suppressed: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.IOException: Permission denied
>                 at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.force(NativeLabelScanStore.java:263)
>                 at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:460)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:160)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:160)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:134)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:64)
>                 ... 8 more
>         Caused by: java.io.IOException: Permission denied
>                 at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
>                 at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
>                 at sun.nio.ch.IOUtil.write(IOUtil.java:148)
>                 at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
>                 at java.nio.channels.FileChannel.write(FileChannel.java:414)
>                 at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.lockPositionWriteVector(SingleFilePageSwapper.java:512)
>                 at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.writePositionedVectoredToFileChannel(SingleFilePageSwapper.java:480)
>                 at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.write(SingleFilePageSwapper.java:458)
>                 at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.vectoredFlush(MuninnPagedFile.java:440)
>                 at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.flushAndForceInternal(MuninnPagedFile.java:413)
>                 at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.flushAndForce(MuninnPagedFile.java:274)
>                 at org.neo4j.index.internal.gbptree.GBPTree.checkpoint(GBPTree.java:865)
>                 at org.neo4j.index.internal.gbptree.GBPTree.checkpoint(GBPTree.java:858)
>                 at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.force(NativeLabelScanStore.java:259)
>                 ... 12 more
>         Suppressed: org.neo4j.kernel.impl.store.UnderlyingStorageException: java.io.IOException: Permission denied
>                 at org.neo4j.kernel.impl.index.labelscan.NativeLabelScanStore.force(NativeLabelScanStore.java:263)
>                 at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.flushAndForce(RecordStorageEngine.java:460)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:160)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.checkPointIfNeeded(CheckPointerImpl.java:134)
>                 at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointScheduler$1.run(CheckPointScheduler.java:64)
>                 ... 8 more
>         Caused by: java.io.IOException: Permission denied
>                 at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
>                 at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
>                 at sun.nio.ch.IOUtil.write(IOUtil.java:148)
>                 at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
>                 at java.nio.2017-12-06 09:55:21.606+0000 INFO [o.n.k.i.l.StoreLogService] Opened new internal log file
>

**Comment by chrisvest** [comment] 2018-01-11 14:39
I can only suggest that you check the permissions and owners on the files and parent directories again.

Are you running Neo4j inside a Docker container or something like that?

Is this happening right after the database starts, or only after it has been running and doing work for a while?

You can try creating a file in the relevant graph.db directory (or whatever it might be called) with the exact same permissions as the other store files, then switch to the same user as Neo4j is running under, and try writing to the test file you created earlier.

**Comment by chrisvest** [comment] 2018-02-12 09:52
I'm still suspecting that the problem is with the operating environment. Neo4j itself never modifies any permissions after installation. Closing until we get an indication to the contrary.

**Closed as completed by chrisvest** 2018-02-12 09:52 UTC
Labels: team-kernel
