### ISSUE TITLE
Neo.ClientError.Schema.ConstraintValidationFailed

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13125] opened 2023-04-09 08:31 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: match p=()-[*]->() foreach (a in reverse(relationships(p))|delete endNode(a) delete a) return 1
error message:
Neo.ClientError.Schema.ConstraintValidationFailed
Cannot delete node<86>, because it still has relationships. To delete this node, you must first delete its relationships.

Steps to reproduce:
create ()-[:T]->()-[:T]->();
match p=()-[*]->() foreach (a in reverse(relationships(p))|delete endNode(a) delete a) return 1;

But if I execute another query on an empty graph:create ()-[:T]->()-[:T]->() with * match p=()-[*]->() foreach (a in reverse(relationships(p))|delete endNode(a) delete a) return 1,then it can run successfully.

I think that query "create ()-[:T]->()-[:T]->() with * match p=()-[*]->() foreach (a in reverse(relationships(p))|delete endNode(a) delete a) return 1" is equivalent to query "create ()-[:T]->()-[:T]->();match p=()-[*]->() foreach (a in reverse(relationships(p))|delete endNode(a) delete a) return 1",so this inconsistency should not occur.

**Comment by AzuObs** [comment] 2023-04-12 13:30
Hi @ljhhuxiaoba 

Thanks for this extra error report. I agree that it is suspicious. I have submitted this to the appropriate team who will get back to you shortly ([private tracker](https://trello.com/c/W264R0I8)).

Warm thanks,

**Comment by sherfert** [comment] 2023-04-18 09:46
Hi @ljhhuxiaoba 

You are right and the 2 queries should behave the same. Neither should throw an error.
We have already found this bug internally a couple of weeks ago, so you will be delighted to hear that this bug is fixed in

* 5.7 (will be released soon)
* 4.4.19 (already released)

**Closed as completed by sherfert** 2023-04-18 09:46 UTC
Labels: bug, team-cypher

**Comment by sherfert** [comment] 2023-11-17 12:11
### Explanation of the issue

The problem was that the execution plan did, before the bugfix, not contain an `Eager` operator. Now it does:

```
+-----------------------+----+----------------------------------------------------------------------------------------+----------------+---------------------+
| Operator              | Id | Details                                                                                | Estimated Rows | Pipeline            |
+-----------------------+----+----------------------------------------------------------------------------------------+----------------+---------------------+
| +ProduceResults       |  0 | `1`                                                                                    |              4 |                     |
| |                     +----+----------------------------------------------------------------------------------------+----------------+                     |
| +Projection           |  1 | $autoint_0 AS `1`                                                                      |              4 |                     |
| |                     +----+----------------------------------------------------------------------------------------+----------------+                     |
| +Foreach              |  2 | a IN reverse(relationships((anon_0)-[anon_1*]->(anon_2))), DELETE endNode(a), DELETE a |              4 |                     |
| |                     +----+----------------------------------------------------------------------------------------+----------------+                     |
| +Eager                |  3 | read/delete conflict for variable: anon_0, read/delete conflict for variable: anon_2   |              4 | Fused in Pipeline 1 |
| |                     +----+----------------------------------------------------------------------------------------+----------------+---------------------+
| +VarLengthExpand(All) |  4 | (anon_0)-[anon_1*]->(anon_2)                                                           |              4 |                     |
| |                     +----+----------------------------------------------------------------------------------------+----------------+                     |
| +AllNodesScan         |  5 | anon_0                                                                                 |             10 | Fused in Pipeline 0 |
+-----------------------+----+----------------------------------------------------------------------------------------+----------------+---------------------+
```

Changing the final clause to `RETURN p` and printing the result one gets:

```
+-----------------------------------------------------------+
| p                                                         |
+-----------------------------------------------------------+
| (0)-[0:T,deleted]->(1,deleted)                            |
| (0)-[0:T,deleted]->(1,deleted)-[1:T,deleted]->(2,deleted) |
| (1,deleted)-[1:T,deleted]->(2,deleted)                    |
+-----------------------------------------------------------+
```
(note that IDs will be different on your machine probably)

---

The `Eager` prevents interleaved execution of the operators before and after it.

Let's take a closer look what happens before the bugfix where `Eager` is missing.
The failure `Cannot delete node<1>, because it still has relationships. To delete this node, you must first delete its relationships.` occurs in the commit phase of the transaction. This means we can look at the query results before attempting to commit the transaction:

```
+--------------------------------+
| p                              |
+--------------------------------+
| (0)-[0:T,deleted]->(1,deleted) |
+--------------------------------+
```

Only 1 result? Should the match not find 3 paths?
The problem is that, after finding the first path, the node with id `1` gets deleted. But that node is part of the remaining two paths, which haven't been found yet. The two other paths will then not be found and subsequently node with id `2` and relationship with id `1` will not get deleted.

Attempting to delete only node with id `1`, but keeping relationship with id `1` leads to the error above. One cannot delete a node that still has relationships.

I hope that explains why the query was failing.

**Comment by ljhhuxiaoba** [comment] 2023-11-18 11:28
Thanks for your patience！
