### ISSUE TITLE
ORDER BY requires property to be RETURNed as well

### ISSUE THREAD

**Issue by rickardoberg** [neo4j/neo4j#12138] opened 2019-01-17 07:01 UTC
Neo4j version: 3.5.1 Community
OS: OSX dev, but same in Ubuntu 16.04 prod
API: embedded Cypher

Steps:
We have a query that looks up a few nodes and does a WITH (one node is computed hence the WITH), then an immediate RETURN and ORDER BY. The catch is that the order by is two properties, the first of which is a property on a node which is not RETURNed (the computed node), the property is only used for ordering. The exact query is as follows:
`MATCH (:Thread {id:$thread_id})-[:HAS_COMMENT]->(comment:Comment)<-[:COMMENTED]-(user:User)
WHERE comment.is_deleted=false 
OPTIONAL MATCH (viewer:User {id:$user_id}) 
WITH comment, user, viewer, coalesce(head(extract(p IN (comment)-[:REPLY_TO]->() | (nodes(p)[1]))), comment) as reply_to 
RETURN comment.id as id, comment.comment as comment, comment.created_on as created_on,user.given_name as given_name, user.family_name as family_name, exists((comment)<-[:DISLIKED_COMMENT]-(viewer)) as disliked, exists((comment)<-[:LIKED_COMMENT]-(viewer)) as liked,size((comment)<-[:DISLIKED_COMMENT]-()) as dislike_count, size((comment)<-[:LIKED_COMMENT]-()) as like_count, comment.replies_count as replies_count, head(extract(p IN (comment)-[:REPLY_TO]->() | (nodes(p)[1]).id)) as reply_to_id 
ORDER BY reply_to.created_on DESC, comment.created_on ASC`

This is for sorting comments in a discussion forum. Top comments are sorted new to old, replies are sorted with their top level comments old to new.

Expected:
ORDER BY the reply_to.created_on property, then comment.created_on. This worked in 3.4.x

Actual:
the ORDER BY on reply_to.created_on is ignored

Workaround:
If I add ", reply_to.created_on as reply_to_created_on" at the end of RETURN it works as expected. So it looks like ORDER BY requires the property to be touched by RETURN. If I return another property from reply_to it doesn't work.

**Comment by Hunterness** [comment] 2019-01-21 07:34
Thanks for reporting, we will look into it.

/Team Cypher

**Comment by Hunterness** [comment] 2019-01-22 10:35
Hi @rickardoberg, could you perhaps supply us with some sample data? This would greatly help the investigation :)

Thanks,
Cypher Team

**Comment by Lojjs** [comment] 2019-02-05 10:59
@rickardoberg Even if I cannot reproduce your error without any data, I've looked a bit into the plans for your query on different versions. It looks like you have ran into a known bug for order by of a mixture of aliased and unaliased columns. This has been fixed in 3.5.2, so an upgrade to that version should fix your problem. If it doesn't, feel free to reopen this issue.

Best regards Louise, Noe4j Cypher Team

**Closed as completed by Lojjs** 2019-02-05 10:59 UTC
Labels: bug, cypher, team-cypher, 3.5
