### ISSUE TITLE
Import tool allowed duplicate records when they are only two characters long

### ISSUE THREAD

**Issue by skmami** [neo4j/neo4j#12513] opened 2020-05-19 03:39 UTC
I am using neo4j-admin import command to load data from csv files. 
I have some duplicate records in my CSV file and I passed the flag to skip duplicate records. It did skip records when the ID field is longer than two character length but some how able make into the neo4j when my ID length is only two characters long. 

I caught these duplicate when I try to run constraint on my node. 

```
Unable to create CONSTRAINT ON ( fareclass:FareClass ) ASSERT (fareclass.fareclass) IS UNIQUE:
Both Node(19785127) and Node(36180104) have the label `FareClass` and property `fareclass` = 'NH'

```

**Comment by tinwelint** [comment] 2020-06-17 12:14
@skmami Hi and thanks for the report.

Strange, I tried the duplicate detection for a couple of two-character node IDs and it could detect them. What did your CSV data look like? Do you have a minimal CSV data set that can reproduce this? Also which Neo4j version?

**Comment by tinwelint** [comment] 2020-07-01 14:04
Have you managed to reproduce this on some sort of minimal data set somehow?

**Comment by tinwelint** [comment] 2020-07-08 07:51
Since I cannot reproduce this and you cannot provide further information I'll close this issue. Please reopen if you get back with more information on this.

Thanks

**Closed as completed by tinwelint** 2020-07-08 07:51 UTC
Labels: bug, team-kernel
