### ISSUE TITLE
Is Neo4j not compatible with Scala 2.12.X ?

### ISSUE THREAD

**Issue by crafty-coder** [neo4j/neo4j#8832] opened 2017-02-16 11:09 UTC
Hi Experts!

I'm using neo4j DB to perform integration test inside my application. Recently I upgraded scala from 2.11.8 to 2.12.1 and it has stopped working.

`build.sbt`

```
name := "testneo"

version := "1.0"

scalaVersion := "2.12.1"

val neo4jVersion = "3.1.1"

libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"

libraryDependencies += "org.neo4j" % "neo4j-kernel" % neo4jVersion % "test" classifier "tests"
libraryDependencies += "org.neo4j" % "neo4j-io" % neo4jVersion % "test" classifier "tests"
libraryDependencies += "org.neo4j" % "neo4j-cypher" % neo4jVersion % "test"

```

`neoTest.scala`

```
import java.util

import org.neo4j.graphdb.config.Setting
import org.neo4j.graphdb.factory.GraphDatabaseSettings
import org.neo4j.graphdb.factory.GraphDatabaseSettings.BoltConnector.EncryptionLevel.DISABLED
import org.neo4j.graphdb.factory.GraphDatabaseSettings.boltConnector
import org.neo4j.test.TestGraphDatabaseFactory
import org.scalatest.FunSuite

class NeoTest extends FunSuite {

  test("Start the server and run a query") {
    
    val settings: java.util.Map[Setting[_], String] = new util.HashMap()

    settings.put(boltConnector("0").enabled, "true")
    settings.put(boltConnector("0").encryption_level, DISABLED.name())
    settings.put(boltConnector("0").`type`, "BOLT")
    settings.put(GraphDatabaseSettings.auth_enabled, "false")
    settings.put(boltConnector("0").address, "localhost:7687")

    val dbServer = new TestGraphDatabaseFactory().newImpermanentDatabase(settings)

    dbServer.execute(CREATE_NODES)
  }

  val CREATE_NODES: String =
    """
      |CREATE
      |(P1:Person { uid:'JOHNSMITH1', forename:'John' , middlename : 'C', surname:'Smith' , fullname: 'John C Smith' , dob: '27/10/1986' , ageBand: '30-35' , gender : 'M'  })
    """.stripMargin
}

```

When I do:

`sbt clean test`

I get

```
[info] NeoTest:
[info] - Start the server and run a query *** FAILED ***
[info]   java.lang.UnsupportedOperationException: No query engine installed.
[info]   at org.neo4j.kernel.impl.query.NoQueryEngine.noQueryEngine(NoQueryEngine.java:56)
[info]   at org.neo4j.kernel.impl.query.NoQueryEngine.executeQuery(NoQueryEngine.java:33)
[info]   at org.neo4j.kernel.impl.factory.ClassicCoreSPI.executeQuery(ClassicCoreSPI.java:77)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:429)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:412)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.execute(GraphDatabaseFacade.java:396)
[info]   at NeoTest.$anonfun$new$1(NeoTest.scala:24)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

If you included neo4j bolt to sbt dependency

`libraryDependencies += "org.neo4j" % "neo4j-bolt" % neo4jVersion % "test"`

you will get
 
```
info] - Start the server and run a query *** FAILED ***
[info]   java.lang.RuntimeException: Error starting org.neo4j.test.TestGraphDatabaseFactory$1$1, /home/carlos/dev/workspace/testneo/target/test-data/impermanent-db
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
[info]   at org.neo4j.test.TestGraphDatabaseFactory$1.newDatabase(TestGraphDatabaseFactory.java:243)
[info]   at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
[info]   at org.neo4j.test.TestGraphDatabaseFactory.newImpermanentDatabase(TestGraphDatabaseFactory.java:80)
[info]   at NeoTest.$anonfun$new$1(NeoTest.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
[info]   Cause: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.bolt.v1.runtime.LifecycleManagedBoltFactory@7865ac04' was successfully initialized, but failed to start. Please see attached cause exception.
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
[info]   at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
[info]   at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
[info]   at org.neo4j.test.TestGraphDatabaseFactory$1.newDatabase(TestGraphDatabaseFactory.java:243)
[info]   ...
[info]   Cause: org.neo4j.kernel.impl.util.UnsatisfiedDependencyException: No dependency satisfies type interface org.neo4j.kernel.impl.query.QueryExecutionEngine
[info]   at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:71)
[info]   at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:67)
[info]   at org.neo4j.graphdb.DependencyResolver$Adapter.resolveDependency(DependencyResolver.java:101)
[info]   at org.neo4j.bolt.v1.runtime.LifecycleManagedBoltFactory.start(LifecycleManagedBoltFactory.java:75)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
[info]   at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
[info]   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
[info]   ...
```

Note that if ran the same but with `scala 2.11.8` it will work.

**Comment by spacecowboy** [comment] 2017-02-16 13:58
The version of scala used by cypher is `2.11.8`, as seen in: https://github.com/neo4j/neo4j/blob/3.2/community/cypher/cypher/pom.xml#L48

It's probably impossible to mix versions.

**Comment by Tvaroh** [comment] 2017-03-07 20:15
Any plans to upgrade to `2.12`?

**Comment by chrisvest** [comment] 2017-03-07 23:14
Upgrading to 2.12 is quite involved because we have binary dependencies on Cypher planners from older versions of Neo4j, as a means to preserve Cypher compatibility across versions. Thus we either have to upgrade several versions of Cypher in tandem - which in turn breaks Scala binary compatibility on older Neo4j series - or do a clean break compatibility wise. Either approach would require at least a major release.

**Comment by Tvaroh** [comment] 2017-03-08 06:37
@chrisvest I see, will hope for the update in a future major release then.

**Comment by codeslubber** [comment] 2017-05-14 22:12
Wow, I did not know that it did not support 2.12 so wasted a bunch of time trying to get a test running in a new project. Thanks! The setup page mentions SBT and says see below but has nothing down there.

**Comment by diversit** [comment] 2017-05-19 10:41
This is holding us back from upgrading to 2.12.
Please find a way to update.
And it would also be nice if neo4j dependencies would reflect the Scala version. It took me a couple of hours to eventually find this issue which I would not had wasted if it was clear the Scala 2.12 neo4j libraries were not available.

**Comment by jexp** [comment] 2017-05-19 10:53
So this is mostly for embedded testing, correct? If we found a way of separating classloaders for neo4j-harness, I think that could help. @chrisvest ?

**Comment by Tvaroh** [comment] 2017-05-19 11:01
@jexp I think it would be nicer to allow extensions to be written using 2.12 as well.

**Comment by protheusfr** [comment] 2017-06-07 14:21
Hi @jexp , did you find a way to use a separate classloader as suggested ?
I've the exact same issue and this is blocking....

**Comment by chrisbeach** [comment] 2017-06-26 21:22
I'm having this issue as well. Please let us know when we can upgrade to 2.12, @chrisvest

**Comment by svaret** [comment] 2017-09-15 06:33
Having the same issue. Any progress on this @jexp ?

**Comment by izhangzhihao** [comment] 2018-01-17 15:08
Same issue here, Any update?

**Comment by codeslubber** [comment] 2018-01-26 03:32
Moved on to orientdb..

**Comment by michaelahlers** [comment] 2018-05-04 16:08
Using Scala 2.12, I've run into this problem, too.

This program:

```scala
import java.net.ServerSocket
import org.neo4j.driver.v1.{ Driver, GraphDatabase }
import org.neo4j.graphdb.factory.GraphDatabaseSettings
import org.neo4j.helpers.ListenSocketAddress._
import org.neo4j.kernel.configuration.BoltConnector.EncryptionLevel._
import org.neo4j.kernel.configuration.Connector.ConnectorType._
import org.neo4j.kernel.configuration.Settings.{ FALSE, TRUE }
import org.neo4j.kernel.configuration._
import org.neo4j.test.TestGraphDatabaseFactory

val connector = new BoltConnector("0")

val host = "localhost"
val port = new ServerSocket(0).getLocalPort

val database =
  new TestGraphDatabaseFactory().newImpermanentDatabaseBuilder()
    .setConfig(connector.`type`, BOLT.name())
    .setConfig(connector.enabled, TRUE)
    .setConfig(GraphDatabaseSettings.auth_enabled, FALSE)
    .setConfig(connector.encryption_level, DISABLED.name())
    .setConfig(connector.listen_address, listenAddress(host, port))
    .newGraphDatabase()

val driver = GraphDatabase.driver(s"bolt://$host:$port")
```

Yields this exception:

```
org.neo4j.kernel.impl.util.UnsatisfiedDependencyException: No dependency satisfies type interface org.neo4j.kernel.impl.query.QueryExecutionEngine
```

See also:

- [Java Reference § 4.14. Accessing Neo4j embedded via the Bolt protocol](https://neo4j.com/docs/java-reference/current/tutorials-java-embedded/#tutorials-java-embedded-bolt)
- [`org.neo4j.jdbc.bolt.Neo4jBoltRule`](https://github.com/neo4j-contrib/neo4j-jdbc/blob/master/neo4j-jdbc-bolt/src/test/java/org/neo4j/jdbc/bolt/Neo4jBoltRule.java)
- [Neo4j Impermanent Database with Bolt Connector](https://gist.github.com/michaelahlers/461c95981a0a2ae346567e5a1ae7a5e7)

Worth noting [Whisk Lab's docker-it-scala](https://github.com/whisklabs/docker-it-scala) offers [Neo4j support](https://github.com/whisklabs/docker-it-scala/blob/master/samples/src/main/scala/com/whisk/docker/DockerNeo4jService.scala) that might serve as a useful alternative to an embedded database for testing purposes.

**Comment by dominics** [comment] 2018-07-02 06:07
Over in https://github.com/neo4j/neo4j/issues/5802#issuecomment-152961778, @boggle said this about future plans for supporting 2.12:

> Going forward, a future GA release will at some point upgrade to scala 2.12 once it has become stable (that may not happen immediately when scala 2.12.0 is release but soon after)

Scala 2.12 went stable in November 2016, and it's now July 2018 (i.e. 20 months later). That's a pretty long wait for "soon after". There's also this bit:

> Our current policy is that a public ("GA") version of Neo4j supports a recent, stable, major version of scala.

Well, that's no longer true either. 2.11.x was EOLd last year, and is no longer maintained. The release notes for 2.11.12 say:

> We strongly encourage you to upgrade to the latest stable version of Scala 2.12.x, as the 2.11.x series is no longer actively maintained.

At the _very least_, it's disingenuous to have this issue tagged as "question".

**Comment by klobuczek** [comment] 2018-07-08 18:37
During last GraphConnect it sounded like we were very close to have Scala 2.12 supported. Apparently neo4j spark connector was holding things up. Since then there were several releases and one major release of neo4j and still nothing changed.

**Comment by lorenz-nlp** [comment] 2018-07-09 07:02
I encountered the same problem when using TestGraphDatabaseFactory in my tests. The problem is that the classpath contains then the application to test, as well as Neo4j, which makes version conflicts of different libraries or Scala likely. I was recommended to use testcontainers instead, which let you spin up a Neo4j instance for each test in Docker. This works like a charm, and I only can recommend it as classpath conflicts are avoided then.

**Comment by boggle** [comment] 2018-07-09 14:41
You are right, currently we do only support scala 2.11. We are looking into supporting 2.12, please stay tuned.

**Comment by waxmittmann** [comment] 2018-07-12 01:47
@boggle Will the 2.12 compatibility fix include definitively solving the issues that made the upgrade from 2.11 -> 2.12 so difficult? 

I ask because we're six months from 2.13, and if the 212 -> 2.13 upgrade will happen in a similar time frame then it's not going to be worth it for me, as I can't afford to rewrite all my tests a year in or stick with an obsolete version of Scala for a couple of years.

**Comment by boggle** [comment] 2018-07-12 07:29
To get some feedback, would you prefer if we'd move to 2.13 right away once it's out, skipping 2.12 entirely?

**Comment by boggle** [comment] 2018-07-12 07:31
Also what issue are you referring to? As we're shipping a database, we tend to follow a versioning policy for dependencies that's more towards the side of stability than recency.

**Comment by waxmittmann** [comment] 2018-07-12 08:16
@boggle Thanks for your response :+1: 

In an earlier comment ChrisVest wrote: "Upgrading to 2.12 is quite involved because we have binary dependencies on Cypher planners from older versions of Neo4j, as a means to preserve Cypher compatibility across versions".

If I had to choose 2.13 probably makes more sense to me than 2.12, but unless compatibility with the most recent version of Scala can be achieved in a much shorter time frame for when 2.14 comes around then for me it's a moot point because I care about keeping my dependencies (especially Scala itself, so I can bump my other Scala dependencies) reasonably up to date, so I'd rather take the pain of running my unit tests against a dockerized instance than waiting (but that's just me).

**Comment by boggle** [comment] 2018-07-12 10:50
@klobuczek you are right, this is also related to CAPS and the spark connector. Since spark hasn't updated to 2.12 (we had high hopes that would have happened by now), and CAPS and Neo4j share the front-end we were tied by that. We recently did the work of separating the cypher front-end from Neo4j and re-publish it under ASL via opencypher. So at least this stumbling block has been removed. The backwards compatibility point made by @chrisvest still holds and is the other issue we need to deal with. 

While I'm not trying to be dismissive of the raised issue (we take things like this serious), I'm still going to say that relying on the scala version shipped with the db is somewhat of an antipattern. It should be possible to separate neo4j embedded and other code using OSGi/jigsaw/class loader magic and doing so probably leads to a much saner architecture. Then again, I'm aware of the pain that these solutions involve, so yes, we need to upgrade.

**Comment by waxmittmann** [comment] 2018-07-29 02:43
@boggle "Relying on the Scala version shipped with the db is somewhat of an antipattern" Is it though? All my other dependencies share my current version of scala. I've never successfully used a library that's built with a binary-incompatible scala version. 
By the comments on this issue so far, I'm not sure anyone else has had much luck either. In scouring the web and stackoverflow the only advice I found was 'cross-build your dependency for your version of Scala'. Or am I misunderstanding the problem or the solution?

It'd be very useful if someone with more knowledge in the dark arts than I could put together a minimal example of how to use 'OSGi/jigsaw/class loader magic' to build a Scala 2.12 project using embedded neo4j because I've had no success so far :+1:

**Comment by klobuczek** [comment] 2018-07-29 19:04
Just to add to @waxmittmann said. The problem is not only with building a Scala 2.12 project using embedded neo4j but also with adding Scala 2.12 built jar files with neo4j server extensions or procedures to standalone server.

**Comment by klobuczek** [comment] 2018-11-29 18:17
Today neo4j 3.5.0 has been released and guess what? It is still on scala 2.11. By now this is much more than disappointing.

**Comment by InverseFalcon** [comment] 2018-12-20 21:30
We're still on track for updating this with the next major release (4.0) within 2019. 

I think there was some confusion earlier mistaking our minor releases for major releases. As we use `major.minor.patch` versioning, we haven't had any major releases since 3.0 several years ago. 

I believe as a consequence this will require some changes to how backwards compatibility works with previous Cypher versions, as we won't be able to use the older scala versions, but our intent is to upgrade.

**Comment by Jorik5702** [comment] 2019-04-10 06:35
Is there a date when the problem will be fixed?

**Comment by boggle** [comment] 2019-04-10 14:47
This will be fixed in the next release of Neo4j. I will inform here once the first milestone is out. Sorry for the delay on this, as already described upgrading this was difficult due to supporting multiple versions of Cypher as a binary dependency.

**Comment by Jorik5702** [comment] 2019-04-11 06:29
The issue is no over two years old. It would be very nice if you could make a statement when this issue will be fixed.

**Comment by Tvaroh** [comment] 2019-04-11 07:33
What about Scala 2.13? :)

**Comment by sherfert** [comment] 2019-08-13 11:04
`Neo4j 4.0.0-alpha09mr02` has been released and can be downloaded [here](https://neo4j.com/download-center/). It uses scala 2.12

**Closed as completed by sherfert** 2019-08-13 11:04 UTC
Labels: question, team-cypher

**Comment by klobuczek** [comment] 2019-08-26 20:09
@sherfert since it is still in alpha could you go straight to scala 2.13 (released 2 months ago)? Otherwise it will take years again and we can keep this thread open right through the 4.0.0 release.

**Comment by Tvaroh** [comment] 2019-11-01 16:52
@sherfert are 2.12 artifacts published anywhere? Can't see them in Maven.

**Comment by dstibbe** [comment] 2019-11-15 09:36
Why on earth is this still an issue? This is basically going on since 2016 :(
