### ISSUE TITLE
Unknown command/entry type exception at shutdown

### ISSUE THREAD

**Issue by jnguyenx** [neo4j/neo4j#7204] opened 2016-05-23 23:37 UTC
I'm using Neo4j in embedded mode and am trying to upgrade to version 3.
After populating the database, I get weird exceptions when invoking the GraphDatabaseService#shutdown method. I did some research but couldn't find anything relevant to my issue.

Also, it gets stranger when I try to reduce the data set to reproduce the exception with a more reasonable runtime, it gets through the load process and succeeds. Therefore I don't really have a way to reproduce that apart from running a long load of several hours.

In hope to receive some hints, I'll paste 2 different logs which have been executed on 2 different machines. (Note that the exception message is different).

**Neo4j Version:** 3.0.1
**Java Version:** 1.8.0_91
**Maven Version:** 3.0.5
**Operating System:** Ubuntu 14.04

**First log:**

> [WARNING] 
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@4a7fe705' failed to stop. Please see attached cause exception.
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
>   at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
>   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
>   at io.scigraph.owlapi.loader.BatchOwlLoader$PostpostprocessorProvider.shutdown(BatchOwlLoader.java:190)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.loadOntology(BatchOwlLoader.java:158)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.load(BatchOwlLoader.java:203)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.main(BatchOwlLoader.java:233)
>   ... 6 more
>   Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@4bdf7742' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:497)
>       at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
>       ... 12 more
>   Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
>   neostore.counts.db.b (1 mapping)
>   neostore (1 mapping)
>   neostore.relationshipgroupstore.db (1 mapping)
>   neostore.schemastore.db (1 mapping)
>   neostore.labeltokenstore.db (1 mapping)
>   neostore.labeltokenstore.db.names (1 mapping)
>   neostore.relationshiptypestore.db (1 mapping)
>   neostore.relationshiptypestore.db.names (1 mapping)
>   neostore.relationshipstore.db (1 mapping)
>   neostore.propertystore.db (1 mapping)
>   neostore.propertystore.db.arrays (1 mapping)
>   neostore.propertystore.db.strings (1 mapping)
>   neostore.propertystore.db.index (1 mapping)
>   neostore.propertystore.db.index.keys (1 mapping)
>   neostore.nodestore.db (1 mapping)
>   neostore.nodestore.db.labels (1 mapping)
>       at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:539)
>       at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:489)
>       ... 13 more
> Caused by: java.lang.RuntimeException: java.io.IOException: Unknown command type[-123] near LogPosition{logVersion=30, byteOffset=24}
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:63)
>   at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
>   at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
>   at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:883)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   ... 19 more
> Caused by: java.io.IOException: Unknown command type[-123] near LogPosition{logVersion=30, byteOffset=24}
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.unknownCommandType(BaseCommandReader.java:76)
>   at org.neo4j.kernel.impl.transaction.command.PhysicalLogCommandReaderV2_0.read(PhysicalLogCommandReaderV2_0.java:76)
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:53)
>   at org.neo4j.kernel.impl.transaction.command.BaseCommandReader.read(BaseCommandReader.java:34)
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_0$4.parse(LogEntryParsersV2_0.java:135)
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryParsersV2_0$4.parse(LogEntryParsersV2_0.java:127)
>   at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:98)
>   at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:611)
>   at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:98)
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
>   ... 25 more

**Second log:**

> [WARNING] 
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@10344bf0' failed to stop. Please see attached cause exception.
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
>   at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
>   at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
>   at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
>   at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
>   at io.scigraph.owlapi.loader.BatchOwlLoader$PostpostprocessorProvider.shutdown(BatchOwlLoader.java:190)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.loadOntology(BatchOwlLoader.java:158)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.load(BatchOwlLoader.java:203)
>   at io.scigraph.owlapi.loader.BatchOwlLoader.main(BatchOwlLoader.java:233)
>   ... 6 more
>   Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@5af2ff6d' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:497)
>       at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
>       ... 12 more
>   Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
>   neostore.counts.db.a (1 mapping)
>   neostore (1 mapping)
>   neostore.relationshipgroupstore.db (1 mapping)
>   neostore.schemastore.db (1 mapping)
>   neostore.labeltokenstore.db (1 mapping)
>   neostore.labeltokenstore.db.names (1 mapping)
>   neostore.relationshiptypestore.db (1 mapping)
>   neostore.relationshiptypestore.db.names (1 mapping)
>   neostore.relationshipstore.db (1 mapping)
>   neostore.propertystore.db (1 mapping)
>   neostore.propertystore.db.arrays (1 mapping)
>   neostore.propertystore.db.strings (1 mapping)
>   neostore.propertystore.db.index (1 mapping)
>   neostore.propertystore.db.index.keys (1 mapping)
>   neostore.nodestore.db (1 mapping)
>   neostore.nodestore.db.labels (1 mapping)
>       at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:539)
>       at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
>       at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:489)
>       ... 13 more
> Caused by: java.lang.IllegalArgumentException: Unknown entry type 105 for version 0. At position LogPosition{logVersion=17, byteOffset=16} and entry version V2_0
>   at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.entryParser(LogEntryVersion.java:126)
>   at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:84)
>   at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:611)
>   at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:98)
>   at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
>   at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
>   at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
>   at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
>   at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:883)
>   at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
>   ... 19 more

**Comment by chrisvest** [comment] 2016-05-24 08:43
That is quite strange indeed.
- Do you make sure to close all transactions before shutting the database down?
  - This should not be a problem, but it's an easy mistake to make. Making sure all transactions are closed will help the database shut down quicker.
- Do you use internal APIs?
  - If so, don't.
- Do you mess with the log files in your code or in your environment in any way?
  - If so, don't. Don't ever touch the store files, and don't ever touch the transaction log files. Review your log pruning configuration instead.

Let me know if any of these ring a bell.

**Comment by jnguyenx** [comment] 2016-05-26 07:20
Thanks for the suggestions. Unfortunately I'm clean on those points.

The biggest headache for me when moving to Neo4j 2.x to 3.x was my custom Lucene index analyzer. Maybe that's the issue.

I'm setting the custom lucene index analyzer as in Neo4j 2.x, [like this](https://github.com/SciGraph/SciGraph/blob/neo4j-3/SciGraph-core/src/main/java/io/scigraph/neo4j/Neo4jModule.java#L83). My issue came for the definition of the analyzer. I use a PerField analyzer wrapper, and need to call the right analyzer depending on the field. In Lucene 5.x some methods visibility changed and it was not clear how to do that. [I ended up using reflection](https://github.com/SciGraph/SciGraph/blob/neo4j-3/SciGraph-core/src/main/java/io/scigraph/lucene/VocabularyIndexAnalyzer.java#L99), which might not be the ideal.

Let me know if you think that it can cause issues.

**Comment by tinwelint** [comment] 2016-05-27 08:07
Is there a possibility that you have transactions that update legacy indexes with more than 127 different property keys? I was thinking about https://github.com/neo4j/neo4j/pull/7213

**Comment by jnguyenx** [comment] 2016-05-29 05:06
I don't think that I have that much property keys, maybe 20 at most.

I'm currently running neo4j 2.2.8 and haven't encountered the issue described in https://github.com/neo4j/neo4j/pull/7213, so I don't think that it's related.

**Comment by tinwelint** [comment] 2016-05-30 05:02
The log (at least the parser) says that the log entries comes from a 2.0.x store, although you say you run on 2.2.8. Is it possible for you to send your db to me directly so that I can analyze it?

**Comment by jnguyenx** [comment] 2016-05-31 08:44
Interesting, I'm wondering where this 2.0.x version is coming from.

The project I'm working on populate a Neo4j db from static files. The production is currently running on 2.2.8 and I was experimenting with 3.0.1, with a fresh reload. It's even weirder to have this log entry version to 2.

Here's the [current graph on 2.2.8](https://scigraph-data.monarchinitiative.org/static_files/scigraph.tgz) for reference. And here's [my test with 3.0.1](https://scigraph-data.monarchinitiative.org/static_files/scigraph_neo3_0_3.tgz), however I don't know its state as the load exited upon the shutdown exception.

Thanks for looking into this, I really appreciate the help!

**Comment by jnguyenx** [comment] 2016-06-17 23:17
@tinwelint I've upgraded to 3.0.3, but still have the exception.
I've checked my dependencies, every neo4j-\* are at version 3.0.3 except neo4j-cypher-compiler which is at 2.3.4. It comes from neo4j-cypher:3.0.3, not sure how relevant it is for this issue though.

Here's the [updated graph](https://scigraph-data.monarchinitiative.org/static_files/scigraph_neo3_0_3.tgz). 

`
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@40366b3f' failed to stop. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:466)
    at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.stop(DataSourceManager.java:119)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
    at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
    at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
    at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
    at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:158)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:324)
    at io.scigraph.owlapi.loader.BatchOwlLoader$PostpostprocessorProvider.shutdown(BatchOwlLoader.java:190)
    at io.scigraph.owlapi.loader.BatchOwlLoader.loadOntology(BatchOwlLoader.java:158)
    at io.scigraph.owlapi.loader.BatchOwlLoader.load(BatchOwlLoader.java:203)
    at io.scigraph.owlapi.loader.BatchOwlLoader.main(BatchOwlLoader.java:233)
    ... 6 more
    Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Failed to transition component 'org.neo4j.kernel.impl.pagecache.PageCacheLifecycle@1177043a' from STOPPED to SHUTTING_DOWN. Please see attached cause exception
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:497)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:206)
        ... 12 more
    Caused by: java.lang.IllegalStateException: Cannot close the PageCache while files are still mapped:
    neostore.counts.db.a (1 mapping)
    neostore (1 mapping)
    neostore.relationshipgroupstore.db (1 mapping)
    neostore.schemastore.db (1 mapping)
    neostore.labeltokenstore.db (1 mapping)
    neostore.labeltokenstore.db.names (1 mapping)
    neostore.relationshiptypestore.db (1 mapping)
    neostore.relationshiptypestore.db.names (1 mapping)
    neostore.relationshipstore.db (1 mapping)
    neostore.propertystore.db (1 mapping)
    neostore.propertystore.db.arrays (1 mapping)
    neostore.propertystore.db.strings (1 mapping)
    neostore.propertystore.db.index (1 mapping)
    neostore.propertystore.db.index.keys (1 mapping)
    neostore.nodestore.db (1 mapping)
    neostore.nodestore.db.labels (1 mapping)
        at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.close(MuninnPageCache.java:539)
        at org.neo4j.kernel.impl.pagecache.PageCacheLifecycle.shutdown(PageCacheLifecycle.java:42)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.shutdown(LifeSupport.java:489)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Unknown entry type 9 for version 0. At position LogPosition{logVersion=17, byteOffset=16} and entry version V2_0
    at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.entryParser(LogEntryVersion.java:141)
    at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:84)
    at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:617)
    at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:98)
    at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
    at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
    at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
    at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
    at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
    at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:889)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:458)
`

**Comment by jnguyenx** [comment] 2016-07-11 21:50
@tinwelint I'm still trying to find a solution for this issue. I've checked again but couldn't find where this V2.x is coming from.

Is it possible that it comes from the deprecated AutoIndexer? I'm still using the NodeAutoIndexer and haven't migrated to Schema indexes yet.

https://github.com/SciGraph/SciGraph/blob/neo4j-3/SciGraph-core/src/main/java/io/scigraph/neo4j/Neo4jModule.java#L86

**Comment by jnguyenx** [comment] 2016-07-12 04:49
Find my attempts to load data on 2 different machines. I upgraded to Neo4j 3.1.0-M4, the 2 loads use the same code base but the errors are different.

[First load](http://data.monarchinitiative.org/neo4j/scigraph_310m04-failed.tgz)
`Caused by: java.lang.IllegalArgumentException: Unknown entry type -1 for version -1. At position LogPosition{logVersion=1, byteOffset=16} and entry version V2_1
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.entryParser(LogEntryVersion.java:141)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:84)
        at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:616)
        at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:97)
        at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
        at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
        at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
        at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:887)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:457)
        ... 19 more
`

[Second load](http://data.monarchinitiative.org/neo4j/scigraph_310m04-failed-tartini.tgz)
`Caused by: java.lang.IllegalArgumentException: Unknown entry type 9 for version 0. At position LogPosition{logVersion=23, byteOffset=16} and entry version V2_0
        at org.neo4j.kernel.impl.transaction.log.entry.LogEntryVersion.entryParser(LogEntryVersion.java:141)
        at org.neo4j.kernel.impl.transaction.log.entry.VersionAwareLogEntryReader.readLogEntry(VersionAwareLogEntryReader.java:84)
        at org.neo4j.kernel.NeoStoreDataSource$2.getTimestampForVersion(NeoStoreDataSource.java:616)
        at org.neo4j.kernel.impl.transaction.log.PhysicalLogFileInformation.getFirstStartRecordTimestamp(PhysicalLogFileInformation.java:97)
        at org.neo4j.kernel.impl.transaction.log.pruning.EntryTimespanThreshold.reached(EntryTimespanThreshold.java:54)
        at org.neo4j.kernel.impl.transaction.log.pruning.ThresholdBasedPruneStrategy.prune(ThresholdBasedPruneStrategy.java:68)
        at org.neo4j.kernel.impl.transaction.log.pruning.LogPruningImpl.pruneLogs(LogPruningImpl.java:54)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.doCheckPoint(CheckPointerImpl.java:224)
        at org.neo4j.kernel.impl.transaction.log.checkpoint.CheckPointerImpl.forceCheckPoint(CheckPointerImpl.java:114)
        at org.neo4j.kernel.NeoStoreDataSource.stop(NeoStoreDataSource.java:887)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:457)
        ... 19 more
`

**Comment by jnguyenx** [comment] 2016-08-04 17:58
By disabling the custom Lucene analyzer the DB loads successfully in a consistent manner.

Basically I removed the following configuration:
`private static final Map<String, String> INDEX_CONFIG = MapUtil.stringMap(IndexManager.PROVIDER,
      "lucene", "analyzer", VocabularyIndexAnalyzer.class.getName());`

I use this to provide full text search. Is this feature still supported in Neo4j 3.x?

**Comment by tinwelint** [comment] 2016-09-07 10:49
The cause of this issue has now been found and a fix is being worked on. Basically this is about log rotation sometimes rotating in the middle of a transaction and later on recovery not reading properly across log files, but read each file individually... which would have it see half transactions.

**Comment by jnguyenx** [comment] 2016-09-07 17:08
Glad to see that, let me know if I can help for testing.

**Comment by jnguyenx** [comment] 2016-11-08 17:10
@tinwelint I've been doing some testing with 3.0.7, so far so good!

**Comment by MishaDemianenko** [comment] 2016-11-28 17:56
@jnguyenx I suppose everything went fine :) Can we close this issue?

**Comment by jnguyenx** [comment] 2016-11-28 18:47
Yes, I did many successful loads. Thanks!

**Comment by MishaDemianenko** [comment] 2016-11-28 20:42
Thx! Closing

**Closed as completed by MishaDemianenko** 2016-11-28 20:42 UTC
Labels: 3.0, team-kernel
