### ISSUE TITLE
Variable shadowing error when using "with p" in exists{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13222] opened 2023-06-20 14:26 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:match p=(a)-[]-() with p where exists{with p} return 1
error message:
Neo.ClientError.Statement.SyntaxError
The variable `p` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 38 (offset: 37))
"match p=(a) with p where exists{with p} return 1"
                                      ^

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by sherfert** [comment] 2023-06-26 08:24
Hello @ljhhuxiaoba and thanks for the report.

This is expected behavior.

The [documentation](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#cypher-subquery-expressions) says that "Any variable that is defined in the outside scope can be referenced inside the subquery’s own scope.". This means `p` can be referenced anywhere.

`WITH p`, however, declares a _new_ variable called `p`, which would shadow the outer variable, which is also called `p`.
It is equivalent to `WITH p AS p`. Shadowing in subquery expressions is forbidden because it can easily lead to confusion.

Please note that rules are unfortunately different for `CALL` subqueries, where one needs to use an "Importing WITH" to import variables into the subquery scope.

I hope this clears the issue. Let me know if there are any further questions.

**Comment by ljhhuxiaoba** [comment] 2023-06-26 10:02
But another query "match p=(a)-[]-() with p where exists{with a} return 1"can run successfully,and I am confused why there is difference between "with a" and "with p" in exists{}.

**Comment by sherfert** [comment] 2023-06-26 11:01
Thanks @ljhhuxiaoba 

You are right. The second query you just provided should also fail with the same error message.
We will investigate why it doesn't and update this issue with more information later.

**Comment by ljhhuxiaoba** [comment] 2023-06-26 13:01
And it is strange that query "match p=(a)-[]-() where exists{with p} return 1"  also can run successfully.

**Comment by gem-neo4j** [comment] 2023-08-01 13:53
Hi, this has now been fixed and should be released in the next release (5.11).

Using `WITH p` inside an EXISTs isn't shadowing, so the first query erroring was the issue here and has been fixed :) Thanks for reporting!

**Closed as completed by gem-neo4j** 2023-08-01 13:53 UTC
Labels: bug, cypher, team-cypher
