### ISSUE TITLE
`Docker compose` can't connect to database from back-end server running in docker compose

### ISSUE THREAD

**Issue by Parthiba-Hazra** [neo4j/neo4j#13381] opened 2024-01-13 16:28 UTC
Cant connect to neo4j database from backend container running in same docker compose .. may be something wrong with my `DATABASE_URL` env. I also tried putting IP address to the url manually.

docker-compose.yaml - 
```
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.rust
    environment:
      - DATABASE_URL=bolt://neo4j:neo12345@neo4j:7687
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.react
    ports:
      - "8081:8081"
    depends_on:
      - backend

  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo12345"

```

create client function - 
```
async fn create_neo4j_client() -> Result<Graph, neo4rs::Error> {

    let x = "DATABASE_URL";
    let mut database_url = String::new();
    match env::var(x) {
        Ok(value) => {
            database_url = value;
            log::info!("The value of {} is: {}", x, database_url)
        } 
        Err(_) => {
            log::error!("{} is not set.", x)
        }
    }

    let config = ConfigBuilder::default()
        .uri(&database_url)
        .user(NEO4J_USER)
        .password(NEO4J_PASS)
        .db("neo4j")
        .fetch_size(500)
        .max_connections(10)
        .build()?;
    
    Graph::connect(config).await
}
```
OS - Ubuntu:23.10

**Comment by jamthief** [comment] 2024-10-28 10:33
Hi Parthiba,

Thanks for taking the time to post this! Sorry it hasn't been answered yet.

Since this github issues space is exclusively for reporting bugs in Neo4j, we would require more specific details around the problem you are having before being able to investigate it. If you have a specific bug you would like to report, it would be helpful if you could provide some of the following so we can investigate further:

- stacktraces / logs showing the nature of the error
- example data and/or a zipped database store with a query that can reliably reproduce the problem

Otherwise, here are some resources that you can use to get answers to more qualitative questions:

- [Neo4j community forums](https://community.neo4j.com/)
- [Neo4j discord servers](https://discord.com/invite/neo4j)
- [Neo4j Aura support](https://support.neo4j.com/s/), if your question relates to an issue with an Aura database
- [Neo4j docs](https://neo4j.com/docs/) can be useful if you prefer to research the problem yourself
- 
I'll close this question for now, but please reopen it if you want to provide more information for a specific bug you've found.

**Closed as completed by jamthief** 2024-10-28 10:33 UTC
Labels: question, need-more-info
