### ISSUE TITLE
Improper UNWIND handling

### ISSUE THREAD

**Issue by Aurora-yzj** [neo4j/neo4j#13364] opened 2023-12-06 09:59 UTC
I discovered a bug where Neo4j returns an empty query result, even though it should return something. 
**Neo4j Version:**
5.14.0 Community
**Operating System:**
Ubuntu 22.04
**API:**
Docker

## Steps to reproduce

1. Pull the image: `docker pull neo4j`
2. Create a directory on the host that will be a mount for the data: `mkdir $HOME/neo4j-data`
3. Start a new container that mounts to this directory: `sudo docker run -d --name neo4j-test -p 17474:7474 -p 17687:7687 -v $HOME/neo4j-data:/data neo4j`
4. Go to the web interface at "[http://127.0.0.1:17474/](http://127.0.0.1:17474/)", login and execute the following series of queries to build the database:

```
CREATE (n0 :L17{k110 : -1527042861, k112 : "Wd3BcZrK", k111 : "OqIFds2", k113 : "OIOlb6nP", id : 5, k107 : "vh8Naa7", k109 : "Pqyzm7ga", k108 : 128394918})
CREATE (n0 :L17{k110 : 1895959948, k112 : "8FfsNm50E", k111 : "cqtnkTnUN", id : 8, k107 : "dMlro", k109 : "hktKiO", k108 : 1298126172})
CREATE (n0 :L17:L4{k31 : "En8Ma", k30 : false, k32 : "Umtaux2q", k28 : "pzns2d", k27 : false, k29 : -609934210, k110 : 1118227467, k112 : "tsTrZB9", k111 : "stFV9S", k113 : "MHs4jVEi", id : 11, k107 : "iGZTmjTiC", k109 : "Az1ihMo", k108 : 1286268367})
CREATE (n0 :L17{k110 : -718103699, k112 : "DU1ohnlTu", k111 : "GTsMwF", k113 : "DejHiV", id : 7, k107 : "4PK8bf0", k109 : "tZsKg", k108 : -543128698})
CREATE (n0 :L17:L4{k31 : "rFnRA", k30 : false, k32 : "R5QXTH", k28 : "6uRnTGUC", k27 : true, k29 : -2037613127, k110 : 1740083984, k112 : "ddt9ji0nt", k111 : "DQfJTZ", k113 : "bsR7Lz", id : 13, k107 : "h1i1uksQ", k109 : "Na4eh1", k108 : -1233986597})
CREATE (n0 :L17{k110 : -1376162976, k112 : "TRAgnCss", k111 : "5YIHBENy", k113 : "kao6BQ", id : 14, k107 : "aIYNlbi", k109 : "8utG8", k108 : -1175534054})
CREATE (n0 :L17{k110 : 542733146, k112 : "dc9kjIX", k111 : "8KcxOC", k113 : "XwpVuj0W", id : 3, k109 : "DH9gxVD", k108 : -2027127311})
CREATE (n0 :L17:L4{k31 : "YnrvOE", k30 : true, k32 : "D5Eid", k28 : "nMmGZs4OO", k27 : false, k29 : 1795880421, k110 : -1817876698, k112 : "yXvjgn4", k111 : "EsKmTk", k113 : "t97wVar", id : 2, k107 : "IgRdJzoe", k108 : -100828713})
CREATE (n0 :L17{k110 : -718103699, k112 : "DU1ohnlTu", k111 : "GTsMwF", k113 : "DejHiV", id : 7, k107 : "4PK8bf0", k109 : "tZsKg", k108 : -543128698})
MATCH (n0 {id : 3}), (n1 {id : 14}) MERGE(n0)-[r :T14{k251 : true, k250 : "5nAl8", k248 : -398247127, id : 24, k247 : -1745802246, k249 : "uXiUbdm9"}]->(n1)
MATCH (n0 {id : 13}), (n1 {id : 7}) MERGE(n0)-[r :T14{k251 : false, k250 : "SaGpgdPs", k248 : 208363691, id : 19, k247 : 976606318, k249 : "btHJB4jsQ"}]->(n1)
MATCH (n0 {id : 7}), (n1 {id : 11}) MERGE(n0)-[r :T14{k251 : true, k250 : "5yj1vE6", k248 : -700965781, id : 28, k247 : 2140150759, k249 : "a5EtwO3tV"}]->(n1)
MATCH (n0 {id : 5}), (n1 {id : 8}) MERGE(n0)-[r :T14{k251 : false, k250 : "R49YIR", k248 : 537040311, id : 21, k247 : -190564245, k249 : "Tlj4C"}]->(n1)
MATCH (n0 {id : 3}), (n1 {id : 2}) MERGE(n0)-[r :T14{k251 : false, k250 : "EkJOMho", k248 : -630935088, id : 30, k247 : -278122580, k249 : "J3hIRFl"}]->(n1)
MATCH (n0 {id : 3}), (n1 {id : 8}) MERGE(n0)-[r :T14{k251 : true, k250 : "D0iWfRJYt", k248 : 1848088589, id : 29, k247 : -1353879882, k249 : "yd6yM"}]->(n1)
```

## **Expected behavior**

The following query should return the result `{a5:-630935088}`. Detailed analysis is shown in the following.

```
MATCH (n0 :L17)-[r0 :T14]->(n1) WHERE ((r0.k248) = 1848088589) AND ((n1.k112) = '8FfsNm50E')
WITH DISTINCT n1
MATCH (n5)-[r4 :T14]->(n1), (n4 :L17)<-[r5 :T14]-(n3 :L17)<-[r6 :T14]-(n6 :L17 :L4), (n2)<-[r7 :T14]-(n0) WHERE (((n6.k112) <> ((n3.k113)+(n1.k109))) AND ((((((((((((n5.k110) = -1527042861) AND ((r4.k248) = 537040311)) AND ((n1.k109) = 'hktKiO')) AND ((n4.k109) = 'Az1ihMo')) AND ((r5.id) = 28)) AND ((n3.k111) = 'GTsMwF')) AND ((r6.k249) = 'btHJB4jsQ')) AND ((n6.k112) = 'ddt9ji0nt')) AND ((n2.id) = 14)) AND ((r7.k248) = -398247127)) AND ((n0.k111) = '8KcxOC'))) 
UNWIND [n3.k110] as a4
MATCH (n0)-[r8 :T14]->(n7 :L17) WHERE (((((n0.k113) = 'XwpVuj0W') AND ((r8.k248) = -630935088)) AND ((n7.k113) = 't97wVar')) AND ((n3.k110) = -718103699)) 
RETURN (r8.k248) AS a5
```

## Actual Behavior

It returns empty results:
![2023-12-03_11-23 (1)](https://github.com/neo4j/neo4j/assets/24768784/83535500-c2cb-4efb-8389-f9eff4cad479)
The root cause I guess could be related to the `UNWIND` parsing, since if I remove the `UNWIND` clause, it works properly:

```
MATCH (n0 :L17)-[r0 :T14]->(n1) WHERE ((r0.k248) = 1848088589) AND ((n1.k112) = '8FfsNm50E')
WITH DISTINCT n1
MATCH (n5)-[r4 :T14]->(n1), (n4 :L17)<-[r5 :T14]-(n3 :L17)<-[r6 :T14]-(n6 :L17 :L4), (n2)<-[r7 :T14]-(n0) WHERE (((n6.k112) <> ((n3.k113)+(n1.k109))) AND ((((((((((((n5.k110) = -1527042861) AND ((r4.k248) = 537040311)) AND ((n1.k109) = 'hktKiO')) AND ((n4.k109) = 'Az1ihMo')) AND ((r5.id) = 28)) AND ((n3.k111) = 'GTsMwF')) AND ((r6.k249) = 'btHJB4jsQ')) AND ((n6.k112) = 'ddt9ji0nt')) AND ((n2.id) = 14)) AND ((r7.k248) = -398247127)) AND ((n0.k111) = '8KcxOC'))) 
// UNWIND [n3.k110] as a4
MATCH (n0)-[r8 :T14]->(n7 :L17) WHERE ((((((((((n0.k113) = 'XwpVuj0W') AND ((r8.k248) = -630935088)) AND ((n7.k113) = 't97wVar')) AND ((n3.k110) = -718103699))))))) 
RETURN (r8.k248) AS a5
```

![2023-12-03_11-24 (1)](https://github.com/neo4j/neo4j/assets/24768784/5806a772-256b-4f21-830c-7d6213b83c8f)

And the value included in the `UNWIND` is a normal number, as can be demonstrated through the following query, in which I only keep the first three clauses and let it return the value `n3.k110` which is originally included in `UNWIND`:

```
MATCH (n0 :L17)-[r0 :T14]->(n1) WHERE ((r0.k248) = 1848088589) AND ((n1.k112) = '8FfsNm50E')
WITH DISTINCT n1
MATCH (n5)-[r4 :T14]->(n1), (n4 :L17)<-[r5 :T14]-(n3 :L17)<-[r6 :T14]-(n6 :L17 :L4), (n2)<-[r7 :T14]-(n0) WHERE (((n6.k112) <> ((n3.k113)+(n1.k109))) AND ((((((((((((n5.k110) = -1527042861) AND ((r4.k248) = 537040311)) AND ((n1.k109) = 'hktKiO')) AND ((n4.k109) = 'Az1ihMo')) AND ((r5.id) = 28)) AND ((n3.k111) = 'GTsMwF')) AND ((r6.k249) = 'btHJB4jsQ')) AND ((n6.k112) = 'ddt9ji0nt')) AND ((n2.id) = 14)) AND ((r7.k248) = -398247127)) AND ((n0.k111) = '8KcxOC'))) 
RETURN n3.k110 // Show the value that is originally inside UNWIND clause
// UNWIND [n3.k110] as a4
// MATCH (n0)-[r8 :T14]->(n7 :L17) WHERE ((((((((((n0.k113) = 'XwpVuj0W') AND ((r8.k248) = -630935088)) AND ((n7.k113) = 't97wVar')) AND ((n3.k110) = -718103699))))))) 
// RETURN (r8.k248) AS a5
```

![2023-12-03_11-25 (1)](https://github.com/neo4j/neo4j/assets/24768784/5b10bf58-2aac-4eef-99e9-7d33ab34da73)

This shows that the UNWIND should work appropriatly with a number included, but in reality it causes the query to return empty result. 

Thank you so much for your help!

**Comment by JonasHolgersson** [comment] 2024-01-15 10:48
Duplicate of https://github.com/neo4j/neo4j/issues/13359

**Closed as completed by JonasHolgersson** 2024-01-15 10:48 UTC
Labels: bug, team-cypher
