### ISSUE TITLE
Surprised error for unknown packed value

### ISSUE THREAD

**Issue by yeoh-ong** [neo4j/neo4j#10339] opened 2017-10-23 11:31 UTC
Hello. Thank you for wonderful Neo4j graph database! My company use Neo4j graph database for reporting system. We use javascript program for sending data. Suddenly clients very often failing with error for unknown packed value. I attach error message. Can you tell me how to fix? We use latest Neo4j.

[cerberr.txt](https://github.com/neo4j/neo4j/files/1406878/cerberr.txt)

**Comment by technige** [comment] 2018-02-19 11:01
Hi @yeoh-ong - thanks for raising this, we'll have a look into it. Could I ask that you raise any future issues with the driver in the appropriate repository? Thanks :)

**Comment by lutovich** [comment] 2018-04-24 14:58
Hi @yeoh-ong,

Do you still experience this problem? Could you please attach `debug.log` and `neo4j.log` to this issue? It would be valuable to see if database logs anything when such error happens in the driver.

I suspect this error can be caused by the same problem as described in https://github.com/neo4j/neo4j-javascript-driver/issues/328 and fixed in https://github.com/neo4j/neo4j/pull/11336.

Which neo4j version are you using? Could you please check if transaction timeout is enabled?

Thanks and sorry for the delayed response!

**Comment by yeoh-ong** [comment] 2018-04-24 18:24
Thank you for reply!! We fixed problem by removing all bytes properties from neo4j and using a other database for these datas.

**Comment by lutovich** [comment] 2018-04-24 20:54
@yeoh-ong okay, glad you found a solution. We've recently added byte arrays support in the database https://github.com/neo4j/neo4j/pull/9150 which are exposed as `Int8Array`s in the JavaScript driver. You might want to experiment with them :)

I'll close this issue now. Please feel free to update it if this issue happens again.

**Closed as completed by lutovich** 2018-04-24 20:54 UTC
Labels: team-drivers
