### ISSUE TITLE
Label disjunction in `WHERE` clause causes unnecessary `AllNodesScan`

### ISSUE THREAD

**Issue by jjaderberg** [neo4j/neo4j#5002] opened 2015-07-20 08:49 UTC
Both rule and cost query planners implement

```
MATCH n
WHERE n:Male
RETURN n
```

with a `NodeByLabelScan` and not with an `AllNodesScan` plus a filter on the label. I therefore would expect

```
MATCH n
WHERE n:Male OR n:Female
RETURN n
```

to be implemented with two `NodeByLabelScan`'s. Instead both planners use an `AllNodesScan` and then a filter.

For a simple label disjunction like this, would it not be possible and prudent for the planners to implement the query with label scans?

Related [SO question](http://stackoverflow.com/questions/20003769/neo4j-match-multiple-labels-2-or-more).

**Comment by tbaum** [comment] 2015-07-21 11:05
+1 

having a syntax like

```
MATCH (n:Female | Male) 
RETURN n
```

would be neat

**Comment by thobe** [comment] 2015-07-21 11:18
@tbaum the problem is not about syntax, even with a syntax like that, the problem would be the same.

The reason the Cypher planner solves this by an `AllNodesScan` and a filter is because that is the semantically correct thing to do. What you are asking for is all nodes that have either the `Male` label or the `Female` label, and that means that the nodes that have both the `Male` label and the `Female` label should only be included once.

The Cypher planner does not have any insight into whether your data actually has any nodes or not that has both the `Male` and `Female` labels, and thus cannot use a plan that only uses two `NodeByLabelScan` operators.

We hope to have data statistics about such things (label overlap) in future versions of Neo4j to allow the Cypher planner to make such optimisations, but as always it is but one item on a long list of features.

If we were to support solving this query by `NodeByLabelScan` operators in the case where there might be overlap between the labels, this would have to involve a few more operators:
1. Find all nodes that have the `Male` label and all nodes that have the `Female` label.
2. Sort these two collections of nodes by something that orders them both in the same way (for example the internal node id).
3. Merge the two collections to omit duplicates.

**Comment by jexp** [comment] 2015-07-22 04:44
So kind of what union would do?

```
MATCH (n:Male) return n
UNION
MATCH (n:Female) return n
```

**Comment by spacecowboy** [comment] 2015-12-16 10:01
Closing. Working as intended.

**Comment by henricook-valtech** [comment] 2016-02-15 12:14
This is enormously inefficient, and a big problem - i can't perform effective multi-label OR lookups without writing loads of UNIONs - are you really closing it for good @spacecowboy ?

**Comment by henricook** [comment] 2016-02-15 12:37
This is enormously inefficient, and a big problem - i can't perform effective multi-label OR lookups without writing loads of UNIONs - are you really closing it for good @spacecowboy ?

**Comment by spacecowboy** [comment] 2016-02-15 16:37
@henricook perhaps that was a bit rash. We can keep it open as a feature request as a reminder.

**Comment by henricook** [comment] 2016-02-15 16:50
Thanks @spacecowboy! Good engagement, in case anyone comes up with better workarounds the only way i've found of doing good multi label OR based matches before a create (my specific use case) was to use a big blob of optional matches, ugly but much much more efficient. 

My query with WHEREs on labels was taking 3000 seconds to execute (because WHEREs weren't using an index), doing it with the optional match method took it down to 5 seconds - so a marked improvement.

The optional match method was detailed in an SO post: http://stackoverflow.com/questions/20003769/neo4j-match-multiple-labels-2-or-more

**Comment by Lojjs** [comment] 2017-10-05 13:28
Like @thobe wrote above, we in the Cypher Team have noticed this issue but it is only one of many items on a long list of feature requests. Right now, this is not a priority feature but let me come back to you if that changes.

**Comment by DachuanZhao** [comment] 2019-09-25 07:22
@Lojjs Is there any progress now?

**Comment by Lojjs** [comment] 2019-10-04 10:58
@DachuanZhao We deem this to be quite much work for a low benefit so it is unfortunately not a priority anytime soon but still on our radar of potential improvements.

**Comment by boggle** [comment] 2019-11-01 11:33
Shouldn't it be possible to at least solve this with two label scans where on one of the scans nodes that have both labels are removed to avoid duplicates as an interim improvement?

**Comment by boggle** [comment] 2019-11-01 11:35
In order to make an educated guess wether that's reasonable (in comparison to the all nodes scan) one could look at per-label cardinalities. Or rather the query planner will do that already when comparing both plans.

**Comment by jetsloan** [comment] 2020-02-27 11:42
MATCH (n:Female | Male) 
RETURN n

We really need this functionality for our system.
Imagine a user has predefined labels and he wants to find his data.
When querying  his data, if he wants to see/act on the data within his defined labels. Either using one or another or multiple labels. 
Current solutions include UNION and WHERE clauses. This means we need to write basically double the query every time. 
Please could we get this feature

**Comment by jexp** [comment] 2020-02-28 15:08
You should be able to do in 4.0

```
call {
MATCH (n:Female) RETURN n
UNION
MATCH (n:Male ) RETURN n
} 
WHERE
WITH ...
RETURN ...
... your remainder of the query

```

**Comment by jetsloan** [comment] 2020-02-28 15:36
Yes this is a good solution, but it forces you to return on every single sub query. 
Secondly what if you doing pattern matching in a where clause? You'll have to write that out for every pattern that you want to match:
i.e. 
```
call {
MATCH (n:Female)
WHERE (n)--(a:Person)
RETURN n,a
UNION
MATCH (n:Male)
WHERE (n)--(a:Person) 
RETURN n,a
}
```
The reason I would need to duplicate the pattern where is this query is generated based on a users allowed labels. I am aware you could do this outside the union. This a very simple example that can be exponentially more complex.

Where as this:

```
MATCH (n:Female | Male) 
WHERE (n)--(a:Person)
RETURN n,a
```
Is so easy to read and equally easy to use and generate.

It exists for the relationships and I don't think asking for it in nodes is an unfair or unnecessary request.

**Comment by jexp** [comment] 2020-02-28 15:55
It's a sensible request, I was just pointing out variant that doesn't need full duplication right now.

You can pull all the other operations after the union.

```
call {
MATCH (n:Female) RETURN n
UNION
MATCH (n:Male) RETURN n
}
MATCH (n)--(a:Person)
RETURN n,a
```
you can also just spell it out like this:

```
MATCH (n) WHERE n:Female OR n:Male
MATCH (n)--(a:Person)
RETURN n,a
```

**Comment by jetsloan** [comment] 2020-02-28 16:03
Yes I understand that it can be done writing the query out manually like that.
My problem is not with the manual writing of the query, I am generating a cypher based on one or more labels the user has selected.

So they may want to query based on 1 or another label and then create something with both of those labels. This level of dynamism would enable a huge amount of flexibility.
I've been trying to generate this for a while and it's become very messy and unmanageable.

I would maybe even need to show you our code and the system we are trying to build to prove that we need this greatly. Which I am willing to do, not asking this due to lack of knowledge of cypher but an actual feature we need.

This has lead us to have a hard constraint of only being able to create with 1 label, because of this.
Unfortunately we won't be able to implement the best solution due to this limitation that neo4j has.

We would greatly appreciate this feature, to be honest I would even volunteer to help implement it. 
As it would mean less work for us in the future.

**Comment by jexp** [comment] 2020-02-28 21:27
The Where OR solution is very well suited for generation

**Comment by jetsloan** [comment] 2020-02-28 22:15
It's not when you have pattern matching in the WHERE and the pattern needs to have an OR on the label as well as the original node that you're MATCHing. 
You have to use brackets to capture all the possibilities. It becomes complex, ugly to read and difficult to script. 
An | in the MATCH would make this exponentially simpler and easier to read. 
And would follow the same pattern for ORing on a relationship. 
Simple queries are easier to maintain, read and use. That's a fact.

**Comment by sherfert** [comment] 2021-02-18 10:48
On the original issue:

```
MATCH n
WHERE n:Male OR n:Female
RETURN n
```

is planned with two `NodeByLabelScan`, joined together with a `Union` followed by a `Distinct`.
This has been the produced plan for years now.

In the upcoming 4.3 release, we will improve upon that by taking advantage of the `NodeByLabelScan`s being ordered by node id, to specialize the `Union` and `Distinct` implementations.

I will close this issue since the original problem has been fixed.

---

With respect to other requests mentioned in comments, specifically new syntax for Label disjunctions, please open a new ticket.

**Closed as completed by sherfert** 2021-02-18 10:48 UTC
Labels: feature, cypher, team-clg
