### ISSUE TITLE
 Client triggered an unexpected error [UnknownError]: null, reference 23d7ba6e-88ce-4579-8429-bd53b1cce240

### ISSUE THREAD

**Issue by Meatballs1** [neo4j/neo4j#10317] opened 2017-10-18 19:11 UTC
```
2017-10-18 18:55:10.227+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 301ms.
2017-10-18 18:55:12.670+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 340ms.
2017-10-18 18:56:03.154+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 232ms.
2017-10-18 18:56:08.716+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 23d7ba6e-88ce-4579-8429-bd53b1cce240.
2017-10-18 18:56:08.716+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: null, reference 23d7ba6e-88ce-4579-8429-bd53b1cce240.
java.lang.NullPointerException
        at org.neo4j.cypher.internal.spi.v3_2.TransactionBoundQueryContext.getRelationshipsForIds(TransactionBoundQueryContext.scala:134)
        at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$$anonfun$getRelationshipsForIds$1.apply(ExceptionTranslatingQueryContext.scala:195)
        at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext$$anonfun$getRelationshipsForIds$1.apply(ExceptionTranslatingQueryContext.scala:195)
        at org.neo4j.cypher.internal.spi.v3_2.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:32)
        at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:34)
        at org.neo4j.cypher.internal.compatibility.v3_2.ExceptionTranslatingQueryContext.getRelationshipsForIds(ExceptionTranslatingQueryContext.scala:195)
        at org.neo4j.cypher.internal.compiler.v3_2.spi.DelegatingQueryContext.getRelationshipsForIds(DelegatingQueryContext.scala:69)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe$Expandable$class.expand(PruningVarLengthExpandPipe.scala:300)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe$PrePruningDFS.expand(PruningVarLengthExpandPipe.scala:81)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe$PrePruningDFS.next(PruningVarLengthExpandPipe.scala:98)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe$LoadNext.next(PruningVarLengthExpandPipe.scala:270)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe$$anon$1.<init>(PruningVarLengthExpandPipe.scala:340)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PruningVarLengthExpandPipe.internalCreateResults(PruningVarLengthExpandPipe.scala:338)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:82)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:33)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.ApplyPipe$$anonfun$internalCreateResults$1.apply(ApplyPipe.scala:30)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.EagerAggregationPipe.internalCreateResults(EagerAggregationPipe.scala:89)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:82)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.pipes.PipeWithSource.createResults(Pipe.scala:79)
        at org.neo4j.cypher.internal.compiler.v3_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:97)
        at org.neo4j.cypher.internal.compiler.v3_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:75)
        at org.neo4j.cypher.internal.compiler.v3_2.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:103)
        at org.neo4j.cypher.internal.compiler.v3_2.BuildInterpretedExecutionPlan$$anonfun$getExecutionPlanFunction$1.apply(BuildInterpretedExecutionPlan.scala:86)
        at org.neo4j.cypher.internal.compiler.v3_2.BuildInterpretedExecutionPlan$$anon$1.run(BuildInterpretedExecutionPlan.scala:55)
        at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:103)
        at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$ExecutionPlanWrapper$$anonfun$run$1.apply(Compatibility.scala:101)
        at org.neo4j.cypher.internal.compatibility.v3_2.exceptionHandler$runSafely$.apply(exceptionHandler.scala:90)
        at org.neo4j.cypher.internal.compatibility.v3_2.Compatibility$ExecutionPlanWrapper.run(Compatibility.scala:101)
        at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:26)
        at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:107)
        at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:144)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:202)
        at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:74)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:395)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:194)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:80)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:130)
        at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:91)
        at java.lang.Thread.run(Thread.java:748)
2017-10-18 18:56:23.340+0000 ERROR [o.n.b.t.SocketTransportHandler] Fatal error occurred when handling a client connection: Connection reset by peer Connection reset by peer
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
```

Client 1.5.0 
neo4j 3.2.5

**Comment by sherfert** [comment] 2017-10-20 13:07
Hi and thanks for reporting this error.
Do you know what Cypher query you were running at that time (and with what data)? That would help us tremendously reproducing the error locally.

**Comment by sherfert** [comment] 2017-10-20 14:30
I think this is a duplicate of #9492

**Closed as completed by sherfert** 2017-10-20 14:30 UTC
Labels: 3.2, team-cypher

**Comment by Meatballs1** [comment] 2017-10-20 15:58
yes could well be, I am using an OPTIONAL MATCH
