### ISSUE TITLE
UnknownError about exists{} in limit

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13127] opened 2023-04-10 09:40 UTC
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:match (a) return a limit case when exists{match()} then 1 end
error message:
Neo.DatabaseError.General.UnknownError
key not found: PositionedNode(SingleQuery(List(Match(false,Pattern(List(EveryPath(NodePattern(None,None,None,None)))),List(),None)))@42)

But if I execute another query:match (a) return a limit case when true then 1 end,then it can run successfully.And I think these two queries are equivalent.

Steps to reproduce:
create ();
match (a) return a limit case when exists{match()} then 1 end;

Expected behavior:
The query should run successfully and return a node.

Actual behavior:
The query failed.

**Comment by ljhhuxiaoba** [comment] 2023-04-10 10:35
The same error also occurs in query:return 1 limit count{return 1}.

**Comment by AzuObs** [comment] 2023-04-12 15:01
Hi @ljhhuxiaoba 

This error is not reproducible in 5.6.0 so I would recommend that you upgrade your system. There is a new error which says "It is not allowed to refer to variables in LIMIT" instead. I think this error is happening because we only accept literals in LIMIT. The error message is not very clear, so I have logged an issue with the team ([private tracker](https://trello.com/c/6r3cLN9S/)).

Warm thanks,

**Comment by arnefischereit** [comment] 2023-06-14 09:05
In the [documentation of `LIMIT`](https://neo4j.com/docs/cypher-manual/current/clauses/limit), one can read

> [...] the expression cannot refer to nodes or relationships.

This is clearly violated in this case, which is why we fail. I have changed the error message to read

> It is not allowed to use patterns in the expression for LIMIT, so that the value for LIMIT can be statically calculated.

This change will be released as part of 5.10.

**Closed as completed by arnefischereit** 2023-06-14 09:05 UTC
Labels: bug, team-cypher
