### ISSUE TITLE
DB recovery (inactivity) -> Timeout

### ISSUE THREAD

**Issue by petamem** [neo4j/neo4j#2364] opened 2014-05-05 09:36 UTC
Neo4j 2.0.3, JDK 1.7.0.55, Gentoo 64bit, big iron machine
# bin/neo4j start

Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
Starting Neo4j Server...process [5318]... waiting for server to be ready............................................................................................................................................................................................................................................................. Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.

11:20:04.236 [main] INFO  org.neo4j.server.CommunityNeoServer - Setting startup timeout to: 120000ms based on -1
Detected incorrectly shut down database, performing recovery..
2014-05-05 09:24:20.311+0000 ERROR [org.neo4j]: Exception when stopping org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@54db08f1 java.nio.channels.ClosedByInterruptException
java.lang.RuntimeException: java.nio.channels.ClosedByInterruptException

...

The interesting part is, that during these 120seconds neo4j isn't doing anything. I see no disk activity, no CPU activity. Seems to be just sitting there and waiting for its demise.

Little bit frustrating after 2 hours of evaluation (download, set up Oracle JDK, set ulimit, set correct URL where neo4j should listen to, pierced the right Firewall hole,...).

**Comment by mvcaraiman** [comment] 2015-02-17 14:48
@bpziegler  Thank's for the tip. It worked for me !

**Comment by jinalskothari** [comment] 2016-01-25 22:33
After 8+ hours of experimenting, my neo4j(2.3.1) finally starts in less than 3 minutes. Somehow remote_shell_enabled=false did it!

I am on Arch linux and using an AUR package. My network is configured to use static ip v4 using systemd-networkd.

While I hadn't disabled remote_shell, it took a long time for neo4j to transition between these two states(from messages.log)

```
2016-01-25 21:31:39.448+0000 INFO  [o.n.k.KernelHealth] Kernel health set to OK
2016-01-25 21:33:47.168+0000 INFO  [o.n.k.AvailabilityGuard] Fulfilling of requirement makes database available: Database available
```

I could somehow start the server by 'neo4j start' / 'neo4j console' (usually took about 3 minutes) . However, running the systemd service always ended up with 120s timeout.

Can I provide more information, since the issue is reproducible if I enable the remote shell?

Any ideas what might the issue be?

**Comment by jinalskothari** [comment] 2016-01-25 22:44
Someone else had an issue which appears related to me
http://stackoverflow.com/questions/27362518/neo4j-start-error-while-network-connection-is-enabled

**Comment by technige** [comment] 2018-02-19 14:36
Closing this issue as it seems to contain a series of separate problems. Please open new issues for any problems that still exist.

**Closed by technige** 2018-02-19 14:36 UTC
Labels: bug, team-drivers
