### ISSUE TITLE
neo4j-admin import with --ignore-missing-nodes hangs on large csv file

### ISSUE THREAD

**Issue by peidaqi** [neo4j/neo4j#12063] opened 2018-10-27 00:06 UTC
I'm trying to import several csv files for a graph of 30mln nodes and 61mln relations. The nodes have been filtered down to 340k so the relation file contains lots of missing nodes. For simplicity I'm using the new neo4j-admin tool instead of the deprecated neo4j-import, which supports a new parameter '--ignore-missing-nodes'.

However, the system always hangs at about 80% of the relation import with all my 12 cores at 100%. When using neo4j-import without filtering out any nodes the process was completed in just a couple of minutes.

I suspect this might have something to do with how the nodes are cached and cross checked. If the nodes id are all cached with a hash set it should take less than 100MB of memory and nearly O(1) time for search.

There is no further debug information from the tool so I cannot provide any.

The command line I used:
neo4j-admin import --database graphdb.db --nodes:MyNodes nodes.txt --relationships:MyRel myrel.txt --ignore-missing-nodes

My system:
- Neo4j version: 3.4.7
- Operating system: Ubuntu 17.04 Kernel: 4.13.16-041316-generic
- API/Driver: Using command line tools

**Comment by tinwelint** [comment] 2018-11-05 09:36
Do you have a thread dump or ability to show this and attach possibly obfuscated csv files?

**Comment by tinwelint** [comment] 2019-01-03 12:07
@peidaqi I was able to reproduce the issue you had. It's caused by the "bad relationship" reporting queue growing indefinitely due to the massive amounts of bad relationships. This fills the heap and blocks everything from progressing. This will be fixed by introducing back pressure in that queue. This issue will be notified when it's fixed. Thank you.

**Comment by peidaqi** [comment] 2019-01-04 14:59
@tinwelint You're welcome. Glad we found where the issue is and look forward to the next release of Neo4j.

**Closed as completed** 2019-01-23 11:07 UTC
Labels: team-kernel
