### ISSUE TITLE
Internal error on simple paths algorithm request

### ISSUE THREAD

**Issue by fcofdez** [neo4j/neo4j#6578] opened 2016-03-02 16:58 UTC
It seems that there's some bug related with [shortestpath](http://neo4j.com/docs/2.2.8/rest-api-graph-algos.html#rest-api-execute-a-dijkstra-algorithm-and-get-a-single-path) algorithms. It returns 500 error even on simple scenarios as the one I'll describe later.
- Neo4j version: 2.2.5, 2.2.8 2.3.2
- Operating system: Linux
- API/Driver: Curl
### Steps to reproduce

``` bash
#!/bin/bash
VERSION=2.3.2
wget http://dist.neo4j.org/neo4j-community-${VERSION}-unix.tar.gz
tar xzf neo4j-community-${VERSION}-unix.tar.gz
cd neo4j-community-${VERSION}/
sed -i -e 's/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g' conf/neo4j-server.properties
./bin/neo4j start
curl -H "Content-Type: application/json" -XPOST http://localhost:7474/db/data/transaction -d "{\"statements\": [{\"statement\": \"CREATE (a:Movie {name: 'test'}) CREATE(b: Movie {name: 'test2'}) CREATE (a)-[:TEST]->(b);\"}]}" | jq .commit | xargs curl -XPOST

# To check that nodes exists
curl http://localhost:7474/db/data/node/0 | jq .
curl http://localhost:7474/db/data/node/1 | jq .

curl -v http://localhost:7474/db/data/node/0/path -d '{
  "to" : "http://localhost:7474/db/data/node/1/path",
  "max_depth" : 1,
  "relationships" : {
    "type" : "to",
    "direction" : "out"
  },
  "algorithm" : "shortestPath"
}'
```
### Expected behavior

Return a path
### Actual behavior

It returns 

```
< HTTP/1.1 500 Server Error
< Date: Wed, 02 Mar 2016 16:47:50 GMT
< Content-Type: text/html; charset=ISO-8859-1
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Length: 0
< Connection: close
< Server: Jetty(9.2.4.v20141103)
<
* Closing connection 0
```

Backtrace

```
2016-03-02 17:43:33.088+0100 ERROR The RuntimeException could not be mapped to a response, re-throwing to
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.neo4j.server.rest.repr.formats.UrlFormFormat.readMap(UrlFormFormat.java:99)
        at org.neo4j.server.rest.web.RestfulGraphDatabase.singlePath(RestfulGraphDatabase.java:1703)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$Respons
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(Resource
        at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalReques
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.jav
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.jav
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.jav
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fcofdez** [comment] 2016-03-02 19:25
It seems like a bug related with the `ContentType` header, it should return something like `Bad Request` instead of 500 status code. This snippet of code seems to work, including the header.

`````` bash
#!/bin/bash
VERSION=2.3.2
wget http://dist.neo4j.org/neo4j-community-${VERSION}-unix.tar.gz
tar xzf neo4j-community-${VERSION}-unix.tar.gz
cd neo4j-community-${VERSION}/
sed -i -e 's/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g' conf/neo4j-server.properties
./bin/neo4j start
curl -H "Content-Type: application/json" -XPOST http://localhost:7474/db/data/transaction -d "{\"statements\": [{\"statement\": \"CREATE (a:Movie {name: 'test'}) CREATE(b: Movie {name: 'test2'}) CREATE (a)-[:TEST]->(b);\"}]}" | jq .commit | xargs curl -XPOST

# To check that nodes exists
curl http://localhost:7474/db/data/node/0 | jq .
curl http://localhost:7474/db/data/node/1 | jq .

curl -v -X POST -H 'Content-Type: application/json' http://localhost:7474/db/data/node/0/paths -d '{
"to" : "http://localhost:7474/db/data/node/1",
"max_depth" : 1,
"relationships" : {
"type" : "TEST",
"direction" : "out"
},
"algorithm" : "shortestPath"
}```
``````

**Comment by jexp** [comment] 2016-03-13 22:39
You probably know that you can run the same in Cypher?

```
MATCH path = shortestPath( (n)-[:TEST*..1]->(m) )
WHERE id(n) = 0 and id(m) = 1
RETURN path
```

PS Good use of jq :)

**Comment by fcofdez** [comment] 2016-03-14 01:12
Yes, I know. But it's confusing to get a 500 error on an invalid content-type request instead of some kind of 4xx since it's an user error.

**Comment by jexp** [comment] 2016-03-14 06:58
That's true!

**Comment by craigtaverner** [comment] 2018-11-09 16:35
Since this issue relates to the REST API for nodes which is deprecated and soon to be entirely removed, I will close this issue. If the problem is still important, feel free to re-open it.

**Closed as completed by craigtaverner** 2018-11-09 16:35 UTC
Labels: bug, team-drivers
