### ISSUE TITLE
Neo4j doesn't build or run on the arm64 M1 Macs

### ISSUE THREAD

**Issue by jacksonps4** [neo4j/neo4j#12692] opened 2021-03-16 21:55 UTC
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.
If you have questions on how to use Neo4j, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

## Feature request template

**Is your feature request related to a problem? Please describe.**
I have an M1 Mac with an arm64 processor and I'm unable to build or run Neo4j. The binary packages don't work - neither does compiling from source and a compatible Docker image hasn't been uploaded to Docker Hub.

**Describe the solution you'd like**
A way to recompile the native libraries distributed with neo4j such that they will function on M1 arm64 processors or an arm64 docker image which I can run.

**Describe alternatives you've considered**
Only alternative is to run on another Linux or Intel-based Mac.

**Additional context**

**Comment by mnd999** [comment] 2021-03-22 14:08
Thanks for the request, I've raised it with our product team and will let you know what the plan is here when I find out more.

**Comment by mnd999** [comment] 2021-03-23 10:37
Neo4j 4.3, expected mid-year, will be M1 compatible.

**Comment by jacksonps4** [comment] 2021-03-27 08:13
Thank you.

**Comment by jennyowen** [comment] 2021-03-29 08:04
@jacksonps4 There are actually experimental docker ARM images available here: https://hub.docker.com/r/neo4j/neo4j-arm64-experimental 

They're not available on our official docker hub because they're untested (although people report being able to successfully use them).

**Comment by ahmadalfy** [comment] 2021-04-30 19:06
Even that doesn't work:

```
➜ docker pull neo4j/neo4j-arm64-experimental
Using default tag: latest
Error response from daemon: manifest for neo4j/neo4j-arm64-experimental:latest not found: manifest unknown: manifest unknown
```

**Comment by jsmith** [comment] 2021-05-02 21:50
@ahmadalfy the experimental version worked for my (simple) app :)

```
docker run -p7474:7474 -p7687:7687 neo4j/neo4j-arm64-experimental:4.2.5-arm64
Unable to find image 'neo4j/neo4j-arm64-experimental:4.2.5-arm64' locally
4.2.5-arm64: Pulling from neo4j/neo4j-arm64-experimental
...
```

**Comment by jennyowen** [comment] 2021-05-04 07:50
@ahmadalfy we don't push a `latest` tag to the experimental branch, so you need to specify the version you want when pulling. That's why `neo4j/neo4j-arm64-experimental:4.2.5-arm64` will work but `neo4j/neo4j-arm64-experimental:latest` will not.

**Comment by nashid** [comment] 2021-05-28 19:57
I faced the same problem. But `neo4j/neo4j-arm64-experimental`do work.

**Comment by jhanggi** [comment] 2021-05-28 22:30
The experimental branch seems to only be the community edition. I was able to build the enterprise edition by cloning the repo and following these directions: https://github.com/neo4j/docker-neo4j/blob/master/DEVELOPMENT.md (note there are special instructions for the arm64 images).

Then the other secret sauce was to re-tag it so it matched my project's docker-compose: `docker image tag test/4991-arm neo4j:4.2.1-enterprise`

It's been working well enough for local development for me.

**Comment by jexp** [comment] 2021-07-02 15:23
Did you see this?

https://astr0baby.wordpress.com/2021/06/26/compiling-and-running-native-neo4j-on-apple-m1-arm64/

**Comment by zaheeruddinfaiz** [comment] 2021-07-11 03:16
@mnd999 Hi! Could you please tell the status? It is already mid year :)

**Comment by mnd999** [comment] 2021-07-13 07:13
We are not aware of any issues preventing running Neo4j 4.3 on Apple Macs with the M1 chip.

**Comment by zaheeruddinfaiz** [comment] 2021-07-14 08:40
I can run Neo4j desktop application. 
I was wondering if I could run the docker image on Apple Macs with the M1 chip?

**Comment by jennyowen** [comment] 2021-07-14 08:54
@zaheeruddinfaiz there still are not official neo4j docker images for ARM. 
There are unofficial ones we publish here though: https://hub.docker.com/r/neo4j/neo4j-arm64-experimental

so you can do: `docker run [arguments] neo4j/neo4j-arm64-experimental:4.3.2-arm64` and get the latest neo4j on your mac.

**Comment by odair-pedro** [comment] 2021-07-15 12:58
The latest experimental arm image is not working here :(

I got the following error: 
`manifest for neo4j/neo4j-arm64-experimental:latest not found: manifest unknown: manifest unknown`

To solve.. i had to use the image neo4j/neo4j-arm64-experimental:4.2.5-arm64, that has worked.

**Comment by jennyowen** [comment] 2021-07-19 07:59
yeah there isn't a `latest` tag on that repo, you have to specify the version. The tags list on https://hub.docker.com/r/neo4j/neo4j-arm64-experimental/tags?page=1&ordering=name is in a weird order, but if you sort Z - A you can see all the latest versions are available.

**Comment by cx-lukas-salkauskas-x** [comment] 2021-07-30 07:47
any updates on this one? when could we expect non experimental support?

**Comment by matt-ward-airwalk** [comment] 2021-08-18 16:51
Looks like the container images (experimental) are working fine on my M1 Macbook, but the container won't start when I introduce plugins. i.e

https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/download/3.5.4.0/graph-algorithms-algo-3.5.4.0.jar
https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.5/apoc-4.2.0.5-all.jar

I get the following error

Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:ApocConfigExtensionFactory[ApocConfig] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/configuration/ExternalSettings'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading allinstalled extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.

Has anyone managed to get this working? I'd rather run this in Docker than install it directly if possible

**Comment by jexp** [comment] 2021-08-18 18:08
You need to use the correct versions of those plugins. They need to match the neo4j version. 

Best use this 
https://neo4j.com/docs/operations-manual/current/docker/operations/#docker-neo4jlabs-plugins

**Comment by mnd999** [comment] 2021-12-16 10:17
Neo4j 4.4 has official docker images for ARM64 so I think we can close this now.

**Closed as completed by mnd999** 2021-12-16 10:17 UTC
Labels: feature
