### ISSUE TITLE
No element found in org.neo4j.helpers.collection.Iterables$FilterIterable$FilterIterator@450b0e07

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#3183] opened 2014-09-30 08:44 UTC
Creating unique constraint and getting the following result:

No element found in org.neo4j.helpers.collection.Iterables$FilterIterable$FilterIterator@450b0e07

Occurred while creating a typical constraint:
CREATE CONSTRAINT ON (n:Movie) ASSERT n.id IS UNIQUE;

Database has been upgraded from 1.9-->2.0-->2.1.3-->2.1.4

**Comment by rajaraodv** [comment] 2015-03-07 00:09
I finally found stacktrace on my localhost for 2.1.7 

Just to give you an idea, I am trying to create a bunch of constraints for different labels and properties combinations using a node.js script. But it just so happens, that several (40%) of the constraints simply don't get created.

Here is an example output from the script:
adding constraint for.. EMAIL_USER    email
adding constraint for.. FACEBOOK_USER    email
adding constraint for.. FACEBOOK_FRIEND    fb_id
adding constraint for.. TWITTER_USER    email
adding constraint for.. GOOGLE_USER    email
adding constraint for.. USER    username
adding constraint for.. FACEBOOK_USER    fb_id
Error: When adding constraint for.. TWITTER_USER    email
[Error: HTTP Error 500 when creating a uniqueness contraint.]
adding constraint for.. TWITTER_USER    tw_id
Error: When adding constraint for.. GOOGLE_USER    email
[Error: HTTP Error 500 when creating a uniqueness contraint.]
adding constraint for.. GOOGLE_USER    goog_id


Below is the exception...


 Marker - Mar 6, 2015, 3:56:27 PM
15:56:54.413 [qtp1759915172-57] WARN  o.e.jetty.servlet.ServletHandler - /db/data/schema/constraint/EMAIL_USER/uniqueness
org.neo4j.graphdb.TransactionFailureException: Unable to commit transaction
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:141) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.transactional.CommitOnSuccessfulStatusCodeRepresentationWriteHandler.closeTransaction(CommitOnSuccessfulStatusCodeRepresentationWriteHandler.java:66) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.transactional.CommitOnSuccessfulStatusCodeRepresentationWriteHandler.onRepresentationFinal(CommitOnSuccessfulStatusCodeRepresentationWriteHandler.java:60) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.toBytes(OutputFormat.java:212) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.formatRepresentation(OutputFormat.java:156) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.response(OutputFormat.java:139) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.ok(OutputFormat.java:71) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.web.RestfulGraphDatabase.createPropertyUniquenessConstraint(RestfulGraphDatabase.java:1838) ~[neo4j-server-2.1.7.jar:2.1.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.9.jar:1.9]
	at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139) ~[neo4j-server-2.1.7.jar:2.1.7]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) ~[jersey-server-1.9.jar:1.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: javax.transaction.HeuristicRollbackException: Failed to commit transaction Transaction(8, owner:"qtp1759915172-57")[STATUS_NO_TRANSACTION,Resources=1], transaction rolled back ---> Database constraints have changed (txId=32619) after this transaction (txId=32617) started, which is not yet supported. Please retry your transaction to ensure all constraints are executed.
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:572) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:385) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:126) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	... 47 common frames omitted
Caused by: javax.transaction.xa.XAException: null
	at org.neo4j.kernel.impl.nioneo.xa.IntegrityValidator.validateTransactionStartKnowledge(IntegrityValidator.java:74) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransaction.doPrepare(NeoStoreTransaction.java:325) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.prepare(XaTransaction.java:307) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commitWriteTx(XaResourceManager.java:588) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commit(XaResourceManager.java:533) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.commit(XaResourceHelpImpl.java:64) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:548) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:448) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	... 49 common frames omitted
Caused by: org.neo4j.graphdb.ConstraintViolationException: Database constraints have changed (txId=32619) after this transaction (txId=32617) started, which is not yet supported. Please retry your transaction to ensure all constraints are executed.
	... 57 common frames omitted
15:56:54.473 [qtp1759915172-54] WARN  o.e.jetty.servlet.ServletHandler - /db/data/schema/constraint/FACEBOOK_FRIEND/uniqueness
org.neo4j.graphdb.TransactionFailureException: Unable to commit transaction
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:141) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.transactional.CommitOnSuccessfulStatusCodeRepresentationWriteHandler.closeTransaction(CommitOnSuccessfulStatusCodeRepresentationWriteHandler.java:66) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.transactional.CommitOnSuccessfulStatusCodeRepresentationWriteHandler.onRepresentationFinal(CommitOnSuccessfulStatusCodeRepresentationWriteHandler.java:60) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.toBytes(OutputFormat.java:212) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.formatRepresentation(OutputFormat.java:156) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.response(OutputFormat.java:139) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.repr.OutputFormat.ok(OutputFormat.java:71) ~[neo4j-server-2.1.7.jar:2.1.7]
	at org.neo4j.server.rest.web.RestfulGraphDatabase.createPropertyUniquenessConstraint(RestfulGraphDatabase.java:1838) ~[neo4j-server-2.1.7.jar:2.1.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.9.jar:1.9]
	at org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139) ~[neo4j-server-2.1.7.jar:2.1.7]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) ~[jersey-server-1.9.jar:1.9]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699) ~[jersey-server-1.9.jar:1.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: javax.transaction.HeuristicRollbackException: Failed to commit transaction Transaction(9, owner:"qtp1759915172-54")[STATUS_NO_TRANSACTION,Resources=1], transaction rolled back ---> Database constraints have changed (txId=32619) after this transaction (txId=32617) started, which is not yet supported. Please retry your transaction to ensure all constraints are executed.
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:572) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:385) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:126) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	... 47 common frames omitted
Caused by: javax.transaction.xa.XAException: null
	at org.neo4j.kernel.impl.nioneo.xa.IntegrityValidator.validateTransactionStartKnowledge(IntegrityValidator.java:74) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.nioneo.xa.NeoStoreTransaction.doPrepare(NeoStoreTransaction.java:325) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaTransaction.prepare(XaTransaction.java:307) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commitWriteTx(XaResourceManager.java:588) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceManager.commit(XaResourceManager.java:533) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.xaframework.XaResourceHelpImpl.commit(XaResourceHelpImpl.java:64) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TransactionImpl.doCommit(TransactionImpl.java:548) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	at org.neo4j.kernel.impl.transaction.TxManager.commit(TxManager.java:448) ~[neo4j-kernel-2.1.7.jar:2.1.7]
	... 49 common frames omitted
Caused by: org.neo4j.graphdb.ConstraintViolationException: Database constraints have changed (txId=32619) after this transaction (txId=32617) started, which is not yet supported. Please retry your transaction to ensure all constraints are executed.
	... 57 common frames omitted

**Comment by klaren** [comment] 2017-10-18 14:38
Since the issue is old and the stack traces are not relevant anymore, we don't have `XAException` or `HeuristicRollbackException` for example, I'm going to close this issue. If you still have similar problems feel free to open a new issue.

**Closed by klaren** 2017-10-18 14:38 UTC
Labels: cypher, team-kernel
