### ISSUE TITLE
Potential Correctness Bug of Neo4j

### ISSUE THREAD

**Issue by Aurora-yzj** [neo4j/neo4j#13360] opened 2023-11-30 16:27 UTC
I discovered a potential correctness bug, where Neo4j returns wrong results when processing my queries. The details are listed below. 
**Neo4j Version:** 5.14.0 Community
**Operating System:** Ubuntu 22.04
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j`
2. Create a directory on the host that will be a mount for the data: `mkdir $HOME/neo4j-data`
3. Start a new container that mounts to this directory: `sudo docker run -d --name neo4j-test -p 17474:7474 -p 17687:7687  -v $HOME/neo4j-data:/data neo4j`
4. Go to the web interface at "http://127.0.0.1:17474", login and execute the following series of queries to build the database:
```
CREATE (n0 :L0:L8:L15{k91 : false, k90 : true, k0 : true, k92 : "16DMF", k1 : true, k51 : "xzZuanST", k2 : false, k50 : 750574987, k3 : true, k53 : "5gnN5J4CE", k4 : "fqVvF7u4", k52 : false, k5 : "Su2XH7Wc0", k88 : -1938209585, k89 : "ChnuN", k48 : -623596506, k49 : false, id : 0});
CREATE (n0 {id : 1});
CREATE (n0 :L0:L8:L15{k91 : true, k92 : "PW9Tk", k1 : true, k51 : "y4I2liZ", k2 : true, k50 : -962596764, k53 : "9HekL", k4 : "MIxcViX7", k52 : false, k5 : "KpXi9", k88 : 2140772062, k6 : "thIA9K", k89 : "T9z2x9PG", k48 : -54280145, k49 : true, id : 3});
CREATE (n0 {id : 9});
CREATE (n0 :L0:L8{k0 : true, k1 : false, k51 : "EPVvVt87", k50 : 1208591465, k3 : false, k53 : "HadewEn", k4 : "0kNFRTIoa", k52 : true, k5 : "9HAg3", id : 10, k6 : "lTHvIV", k48 : 313614850});
CREATE (n0 :L0:L8{k0 : false, k1 : true, k51 : "lasGLaxq", k2 : false, k50 : -94301266, k3 : false, k53 : "gSRinMOe", k4 : "Hr2c2wr", k52 : true, k5 : "gndXze7nY", k6 : "kZMcDXf", k48 : -1574325549, k49 : true, id : 12});
CREATE (n0 :L0:L8{k0 : false, k1 : false, k51 : "azX2Q", k2 : false, k50 : -525243022, k3 : false, k53 : "GwHh89Bu", k4 : "aATtqbX", k52 : false, k5 : "VGYhlhM", k6 : "9dFqK", k48 : 1664192090, k49 : true, id : 13});
MATCH (n0 {id : 3}), (n1 {id : 1}) MERGE(n0)-[r :T0{k182 : false, k178 : "5Db9TbLl", k177 : -178228757, k179 : false, id : 19, k181 : false, k180 : "jRXWcx90d"}]->(n1);
MATCH (n0 {id : 13}), (n1 {id : 12}) MERGE(n0)-[r :T0{k182 : false, k178 : "POnBIfKn", k177 : -75287909, k179 : false, id : 20, k181 : true}]->(n1);
MATCH (n0 {id : 1}), (n1 {id : 0}) MERGE(n0)-[r :T0{k182 : true, k178 : "tq6VaC", k177 : -1954582776, k179 : true, id : 22, k181 : false, k180 : "sBGOm"}]->(n1);
MATCH (n0 {id : 9}), (n1 {id : 10}) MERGE(n0)-[r :T0{k182 : true, k178 : "vGaEpAAl", k177 : -2010594197, k179 : false, id : 23, k181 : false}]->(n1);
```
5. Run the query (for ease of analysis, I have adjusted the format of where predicates, and this will not affect the reproduction of the bug):
```
MATCH (n0 :L8)-[r0 :T0]->(n1 :L0 :L8)
WHERE (((n1.k48) > -1842629237) AND ((((n0.k6) = '9dFqK') AND ((r0.k177) = -75287909)) AND ((n1.k53) = 'gSRinMOe')))
OPTIONAL MATCH (n2 :L0 :L8)<-[r1 :T0]-(n3), (n0)-[r2 :T0]->(n1), (n4 :L15 :L0)<-[r3 :T0]-(n5)<-[r4 :T0]-(n6 :L0 :L8 :L15)
WHERE (
    ( (( (((n6.k5) <> ('g7XEjn'+(n0.k53))) AND (n4.k49))) OR ((n1.k6) >= ((('S7476'+(n0.k5))+('psYmqpNSY'+'uHKufM'))+(n0.k51)))))
    AND 
    ((r2.id=20) AND  ((n3.id) = 9) AND ((n0.k53) = 'GwHh89Bu') AND ((n1.k6) = 'kZMcDXf') AND ((r3.k178) = 'tq6VaC'))
    )
RETURN (r2.k178) AS a0
```

### Expected behavior
The condition for selecting r2 includes `(r2.id) = 20`:
```
...
WHERE (
    ...
    AND 
    ((r2.id=20) AND ...)
    )
RETURN (r2.k178) AS a0
```
Therefore, the only matching relation would be:
`MATCH (n0 {id : 13}), (n1 {id : 12}) MERGE(n0)-[r :T0{k182 : false, k178 : "POnBIfKn", k177 : -75287909, k179 : false, id : 20, k181 : true}]->(n1);`
For `a0`, the return should be `POnBIfKn`, as `r2.k178="POnBIfKn"`. Therefore, the result should be: `{'a0': 'POnBIfKn'}`

### Actual behavior
The return value of neo4j is:`{'a0': 'azX2Q'}`
By the way, I am not 100% certain, but the behavior of this bug is a little bit similar to the bug I discovered earlier. The issue is [here](https://github.com/neo4j/neo4j/issues/13359). Since I am not certain whether the root causes of these two bugs are the same or not, and the guidelines remind me that I should not talk about two problems in one issue, I submitted this separately. Hope this could help you identify the root cause.
Thank you so much for your help!
![2023-11-30_17-23](https://github.com/neo4j/neo4j/assets/24768784/31ba1382-ddc7-41ad-a84b-bb955079ef44)

**Comment by pontusmelke** [comment] 2023-12-06 07:38
Hi @Aurora-yzj 
Thanks for reporting, we'll have a look at it!

Regards,
Pontus

**Comment by JonasHolgersson** [comment] 2024-01-15 10:48
Duplicate of https://github.com/neo4j/neo4j/issues/13359

**Closed as completed by JonasHolgersson** 2024-01-15 10:48 UTC
Labels: bug, team-cypher
