### ISSUE TITLE
Neo4j Server should return error message when cypher-shell is wrong version

### ISSUE THREAD

**Issue by mojo2go** [neo4j/neo4j#12385] opened 2020-01-23 21:38 UTC
## Neo4j Server should only accept connections from a matching version cypher-shell 

I started using a small widget app to make it more speedy for me to switch between servers:
https://community.neo4j.com/t/a-wrapper-for-cypher-shell-with-profiles/12573
But it's naive in this early version in that it does not try to match the cypher-shell version with the server version.  It uses what ever local cypher-shell.jar file you pointed it to, for every connection.

Last time I installed this widget I was testing out the Neo4j 4.0.0-alpha, and that version of cypher-shell ended up being the version of cypher-shell I used through the widget.  I used it across 4 different versions of Neo4j Server without incident, for weeks, until I ran one particular query on Neo4j Server 3.5.8.  This is the query:

`CREATE (t:Thing1) DETACH DELETE t;`

### Aside:
_My  intent for running this (as admin) was to make it possible for developers (as editor) to be able to use the label "Thing1" on nodes.  It's a way of roughly controlling what is allowed in the schema.  Thing1 label did't exist in the database, and so no developer was able to create that new token until I did, as admin.  It has always worked as intended.  It would create and delete the new token in a single transaction, and as a side effect make it an allowed token in the database for those with only editor role.  And the query ran within a transaction, so I was not polluting the database with unintended objects._  

But when I ran that query from cypher-shell 4.0.0-alpha on Neo4j Server 3.5.8, it did something unpredictable;  It 'aliased' an existing label in the database, Person, and made Person not visible in the database (still useable, but not visible).  What I mean is that when I looked at the Database Information tab in Neo4j Desktop I no longer saw a Person label.  Instead it was represented as Thing1.  When I searched for Thing1 labelled nodes I got my person nodes, but in the results when I reported the labels on those nodes they also showed Thing1.  I say 'aliased' because I could search for Person nodes and would get the same result, the person nodes but labelled as Thing1, not person.

**Comment by sherfert** [comment] 2020-01-27 08:18
Hi @mojo2go 
This sounds rather like a bug in Neo4j 3.5.8 than a version mismatch between Cypher-shell and the server. Did you try running the same query (on a database before the label "aliasing") via e.g. browser and it did not behave that way? 

Did you try a newer version of 3.5?

If possible, you you create a small `.cypher` script that reliably reproduces the aliasing issue in Neo4j 3.5.8?

**Comment by sherfert** [comment] 2020-04-20 09:25
I will close this issue because we cannot reproduce the issue without further information.

**Closed as completed by sherfert** 2020-04-20 09:25 UTC
Labels: bug
