### ISSUE TITLE
Wrong results using LIMIT in RETURN (non-deterministic)

### ISSUE THREAD

**Issue by hijan94** [neo4j/neo4j#12247] opened 2019-07-12 08:18 UTC
I discovered that when I use the LIMIT operator in the RETURN, the database returns invalid results sometimes (non-deterministic) - but only on large size patterns/quiers. I.e: Altough there are 4 matches in the database, the database returns no matches when using LIMIT 1 (or 2,3), but 4 when using LIMIT 4. After restarting the database the error disappears sometimes - but sometimes not. 

Has this issue been fixed in recent releases? If not, please use the following steps to reproduce the problem: Note: be advised, that the problem occures only sporadic.

- Neo4j version: 3.5.2
- Operating system: Win10 x64
- API/Driver: Neo4j Browser or JavaAPI

Steps:
1. Initiate Database, run the following queries. The query create a game board with 4x4 fields( label _:Field_), which are connected by _:right_ and _:bottom_ edges to their neighbors, and a node _:Board_, with edges to every _:Field_.

```
CREATE
(f00: Field {name: "f00"})-[:right]->(f01: Field {name: "f01"})-[:right]->(f02: Field {name: "f02"})-[:right]->(f03:Field {name: "f03"}), 
(f10: Field {name: "f10"})-[:right]->(f11: Field {name: "f11"})-[:right]->(f12: Field {name: "f12"})-[:right]->(f13:Field {name: "f13"}), 
(f20: Field {name: "f20"})-[:right]->(f21: Field {name: "f21"})-[:right]->(f22: Field {name: "f22"})-[:right]->(f23:Field {name: "f23"}), 
(f30: Field {name: "f30"})-[:right]->(f31: Field {name: "f31"})-[:right]->(f32: Field {name: "f32"})-[:right]->(f33:Field {name: "f33"}), 
(f00)-[:bottom]->(f10)-[:bottom]->(f20)-[:bottom]->(f30), 
(f01)-[:bottom]->(f11)-[:bottom]->(f21)-[:bottom]->(f31), 
(f02)-[:bottom]->(f12)-[:bottom]->(f22)-[:bottom]->(f32), 
(f03)-[:bottom]->(f13)-[:bottom]->(f23)-[:bottom]->(f33),
(b:Board)
```

and 

`MATCH (f:Field), (b:Board) CREATE (b)-[:fields]->(f)`

2. Execute the pattern matching query. 

```
MATCH 
(b:Board)-[b_fields_0_field11:fields]->(field11:Field), (b:Board)-[b_fields_1_field12:fields]->(field12:Field), (b:Board)-[b_fields_2_field13:fields]->(field13:Field), (b:Board)-[b_fields_3_field21:fields]->(field21:Field), (b:Board)-[b_fields_4_field22:fields]->(field22:Field), (b:Board)-[b_fields_5_field23:fields]->(field23:Field), (b:Board)-[b_fields_6_field31:fields]->(field31:Field), (b:Board)-[b_fields_7_field32:fields]->(field32:Field), (b:Board)-[b_fields_8_field33:fields]->(field33:Field), 
(field11:Field)-[field11_right_0_field12:right]->(field12:Field), (field11:Field)-[field11_bottom_1_field21:bottom]->(field21:Field), 
(field12:Field)-[field12_right_0_field13:right]->(field13:Field), (field12:Field)-[field12_bottom_1_field22:bottom]->(field22:Field), 
(field13:Field)-[field13_bottom_0_field23:bottom]->(field23:Field), 
(field21:Field)-[field21_right_0_field22:right]->(field22:Field), (field21:Field)-[field21_bottom_1_field31:bottom]->(field31:Field), 
(field22:Field)-[field22_right_0_field23:right]->(field23:Field), (field22:Field)-[field22_bottom_1_field32:bottom]->(field32:Field), 
(field23:Field)-[field23_bottom_0_field33:bottom]->(field33:Field), 
(field31:Field)-[field31_right_0_field32:right]->(field32:Field), 
(field32:Field)-[field32_right_0_field33:right]->(field33:Field), 
(field33:Field)
WHERE  NOT id(field11) = id(field12) AND NOT id(field11) = id(field13) AND NOT id(field11) = id(field21) AND NOT id(field11) = id(field22) AND NOT id(field11) = id(field23) AND NOT id(field11) = id(field31) AND NOT id(field11) = id(field32) AND NOT id(field11) = id(field33)
AND NOT id(field12) = id(field13) AND NOT id(field12) = id(field21) AND NOT id(field12) = id(field22) AND NOT id(field12) = id(field23) AND NOT id(field12) = id(field31) AND NOT id(field12) = id(field32) AND NOT id(field12) = id(field33)
AND NOT id(field13) = id(field21) AND NOT id(field13) = id(field22) AND NOT id(field13) = id(field23) AND NOT id(field13) = id(field31) AND NOT id(field13) = id(field32) AND NOT id(field13) = id(field33)
AND NOT id(field21) = id(field22) AND NOT id(field21) = id(field23) AND NOT id(field21) = id(field31) AND NOT id(field21) = id(field32) AND NOT id(field21) = id(field33)
AND NOT id(field22) = id(field23) AND NOT id(field22) = id(field31) AND NOT id(field22) = id(field32) AND NOT id(field22) = id(field33)
AND NOT id(field23) = id(field31) AND NOT id(field23) = id(field32) AND NOT id(field23) = id(field33)
AND NOT id(field31) = id(field32) AND NOT id(field31) = id(field33)
AND NOT id(field32) = id(field33)
RETURN 
id(b_fields_0_field11) AS b_fields_0_field11, id(b_fields_1_field12) AS b_fields_1_field12, id(b_fields_2_field13) AS b_fields_2_field13,
id(b_fields_3_field21) AS b_fields_3_field21, id(b_fields_4_field22) AS b_fields_4_field22, id(b_fields_5_field23) AS b_fields_5_field23,
id(b_fields_6_field31) AS b_fields_6_field31, id(b_fields_7_field32) AS b_fields_7_field32, id(b_fields_8_field33) AS b_fields_8_field33,
id(field11_right_0_field12) AS field11_right_0_field12, id(field11_bottom_1_field21) AS field11_bottom_1_field21, id(field12_right_0_field13) AS field12_right_0_field13,
id(field12_bottom_1_field22) AS field12_bottom_1_field22, id(field13_bottom_0_field23) AS field13_bottom_0_field23, id(field21_right_0_field22) AS field21_right_0_field22, 
id(field21_bottom_1_field31) AS field21_bottom_1_field31, id(field22_right_0_field23) AS field22_right_0_field23, id(field22_bottom_1_field32) AS field22_bottom_1_field32,
id(field23_bottom_0_field33) AS field23_bottom_0_field33, id(field31_right_0_field32) AS field31_right_0_field32, id(field32_right_0_field33) AS field32_right_0_field33, id(field33) AS field33
 LIMIT 1
```

The query returns all 3x3 size sub boards. Hence the expected result in a 4x4 board is 4. Using the LIMIT opertor at the end, we limit the return to 1 sub board, such that the expected result size is 1. But sometimes the database returns no matches. Same behavior when using LIMIT 1, LIMIT 2 or LIMIT 3. Using LIMIT 4 the database return the 4 matches.

**Comment by InverseFalcon** [comment] 2019-07-15 08:43
Hello, you're using a rather old version 3.5.x, could you instead try this out with 3.5.7, the current latest version? 

I wasn't able to replicate your issue on this, so I would venture that whatever bug is at work here has since been fixed.

If you're still able to replicate this, could you PROFILE the query and (after expanding all elements of the plan using the double-down arrows in the bottom right of the result pane) include the query plan here?

**Comment by hijan94** [comment] 2019-07-15 10:19
Okay, i have updated to version 3.5.7. The problem is still present - but now the query from above returns 0 matches either when LIMIT is used or not.

![plan](https://user-images.githubusercontent.com/48552288/61209686-b5953480-a6fa-11e9-85b1-1f1cd02c91fc.png)

**Comment by hijan94** [comment] 2019-07-15 13:18
Note: When executing the query to find all 2x2 size fields (instead of the 3x3 size field query from above), Neo4j finds all matches successfully without any problems. Could it be that the problem is a too big pattern, such not all possibilities can be considerd correctly?

**Comment by SaschaPeukert** [comment] 2019-07-26 14:26
Hej @hijan94 

Thanks for reporting this. We will have a look and get back to you!

Cheers,
Sascha

Neo4j Cypher Team

**Comment by Lojjs** [comment] 2019-08-06 09:37
@hijan94 We are currently investigating this and, as you pointed out, the problem is only occurring when the pattern is big enough. The cause seems to be a bug with combining 2 complex patterns with a hash-join in the slotted runtime (which is the default runtime in 3.5). As a workaround you can try to prepend your query with `CYPHER runtime=interpreted `. Please let us know whether that solves your problem.

Best regards Louise, Neo4j Cypher team

**Comment by hijan94** [comment] 2019-08-06 10:11
@Lojjs Thanks for your help. 

Your suggested workaround works fine on my computer and has fixed the problem so far.
All matching processes (with or without using LIMIT) now return the correct results.

**Comment by Lojjs** [comment] 2019-08-06 14:46
@hijan94 That is great to hear! A fix for the slotted runtime will be included in the next patch release of Neo4j (3.5.9)

**Comment by hijan94** [comment] 2019-09-05 14:44
I have upgraded from version 3.5.8 to 3.5.9, but the bug still exists. 
The database still returns invalid results in this situation. This was testes on different machines using the latest Neo4j version and the latest Windows or Ubuntu. Even if i remove the LIMIT operator in the query, wrong results will be returned.

**Comment by Hunterness** [comment] 2019-10-16 11:13
Hi @hijan94,

I'm investigating this bug and found that when we tried to solve the issue last time we rewrote the query slightly while still keeping the bug (to easier find the bug). We then solved the bug that we saw and thought that solved this issue. However, there seems like it has been more then one bug around for this query so I'll try and find what that second bug might be.

A rewritten working (for me on 3.5.11 at least) query is:

```
MATCH (b:Board)
WITH b, 1 AS ignore
MATCH
(b)-[b_fields_0_field11:fields]->(field11:Field), (b)-[b_fields_1_field12:fields]->(field12:Field), (b)-[b_fields_2_field13:fields]->(field13:Field),
(b)-[b_fields_3_field21:fields]->(field21:Field), (b)-[b_fields_4_field22:fields]->(field22:Field), (b)-[b_fields_5_field23:fields]->(field23:Field),
(b)-[b_fields_6_field31:fields]->(field31:Field), (b)-[b_fields_7_field32:fields]->(field32:Field), (b)-[b_fields_8_field33:fields]->(field33:Field),
(field11)-[field11_right_0_field12:right]->(field12), (field11)-[field11_bottom_1_field21:bottom]->(field21), 
(field12)-[field12_right_0_field13:right]->(field13), (field12)-[field12_bottom_1_field22:bottom]->(field22),
(field13)-[field13_bottom_0_field23:bottom]->(field23),
(field21)-[field21_right_0_field22:right]->(field22), (field21)-[field21_bottom_1_field31:bottom]->(field31),
(field22)-[field22_right_0_field23:right]->(field23), (field22)-[field22_bottom_1_field32:bottom]->(field32),
(field23)-[field23_bottom_0_field33:bottom]->(field33),
(field31)-[field31_right_0_field32:right]->(field32),
(field32)-[field32_right_0_field33:right]->(field33)
WHERE  NOT id(field11) = id(field12) AND NOT id(field11) = id(field13) AND NOT id(field11) = id(field21) AND NOT id(field11) = id(field22) AND NOT id(field11) = id(field23) AND NOT id(field11) = id(field31) AND NOT id(field11) = id(field32) AND NOT id(field11) = id(field33)
AND NOT id(field12) = id(field13) AND NOT id(field12) = id(field21) AND NOT id(field12) = id(field22) AND NOT id(field12) = id(field23) AND NOT id(field12) = id(field31) AND NOT id(field12) = id(field32) AND NOT id(field12) = id(field33)
AND NOT id(field13) = id(field21) AND NOT id(field13) = id(field22) AND NOT id(field13) = id(field23) AND NOT id(field13) = id(field31) AND NOT id(field13) = id(field32) AND NOT id(field13) = id(field33)
AND NOT id(field21) = id(field22) AND NOT id(field21) = id(field23) AND NOT id(field21) = id(field31) AND NOT id(field21) = id(field32) AND NOT id(field21) = id(field33)
AND NOT id(field22) = id(field23) AND NOT id(field22) = id(field31) AND NOT id(field22) = id(field32) AND NOT id(field22) = id(field33)
AND NOT id(field23) = id(field31) AND NOT id(field23) = id(field32) AND NOT id(field23) = id(field33)
AND NOT id(field31) = id(field32) AND NOT id(field31) = id(field33)
AND NOT id(field32) = id(field33)
RETURN 
id(b_fields_0_field11) AS b_fields_0_field11, id(b_fields_1_field12) AS b_fields_1_field12, id(b_fields_2_field13) AS b_fields_2_field13,
id(b_fields_3_field21) AS b_fields_3_field21, id(b_fields_4_field22) AS b_fields_4_field22, id(b_fields_5_field23) AS b_fields_5_field23,
id(b_fields_6_field31) AS b_fields_6_field31, id(b_fields_7_field32) AS b_fields_7_field32, id(b_fields_8_field33) AS b_fields_8_field33,
id(field11_right_0_field12) AS field11_right_0_field12, id(field11_bottom_1_field21) AS field11_bottom_1_field21, id(field12_right_0_field13) AS field12_right_0_field13,
id(field12_bottom_1_field22) AS field12_bottom_1_field22, id(field13_bottom_0_field23) AS field13_bottom_0_field23, id(field21_right_0_field22) AS field21_right_0_field22, 
id(field21_bottom_1_field31) AS field21_bottom_1_field31, id(field22_right_0_field23) AS field22_right_0_field23, id(field22_bottom_1_field32) AS field22_bottom_1_field32,
id(field23_bottom_0_field33) AS field23_bottom_0_field33, id(field31_right_0_field32) AS field31_right_0_field32, id(field32_right_0_field33) AS field32_right_0_field33, id(field33) AS field33
LIMIT 1
```

The only changes made are in the initial MATCH, which have been split into two different MATCHes. The first one matches the `Board` node (the `WITH b, 1 AS ignore` is necessary to separate the MATCH otherwise they will be rewritten and still have the issue). The second MATCH is almost the same except for the removal of several unnecessary labels. Since we have matched the `Board` node already with the label we no longer need to have its label in the MATCHes. In the first 9 relationship matches we find the different `Field` nodes with the correct label, we therefore don't need to specify the label in the relationship matches that follow but only need to use the node reference.

This simplifies for the planner since it now can keep track of the nodes easier and don't need to join them together on the same variable which might happen in your version :) (not sure if it does but it might)

Hope this query rewrite helps you, and I'll try and figure out what the issue behind your original query not working might be.

Best Regards,
Therese, Team Cypher

**Comment by Hunterness** [comment] 2019-10-17 08:57
Hi @hijan94,

I found the issue :) Last time we fixed this bug in the slotted runtime, but it also existed in the compiled runtime. Our rewrite of the query did not allow the compiled runtime, which is why we did not find it last time. However, your query can use the compiled runtime which is why it still doesn't work for you.

A fix is on its way and should make the next patch release (3.5.13), until then you can prepend your query with `CYPHER runtime=slotted ` since the bug is already fixed there :)

Hope this helps you :)
Therese, Team Cypher

**Comment by hijan94** [comment] 2019-10-26 21:58
Hi @Hunterness ,

thanks a lot for your help. The improved query and the unimproved query with the slotted runtime works on my machine as well. 

Since we auto-generate our queries, we are limited in optimizing the queries. So we can not tell how to split our pattern into different MATCHes, but we will try to remove the duplicate labels in future :-)

**Comment by Hunterness** [comment] 2019-10-28 07:25
@hijan94 That's good to hear that our first fix helped for the slotted runtime at least, even if we did miss the compiled runtime in the first round :)

That sounds good :)

**Closed as completed by Hunterness** 2019-10-28 07:25 UTC
Labels: bug, team-cypher, 3.5
