### ISSUE TITLE
Incorrect result from executing Cypher query

### ISSUE THREAD

**Issue by 1sand0s** [neo4j/neo4j#13536] opened 2024-10-15 22:25 UTC
## Incorrect query result

I discovered that executing the query described below gives an incorrect result.

**Neo4j Version:** 5.23.0
**Operating System:** Ubuntu 20.04
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:5.23.0-community`
2. Start a new container: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j-data:/data neo4j/neo4j:5.23.0-community`
3. Execute the following Cypher script to load the data in the neo4j instance
```
CREATE (a: Blue {nodeID: 1}), 
(b: Yellow {nodeID: 2}), 
(c: Pink {nodeID: 3}),
(a)-[:R1 {edgeID: 1}]->(b),
(a)-[:R1 {edgeID: 2}]->(b),
(b)-[:R2 {edgeID: 3}]->(c),
(b)-[:R2 {edgeID: 4}]->(c),
(c)-[:R3 {edgeID: 5}]->(a),
(c)-[:R3 {edgeID: 6}]->(a),
(c)-[:R3 {edgeID: 7}]->(a);
```
 
5. Now execute the problematic query:
```
MATCH (:Yellow)<-[:R1]-(:Blue)<-[:R3]-(:Pink)<-[:R2]-(:Yellow)<-[:R1]-(a:Blue) RETURN a.nodeID
```

### Expected behavior
24 items since the pattern contains 2 x 2 x 3 x 2 = 24

### Actual behavior
12 items are returned

**Comment by loveleif** [comment] 2024-10-16 10:59
Thanks for the report @1sand0s and the excellent example.

Your graph looks like this:
![Screenshot 2024-10-16 at 12 48 56](https://github.com/user-attachments/assets/11ed56fd-04a6-443b-ac10-b39bfc6b9ba9)

In a Cypher `MATCH` each relationship is only allowed once per path (what is known as [trail in graph theory](https://en.wikipedia.org/wiki/Path_(graph_theory))). See https://neo4j.com/docs/cypher-manual/current/patterns/reference/#graph-patterns-rules-relationship-uniqueness. If you want "walk" semantics you have to rewrite your query, as it's not available in MATCH (yet).

**Comment by loveleif** [comment] 2024-10-21 08:17
Closing this issue, as I believe it's the expected behavior (see last comment). Please feel free to open a new issue if I missed something.

**Closed as completed by loveleif** 2024-10-21 08:17 UTC
Labels: cypher, team-cypher
