### ISSUE TITLE
Crashes with `malloc(): invalid size (unsorted)`

### ISSUE THREAD

**Issue by micheljung** [neo4j/neo4j#12564] opened 2020-08-03 22:46 UTC
I'm trying to insert about 12mio nodes into an empty neo4j instance via Java, inserting chunks of 10k (one transaction per chunk). After about 3-4mio nodes, neo4j (running within a `neo4j:4.1.1` Docker container) crashes.

**Neo4j Version:** 4.1.1
**Operating System:** Fedora Core OS 32 (Docker)
**API:** Java API

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:4.1.1`
1. Create an index `CREATE INDEX ON :City(geoNameId)`
1. Insert 10mio nodes in chunks of 10k using:
    ```
    MERGE (c:City{id: $id}) 
    ON CREATE SET c.name = $name, 
    c.location = point({latitude: toFloat($latitude), longitude: toFloat($longitude), crs:'WGS-84'}),
    c.population = toInteger($population)
    RETURN c
    ```

### Expected behavior
Don't crash

### Actual behavior
Crashes:

```
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2020-08-03 22:27:32.989+0000 INFO  Starting...
2020-08-03 22:27:35.266+0000 INFO  ======== Neo4j 4.1.1 ========
2020-08-03 22:27:36.703+0000 INFO  Performing postInitialization step for component 'security-users' with version 2 and status CURRENT
2020-08-03 22:27:36.704+0000 INFO  Updating the initial password in component 'security-users'  
2020-08-03 22:27:38.198+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-08-03 22:27:39.165+0000 INFO  Remote interface available at http://localhost:7474/
2020-08-03 22:27:39.165+0000 INFO  Started.
malloc(): invalid size (unsorted)
```

**Comment by micheljung** [comment] 2020-08-04 05:53
With about ~4mio of those nodes added, the same crash happens when I query  `MATCH (c:City) RETURN c`

**Comment by micheljung** [comment] 2020-08-04 19:48
Couldn't reproduce with `3.5.20`

**Comment by thatapplefreak** [comment] 2020-08-05 13:35
I am also having this issue trying to import data from a csv with approx ~2 million rows.

Neo4j Version: 4.1.1
Operating System: rancher
API: Web UI
Also running in a docker container

```
CREATE INDEX grid_key FOR (n:Block) ON (n.searchKey);
CREATE INDEX grid_res FOR (n:Block) ON (n.res);

USING PERIODIC COMMIT 1000
LOAD CSV WITH HEADERS FROM 'file:///grid_reference.csv' as row
MERGE (n:Block {
    searchKey: toInteger(row.KEY_500),
    res: 500,
    center_1: point({
        longitude: toFloat(row.LON_500), 
        latitude: toFloat(row.LAT_500)
    }),
    center_2: point({
        x: toFloat(row.CONX_500),
        y: toFloat(row.CONY_500)
    })
});
```

**Comment by SimplicityGuy** [comment] 2020-08-08 13:50
Similar issue here, at about 1.2M nodes added I hit this issue.
Neo4j Version 4.1.1
Running in docker (using official image)
Host OS: mac OS Catalina

**Comment by SimplicityGuy** [comment] 2020-08-08 13:52
Related: https://community.neo4j.com/t/java-memory-allocation-issue-with-bulk-upload-in-docker-neo4j-4-1-0/20990

Good suggestion in here: https://phpboyscout.uk/pre-populating-neo4j-using-kubernetes-init-containers-and-neo4j-admin-import/

Trying this: `docker exec -it neo4j neo4j-admin memrec`, and updating my `neo4j.conf` along with container restart.

UPDATE: I applied the settings recommended from `memrec` (actually went a little higher than the recommendations), but still got the same `malloc(): invalid size (unsorted)` error. Made it a little farther with my import though... now about 1.3M nodes.

**Comment by SimplicityGuy** [comment] 2020-08-08 17:40
Besides the upgrade to neo4j, the docker image between 3.5.20 and 4.1.1 also has the upgrade from OpenJDK 8 to 11.

Is this issue specific to running in docker? e.g. if neo4j is installed on a VM, does this issue happen as well?

UPDATE: I have a small (2 vCPUs, 4gb RAM) running Debian 10 and Neo4j 4.1.1 (installed through the neo4j apt repo), and my import is working fine. OVer 5M nodes currently and still importing more. The same importer with the same data with the docker image caused the problem above.

**Comment by PetrJanouch** [comment] 2020-08-19 14:23
We have been able to reproduce the issue and fix it. The fix will be available in the next released version (4.1.2).

This issue is dependent on the cache size ( dbms.memory.pagecache.size setting ) and the only size we have been able to observe it with is 512MB, which is unfortunately the default value for our docker images. So until 4.1.2 is released, you can try to set dbms.memory.pagecache.size to something else.

**Comment by SimplicityGuy** [comment] 2020-08-21 20:09
> We have been able to reproduce the issue and fix it. The fix will be available in the next released version (4.1.2).
> 
> This issue is dependent on the cache size ( dbms.memory.pagecache.size setting ) and the only size we have been able to observe it with is 512MB, which is unfortunately the default value for our docker images. So until 4.1.2 is released, you can try to set dbms.memory.pagecache.size to something else.

Great to hear! Thanks for addressing this. Can you link a PR for this? I'm curious what the fix looks like for this.

**Comment by PetrJanouch** [comment] 2020-09-02 11:52
@SimplicityGuy [It was fixed by this commit](https://github.com/neo4j/neo4j/commit/2786487bc350dec6065ea661bb1a5c179b60b9c2)

**Comment by PetrJanouch** [comment] 2020-09-28 09:26
4.1.2 was released last week. Please re-test with that version. I am closing this now, but feel free to reopen this issue if the issue is still present with 4.1.2.

**Closed as completed by PetrJanouch** 2020-09-28 09:26 UTC
Labels: bug, team-kernel
