### ISSUE TITLE
db.schema.visualization produces incorrect results

### ISSUE THREAD

**Issue by Bikeman868** [neo4j/neo4j#12608] opened 2020-10-15 17:10 UTC
- Neo4j version: 4.1.3
- Operating system: MacOS Catalina 10.15.7
- API/Driver: Neo4j Browser

The command db.schema.visualization contains loops suggesting that nodes have relationships with other nodes of the same type, but this it not the case in this graph.

I include a screenshot below in which you can see the output of db.schema.visualization and also a Cypher query showing that there are no nodes with this loopback relationship.

![Screen Shot 2020-10-15 at 10 00 40 AM](https://user-images.githubusercontent.com/5679259/96163245-84437f80-0ece-11eb-80f4-a04912fd031c.png)

**Comment by sherfert** [comment] 2020-10-19 06:32
Duplicate of https://github.com/neo4j/neo4j/issues/9726

**Closed as completed by sherfert** 2020-10-19 06:32 UTC
Labels: bug
