### ISSUE TITLE
java.io.IOException: Exception closing multiple resources.

### ISSUE THREAD

**Issue by cnwangjie** [neo4j/neo4j#12897] opened 2022-06-16 11:09 UTC
Docker image: neo4j:4.4.5 (sha256:dda806294888780a1e32f44d9cb8729cf402d3962ba02e0ce75effeb013e6d43)

### Steps to reproduce

It will raise an error definitely when I run the following query. But it occurs on these parameters only. When I change the id or decrease the LIMIT below 3, It is fine.

```
MATCH (b:User)-[i:IN_MORI]->(a:User) WHERE i.moriId = 1490047545788469597
MATCH (s:Story) WHERE s.id < 1491709998202196186
MATCH (a)-[t:IN_MORI]->(b)-[au:AUTHOR]->(s:Story)
  WHERE 1490047545788469597 IN au.moriIds
    OR a <> b AND t.moriId IN au.moriIds
RETURN DISTINCT s
ORDER BY s.id DESC
LIMIT 20
```

<details>
<summary>error detail</summary>

```
2022-06-16 10:36:37.332+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Exception closing multiple resources., reference 8ce77297-88da-48e0-9a3d-12d470e220e4.
2022-06-16 10:36:37.332+0000 ERROR [o.n.b.r.s.i.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Exception closing multiple resources., reference 8ce77297-88da-48e0-9a3d-12d470e220e4.
org.neo4j.fabric.executor.FabricException: Exception closing multiple resources.
        at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:65) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.executor.Exceptions.transform(Exceptions.java:35) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:69) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.bolt.BoltQueryExecutionImpl$QueryExecutionImpl.request(BoltQueryExecutionImpl.java:179) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.AbstractCypherAdapterStream.handleRecords(AbstractCypherAdapterStream.java:105) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.v3.messaging.ResultHandler.onPullRecords(ResultHandler.java:41) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.v4.messaging.PullResultConsumer.consume(PullResultConsumer.java:42) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:507) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:260) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.statemachine.impl.TransactionStateMachine.streamResult(TransactionStateMachine.java:99) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.transaction.StatementProcessorTxManager.streamResults(StatementProcessorTxManager.java:251) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.transaction.StatementProcessorTxManager.pullData(StatementProcessorTxManager.java:111) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.v4.runtime.AutoCommitState.processStreamPullResultMessage(AutoCommitState.java:45) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.v4.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:51) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.nextState(AbstractBoltStateMachine.java:154) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.statemachine.impl.AbstractBoltStateMachine.process(AbstractBoltStateMachine.java:102) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:93) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.DefaultBoltConnection.lambda$enqueue$0(DefaultBoltConnection.java:156) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatchInternal(DefaultBoltConnection.java:252) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:187) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:177) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:257) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at org.neo4j.bolt.runtime.scheduling.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$3(ExecutorBoltScheduler.java:240) ~[neo4j-bolt-4.4.5.jar:4.4.5]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [apoc-4.4.0.3-core.jar:4.4.0.3]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: Exception closing multiple resources.
        at org.neo4j.io.IOUtils.close(IOUtils.java:159) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:95) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.doRequest(QuerySubject.java:184) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.request(QuerySubject.java:167) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.StrictSubscriber.request(StrictSubscriber.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at org.neo4j.fabric.stream.Rx2SyncStream$RecordSubscriber.request(Rx2SyncStream.java:129) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.maybeRequest(Rx2SyncStream.java:91) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:50) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        ... 26 more
Caused by: java.io.IOException: Exception closing multiple resources.
        at org.neo4j.io.IOUtils.close(IOUtils.java:159) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:95) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.doRequest(QuerySubject.java:184) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.request(QuerySubject.java:167) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.StrictSubscriber.request(StrictSubscriber.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at org.neo4j.fabric.stream.Rx2SyncStream$RecordSubscriber.request(Rx2SyncStream.java:129) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.maybeRequest(Rx2SyncStream.java:91) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:50) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        ... 26 more
Caused by: java.io.IOException: Exception closing multiple resources.
        at org.neo4j.io.IOUtils.close(IOUtils.java:159) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:95) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.doRequest(QuerySubject.java:184) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.request(QuerySubject.java:167) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.StrictSubscriber.request(StrictSubscriber.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at org.neo4j.fabric.stream.Rx2SyncStream$RecordSubscriber.request(Rx2SyncStream.java:129) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.maybeRequest(Rx2SyncStream.java:91) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:50) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        ... 26 more
Caused by: java.lang.IllegalStateException: Should not use a closed ScopedMemoryTracker
        at org.neo4j.memory.ScopedMemoryTracker.throwIfClosed(ScopedMemoryTracker.java:87) ~[neo4j-common-4.4.5.jar:4.4.5]
        at org.neo4j.memory.ScopedMemoryTracker.releaseHeap(ScopedMemoryTracker.java:78) ~[neo4j-common-4.4.5.jar:4.4.5]
        at org.neo4j.internal.kernel.api.helpers.CachingExpandInto$FromCachedSelectionCursor.close(CachingExpandInto.java:321) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$RelationshipCursorIterator.close(TransactionBoundQueryContext.scala:1419) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.PrimitiveLongHelper$$anon$1.closeMore(PrimitiveLongHelper.scala:30) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:87) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$1.closeMore(ClosingIterator.scala:123) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:87) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.close(IOUtils.java:152) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.io.IOUtils.closeAll(IOUtils.java:56) ~[neo4j-io-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.close(ClosingIterator.scala:85) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:95) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator$$anon$3.innerHasNext(ClosingIterator.scala:152) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.ClosingIterator.hasNext(ClosingIterator.scala:93) ~[neo4j-cypher-runtime-util-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.serveResults(PipeExecutionResult.scala:85) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.runtime.interpreted.PipeExecutionResult.request(PipeExecutionResult.scala:73) ~[neo4j-cypher-interpreted-runtime-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.StandardInternalExecutionResult.request(StandardInternalExecutionResult.scala:90) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.cypher.internal.result.ClosingExecutionResult.request(ClosingExecutionResult.scala:144) ~[neo4j-cypher-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.doRequest(QuerySubject.java:184) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.QuerySubject$BasicQuerySubject$1.request(QuerySubject.java:167) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2158) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at reactor.core.publisher.StrictSubscriber.request(StrictSubscriber.java:138) ~[reactor-core-3.4.11.jar:3.4.11]
        at org.neo4j.fabric.stream.Rx2SyncStream$RecordSubscriber.request(Rx2SyncStream.java:129) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.maybeRequest(Rx2SyncStream.java:91) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        at org.neo4j.fabric.stream.Rx2SyncStream.readRecord(Rx2SyncStream.java:50) ~[neo4j-fabric-4.4.5.jar:4.4.5]
        ... 26 more
```

</details>

**Comment by chasemc** [comment] 2023-04-28 21:13
Ran into this today, docker image 5.1.0

**Comment by chasemc** [comment] 2023-04-28 21:14
Note: It happens when increasing a LIMIT as well. But I am doing a really large relationship property update in the background which I would suspect is the cause

**Comment by sherfert** [comment] 2023-06-20 08:39
@cnwangjie @chasemc 

Sorry for being so unresponsive on this issue!

Is it possible to provide us with a sample dataset on which the issue is reproducible?

**Comment by chasemc** [comment] 2023-06-20 12:47
I don't have an example. It's been a while but `really large relationship property` probably meant it was a >100GBs database. If I run into it again I'll provide an update

**Comment by mnd999** [comment] 2024-11-08 09:12
Closing as we have not had a response for some time. If it is still an problem, feel free to reopen the issue.

**Closed as completed by mnd999** 2024-11-08 09:12 UTC
Labels: bug, team-cypher
