### ISSUE TITLE
AuthenticationException on query execution

### ISSUE THREAD

**Issue by calebebrim** [neo4j/neo4j#12018] opened 2018-08-15 20:16 UTC
- Neo4j version: Tested With different Versions
- Operating system: OSX HighSierra
- API/Driver: Python Driver, neo4j Client
- **Steps to reproduce**

Error: 
- Open client; 
- Start Database;
- Open Browser;
- Run Query; 
- Open Client Log; 
- Then: 

2018-08-15 20:02:01.030+0000 ERROR Unexpected error detected in bolt session '28cfe9fffe1df93f-0000d1c8-00000024-e9fb2b4f62ff4297-c7ee3141'. Failed to process a bolt message
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: Failed to process a bolt message
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
	at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
	at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.neo4j.bolt.security.auth.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.bolt.security.auth.BasicAuthentication.doAuthenticate(BasicAuthentication.java:78)
	at org.neo4j.bolt.security.auth.BasicAuthentication.authenticate(BasicAuthentication.java:60)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineSPI.authenticate(BoltStateMachineSPI.java:93)
	at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:412)
	... 12 more

===================== UPDATE =================================

I've checked out the console of browser and it keep logging a lot this error:  

Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at r (vendor-8e76f7dbd0cd6ce654d5.js:1)
    at l (app-8e76f7dbd0cd6ce654d5.js:1)
    at $n (app-8e76f7dbd0cd6ce654d5.js:1)
    at Object.enqueueSetState (app-8e76f7dbd0cd6ce654d5.js:1)
    at t.o.setState (vendor-8e76f7dbd0cd6ce654d5.js:1)
    at t.value (app-8e76f7dbd0cd6ce654d5.js:1)
    at e.value (app-8e76f7dbd0cd6ce654d5.js:1)
    at Object.trigger (app-8e76f7dbd0cd6ce654d5.js:1)
    at SVGGElement.j (app-8e76f7dbd0cd6ce654d5.js:1)
    at SVGGElement.__onmouseout (d3.min.js:21)

================================= Update ==============================

I've downloaded the terminal version of n4j and the problem keep happening. 

And about the browser error, after the first query the error start to appear on the console. And then any button works anymore. 

================================= Update ==============================
When I open the console without do anything it start to log this error: 

(33) Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').

And it keep happening, it was 33th time when I copied the log message.

**Comment by zhenlineo** [comment] 2018-10-02 09:24
@calebebrim 
We are missing a lot of information to help with this issue.
Could you give us more information that might be helpful you think to recreate the issue?

For example:
How did you got this error? Did you get it with our Neo4j browser? What version of the neo4j and browser? Is any driver related in this issue? Where did you got the error message you posted? Is it in Neo4j `debug.log` or `neo4j.log`? What query you are running to tigger this error?

Could you give some example code to reproduce this error?
Regards,
Zhen

**Comment by zhenlineo** [comment] 2018-11-05 14:45
Hi @calebebrim,
We are closing this issue temporarily because we are missing information from you to help us understand the error better.

Be free to reopen this issue if the problem still persists. When opening the issue, pls provide us more information regards:
```How did you got this error? 
Did you get it with our Neo4j browser?
What version of the neo4j and browser? 
Is any driver related in this issue? 
Where did you got the error message you posted? 
Is it in Neo4j debug.log or neo4j.log? 
What query you are running to tigger this error?
```
Zhen

**Closed as completed by zhenlineo** 2018-11-05 14:45 UTC
Labels: team-drivers, need-more-info
