### ISSUE TITLE
Neo4j  5.21.0 error - NullCheckReferenceProperty cannot be cast to class org.neo4j.cypher.internal.expressions.ASTCachedProperty

### ISSUE THREAD

**Issue by alexanoid** [neo4j/neo4j#13488] opened 2024-07-14 12:53 UTC
I'm trying to migrate from Neo4j 5.18.0 to 5.21.0 Community Edition.

I have the following query:

```
CALL db.index.fulltext.queryNodes("countryAndTranslationLowerNames", "test1") YIELD node, score
WHERE any(x IN labels(node) WHERE x IN ['Country']) OR (node)-[:CONTAINS]-(:Country)
OPTIONAL MATCH (node)-[:ALIAS_FOR*]->(rootAliasOwner:Country)
WHERE NOT (rootAliasOwner)-[:ALIAS_FOR*]->(:Country)
OPTIONAL MATCH (node)<-[:CONTAINS]-(translationOwner:Country) WHERE any(x IN labels(node) WHERE x IN ['Translation'])
OPTIONAL MATCH (translationOwner)-[:ALIAS_FOR*]->(rootTranslationOwner:Country)
WHERE NOT (rootTranslationOwner)-[:ALIAS_FOR*]->(:Country)
WITH node, rootAliasOwner, coalesce(rootTranslationOwner, translationOwner) as rootTranslationOwner, score
WITH node, coalesce(rootAliasOwner, rootTranslationOwner) as rootNode, score
WITH node, rootNode
WITH node, rootNode, coalesce(rootNode, node) as resultNode
WITH resultNode, COLLECT(node) AS nodes, COLLECT(rootNode) AS rootNodes
WITH resultNode, apoc.coll.unionAll(nodes, rootNodes) AS allNodes
WITH resultNode, allNodes
WITH resultNode, [x IN allNodes WHERE x <> resultNode | x ] AS result
RETURN DISTINCT resultNode as node, result as alsoKnownAs
ORDER BY node.usageCount DESC, node.lowerName ASC
```

When I execute this query on 5.21.0 it fails with the following error:

```
Neo.DatabaseError.General.UnknownError

class org.neo4j.cypher.internal.physicalplanning.ast.NullCheckReferenceProperty cannot be cast to class org.neo4j.cypher.internal.expressions.ASTCachedProperty (org.neo4j.cypher.internal.physicalplanning.ast.NullCheckReferenceProperty and org.neo4j.cypher.internal.expressions.ASTCachedProperty are in unnamed module of loader 'app')
```

What am I doing wrong and how to fix it?

**Comment by ericsporre** [comment] 2024-07-15 07:38
Hi, and thanks for reporting this bug!

This issue has already been patched and fixed in 5.21.2, see [changelog](https://github.com/neo4j/neo4j/wiki/Neo4j-5-changelog). Try it out and please get back to me if you're still running into problems.

Sorry for any inconvenience caused by this!
Eric

**Comment by pontusmelke** [comment] 2024-08-19 06:55
I'll close this issue. If the problem remains please reopen or open a new issue.

Best regards
Pontus

**Closed as completed by pontusmelke** 2024-08-19 06:55 UTC
Labels: bug

**Comment by alexanoid** [comment] 2024-09-11 21:19
@pontusmelke I apologize for the late response. I have just tried version 5.23.0 and I am happy to report that this issue is resolved. Thank you very much!
