### ISSUE TITLE
TOSTRING() fails in cases where STR() worked

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#7053] opened 2016-05-03 21:14 UTC
TOSTRING() fails in cases where STR() worked

**Neo4j Version:** 2.3.1
**Operating System:** Ubuntu 14.10  
### Steps to reproduce

I have an collection of arrays

`Collect([TOINT(idn),STR(name),TOINT(status),TOINT(days_norm),TOINT(days_spent)]) as flowsteps``

This

`REDUCE (x=0, i IN flowsteps | x + TOINT(STR(i[3]))) as normP`  

works, but this  

REDUCE (x=0, i IN flowsteps | x + TOINT(TOSTRING(i[3]))) as normP` 

 throws an error

`Cypher error: Type mismatch: expected Float, Integer or String but was Any (line 33, column 57 (offset: 1271)) " REDUCE (x=0, i IN flowsteps | x + TOINT(TOSTRING(i[3]))) as normP`  

Same error can be observed when running this:

`UNWIND [1,"12",37,"27654"] as elt RETURN toString(elt)``
### Expected behavior

TOSTRING() should accept Any, like STR() dis

**Comment by systay** [comment] 2016-05-19 04:38
I think that this is a duplicate of #7055. If #7169 does not solve the problems for this issue, please re-open it again.

Thanks so much for reporting!

**Closed as completed by systay** 2016-05-19 04:38 UTC
Labels: bug, cypher, changelog
