### ISSUE TITLE
Full text indexes in cypher

### ISSUE THREAD

**Issue by thomasfr** [neo4j/neo4j#2048] opened 2014-02-25 16:14 UTC
I am not sure if the title is clear enough. The reason for this issue for me is the spatial plugin for neo4j (https://github.com/neo4j/spatial). If you want to use neo4j with the spatial plugin completly via cypher and the rest api over http, it is not possible to configure an autoindex which takes care of adding node with 'lat' and 'lon' properties to the correct index. Without adding the nodes to the correct index they will be not found when using cypher with a `withinDistance` query. So after each `CREATE` cypher query on would have to make an additional call to the REST API.
See here for a complete example / list of actions: https://gist.github.com/thomasfr/8103037
There is also a related issue on the spatial plugin: https://github.com/neo4j/spatial/issues/125

Is it possible to add more than one auto indexing configuration, with the possibility to define the index type for different node "types", to the neo4.properties file? A node type could be identified via their labels or simply when the node has the configured properties in `node_keys_indexable`.

cheers

**Comment by jspenc72** [comment] 2015-04-20 05:27
I would like to 1+ this request!

**Comment by bugs181** [comment] 2015-06-24 05:42
+1 here too for the feature request.

**Comment by pangguoming** [comment] 2015-10-15 14:04
+1

**Comment by versae** [comment] 2015-11-19 16:37
+1

**Comment by jakewins** [comment] 2015-12-06 18:12
Closing as duplicate of https://github.com/neo4j/neo4j/issues/1919

**Closed by jakewins** 2015-12-06 18:12 UTC
Labels: cypher, feature
