### ISSUE TITLE
Instance fails to start after upgrade if upgrade_backup directory is present

### ISSUE THREAD

**Issue by amorgner** [neo4j/neo4j#2557] opened 2014-06-12 00:18 UTC
If you have a directory named ''upgrade_backup'' in your Neo4j database directory, startup can fail.

	axel@dev1 ~/Downloads/neo4j-community-2.1.2$ bin/neo4j start
	WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
	Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
	Starting Neo4j Server...WARNING: not changing user
	process [4736]... waiting for server to be ready..... Failed to start within 120 seconds.
	Neo4j Server may have failed to start, please check the logs.

**Comment by fsperling** [comment] 2015-11-02 00:57
Seems like a duplicate of #220 to me.
Should we close this issue and try to solve it over there?

**Comment by jakewins** [comment] 2015-12-06 06:12
+1, closing as duplicate of #220 and relabeling #220 as a bug

**Closed by jakewins** 2015-12-06 06:12 UTC
