### ISSUE TITLE
Nothing match anymore, only the indexed things

### ISSUE THREAD

**Issue by Mintactus** [neo4j/neo4j#12590] opened 2020-09-27 07:25 UTC
Neo4j Browser version: 4.1.2 Remote Session on Neo4j Desktop
Neo4j Server version: 3.5.21 (enterprise) Neo4j Desktop
Client OS : Linux mint 20
Server OS: Linux mint 20

API: I'm using neo4j Desktop Remote connection on the client

When I execute the most simple Cypher request like:

MATCH (p:Proprietaire:Quebec {postalCode:'G1W 0C1'})
RETURN p

RESULT : (no changes, no records)

EXPECTED RESULT: Some data as this request is based on a postalCode present in the database. I try with other properties and it didn't work.

It doesn't match any of the properties anymore. It seems that only the indexed ones work.

The show error log option did't work in the neo4j desktop menu and there was no log.

**Comment by mnd999** [comment] 2020-10-01 09:44
Thanks for the report, we would need a bit more information to look into this. Can you provide a plan for the working and non-working query (prepend `PROFILE` or `EXPLAIN`) to your working and non-working queries. Also, it's useful to look at the counts and indexes on the graph to see what is there. Can you provide the out put of `call db.stats.retrieve("GRAPH COUNTS")`?

**Comment by Mintactus** [comment] 2020-10-01 17:56
Here is some more information about my issue, I have a weird feeling that it might be link to the pagecache.

![explain](https://user-images.githubusercontent.com/30415501/94844976-dc10bf80-03d3-11eb-8661-c265c4d58a17.png)
![profile](https://user-images.githubusercontent.com/30415501/94844984-df0bb000-03d3-11eb-97ef-269245a0eb9c.png)
[GraphCounts.csv.zip](https://github.com/neo4j/neo4j/files/5313939/GraphCounts.csv.zip)

**Comment by pontusmelke** [comment] 2020-10-05 09:34
Hi @Mintactus 
Are you sure there are nodes that both have the labels `Proprietaire` and `Quebec`,  the pattern `(p:Proprietaire:Quebec {postalCode:'G1W 0C1'})` means that it matches node having both the labels `Proprietaire` and `Quebec` as well as having the provided postal code. From the execution profile it looks like there are no nodes that have both the labels.

Regards,
Pontus

**Comment by Mintactus** [comment] 2020-10-05 22:46
Here is the request:

MATCH (p:Proprietaire:Quebec) RETURN p LIMIT 1

You can see the result of this request in the records.json file.

Here is another request to match the same node:

PROFILE
MATCH (p:Proprietaire:Quebec) WHERE p.codePostal = "G1R 5L5"
RETURN p LIMIT 10

You can see the result of this request in the plan.png file.

Am I crazy, is it me, my request or something is wrong.

Thanks

**Comment by Mintactus** [comment] 2020-10-05 23:01
Attached files for the last message above.

![plan](https://user-images.githubusercontent.com/30415501/95140483-d85aa100-0723-11eb-8079-5eacef510f0a.png)
[records.json.zip](https://github.com/neo4j/neo4j/files/5330534/records.json.zip)

**Comment by pontusmelke** [comment] 2020-10-06 07:59
Yeah that is weird. I am not able to reproduce that behavior though. Could you try prepending `CYPHER runtime=interpreted` to your query. Maybe also run the other query with profile, so run `PROFILE MATCH (p:Proprietaire:Quebec) RETURN p LIMIT 1. and paste the plan here?

**Comment by pontusmelke** [comment] 2020-10-06 12:19
Ah we found it now. In your records.json the space is not a normal space but a non-breaking space, so what you have stored in the node is actually something like `G1R[NBSP]5L5` but in your query you are looking for `G1R 5L5`. 

Something probably went wrong when the node was created or at least when the property was set.

Regards
Pontus

**Comment by Mintactus** [comment] 2020-10-07 20:22
Thank you for your support.

Indeed there was a non-breaking space in the postal code and some other
fields causing this weird behavior.
My data was coming from a HTML table grab from python read_csv function
from pandas module.
Case closed but I would like to add a detail who might improve the neo4j
browser app.

When I created the MATCH close, I took the value from the one shown on the
browser on a RETURN node request, the one on the json file created from the
browser. So the question is, why I copied a normal space from the json
shown by the browser if the actual database value was a non-breaking space.

It seems that the "viewer" part of the browser converts non-breaking to
breaking space but when you paste it back to the request, surprise!
As you copy and paste it you can't expect a special character to be the
cause.

Thank you again for your support

**Comment by pontusmelke** [comment] 2020-10-08 08:29
no problem, I'll close this issue. Thanks for reaching out.
Regards,
Pontus

**Closed as completed by pontusmelke** 2020-10-08 08:29 UTC
Labels: bug, team-cypher
