### ISSUE TITLE
Some resource was not correct release after org.neo4j.unsafe.batchinsert.BatchInserter.shutdown()

### ISSUE THREAD

**Issue by pyzhou-talend** [neo4j/neo4j#10534] opened 2017-11-29 08:44 UTC
I'm using org.neo4j-3.2.6.jar . I got a java.io.Exception when I try to delete the whole database after shut dowm. It seems some file stream was not released. ```{databse.root}\schema\index\lucene\1\1``` this folder is the one which have been left and cause the java.io.Exception
Note that, this only occurs when a IndexEntryConfilctException was happening.

**Comment by burqen** [comment] 2017-12-18 07:45
@pyzhou-talend Thank you for reporting!
To make further investigations I'd like to ask you some questions:
- Have you got the full stack trace from the exception?
- Was the shutdown successful before deleting this store? 
- Do you have any logs from the incident? Most notably the `debug.log` is of great interest.
- Have you found a reliable way to reproduce it?

**Comment by burqen** [comment] 2018-04-30 12:10
Closing this issue due to lack of answer. Please open again if you have additional information that would make investigation possible.

**Closed as completed by burqen** 2018-04-30 12:10 UTC
Labels: team-kernel
