### ISSUE TITLE
Cannot start service from Windows paths containing blanks

### ISSUE THREAD

**Issue by fsteinke** [neo4j/neo4j#9646] opened 2017-07-10 05:05 UTC
When using the Neo4j CE 3.2.2 (x64 zip) i cannot get the service to start. Starting from `C:\temp\` or `C:\Windows\` works fine, so i'd assume the issue has something to do with the blank in `C:\Program Files\`.

**Neo4j Version:** CE 3.2.2 (x64 zip)
**Operating System:** Windows 10 Pro
**Java (JDK):** 1.8.0_131

### Steps to reproduce
1. Download neo4j (zip) from neo4j.com
2. Extract data to `C:\Program Files\neo4j-community-3.2.2`
3. Execute `C:\Program Files\neo4j-community-3.2.2\bin\neo4j.bat install-service`
4. Execute `C:\Program Files\neo4j-community-3.2.2\bin\neo4j.bat start`

### Expected behavior
neo4j service starts

### Actual behavior
`neo4j.bat start` returns
```
Invoke-Neo4j : Error on starting service "Neo4j Graph Database - neo4j (neo4j)".
On Line:1 Char:223
+ ... \neo4j-ce-3.2.1\bin\Neo4j-Management.psd1'; Exit (Invoke-Neo4j start)
+                                                       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j
```

**Comment by eebus** [comment] 2017-12-11 20:02
Hello @fsteinke 
Have you tried with the latest 3.2.8? This seems have been fixed in #10407 .

**Comment by jyotsna792** [comment] 2017-12-18 11:13
Hey,

I am using Neo4j 3.3.1( x64 zip) but I am getting the exact same error. I am using windows 10 and Java 1.8.0_151. 

I tried to change the directory to C:\Neo4j as mentioned in this answer(https://goo.gl/fQkZu8) but that does not work for me.

**Comment by yuri-karkh** [comment] 2018-01-08 09:51
confirm such behavior on win 10 neo4j 3.3.1 x64

**Comment by jyotsna792** [comment] 2018-01-08 10:21
@yuri-karkh I solved the problem. The issue was that my Java files were located in the Program Files(x86) folder. I just moved them to the Program Files folder and changed the environment variables and it worked after that!

**Comment by yuri-karkh** [comment] 2018-01-08 12:13
thanks @jyotsna792 will try your solution as I see my Java files located in x86 too.

**Comment by yuri-karkh** [comment] 2018-01-08 12:19
still facing the issue 
![issue](https://user-images.githubusercontent.com/12514101/34670433-f529c4b0-f47e-11e7-8dcf-59485f747363.PNG)

**Comment by jyotsna792** [comment] 2018-01-08 12:22
@yuri-karkh Did you change your environment variable as well?

**Comment by yuri-karkh** [comment] 2018-01-08 12:27
I just found that even after I set installation folder to PF without x86 it still installs it in x86 folder, so checking why so.

**Comment by jyotsna792** [comment] 2018-01-08 12:46
@yuri-karkh you do not need to install it again. Just copy the files to the PF folder and make sure you are getting the 64 bit version and it will be fine.

**Comment by yuri-karkh** [comment] 2018-01-08 12:47
So the same, I have JAVA_HOME set,  also updated policy to Set-ExecutionPolicy -ExecutionPolicy Bypass and still can't install the service.
![issue](https://user-images.githubusercontent.com/12514101/34671319-c95e5b76-f482-11e7-90d8-55b637fa21f0.PNG)

**Comment by yuri-karkh** [comment] 2018-01-08 12:48
same I get in installed desktop version of neo4j:
![issue](https://user-images.githubusercontent.com/12514101/34671375-01e44e24-f483-11e7-8c5e-aa9971b6aff7.PNG)

**Comment by jyotsna792** [comment] 2018-01-08 12:53
@yuri-karkh perhaps try to set the NEO4J_CONF variable to C:\neo4j\conf and try again?

**Comment by yuri-karkh** [comment] 2018-01-08 12:57
just set and the same, do u maybe know what it tries to run from C:\Users... 
![issue](https://user-images.githubusercontent.com/12514101/34671710-3f94f326-f484-11e7-9e90-eb9f9cc939ef.PNG)

**Comment by yuri-karkh** [comment] 2018-01-08 13:18
![issue](https://user-images.githubusercontent.com/12514101/34672470-3263396c-f487-11e7-8f1b-7f69a6ad4178.PNG)

so it is kind an another issue not java...

**Comment by yuri-karkh** [comment] 2018-01-13 16:36
for me issue was related to TMP/TEMP env variables. It was set to User app data dir and application was not able to write to it, hope this helps.

**Comment by chrisp429** [comment] 2018-01-15 15:51
> TMP/TEMP env variables. It was set to User app data dir and application was not able to write to it, 

@yuri-karkh  could you please explain better what you did? I think I am in the same situation:
![neo](https://user-images.githubusercontent.com/25708248/34950695-2f57410e-fa14-11e7-8e48-379c832907ca.jpg)

**Comment by chrisp429** [comment] 2018-01-15 17:20
I managed, it was easy indeed:
![image](https://user-images.githubusercontent.com/25708248/34954379-7d45d950-fa20-11e7-9bce-81ee9661ad94.png)
I just creater C:\Temp, opened Environment Variables and replaced the default TEMP and TMP path which was "%USERPROFILE%\AppData\Local\Temp" with it.

**Comment by loritzm** [comment] 2018-02-17 17:53
I had the same problem with a “shortened” directory name in the TEMP variable, leading to an abort like @yuri-karkh and @chrisb429 mentioned. In English, the error message, given a user profile in C:\Users\user.name, was:

> Invoke-Neo4j : An object at the specified path C:\Users\USER~1.NAM does not exist. 

Debugging the script, I found the error raised in line 68 of `bin/Neo4j-Management/Confirm-JavaVersion.ps1`. Apparently, the script uses a temp file to store the output of “java -version”, reads it, then tries to delete it:
```PowerShell
Remove-Item -Path $stdError -Force | Out-Null
```
At this point, the `$stdError` variable contains the full path name of the temp file, just the user profile part is shortened to 8.3. It seems `Remove-Item` cannot deal with that cleanly.
However, `Get-Item` can, and can be used to sanitize the file name before passing it to `Remove-Item`:
```PowerShell
Get-Item -Path $stdError | Remove-Item -Force | Out-Null
```
After modifying the file like that, the error disappeared and the neo4j server could start.
Does that solve your problem as well?

**Comment by ali-ince** [comment] 2018-03-06 16:55
Dear @loritzm,

We have tried to reproduce the issue in an attempt to verify your proposed fix, but it worked as expected in our test environments. We've tried with different user name combinations that would result in `8.3` folder names but it seems that it is not related with the problem itself.

Could you please send us the exact windows and powershell versions you've been using?

Thanks.

**Comment by loritzm** [comment] 2018-03-23 13:44
I experienced this on Windows 10 Enterprise, v1703, OS Build 15063.909 with PowerShell 5.1.15063.909.
If you can’t reproduce, fine. At least, someone else with the same problem has one more lever to try ;)

**Comment by ali-ince** [comment] 2018-04-05 16:39
Hi All,

This issue should have been resolved with #11469. 

The fixed script will be included in upcoming releases. For the time being, you can override your `TEMP` and `TMP` environment variables with a path that doesn't contain MSDOS8.3 convention path entries (as suggested by @chrisp429 above).

Feel free to re-open the issue if you encounter the error again with new versions.

Thanks for reporting this issue and providing workarounds.

**Comment by loritzm** [comment] 2018-04-06 19:21
I can confirm that the change in #11469 works for me, too.

**Comment by ajit1234** [comment] 2018-10-28 04:29
Not working in version 3.4.7 community

**Comment by mahmoudafer** [comment] 2018-10-28 12:16
Not working in version 3.4.0, 3.4.1, nor 3.4.9 ( I tried only these) on Neo4j desktop 1.1.10. Anyone?

**Comment by ali-ince** [comment] 2018-10-28 20:25
Hi @ajit1234 and @mahmoudafer,

Could you please provide more info about your environment?

1. What version of Windows are your running on?
2. Are you both running with Neo4j Desktop?
3. What is the folder Neo4j Desktop is configured to use? or what is the folder you're trying to run neo4j from?
4. Could you attach logs from Neo4j Desktop? If not on neo4j desktop, could you try adding `-verbose` argument to your `neo4j.bat` or `neo4j-admin.bat` invocation? This will provide more info on what's going wrong.

Thanks.

**Comment by mahmoudafer** [comment] 2018-10-28 20:36
Hello, I just uninstalled the desktop app and going to install it on ubuntu. However, I can give you the info hoping it helps others. I think it might be because of java version incompatibility: 

1. Windows Version: 10 pro build 17134
 Neo4j Desktop App version: 1.1.10
Neo4j versions tested: 3.4.0, 3.4.1, & 3.4.9

2. Yeah desktop app

3.C:/users/USER_NAME/

4. It's deleted but I have written the error part:

> the string is missing the terminator: '. + CategoryInfo : ParseError: (:) [], ParentContainsErrorRecordException + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

> [info] Process [3428] exit with code '1', signal 'null'
[info] Action[DATABASE_CREATION_FAILED]...

**Comment by ajit1234** [comment] 2018-10-30 08:25
Hello,
    I suspected if some windows updates had installed day before i saw this
issue. So i restarted the machine and found this issue gone.

Thanks,
Ajit

**Comment by ali-ince** [comment] 2018-10-31 13:38
@mahmoudafer Does your password include some special characters like `{`, `}`, `[`, `]`, `&`, `"`, etc? If so, could you please try with an alternative one that doesn't contain such characters?

**Comment by mahmoudafer** [comment] 2018-10-31 16:50
@ali-ince no i tried several passwords with letters only and didn't work

**Comment by dahaynes** [comment] 2018-11-15 03:49
I'm running into this problem as well

Windows 10; Neo4j 3.3.2
`C:\Program Files\neo4j\installation-3.3.2\bin>neo4j start -verbose
VERBOSE: Neo4j Root is 'C:\Program Files\neo4j\installation-3.3.2'
VERBOSE: Neo4j Server Type is 'Enterprise'
VERBOSE: Neo4j Version is '3.3.2'
VERBOSE: Neo4j Database Mode is ''
VERBOSE: Start command specified
VERBOSE: Neo4j Windows Service Name is neo4j
VERBOSE: Starting the service.  This can take some time...
Invoke-Neo4j : Failed to start service 'Neo4j Graph Database - neo4j (neo4j)'.
At line:1 char:229
+ ... -3.3.2\bin\Neo4j-Management.psd1'; Exit (Invoke-Neo4j start -verbose)
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Invoke-Neo4j`

**Comment by ali-ince** [comment] 2018-12-03 13:12
Hi @dahaynes,

Neo4j 3.3.2 is a fairly old release, and the fix I've mentioned above (PR #11469) should be included in the latest versions (it should at least be 3.3.5 for 3.3 versions). Please update to one of the latest patch versions and retry the same setup.

@mahmoudafer we're not able to reproduce the error in our environments. It would be awesome if you could provide us with reproduction steps or detailed outputs from command prompt executing `neo4j.bat -v start` or `neo4j-admin.bat set-initial-password password`.

Thanks.

**Comment by mahmoudafer** [comment] 2018-12-03 22:24
Hi @ali-ince I'm really sorry as I already ditched windows and set it up on aws ubuntu instance and working like a charm. 
Thanks for your efforts!

**Comment by ali-ince** [comment] 2018-12-05 17:19
I'm re-closing this issue since the original issue has been resolved and I would kindly ask anyone running into a similar problem to create a new issue with as much information as possible describing the problem (and their environment as well).

Thanks.

**Closed as completed by ali-ince** 2018-12-05 17:19 UTC
Labels: team-drivers
