### ISSUE TITLE
Error when using merge with node from optional match

### ISSUE THREAD

**Issue by Gudahtt** [neo4j/neo4j#8512] opened 2016-12-13 19:55 UTC
I believe I found an undocumented breaking change between versions 2 and 3 of Neo4j, involving the use of `MERGE` using a node that has been optionally matched.

- Neo4j version: 3.0.6, 3.0.7
- Operating system: Windows 10
- API/Driver: Tested with Neo4j Browser and REST API

### Steps to reproduce
1. Create node with label 'test1', and ensure no node with label 'test2' exists
2. Run this cypher:
`MATCH (n1:test1)
OPTIONAL MATCH (n2:test2)
MERGE (n1)-[:rel]->(n2)
RETURN n1, n2`

### Expected behavior
It should should return `n1, null`, and not result in an error. This was the behavior on v2.3.2 and 2.3.7.

### Actual behavior
It results in an error on Neo4j v3.0.6,  and 3.0.7: `Expected to find a node at n2 but found nothing Some(null)`

Maybe the original behavior was a bug, and this change intentional? It does seem a bit intuitive that that ever worked in the first place. But, it was a breaking change, so I thought I'd bring it up.

**Comment by Gudahtt** [comment] 2016-12-13 20:01
This seems similar to the problem described here: https://github.com/opencypher/openCypher/issues/68

**Comment by spacecowboy** [comment] 2016-12-19 10:47
Breaking changes are to be expected between major versions (v2 vs v3).

This was very likely an intentional change. An error should be expected because executing a merge/create with a null-node makes no sense.

Closing as working as intended.

**Closed as completed by spacecowboy** 2016-12-19 10:47 UTC

**Comment by Gudahtt** [comment] 2016-12-19 14:37
Well, I can see why you'd say it makes no sense. It's more consistent for it to behave this way.

But the previous behavior *was* useful, in that it allowed for the functionality described in https://github.com/opencypher/openCypher/issues/68 . So, it's reasonable to expect people had taken advantage of this.

Would you be able to add an entry in the changelog making note of this change? Or is there another document somewhere describing how to migrate from v2 to v3? I looked to the changelog for this information, and it would have been helpful if this change was mentioned.

I wouldn't mind doing the work of tracking down where this change was introduced, to find out where in the changelog to document it.

**Comment by gotomgo** [comment] 2017-03-19 21:34
apparently @spacecowboy don't give a F

**Comment by gotomgo** [comment] 2017-03-19 21:35
(with his Windows down and his System up?)
